# Database Queries and Analysis
This notebook contains queries for various database tables, identifies potential data issues, and provides insights for further analysis.

In [126]:
# Import required libraries
import pandas as pd
import os
from utils import connect_to_db

In [2]:
# Query the `stock_metadata` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.stock_profiles;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_15611/1318935063.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,name,sector,industry,country,market_cap,employees,description,website,exchange,currency,summary,short_summary,raw_json_sha256,updated_at
0,NVDA,NVIDIA Corporation,Technology,Semiconductors,United States,4534872047616,36000,"NVIDIA Corporation, a computing infrastructure...",https://www.nvidia.com,NASDAQ,USD,NVIDIA Corporation is a prominent computing in...,"NVIDIA Corporation, headquartered in Santa Cla...",2b03f4a47c265a14a12a86ec5e1bae05513e0a87ce196e...,2025-10-27 04:03:37.187649+00:00
1,AAPL,Apple Inc.,Technology,Consumer Electronics,United States,3900351184896,150000,"Apple Inc. designs, manufactures, and markets ...",https://www.apple.com,NASDAQ,USD,Apple Inc. is a leading technology company tha...,Apple Inc. is a prominent technology company t...,bf0aa12b3e7efd09f04e8ad180d2a816be94647f89b999...,2025-10-27 04:03:37.187649+00:00
2,TSLA,"Tesla, Inc.",Consumer Cyclical,Auto Manufacturers,United States,1442474229760,125665,"Tesla, Inc. designs, develops, manufactures, l...",https://www.tesla.com,NASDAQ,USD,"Tesla, Inc. is a prominent manufacturer and pr...","Tesla, Inc. is a leading manufacturer of elect...",ad14d1717f063b1dc2637c3636c11d594f1c6315333d87...,2025-10-27 04:03:37.187649+00:00
3,SOFI,"SoFi Technologies, Inc.",Financial Services,Credit Services,United States,34738028544,5000,"SoFi Technologies, Inc. provides various finan...",https://www.sofi.com,NASDAQ,USD,"SoFi Technologies, Inc. is a financial service...","SoFi Technologies, Inc., founded in 2011 and h...",0d2d4bde0e2b3e355e30a5e57bac951e1b5a7ba2788e6a...,2025-10-27 04:03:37.187649+00:00
4,AMZN,"Amazon.com, Inc.",Consumer Cyclical,Internet Retail,United States,2391180050432,1546000,"Amazon.com, Inc. engages in the retail sale of...",https://www.aboutamazon.com,NASDAQ,USD,"Amazon.com, Inc. is a leading player in the co...","Amazon.com, Inc. is a major player in the cons...",2cae40a3f7e3dd161b3258b39b87893add2384974c997f...,2025-10-27 04:03:37.187649+00:00
5,PLTR,Palantir Technologies Inc.,Technology,Software - Infrastructure,United States,438005596160,4164,Palantir Technologies Inc. builds and deploys ...,https://www.palantir.com,NASDAQ,USD,Palantir Technologies Inc. is a technology com...,Palantir Technologies Inc. is a U.S.-based tec...,3bfb2e9235e3e06e5290f0755be093ceb9eb66ac8b76ad...,2025-10-27 04:13:53.152273+00:00
6,HOOD,"Robinhood Markets, Inc.",Financial Services,Capital Markets,United States,124227878912,2300,"Robinhood Markets, Inc. operates financial ser...",https://robinhood.com,NASDAQ,USD,"Robinhood Markets, Inc. is a financial service...","Robinhood Markets, Inc., headquartered in Menl...",3e4e7e52fd7a673be4366f6cb0aa34e5f06542e069f7e5...,2025-10-27 04:13:53.152273+00:00

In [20]:
# Query the `earnings_calendar` table
# display all rows
pd.set_option('display.max_rows', None)
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.earnings_calendar ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_51229/1162926849.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,calendar_year,calendar_quarter,earnings_date,fiscal_year,fiscal_quarter,fiscal_date,session,updated_at
0,AAPL,2026,1,2026-04-26,NaN,NaN,2026-03-29,amc,2025-11-02 12:01:05.272578+00:00
1,AAPL,2025,4,2026-01-28,NaN,NaN,2025-12-28,amc,2025-11-02 12:01:05.272578+00:00
2,AAPL,2025,3,2025-10-30,NaN,NaN,None,None,2025-11-02 12:01:05.272578+00:00
3,AAPL,2025,2,2025-07-31,2025.0,3.0,2025-06-28,amc,2025-11-02 12:01:05.272578+00:00
4,AAPL,2025,1,2025-05-01,2025.0,2.0,2025-03-29,amc,2025-11-02 12:01:05.272578+00:00
5,AAPL,2024,4,2025-01-30,2025.0,1.0,2024-12-28,amc,2025-11-02 12:01:05.272578+00:00
6,AAPL,2024,3,2024-10-31,2024.0,4.0,2024-09-28,amc,2025-11-02 12:01:05.272578+00:00
7,AAPL,2024,2,2024-08-01,2024.0,3.0,2024-06-29,amc,2025-11-02 12:01:05.272578+00:00
8,AAPL,2024,1,2024-05-02,2024.0,2.0,2024-03-30,amc,2025-11-02 12:01:05.272578+00:00
9,AAPL,2023,4,2024-02-01,2024.0,1.0,2023-12-30,amc,2025-11-02 12:01:05.272578+00:00
10,AAPL,2023,3,2023-11-02,2023.0,4.0,2023-09-30,amc,2025-11-02 12:01:05.272578+00:00
11,AAPL,2023,2,2023-08-03,2023.0,3.0,2023-07-01,amc,2025-11-02 12:01:05.272578+00:00
12,AAPL,2023,1,2023-05-04,2023.0,2.0,2023-04-01,amc,2025-11-02 12:01:05.272578+00:00
13,AAPL,2022,4,2023-02-02,2023.0,1.0,2022-12-31,amc,2025-11-02 12:01:05.272578+00:00
14,AAPL,2022,3,2022-10-27,2022.0,4.0,2022-09-24,amc,2025-11-02 12:01:05.272578+00:00
15,AAPL,2022,2,2022-07-28,2022.0,3.0,2022-06-25,amc,2025-11-02 12:01:05.272578+00:00
16,AAPL,2022,1,2022-04-28,2022.0,2.0,2022-03-26,amc,2025-11-02 12:01:05.272578+00:00
17,AAPL,2021,4,2022-01-27,2022.0,1.0,2021-12-25,amc,2025-11-02 12:01:05.272578+00:00
18,AAPL,2021,3,2021-10-28,2021.0,4.0,2021-09-25,amc,2025-11-02 12:01:05.272578+00:00
19,AAPL,2021,2,2021-07-27,2021.0,3.0,2021-06-26,amc,2025-11-02 12:01:05.272578+00:00
20,AAPL,2021,1,2021-04-28,2021.0,2.0,2021-03-27,amc,2025-11-02 12:01:05.272578+00:00
21,AAPL,2020,4,2021-01-27,2021.0,1.0,2020-12-26,amc,2025-11-02 12:01:05.272578+00:00
22,AAPL,2020,3,2020-10-29,2020.0,4.0,2020-09-26,amc,2025-11-02 12:01:05.272578+00:00
23,AAPL,2020,2,2020-07-30,NaN,NaN,2020-06-26,amc,2025-11-02 12:01:05.272578+00:00
24,AAPL,2020,1,2020-04-30,NaN,NaN,2020-03-27,amc,2025-11-02 12:01:05.272578+00:00
25,AAPL,2019,4,2020-01-28,NaN,NaN,2019-12-27,amc,2025-11-02 12:01:05.272578+00:00
26,AAPL,2019,3,2019-10-30,NaN,NaN,2019-09-27,amc,2025-11-02 12:01:05.272578+00:00
27,AAPL,2019,2,2019-07-30,NaN,NaN,2019-06-28,amc,2025-11-02 12:01:05.272578+00:00
28,AAPL,2019,1,2019-04-30,NaN,NaN,2019-03-29,amc,2025-11-02 12:01:05.272578+00:00
29,AAPL,2018,4,2019-01-29,NaN,NaN,2018-12-28,amc,2025-11-02 12:01:05.272578+00:00
30,AAPL,2018,3,2018-11-01,NaN,NaN,2018-09-28,amc,2025-11-02 12:01:05.272578+00:00
31,AAPL,2018,2,2018-07-31,NaN,NaN,2018-06-29,amc,2025-11-02 12:01:05.272578+00:00
32,AAPL,2018,1,2018-05-01,NaN,NaN,2018-03-30,amc,2025-11-02 12:01:05.272578+00:00
33,AAPL,2017,4,2018-02-01,NaN,NaN,2017-12-29,amc,2025-11-02 12:01:05.272578+00:00
34,AAPL,2017,3,2017-11-02,NaN,NaN,2017-09-29,amc,2025-11-02 12:01:05.272578+00:00
35,AAPL,2017,2,2017-08-01,NaN,NaN,2017-06-30,amc,2025-11-02 12:01:05.272578+00:00
36,AAPL,2017,1,2017-05-02,NaN,NaN,2017-03-31,amc,2025-11-02 12:01:05.272578+00:00
37,AAPL,2016,4,2017-01-31,NaN,NaN,2016-12-30,amc,2025-11-02 12:01:05.272578+00:00
38,AAPL,2016,3,2016-10-25,NaN,NaN,2016-09-23,amc,2025-11-02 12:01:05.272578+00:00
39,AAPL,2016,2,2016-07-26,NaN,NaN,2016-06-24,amc,2025-11-02 12:01:05.272578+00:00
40,AAPL,2016,1,2016-04-26,NaN,NaN,2016-03-25,amc,2025-11-02 12:01:05.272578+00:00
41,AAPL,2015,4,2016-01-26,NaN,NaN,2015-12-25,amc,2025-11-02 12:01:05.272578+00:00
42,AAPL,2015,3,2015-10-27,NaN,NaN,2015-09-25,amc,2025-11-02 12:01:05.272578+00:00
43,AAPL,2015,2,2015-07-21,NaN,NaN,2015-06-26,amc,2025-11-02 12:01:05.272578+00:00
44,AAPL,2015,1,2015-04-27,NaN,NaN,2015-03-27,amc,2025-11-02 12:01:05.272578+00:00
45,AAPL,2014,4,2015-01-27,NaN,NaN,2014-12-26,amc,2025-11-02 12:01:05.272578+00:00
46,AAPL,2014,3,2014-10-20,NaN,NaN,2014-09-26,amc,2025-11-02 12:01:05.272578+00:00
47,AAPL,2014,2,2014-07-22,NaN,NaN,2014-06-27,amc,2025-11-02 12:01:05.272578+00:00
48,AAPL,2014,1,2014-04-23,NaN,NaN,2014-03-28,amc,2025-11-02 12:01:05.272578+00:00
49,AAPL,2013,4,2014-01-27,NaN,NaN,2013-12-27,amc,2025-11-02 12:01:05.272578+00:00
50,AAPL,2013,3,2013-10-28,NaN,NaN,2013-09-27,amc,2025-11-02 12:01:05.272578+00:00
51,AAPL,2013,2,2013-07-23,NaN,NaN,2013-06-28,amc,2025-11-02 12:01:05.272578+00:00
52,AAPL,2013,1,2013-04-23,NaN,NaN,None,None,2025-11-02 12:01:05.272578+00:00
53,AAPL,2012,4,2013-01-23,NaN,NaN,2012-12-28,amc,2025-11-02 12:01:05.272578+00:00
54,AAPL,2012,3,2012-10-25,NaN,NaN,2012-09-28,amc,2025-11-02 12:01:05.272578+00:00
55,AAPL,2012,2,2012-07-24,NaN,NaN,2012-06-29,amc,2025-11-02 12:01:05.272578+00:00
56,AAPL,2012,1,2012-04-24,NaN,NaN,2012-03-30,amc,2025-11-02 12:01:05.272578+00:00
57,AAPL,2011,4,2012-01-24,NaN,NaN,2011-12-30,amc,2025-11-02 12:01:05.272578+00:00
58,AAPL,2011,3,2011-10-18,NaN,NaN,None,None,2025-11-02 12:01:05.272578+00:00
59,AAPL,2011,2,2011-07-19,NaN,NaN,2011-06-24,amc,2025-11-02 12:01:05.272578+00:00
60,AAPL,2011,1,2011-04-20,NaN,NaN,2011-03-25,amc,2025-11-02 12:01:05.272578+00:00
61,AAPL,2010,4,2011-01-18,NaN,NaN,2010-12-24,amc,2025-11-02 12:01:05.272578+00:00
62,AAPL,2010,3,2010-10-18,NaN,NaN,2010-09-24,amc,2025-11-02 12:01:05.272578+00:00
63,AAPL,2010,2,2010-07-20,NaN,NaN,2010-06-25,amc,2025-11-02 12:01:05.272578+00:00
64,AAPL,2010,1,2010-04-20,NaN,NaN,2010-03-26,amc,2025-11-02 12:01:05.272578+00:00
65,AAPL,2009,4,2010-01-25,NaN,NaN,2009-12-25,amc,2025-11-02 12:01:05.272578+00:00
66,AAPL,2009,3,2009-10-19,NaN,NaN,2009-09-25,amc,2025-11-02 12:01:05.272578+00:00
67,AAPL,2009,2,2009-07-21,NaN,NaN,2009-06-26,amc,2025-11-02 12:01:05.272578+00:00
68,AAPL,2009,1,2009-04-22,NaN,NaN,2009-03-27,amc,2025-11-02 12:01:05.272578+00:00
69,AAPL,2008,4,2009-01-21,NaN,NaN,2008-12-26,amc,2025-11-02 12:01:05.272578+00:00
70,AAPL,2008,3,2008-10-21,NaN,NaN,2008-09-26,amc,2025-11-02 12:01:05.272578+00:00
71,AAPL,2008,2,2008-07-21,NaN,NaN,2008-06-27,amc,2025-11-02 12:01:05.272578+00:00
72,AAPL,2008,1,2008-04-23,NaN,NaN,2008-03-28,amc,2025-11-02 12:01:05.272578+00:00
73,AAPL,2007,4,2008-01-22,NaN,NaN,2007-12-28,amc,2025-11-02 12:01:05.272578+00:00
74,AAPL,2007,3,2007-10-22,NaN,NaN,2007-09-28,amc,2025-11-02 12:01:05.272578+00:00
75,AAPL,2007,2,2007-07-25,NaN,NaN,2007-06-29,amc,2025-11-02 12:01:05.272578+00:00
76,AAPL,2007,1,2007-04-25,NaN,NaN,2007-03-30,amc,2025-11-02 12:01:05.272578+00:00
77,AAPL,2006,4,2007-01-17,NaN,NaN,2006-12-29,amc,2025-11-02 12:01:05.272578+00:00
78,AMZN,2026,1,2026-04-29,NaN,NaN,2026-03-30,amc,2025-11-02 12:01:05.363736+00:00
79,AMZN,2025,4,2026-02-04,NaN,NaN,2025-12-30,amc,2025-11-02 12:01:05.363736+00:00
80,AMZN,2025,3,2025-10-30,NaN,NaN,None,None,2025-11-02 12:01:05.363736+00:00
81,AMZN,2025,2,2025-07-31,2025.0,2.0,2025-06-30,amc,2025-11-02 12:01:05.363736+00:00
82,AMZN,2025,1,2025-05-01,2025.0,1.0,2025-03-31,amc,2025-11-02 12:01:05.363736+00:00
83,AMZN,2024,4,2025-02-06,2024.0,4.0,2024-12-31,amc,2025-11-02 12:01:05.363736+00:00
84,AMZN,2024,3,2024-10-31,2024.0,3.0,2024-09-30,amc,2025-11-02 12:01:05.363736+00:00
85,AMZN,2024,2,2024-08-01,2024.0,2.0,2024-06-30,amc,2025-11-02 12:01:05.363736+00:00
86,AMZN,2024,1,2024-04-30,2024.0,1.0,2024-03-31,amc,2025-11-02 12:01:05.363736+00:00
87,AMZN,2023,4,2024-02-01,2023.0,4.0,2023-12-31,amc,2025-11-02 12:01:05.363736+00:00
88,AMZN,2023,3,2023-10-26,2023.0,3.0,2023-09-30,amc,2025-11-02 12:01:05.363736+00:00
89,AMZN,2023,2,2023-08-03,2023.0,2.0,2023-06-30,amc,2025-11-02 12:01:05.363736+00:00
90,AMZN,2023,1,2023-04-27,2023.0,1.0,2023-03-31,amc,2025-11-02 12:01:05.363736+00:00
91,AMZN,2022,4,2023-02-02,2022.0,4.0,2022-12-31,amc,2025-11-02 12:01:05.363736+00:00
92,AMZN,2022,3,2022-10-27,2022.0,3.0,2022-09-30,amc,2025-11-02 12:01:05.363736+00:00
93,AMZN,2022,2,2022-07-28,2022.0,2.0,2022-06-30,amc,2025-11-02 12:01:05.363736+00:00
94,AMZN,2022,1,2022-04-28,2022.0,1.0,2022-03-31,amc,2025-11-02 12:01:05.363736+00:00
95,AMZN,2021,4,2022-02-03,2021.0,4.0,2021-12-31,amc,2025-11-02 12:01:05.363736+00:00
96,AMZN,2021,3,2021-10-28,2021.0,3.0,2021-09-30,amc,2025-11-02 12:01:05.363736+00:00
97,AMZN,2021,2,2021-07-29,2021.0,2.0,2021-06-30,amc,2025-11-02 12:01:05.363736+00:00
98,AMZN,2021,1,2021-04-29,2021.0,1.0,2021-03-31,amc,2025-11-02 12:01:05.363736+00:00
99,AMZN,2020,4,2021-02-02,2020.0,4.0,2020-12-31,amc,2025-11-02 12:01:05.363736+00:00
100,AMZN,2020,3,2020-10-29,2020.0,3.0,2020-09-30,amc,2025-11-02 12:01:05.363736+00:00
101,AMZN,2020,2,2020-07-30,NaN,NaN,2020-06-29,amc,2025-11-02 12:01:05.363736+00:00
102,AMZN,2020,1,2020-04-30,NaN,NaN,2020-03-30,amc,2025-11-02 12:01:05.363736+00:00
103,AMZN,2019,4,2020-01-30,NaN,NaN,2019-12-30,amc,2025-11-02 12:01:05.363736+00:00
104,AMZN,2019,3,2019-10-24,NaN,NaN,2019-09-29,amc,2025-11-02 12:01:05.363736+00:00
105,AMZN,2019,2,2019-07-25,NaN,NaN,2019-06-29,amc,2025-11-02 12:01:05.363736+00:00
106,AMZN,2019,1,2019-04-25,NaN,NaN,2019-03-30,amc,2025-11-02 12:01:05.363736+00:00
107,AMZN,2018,4,2019-01-31,NaN,NaN,2018-12-30,amc,2025-11-02 12:01:05.363736+00:00
108,AMZN,2018,3,2018-10-25,NaN,NaN,2018-09-29,amc,2025-11-02 12:01:05.363736+00:00
109,AMZN,2018,2,2018-07-26,NaN,NaN,2018-06-29,amc,2025-11-02 12:01:05.363736+00:00
110,AMZN,2018,1,2018-04-26,NaN,NaN,2018-03-30,amc,2025-11-02 12:01:05.363736+00:00
111,AMZN,2017,4,2018-02-01,NaN,NaN,2017-12-30,amc,2025-11-02 12:01:05.363736+00:00
112,AMZN,2017,3,2017-10-26,NaN,NaN,2017-09-29,amc,2025-11-02 12:01:05.363736+00:00
113,AMZN,2017,2,2017-07-27,NaN,NaN,2017-06-29,amc,2025-11-02 12:01:05.363736+00:00
114,AMZN,2017,1,2017-04-27,NaN,NaN,2017-03-30,amc,2025-11-02 12:01:05.363736+00:00
115,AMZN,2016,4,2017-02-02,NaN,NaN,2016-12-30,amc,2025-11-02 12:01:05.363736+00:00
116,AMZN,2016,3,2016-10-27,NaN,NaN,2016-09-29,amc,2025-11-02 12:01:05.363736+00:00
117,AMZN,2016,2,2016-07-28,NaN,NaN,2016-06-29,amc,2025-11-02 12:01:05.363736+00:00
118,AMZN,2016,1,2016-04-28,NaN,NaN,2016-03-30,amc,2025-11-02 12:01:05.363736+00:00
119,AMZN,2015,4,2016-01-28,NaN,NaN,2015-12-30,amc,2025-11-02 12:01:05.363736+00:00
120,AMZN,2015,3,2015-10-22,NaN,NaN,2015-09-29,amc,2025-11-02 12:01:05.363736+00:00
121,AMZN,2015,2,2015-07-23,NaN,NaN,2015-06-29,amc,2025-11-02 12:01:05.363736+00:00
122,AMZN,2015,1,2015-04-23,NaN,NaN,2015-03-30,amc,2025-11-02 12:01:05.363736+00:00
123,AMZN,2014,4,2015-01-29,NaN,NaN,2014-12-30,amc,2025-11-02 12:01:05.363736+00:00
124,AMZN,2014,3,2014-10-23,NaN,NaN,2014-09-29,amc,2025-11-02 12:01:05.363736+00:00
125,AMZN,2014,2,2014-07-24,NaN,NaN,2014-06-29,amc,2025-11-02 12:01:05.363736+00:00
126,AMZN,2014,1,2014-04-24,NaN,NaN,2014-03-30,amc,2025-11-02 12:01:05.363736+00:00
127,AMZN,2013,4,2014-01-30,NaN,NaN,2013-12-30,amc,2025-11-02 12:01:05.363736+00:00
128,AMZN,2013,3,2013-10-24,NaN,NaN,2013-09-29,amc,2025-11-02 12:01:05.363736+00:00
129,AMZN,2013,2,2013-07-25,NaN,NaN,None,None,2025-11-02 12:01:05.363736+00:00
130,AMZN,2013,1,2013-04-25,NaN,NaN,2013-03-30,amc,2025-11-02 12:01:05.363736+00:00
131,AMZN,2012,4,2013-01-29,NaN,NaN,2012-12-30,amc,2025-11-02 12:01:05.363736+00:00
132,AMZN,2012,3,2012-10-25,NaN,NaN,2012-09-29,amc,2025-11-02 12:01:05.363736+00:00
133,AMZN,2012,2,2012-07-26,NaN,NaN,2012-06-29,amc,2025-11-02 12:01:05.363736+00:00
134,AMZN,2012,1,2012-04-26,NaN,NaN,2012-03-30,amc,2025-11-02 12:01:05.363736+00:00
135,AMZN,2011,4,2012-01-31,NaN,NaN,2011-12-30,amc,2025-11-02 12:01:05.363736+00:00
136,AMZN,2011,3,2011-10-25,NaN,NaN,2011-09-29,amc,2025-11-02 12:01:05.363736+00:00
137,AMZN,2011,2,2011-07-26,NaN,NaN,2011-06-29,amc,2025-11-02 12:01:05.363736+00:00
138,AMZN,2011,1,2011-04-26,NaN,NaN,2011-03-30,amc,2025-11-02 12:01:05.363736+00:00
139,AMZN,2010,4,2011-01-27,NaN,NaN,2010-12-30,amc,2025-11-02 12:01:05.363736+00:00
140,AMZN,2010,3,2010-10-21,NaN,NaN,2010-09-29,amc,2025-11-02 12:01:05.363736+00:00
141,AMZN,2010,2,2010-07-22,NaN,NaN,2010-06-29,amc,2025-11-02 12:01:05.363736+00:00
142,AMZN,2010,1,2010-04-22,NaN,NaN,2010-03-30,amc,2025-11-02 12:01:05.363736+00:00
143,AMZN,2009,4,2010-01-28,NaN,NaN,2009-12-30,amc,2025-11-02 12:01:05.363736+00:00
144,AMZN,2009,3,2009-10-22,NaN,NaN,2009-09-29,amc,2025-11-02 12:01:05.363736+00:00
145,AMZN,2009,2,2009-07-23,NaN,NaN,2009-06-29,amc,2025-11-02 12:01:05.363736+00:00
146,AMZN,2009,1,2009-04-23,NaN,NaN,2009-03-30,amc,2025-11-02 12:01:05.363736+00:00
147,AMZN,2008,4,2009-01-29,NaN,NaN,2008-12-30,amc,2025-11-02 12:01:05.363736+00:00
148,AMZN,2008,3,2008-10-22,NaN,NaN,2008-09-29,amc,2025-11-02 12:01:05.363736+00:00
149,AMZN,2008,2,2008-07-23,NaN,NaN,2008-06-29,amc,2025-11-02 12:01:05.363736+00:00
150,AMZN,2008,1,2008-04-23,NaN,NaN,2008-03-30,amc,2025-11-02 12:01:05.363736+00:00
151,AMZN,2007,4,2008-01-30,NaN,NaN,2007-12-30,amc,2025-11-02 12:01:05.363736+00:00
152,AMZN,2007,3,2007-10-23,NaN,NaN,2007-09-29,amc,2025-11-02 12:01:05.363736+00:00
153,AMZN,2007,2,2007-07-24,NaN,NaN,2007-06-29,amc,2025-11-02 12:01:05.363736+00:00
154,AMZN,2007,1,2007-04-24,NaN,NaN,2007-03-30,amc,2025-11-02 12:01:05.363736+00:00
155,AMZN,2006,4,2007-02-01,NaN,NaN,2006-12-30,bmo,2025-11-02 12:01:05.363736+00:00
156,AMZN,2006,3,2006-10-24,NaN,NaN,2006-09-29,amc,2025-11-02 12:01:05.363736+00:00
157,AMZN,2006,2,2006-07-25,NaN,NaN,2006-06-29,amc,2025-11-02 12:01:05.363736+00:00
158,AMZN,2006,1,2006-04-25,NaN,NaN,2006-03-30,amc,2025-11-02 12:01:05.363736+00:00
159,AMZN,2005,4,2006-02-02,NaN,NaN,2005-12-30,amc,2025-11-02 12:01:05.363736+00:00
160,AMZN,2005,3,2005-10-25,NaN,NaN,2005-09-29,amc,2025-11-02 12:01:05.363736+00:00
161,AMZN,2005,2,2005-07-26,NaN,NaN,2005-06-29,amc,2025-11-02 12:01:05.363736+00:00
162,AMZN,2005,1,2005-04-26,NaN,NaN,2005-03-30,amc,2025-11-02 12:01:05.363736+00:00
163,AMZN,2004,4,2005-02-02,NaN,NaN,2004-12-30,amc,2025-11-02 12:01:05.363736+00:00
164,AMZN,2004,3,2004-10-21,NaN,NaN,2004-09-29,amc,2025-11-02 12:01:05.363736+00:00
165,AMZN,2004,2,2004-07-22,NaN,NaN,2004-06-29,amc,2025-11-02 12:01:05.363736+00:00
166,AMZN,2004,1,2004-04-22,NaN,NaN,2004-03-30,amc,2025-11-02 12:01:05.363736+00:00
167,AMZN,2003,4,2004-01-27,NaN,NaN,2003-12-30,amc,2025-11-02 12:01:05.363736+00:00
168,AMZN,2003,3,2003-10-21,NaN,NaN,2003-09-29,amc,2025-11-02 12:01:05.363736+00:00
169,AMZN,2003,2,2003-07-22,NaN,NaN,2003-06-29,amc,2025-11-02 12:01:05.363736+00:00
170,AMZN,2003,1,2003-04-24,NaN,NaN,2003-03-30,amc,2025-11-02 12:01:05.363736+00:00
171,AMZN,2002,4,2003-01-23,NaN,NaN,2002-12-30,amc,2025-11-02 12:01:05.363736+00:00
172,AMZN,2002,3,2002-10-24,NaN,NaN,2002-09-29,amc,2025-11-02 12:01:05.363736+00:00
173,AMZN,2002,2,2002-07-23,NaN,NaN,2002-06-29,amc,2025-11-02 12:01:05.363736+00:00
174,AMZN,2002,1,2002-04-23,NaN,NaN,2002-03-30,amc,2025-11-02 12:01:05.363736+00:00
175,AMZN,2001,4,2002-01-22,NaN,NaN,2001-12-30,bmo,2025-11-02 12:01:05.363736+00:00
176,AMZN,2001,3,2001-10-23,NaN,NaN,2001-09-29,bmo,2025-11-02 12:01:05.363736+00:00
177,AMZN,2001,2,2001-07-23,NaN,NaN,2001-06-29,bmo,2025-11-02 12:01:05.363736+00:00
178,AMZN,2001,1,2001-04-24,NaN,NaN,2001-03-30,bmo,2025-11-02 12:01:05.363736+00:00
179,AMZN,2000,4,2001-01-30,NaN,NaN,2000-12-30,bmo,2025-11-02 12:01:05.363736+00:00
180,AMZN,2000,3,2000-10-24,NaN,NaN,2000-09-29,bmo,2025-11-02 12:01:05.363736+00:00
181,AMZN,2000,2,2000-07-26,NaN,NaN,2000-06-29,bmo,2025-11-02 12:01:05.363736+00:00
182,AMZN,2000,1,2000-04-26,NaN,NaN,2000-03-30,bmo,2025-11-02 12:01:05.363736+00:00
183,AMZN,1999,4,2000-02-02,NaN,NaN,1999-12-30,bmo,2025-11-02 12:01:05.363736+00:00
184,AMZN,1999,3,1999-10-27,NaN,NaN,1999-09-29,bmo,2025-11-02 12:01:05.363736+00:00
185,AMZN,1999,2,1999-07-21,NaN,NaN,1999-06-29,bmo,2025-11-02 12:01:05.363736+00:00
186,AMZN,1999,1,1999-04-28,NaN,NaN,1999-03-30,bmo,2025-11-02 12:01:05.363736+00:00
187,AMZN,1998,4,1999-01-26,NaN,NaN,1998-12-30,bmo,2025-11-02 12:01:05.363736+00:00
188,AMZN,1998,3,1998-10-28,NaN,NaN,1998-09-29,bmo,2025-11-02 12:01:05.363736+00:00
189,AMZN,1998,2,1998-07-22,NaN,NaN,1998-06-29,bmo,2025-11-02 12:01:05.363736+00:00
190,AMZN,1998,1,1998-04-27,NaN,NaN,1998-03-30,bmo,2025-11-02 12:01:05.363736+00:00
191,AMZN,1997,4,1998-01-22,NaN,NaN,1997-12-30,bmo,2025-11-02 12:01:05.363736+00:00
192,HOOD,2026,1,2026-04-28,NaN,NaN,2026-03-30,amc,2025-11-02 12:01:05.415796+00:00
193,HOOD,2025,4,2026-02-10,NaN,NaN,2025-12-30,amc,2025-11-02 12:01:05.415796+00:00
194,HOOD,2025,3,2025-11-05,NaN,NaN,2025-09-30,amc,2025-11-02 12:01:05.415796+00:00
195,HOOD,2025,2,2025-07-30,2025.0,2.0,2025-06-30,amc,2025-11-02 12:01:05.415796+00:00
196,HOOD,2025,1,2025-04-30,2025.0,1.0,2025-03-31,amc,2025-11-02 12:01:05.415796+00:00
197,HOOD,2024,4,2025-02-12,2024.0,4.0,2024-12-31,amc,2025-11-02 12:01:05.415796+00:00
198,HOOD,2024,3,2024-10-30,2024.0,3.0,2024-09-30,amc,2025-11-02 12:01:05.415796+00:00
199,HOOD,2024,2,2024-08-07,2024.0,2.0,2024-06-30,amc,2025-11-02 12:01:05.415796+00:00
200,HOOD,2024,1,2024-05-08,2024.0,1.0,2024-03-31,amc,2025-11-02 12:01:05.415796+00:00
201,HOOD,2023,4,2024-02-13,2023.0,4.0,2023-12-31,amc,2025-11-02 12:01:05.415796+00:00
202,HOOD,2023,3,2023-11-07,2023.0,3.0,2023-09-30,amc,2025-11-02 12:01:05.415796+00:00
203,HOOD,2023,2,2023-08-02,2023.0,2.0,2023-06-30,amc,2025-11-02 12:01:05.415796+00:00
204,HOOD,2023,1,2023-05-10,2023.0,1.0,2023-03-31,amc,2025-11-02 12:01:05.415796+00:00
205,HOOD,2022,4,2023-02-08,2022.0,4.0,2022-12-31,amc,2025-11-02 12:01:05.415796+00:00
206,HOOD,2022,3,2022-11-02,2022.0,3.0,2022-09-30,amc,2025-11-02 12:01:05.415796+00:00
207,HOOD,2022,2,2022-08-02,2022.0,2.0,2022-06-30,amc,2025-11-02 12:01:05.415796+00:00
208,HOOD,2022,1,2022-04-28,2022.0,1.0,2022-03-31,amc,2025-11-02 12:01:05.415796+00:00
209,HOOD,2021,4,2022-01-27,2021.0,4.0,2021-12-31,amc,2025-11-02 12:01:05.415796+00:00
210,NVDA,2026,1,2026-05-26,NaN,NaN,None,None,2025-11-02 12:01:05.235201+00:00
211,NVDA,2025,4,2026-02-24,NaN,NaN,2026-01-27,amc,2025-11-02 12:01:05.235201+00:00
212,NVDA,2025,3,2025-11-19,NaN,NaN,2025-10-27,bmo,2025-11-02 12:01:05.235201+00:00
213,NVDA,2025,2,2025-08-27,2026.0,2.0,2025-07-27,amc,2025-11-02 12:01:05.235201+00:00
214,NVDA,2025,1,2025-05-28,2026.0,1.0,2025-04-27,amc,2025-11-02 12:01:05.235201+00:00
215,NVDA,2024,4,2025-02-26,2025.0,4.0,2025-01-31,amc,2025-11-02 12:01:05.235201+00:00
216,NVDA,2024,3,2024-11-20,2025.0,3.0,2024-10-27,amc,2025-11-02 12:01:05.235201+00:00
217,NVDA,2024,2,2024-08-28,2025.0,2.0,2024-07-28,amc,2025-11-02 12:01:05.235201+00:00
218,NVDA,2024,1,2024-05-22,2025.0,1.0,2024-04-28,None,2025-11-02 12:01:05.235201+00:00
219,NVDA,2023,4,2024-02-21,2024.0,4.0,2024-01-31,amc,2025-11-02 12:01:05.235201+00:00
220,NVDA,2023,3,2023-11-21,2024.0,3.0,2023-10-29,amc,2025-11-02 12:01:05.235201+00:00
221,NVDA,2023,2,2023-08-23,2024.0,2.0,2023-07-30,amc,2025-11-02 12:01:05.235201+00:00
222,NVDA,2023,1,2023-05-24,2024.0,1.0,2023-04-30,amc,2025-11-02 12:01:05.235201+00:00
223,NVDA,2022,4,2023-02-22,2023.0,4.0,2023-01-31,amc,2025-11-02 12:01:05.235201+00:00
224,NVDA,2022,3,2022-11-16,2023.0,3.0,2022-10-30,amc,2025-11-02 12:01:05.235201+00:00
225,NVDA,2022,2,2022-08-24,2023.0,2.0,2022-07-31,amc,2025-11-02 12:01:05.235201+00:00
226,NVDA,2022,1,2022-05-25,2023.0,1.0,2022-05-01,amc,2025-11-02 12:01:05.235201+00:00
227,NVDA,2021,4,2022-02-16,2022.0,4.0,2022-01-31,amc,2025-11-02 12:01:05.235201+00:00
228,NVDA,2021,3,2021-11-17,2022.0,3.0,2021-10-31,amc,2025-11-02 12:01:05.235201+00:00
229,NVDA,2021,2,2021-08-18,2022.0,2.0,2021-08-01,amc,2025-11-02 12:01:05.235201+00:00
230,NVDA,2021,1,2021-05-26,2022.0,1.0,2021-05-02,None,2025-11-02 12:01:05.235201+00:00
231,NVDA,2020,4,2021-02-24,2021.0,4.0,2021-01-31,amc,2025-11-02 12:01:05.235201+00:00
232,NVDA,2020,3,2020-11-18,2021.0,3.0,2020-10-25,amc,2025-11-02 12:01:05.235201+00:00
233,NVDA,2020,2,2020-08-19,NaN,NaN,2020-07-25,amc,2025-11-02 12:01:05.235201+00:00
234,NVDA,2020,1,2020-05-21,NaN,NaN,None,None,2025-11-02 12:01:05.235201+00:00
235,NVDA,2019,4,2020-02-13,NaN,NaN,2020-01-25,amc,2025-11-02 12:01:05.235201+00:00
236,NVDA,2019,3,2019-11-14,NaN,NaN,2019-10-26,amc,2025-11-02 12:01:05.235201+00:00
237,NVDA,2019,2,2019-08-15,NaN,NaN,2019-07-27,amc,2025-11-02 12:01:05.235201+00:00

In [21]:
# Query the `earnings` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.earnings ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_51229/2825776678.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,event_id,tic,calendar_year,calendar_quarter,earnings_date,fiscal_date,session,eps,eps_estimated,revenue,revenue_estimated,price_before,price_after,source,raw_json,raw_json_sha256,updated_at
0,95e309d2-27b1-4eb7-b9f2-58547f1aa01e,AAPL,2026,1,2026-04-26,2026-03-29,amc,NaN,NaN,NaN,NaN,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2026-04-26', 'symbol': 'AAPL', 'epsA...",06cf18a752284b73358709470c8f7dd84cc48a744e8ce2...,2025-10-27 07:39:43.975064+00:00
1,de44a0a2-2ea3-45ac-bbe7-0b65823aeb9a,AAPL,2025,4,2026-01-28,2025-12-28,amc,NaN,NaN,NaN,NaN,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2026-01-28', 'symbol': 'AAPL', 'epsA...",9a060126cf3f854c7aea63df4875b4582c7785feb0d4e2...,2025-10-27 07:39:43.975064+00:00
2,52c42e2c-738c-4416-84f8-cc318dbc7566,AAPL,2025,3,2025-10-30,None,None,NaN,1.7300,NaN,1.020888e+11,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-10-30', 'symbol': 'AAPL', 'epsA...",2fda15cd2548d854f25e23b1db4ba5376ab471917f0f48...,2025-10-27 07:39:43.975064+00:00
3,18b80dd5-acda-48a2-9d3d-cd72cc6c56ad,AAPL,2025,2,2025-07-31,2025-06-28,amc,1.5700,1.4400,9.403600e+10,8.956274e+10,209.0500,202.3800,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-07-31', 'symbol': 'AAPL', 'epsA...",737dcf63b916a8ffe43edeaa69041921417b57df04ae1a...,2025-10-27 07:39:43.975064+00:00
4,7fedbfe1-0078-4300-95f5-2a3d1f86f16b,AAPL,2025,1,2025-05-01,2025-03-29,amc,1.6500,1.6300,9.535900e+10,9.454218e+10,213.0650,204.8800,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-05-01', 'symbol': 'AAPL', 'epsA...",09e01e72b1c2a94a6310e83dcedfd1be5c4a3a0d7bde41...,2025-10-27 07:39:43.975064+00:00
5,e774d398-051e-4919-bd4b-8e1de059666e,AAPL,2024,4,2025-01-30,2024-12-28,amc,2.4000,2.3600,1.243000e+11,1.242574e+11,239.2800,236.0100,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-01-30', 'symbol': 'AAPL', 'epsA...",63812b39ed6c8040579166b4c3b1b6c01cac368cc4fec0...,2025-10-27 07:39:43.975064+00:00
6,0bcacd11-7843-430e-a91a-d151cf71d4a7,AAPL,2024,3,2024-10-31,2024-09-28,amc,1.6400,1.6000,9.493000e+10,9.451195e+10,229.8500,223.1820,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-10-31', 'symbol': 'AAPL', 'epsA...",33974ec735cb08279f3c7a0c2a87a5ac3b357455de7fb3...,2025-10-27 07:39:43.975064+00:00
7,d191c98b-d169-4f57-85bc-c25b1cbe9388,AAPL,2024,2,2024-08-01,2024-06-29,amc,1.4000,1.3500,8.577700e+10,8.443254e+10,222.4000,219.6800,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-08-01', 'symbol': 'AAPL', 'epsA...",8708e05d49f26325ae584dc1f02103b489f33fb3585c9a...,2025-10-27 07:39:43.975064+00:00
8,e6bb63b3-2680-4d62-a00b-72a2ee557857,AAPL,2024,1,2024-05-02,2024-03-30,amc,1.5300,1.5000,9.075300e+10,9.036611e+10,169.3000,183.4100,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-05-02', 'symbol': 'AAPL', 'epsA...",5a7c7578e318413b788bf1e3c274a4b5f01207c4ebc9d3...,2025-10-27 07:39:43.975064+00:00
9,396954de-7b2e-475b-9bb8-a8449bf65f34,AAPL,2023,4,2024-02-01,2023-12-30,amc,2.1800,2.1000,1.195750e+11,1.179866e+11,184.4000,185.8500,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-02-01', 'symbol': 'AAPL', 'epsA...",814b535e2bf2933166e9d6ce380cc866489d735296756e...,2025-10-27 07:39:43.975064+00:00
10,319b8479-df04-42b8-af1e-509152a16aa6,AAPL,2023,3,2023-11-02,2023-09-30,amc,1.4600,1.3900,8.949800e+10,8.417580e+10,173.9700,176.6500,https://financialmodelingprep.com/stable/earni...,"{'date': '2023-11-02', 'symbol': 'AAPL', 'epsA...",62796716c404cc1d3511b27232a6c3318378f5d60ff01e...,2025-10-27 07:39:43.975064+00:00
11,3a6f7044-be9b-4617-aa46-6a31a809fb78,AAPL,2023,2,2023-08-03,2023-07-01,amc,1.2600,1.1900,8.179700e+10,8.168570e+10,192.5200,182.2000,https://financialmodelingprep.com/stable/earni...,"{'date': '2023-08-03', 'symbol': 'AAPL', 'epsA...",7542b8ee5cfd9149f4298cc509eca6c8cb1abba307c3f8...,2025-10-27 07:39:43.975064+00:00
12,3b87a70b-aa31-46af-bd00-61fff0517830,AAPL,2023,1,2023-05-04,2023-04-01,amc,1.5200,1.4300,9.483600e+10,9.296020e+10,167.4300,173.6400,https://financialmodelingprep.com/stable/earni...,"{'date': '2023-05-04', 'symbol': 'AAPL', 'epsA...",c974fc1ed65540c831f5791da26cab29106431ae1e3896...,2025-10-27 07:39:43.975064+00:00
13,31a0fba4-885e-4e24-b9a2-d029113af008,AAPL,2022,4,2023-02-02,2022-12-31,amc,1.8800,1.9400,1.171540e+11,1.213333e+11,145.4500,154.8350,https://financialmodelingprep.com/stable/earni...,"{'date': '2023-02-02', 'symbol': 'AAPL', 'epsA...",707cbf8e38da86589d190ab475bdb34f81fb13c8d335fe...,2025-10-27 07:39:43.975064+00:00
14,76991b99-98cd-466a-b720-80793145b55e,AAPL,2022,3,2022-10-27,2022-09-24,amc,1.2900,1.2700,9.014600e+10,8.873928e+10,149.2800,156.0910,https://financialmodelingprep.com/stable/earni...,"{'date': '2022-10-27', 'symbol': 'AAPL', 'epsA...",40e3c3ed06cdc56da9d27a74c8783776c5bdbdf3d66478...,2025-10-27 07:39:43.975064+00:00
15,beda5422-fa9c-4c15-a5a1-9183c64c3567,AAPL,2022,2,2022-07-28,2022-06-25,amc,1.2000,1.1600,8.295900e+10,8.279124e+10,156.9300,162.8200,https://financialmodelingprep.com/stable/earni...,"{'date': '2022-07-28', 'symbol': 'AAPL', 'epsA...",75f2c6c7fdcbf41ce48089f4e99d69303793ccf180c199...,2025-10-27 07:39:43.975064+00:00
16,70b38fc4-f7d1-4d73-833f-dd2c8d523692,AAPL,2022,1,2022-04-28,2022-03-26,amc,1.5200,1.4300,9.727800e+10,9.403380e+10,156.7000,157.5610,https://financialmodelingprep.com/stable/earni...,"{'date': '2022-04-28', 'symbol': 'AAPL', 'epsA...",0b2ab9190ac9d14b11b4edcec3941eb8191e36f88eab65...,2025-10-27 07:39:43.975064+00:00
17,e4e1838d-9c08-4633-af70-df3fab339dae,AAPL,2021,4,2022-01-27,2021-12-25,amc,2.1000,1.8900,1.239450e+11,1.190025e+11,160.0100,167.3800,https://financialmodelingprep.com/stable/earni...,"{'date': '2022-01-27', 'symbol': 'AAPL', 'epsA...",e38b361f714e7bd4f1f2007853b94fc8fb8fde0c92b9be...,2025-10-27 07:39:43.975064+00:00
18,8f41a5ed-424c-4a2e-8136-d4c20eddfc69,AAPL,2021,3,2021-10-28,2021-09-25,amc,1.2400,1.2400,8.336000e+10,1.179860e+11,148.9300,149.8350,https://financialmodelingprep.com/stable/earni...,"{'date': '2021-10-28', 'symbol': 'AAPL', 'epsA...",94cc51bb87ceb5889c0feb6840e362fe4e1d142e46c605...,2025-10-27 07:39:43.975064+00:00
19,03f62248-e342-4f95-bcff-712973e5b42f,AAPL,2021,2,2021-07-27,2021-06-26,amc,1.3000,1.0100,8.143400e+10,8.458190e+10,147.7350,143.6570,https://financialmodelingprep.com/stable/earni...,"{'date': '2021-07-27', 'symbol': 'AAPL', 'epsA...",3f7511f708f97bff656a433ad8a51aa10e7872d4b82746...,2025-10-27 07:39:43.975064+00:00
20,c1adb55e-501f-4230-8c87-febd294bc678,AAPL,2021,1,2021-04-28,2021-03-27,amc,1.4000,0.9900,8.958400e+10,7.692070e+10,133.1870,133.5000,https://financialmodelingprep.com/stable/earni...,"{'date': '2021-04-28', 'symbol': 'AAPL', 'epsA...",6aab7aa4464a8204e915a325f980b4a186247702433840...,2025-10-27 07:39:43.975064+00:00
21,c21c165a-bb65-4c89-998b-4895b203ca39,AAPL,2020,4,2021-01-27,2020-12-26,amc,1.6800,1.4100,1.114390e+11,9.009962e+10,143.0700,137.0200,https://financialmodelingprep.com/stable/earni...,"{'date': '2021-01-27', 'symbol': 'AAPL', 'epsA...",43a2937b4b179dbadd79187d10328622c967ce6dee8ce1...,2025-10-27 07:39:43.975064+00:00
22,dfe26214-22ed-4d8d-a1c7-0c1a06f893a9,AAPL,2020,3,2020-10-29,2020-09-26,amc,0.7300,0.7000,6.469800e+10,6.203918e+10,111.2000,108.8600,https://financialmodelingprep.com/stable/earni...,"{'date': '2020-10-29', 'symbol': 'AAPL', 'epsA...",2cc2da1fe353ba65cbf4ea63ea00908ad7ff9c9f0bce81...,2025-10-27 07:39:43.975064+00:00
23,873192ec-f320-4064-b34b-37a7b1ed2c2b,AAPL,2020,2,2020-07-30,2020-06-26,amc,0.6500,0.5100,5.968500e+10,4.682977e+10,95.0400,106.2600,https://financialmodelingprep.com/stable/earni...,"{'date': '2020-07-30', 'symbol': 'AAPL', 'epsA...",40efc4548ec16948175642baa4e0396b4d0fbf7b05e069...,2025-10-27 07:39:43.975064+00:00
24,cae52c50-c100-43fc-a60b-535881e0fb38,AAPL,2020,1,2020-04-30,2020-03-27,amc,0.6400,0.5700,5.831300e+10,5.102388e+10,71.9325,72.2675,https://financialmodelingprep.com/stable/earni...,"{'date': '2020-04-30', 'symbol': 'AAPL', 'epsA...",c6a2e40b2f071526e196a6a910796c786232e97baf1cc5...,2025-10-27 07:39:43.975064+00:00
25,b0c9450d-d8b7-46f2-abce-a65cca203fb7,AAPL,2019,4,2020-01-28,2019-12-27,amc,1.2500,1.1400,9.181900e+10,8.373893e+10,77.2375,81.0850,https://financialmodelingprep.com/stable/earni...,"{'date': '2020-01-28', 'symbol': 'AAPL', 'epsA...",8419daf8bdcfc0a6a4826e14685677a7ac5c0245596199...,2025-10-27 07:39:43.975064+00:00
26,04c0e547-b015-405a-8eb1-830899885aa7,AAPL,2019,3,2019-10-30,2020-09-26,amc,0.7600,0.7100,6.404000e+10,5.982684e+10,60.8225,62.1900,https://financialmodelingprep.com/stable/earni...,"{'date': '2019-10-30', 'symbol': 'AAPL', 'epsA...",823b6031cdd882b20e9732adef86b59f7185e4002fc4ce...,2025-10-27 07:39:43.975064+00:00
27,7e873563-9389-47cc-8eb2-b1b5731b2e55,AAPL,2019,2,2019-07-30,2019-06-28,amc,0.5500,0.5200,5.380900e+10,5.185231e+10,52.4200,53.2600,https://financialmodelingprep.com/stable/earni...,"{'date': '2019-07-30', 'symbol': 'AAPL', 'epsA...",0ecb86e59cb566a5e0477b47932fbb9ad1047ac3766dac...,2025-10-27 07:39:43.975064+00:00
28,3711ec92-6bd6-4a4f-8cd7-da7c30cd2fe0,AAPL,2019,1,2019-04-30,2019-03-29,amc,0.6200,0.5900,5.801500e+10,5.520782e+10,51.1525,52.6300,https://financialmodelingprep.com/stable/earni...,"{'date': '2019-04-30', 'symbol': 'AAPL', 'epsA...",1e36b22373dda650780c8f58611c3b8d28d1d410488174...,2025-10-27 07:39:43.975064+00:00
29,dc88ff60-c603-4f20-be64-82db0bc93ff2,AAPL,2018,4,2019-01-29,2018-12-28,amc,1.0500,1.0400,8.431000e+10,8.350705e+10,39.0750,41.3125,https://financialmodelingprep.com/stable/earni...,"{'date': '2019-01-29', 'symbol': 'AAPL', 'epsA...",ec2976b8e751428ef55f42faaf143defec5e52d31dbf60...,2025-10-27 07:39:43.975064+00:00
30,2bd84de4-c6f5-4f63-8b7b-d19b8b997998,AAPL,2018,3,2018-11-01,2018-09-28,amc,0.7300,0.7000,6.290000e+10,6.031507e+10,54.7150,51.8700,https://financialmodelingprep.com/stable/earni...,"{'date': '2018-11-01', 'symbol': 'AAPL', 'epsA...",213e5ea1fe54619d604b7c4691fecb0337e6ebfbc8d114...,2025-10-27 07:39:43.975064+00:00
31,82b94e31-d851-435d-b156-4f3cbbf4d286,AAPL,2018,2,2018-07-31,2018-06-29,amc,0.5900,0.5500,5.326500e+10,4.962295e+10,47.4775,50.3750,https://financialmodelingprep.com/stable/earni...,"{'date': '2018-07-31', 'symbol': 'AAPL', 'epsA...",e594dc3fa38fa2ffabd96d9bd05452325f63396a8167a3...,2025-10-27 07:39:43.975064+00:00
32,eafda08a-5f6c-4c9b-acfb-fbad221fb99d,AAPL,2018,1,2018-05-01,2018-03-30,amc,0.6800,0.6700,6.113700e+10,5.979333e+10,41.3150,44.1425,https://financialmodelingprep.com/stable/earni...,"{'date': '2018-05-01', 'symbol': 'AAPL', 'epsA...",c63796c423e97d022882ce1ce02cad2eeeb92b6ccc5cb8...,2025-10-27 07:39:43.975064+00:00
33,2d27f020-bed2-4a6d-8845-fb348cd61d21,AAPL,2017,4,2018-02-01,2017-12-29,amc,0.9700,0.9600,8.829300e+10,8.761208e+10,41.8575,40.1250,https://financialmodelingprep.com/stable/earni...,"{'date': '2018-02-01', 'symbol': 'AAPL', 'epsA...",df86cc1a7d5564a85b9ea4318a318b261c2253bea731f0...,2025-10-27 07:39:43.975064+00:00
34,fbf7dcf2-adb5-4e49-989c-728bf6d2d0f9,AAPL,2017,3,2017-11-02,2017-09-29,amc,0.5200,0.4700,5.257900e+10,4.749890e+10,41.7225,43.1250,https://financialmodelingprep.com/stable/earni...,"{'date': '2017-11-02', 'symbol': 'AAPL', 'epsA...",b63a55ec49bfc4485751038585a6d9ec21d8c5a8ea7852...,2025-10-27 07:39:43.975064+00:00
35,b36614b3-9237-468e-955d-dde9fdb6002a,AAPL,2017,2,2017-08-01,2017-06-30,amc,0.4200,0.3900,4.540800e+10,4.268896e+10,37.1825,39.2850,https://financialmodelingprep.com/stable/earni...,"{'date': '2017-08-01', 'symbol': 'AAPL', 'epsA...",ad3e6995c2ac5e7e13df334bd1aae06d19fe07fd887223...,2025-10-27 07:39:43.975064+00:00
36,859b35d3-e28b-4372-90da-dfb3f2b189ee,AAPL,2017,1,2017-05-02,2017-03-31,amc,0.5300,0.5000,5.289600e+10,5.088091e+10,36.6450,36.7650,https://financialmodelingprep.com/stable/earni...,"{'date': '2017-05-02', 'symbol': 'AAPL', 'epsA...",8d8e2e04b6cfd886141c70522fbbdd3605dd951e514455...,2025-10-27 07:39:43.975064+00:00
37,3fe21129-27a2-4a98-b4ff-356656d491d8,AAPL,2016,4,2017-01-31,2016-12-30,amc,0.8400,0.8000,7.835100e+10,7.485319e+10,30.4075,32.1875,https://financialmodelingprep.com/stable/earni...,"{'date': '2017-01-31', 'symbol': 'AAPL', 'epsA...",edc5bbb051d6f181202bb1692fa4eb6d0f3aaa320f78fc...,2025-10-27 07:39:43.975064+00:00
38,404f3909-6863-4447-82fc-ca8a1ca2674d,AAPL,2016,3,2016-10-25,2016-09-23,amc,0.4200,0.4100,4.685200e+10,4.657145e+10,29.4125,28.8975,https://financialmodelingprep.com/stable/earni...,"{'date': '2016-10-25', 'symbol': 'AAPL', 'epsA...",12fc61fb722fe0a426c6994142a0d2db1bef19cfbc2a64...,2025-10-27 07:39:43.975064+00:00
39,9a65aa43-f296-43ad-b2f4-a275c47dd62d,AAPL,2016,2,2016-07-26,2016-06-24,amc,0.3600,0.3500,4.235800e+10,4.116482e+10,24.3350,25.7375,https://financialmodelingprep.com/stable/earni...,"{'date': '2016-07-26', 'symbol': 'AAPL', 'epsA...",025dedceaed3adb8f4b6cd945eea16bd453a3d645f9c24...,2025-10-27 07:39:43.975064+00:00
40,b154c0e8-907e-483a-99a6-5cc6dbdf774c,AAPL,2016,1,2016-04-26,2016-03-25,amc,0.4800,0.5000,5.055700e+10,5.321789e+10,26.2700,24.4550,https://financialmodelingprep.com/stable/earni...,"{'date': '2016-04-26', 'symbol': 'AAPL', 'epsA...",72a13a412658ad3ddbf1d0b1c87bb4dc31b010b3d8c072...,2025-10-27 07:39:43.975064+00:00
41,87f3ec46-1b2e-42ce-9a15-a754ff16353f,AAPL,2015,4,2016-01-26,2015-12-25,amc,0.8200,0.8100,7.587200e+10,7.471541e+10,24.8600,23.3550,https://financialmodelingprep.com/stable/earni...,"{'date': '2016-01-26', 'symbol': 'AAPL', 'epsA...",40dac14c4c30d9707dc1ab72a53e306b5f58734a6e947d...,2025-10-27 07:39:43.975064+00:00
42,a4ff660c-7706-442e-85c6-bf2de4f84aa9,AAPL,2015,3,2015-10-27,2015-09-25,amc,0.4900,0.4700,5.150100e+10,4.939892e+10,28.8200,29.8175,https://financialmodelingprep.com/stable/earni...,"{'date': '2015-10-27', 'symbol': 'AAPL', 'epsA...",ac043c5f9304f22718b5421d6285c25663bd3b81af34fe...,2025-10-27 07:39:43.975064+00:00
43,620a3cb5-1177-4e23-bbdb-7b9dc93d0454,AAPL,2015,2,2015-07-21,2015-06-26,amc,0.4600,0.4500,4.960500e+10,4.853246e+10,33.0175,31.3050,https://financialmodelingprep.com/stable/earni...,"{'date': '2015-07-21', 'symbol': 'AAPL', 'epsA...",96563ee03ecca034d95b16d4b541410f2bda9d71cfe9d8...,2025-10-27 07:39:43.975064+00:00
44,26be1a8f-282a-4baa-b994-26e67e5dddd9,AAPL,2015,1,2015-04-27,2015-03-27,amc,0.5800,0.5400,5.801000e+10,5.377751e+10,32.5700,32.6400,https://financialmodelingprep.com/stable/earni...,"{'date': '2015-04-27', 'symbol': 'AAPL', 'epsA...",2bb08341c5fff07d65eb23fde70b96d1c4c072090fee84...,2025-10-27 07:39:43.975064+00:00
45,ed6df516-9913-402e-ad4a-776a14393948,AAPL,2014,4,2015-01-27,2014-12-26,amc,0.7700,0.6500,7.459900e+10,6.338477e+10,28.2750,28.8275,https://financialmodelingprep.com/stable/earni...,"{'date': '2015-01-27', 'symbol': 'AAPL', 'epsA...",dbee509d492f2b24ccdfd4fbcee7e735b1c1467b901ca2...,2025-10-27 07:39:43.975064+00:00
46,8e87b3dc-3d53-45ce-87b2-126af90aaad7,AAPL,2014,3,2014-10-20,2014-09-26,amc,0.3600,0.3300,4.212300e+10,3.885995e+10,24.4175,25.6175,https://financialmodelingprep.com/stable/earni...,"{'date': '2014-10-20', 'symbol': 'AAPL', 'epsA...",5964704995ddf5c593497e3776633e83b5368b0cb4ab71...,2025-10-27 07:39:43.975064+00:00
47,2c38b5a9-9d98-45d1-8182-fa0a5e77d65f,AAPL,2014,2,2014-07-22,2014-06-27,amc,0.3200,0.3100,3.743200e+10,3.596981e+10,23.4848,24.2975,https://financialmodelingprep.com/stable/earni...,"{'date': '2014-07-22', 'symbol': 'AAPL', 'epsA...",3ea331bfd32488fe990e5c54feadef4b61ef6d416c57f1...,2025-10-27 07:39:43.975064+00:00
48,44e490bf-8caf-4522-9b71-11ae264a1b54,AAPL,2014,1,2014-04-23,2014-03-28,amc,0.4200,0.3600,4.564600e+10,4.014648e+10,18.9893,20.2775,https://financialmodelingprep.com/stable/earni...,"{'date': '2014-04-23', 'symbol': 'AAPL', 'epsA...",9567497761ef4354faa6f91f499acae7ee27d1a9f89369...,2025-10-27 07:39:43.975064+00:00
49,8d88361e-5298-46d9-a65d-4b6c7ce6550b,AAPL,2013,4,2014-01-27,2013-12-27,amc,0.5200,0.5000,5.759400e+10,5.592461e+10,19.5025,18.0893,https://financialmodelingprep.com/stable/earni...,"{'date': '2014-01-27', 'symbol': 'AAPL', 'epsA...",1e2e65c7a4d1e462723abfe2220aad284c04d5812d17db...,2025-10-27 07:39:43.975064+00:00
50,1935df6f-8dec-4533-abe3-61ccf17c6ebe,AAPL,2013,3,2013-10-28,2013-09-27,amc,0.3000,0.2800,3.747200e+10,3.620176e+10,18.7842,18.4528,https://financialmodelingprep.com/stable/earni...,"{'date': '2013-10-28', 'symbol': 'AAPL', 'epsA...",d06c81eed09ce6341ed2fc94dfc05e49691d04e0f57274...,2025-10-27 07:39:43.975064+00:00
51,e96ffbcb-5752-4a62-936e-d4c9ba195d56,AAPL,2013,2,2013-07-23,2013-06-28,amc,0.2700,0.2600,3.532300e+10,3.466276e+10,15.2254,15.7325,https://financialmodelingprep.com/stable/earni...,"{'date': '2013-07-23', 'symbol': 'AAPL', 'epsA...",7ea6ebd708c5749bedf2ba9c3c9466c2aeb4ab05af4857...,2025-10-27 07:39:43.975064+00:00
52,5a656871-207f-4572-9ada-654a136a23de,AAPL,2013,1,2013-04-23,None,None,0.3600,0.3600,4.360300e+10,4.330020e+10,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2013-04-23', 'symbol': 'AAPL', 'epsA...",79a55dbe5a5bd3c4bba48dd8135cc5980a40281e6b37ec...,2025-10-27 07:39:43.975064+00:00
53,5644ec39-c859-4e81-a8d8-bb77acf5b9d8,AAPL,2012,4,2013-01-23,2012-12-28,amc,0.4900,0.4800,5.451200e+10,5.312845e+10,18.0275,16.0893,https://financialmodelingprep.com/stable/earni...,"{'date': '2013-01-23', 'symbol': 'AAPL', 'epsA...",08a65c902197a402f09a567f3032ad055793def0ba2b34...,2025-10-27 07:39:43.975064+00:00
54,45f68a47-9c3f-4fb5-889d-88f9b6e6a076,AAPL,2012,3,2012-10-25,2012-09-28,amc,0.3100,0.3100,3.596600e+10,3.625605e+10,22.0296,21.5714,https://financialmodelingprep.com/stable/earni...,"{'date': '2012-10-25', 'symbol': 'AAPL', 'epsA...",387b5babd9e2f826ac9ed09b71b02d4f172f32f68eb217...,2025-10-27 07:39:43.975064+00:00
55,12749941-c03e-4780-8089-bfcd3f13733c,AAPL,2012,2,2012-07-24,2012-06-29,amc,0.3300,0.3700,3.502300e+10,3.897296e+10,21.5654,20.5346,https://financialmodelingprep.com/stable/earni...,"{'date': '2012-07-24', 'symbol': 'AAPL', 'epsA...",a467ae5480f1ee4054e464b7fa4e698eac1ba8cfee919c...,2025-10-27 07:39:43.975064+00:00
56,13fc9b2b-c02e-4eba-b3f9-f7c5c6cc8fc9,AAPL,2012,1,2012-04-24,2012-03-30,amc,0.4400,0.3600,3.918600e+10,3.183862e+10,20.4179,21.7857,https://financialmodelingprep.com/stable/earni...,"{'date': '2012-04-24', 'symbol': 'AAPL', 'epsA...",19471acc5b45995464d9e5bafeeabc04c1743bb36fcb39...,2025-10-27 07:39:43.975064+00:00
57,0123fef7-d0d7-4358-9b85-f1a53488f3be,AAPL,2011,4,2012-01-24,2011-12-30,amc,0.5000,0.3600,4.633300e+10,3.393073e+10,15.2646,15.9521,https://financialmodelingprep.com/stable/earni...,"{'date': '2012-01-24', 'symbol': 'AAPL', 'epsA...",e8b49b8cc1663f2aa9e459b283c398adfa969f90485c8b...,2025-10-27 07:39:43.975064+00:00
58,7c6be269-909f-4dea-a74f-f92c833ee877,AAPL,2011,3,2011-10-18,None,None,0.2500,0.2600,2.827000e+10,2.966950e+10,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2011-10-18', 'symbol': 'AAPL', 'epsA...",f45d06680767d4388149538d21717c26174ab3cd0db16b...,2025-10-27 07:39:43.975064+00:00
59,15312c64-d4bf-4bcc-ad81-cf847ed748ca,AAPL,2011,2,2011-07-19,2011-06-24,amc,0.2800,0.2100,2.857100e+10,2.136390e+10,13.3500,13.8179,https://financialmodelingprep.com/stable/earni...,"{'date': '2011-07-19', 'symbol': 'AAPL', 'epsA...",5d2545d06b14a769ea9ba2a0b78c8d6f2b43e5cf14a61b...,2025-10-27 07:39:43.975064+00:00
60,8464cc96-e479-4830-8a66-72dd90aebefb,AAPL,2011,1,2011-04-20,2011-03-25,amc,0.2300,0.1900,2.466700e+10,2.087208e+10,12.0664,12.5249,https://financialmodelingprep.com/stable/earni...,"{'date': '2011-04-20', 'symbol': 'AAPL', 'epsA...",5db857ca8e3f2c7d1084efe1602dec939dd7033f0e8131...,2025-10-27 07:39:43.975064+00:00
61,69acb68e-058f-4ad3-85c4-61365994a7d5,AAPL,2010,4,2011-01-18,2010-12-24,amc,0.2300,0.1900,2.674100e+10,2.238105e+10,12.4457,12.1014,https://financialmodelingprep.com/stable/earni...,"{'date': '2011-01-18', 'symbol': 'AAPL', 'epsA...",aed76ec771c661314986097faf4354c4fb0b41c5274122...,2025-10-27 07:39:43.975064+00:00

In [2]:
# Query the `earnings_transcripts` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.earnings_transcripts ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/2797138568.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,event_id,tic,calendar_year,calendar_quarter,earnings_date,transcript,transcript_sha256,source,raw_json,raw_json_sha256,updated_at
0,a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f,AAPL,2025,2,2025-07-31,"Suhasini Chandramouli: Good afternoon, and wel...",3dbd9b4e2d9b271c169d08896e655157680e8276bd4014...,https://api.api-ninjas.com/v1/earningstranscri...,"{'date': '2025-07-31', 'year': '2025', 'ticker...",4a9aad7deb9a0c6c393b47303cfbb642861185d37f7bb8...,2025-10-27 07:39:49.033030+00:00
1,11cd1449-ba38-4626-b62f-65a1c512c7f4,AAPL,2025,1,2025-05-01,"Suhasini Chandramouli: Good afternoon, and wel...",8dee5e77fbc239c31063645f176cb6a03541331e0373e2...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '320193', 'date': '2025-05-01', 'year'...",f5993ffb3027c88dc1ab792d268ef51c6249a453b0c5f9...,2025-10-27 07:39:49.033030+00:00
2,03b75b38-db37-43f1-9c74-2dc181b770d5,AAPL,2024,4,2025-01-30,"Suhasini Chandramouli: Good afternoon, and wel...",abba2130960470fb89ec6dd28ea23fbeb60cff51be7654...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '320193', 'date': '2025-01-30', 'year'...",97b8dabae79e878d4a52f0e6461169985d73bbcb352256...,2025-10-27 07:39:49.033030+00:00
3,78673a05-435e-4b7e-bcf1-1de8cd83257f,AMZN,2025,2,2025-07-31,"Operator: Thank you for standing by. Good day,...",093f8732835493b26f1d23ff3e948fd5e9ab5d5c403419...,https://api.api-ninjas.com/v1/earningstranscri...,"{'date': '2025-07-31', 'year': '2025', 'ticker...",a4651ddb14e4e730e29fb2f57cd79dc47d70c86f18699f...,2025-10-27 07:39:49.033030+00:00
4,75ab83be-f654-433f-b3a7-a280c150a091,AMZN,2025,1,2025-05-01,"Operator: Thank you for standing by. Good day,...",a5823d2ecf46d583662d2e6b92f021be1e7c69c88ebe14...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '1018724', 'date': '2025-05-01', 'year...",28336f96ceeb1df705969994922fcf927250bcb20de5ee...,2025-10-27 07:39:49.033030+00:00
5,496cdc74-f685-498f-8d4d-3d90ca7b65ab,HOOD,2025,2,2025-07-30,Operator: Thank you to everyone for joining Ro...,49d9bbb8f7ed4cf2ac7c6ba4754749a79bf1dd366a1e7a...,https://api.api-ninjas.com/v1/earningstranscri...,"{'date': '2025-07-31', 'year': '2025', 'ticker...",bf1e068c54d935663fc27ccad7ff8b145971299f9a165d...,2025-10-27 07:39:49.033030+00:00
6,90d3c8c3-8bcd-4218-b299-c0be78d51d1e,HOOD,2025,1,2025-04-30,Operator: Thank you to everyone for joining Ro...,c3d8377cfeb2d5fe514767a895a4d3cda17e2e4ff0204a...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '1783879', 'date': '2025-04-30', 'year...",e0a6e0199b986ca7ad3312e5e65567c53dd4fcb6abc1b2...,2025-10-27 07:39:49.033030+00:00
7,1ee975fb-a5f5-4fa2-8fd8-45c1052493fd,NVDA,2025,2,2025-08-27,"Sarah: Good afternoon. My name is Sarah, and I...",389f300f6683c7c63d35c577bdf7d4167259fd665c1f04...,https://api.api-ninjas.com/v1/earningstranscri...,"{'date': '2025-08-27', 'year': '2026', 'ticker...",2eb12278174c96012f06e3c14d54f6df8907d08f2784dc...,2025-10-27 07:39:49.033030+00:00
8,80a35412-4e34-40bf-bc72-eb42088fac26,NVDA,2025,1,2025-05-28,"Sarah: Good afternoon. My name is Sarah, and I...",a1fadba73eb8d252dd28b16b3b4e6d1f4f14403d59da2d...,https://api.api-ninjas.com/v1/earningstranscri...,"{'date': '2025-05-28', 'transcript': 'Sarah: G...",54af7e30c174255d95cbba52f3ac16ae3a547d130e3e98...,2025-10-27 07:39:49.033030+00:00
9,f8de490f-4457-4254-b605-50771fdd3229,NVDA,2024,4,2025-02-26,"Christa: Good afternoon. My name is Christa, a...",2b1dbb5ba288230b9398f67a47e3a56fab3a01a3bb0d26...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '1045810', 'date': '2025-02-26', 'year...",f40369f9892f8d366d384606d339bdffdb690ea4fe996f...,2025-10-27 07:39:49.033030+00:00
10,2d7f3557-ea2e-467c-8a6f-1760b0b6aa79,NVDA,2024,3,2024-11-20,"Operator: Good afternoon. My name is Joel, and...",a8c6d85f9197127b9b61dab448eadae8d9e2ce6f9734fc...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '1045810', 'date': '2024-11-20', 'year...",d4d8f8719859f8a3e1902d90ff5b2b8996ba13684420ff...,2025-10-27 07:39:49.033030+00:00
11,3d7975f3-b730-4af0-bb3b-9265de3b4b4d,NVDA,2024,2,2024-08-28,Operator: Good afternoon. My name is Abby and ...,a2761d5d8ffcf351fbb8aa69ed77cf7a758c0fff7f4bee...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '1045810', 'date': '2024-08-28', 'year...",1bf81d29b94f2b4d4b2a8b47aeceaf3bb1eaaf331cdd70...,2025-10-27 07:39:49.033030+00:00
12,25a97050-8286-459b-9590-784570b4a145,NVDA,2024,1,2024-05-22,Operator: Good afternoon. My name is Regina an...,9f26904091beb059ee549ef463167fbc03e4fac07ffe82...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '1045810', 'date': '2024-05-22', 'year...",0a12c9690b6b11302c976ab388b5577c45e502d49f4476...,2025-10-27 07:39:49.033030+00:00
13,20ac01b1-ef21-4a02-ae04-a8df8eb53eb2,PLTR,2025,2,2025-08-04,Ana Soro: Good afternoon. I'm Ana Soro from Pa...,a98bbe43f761bfef9f3aeac1f9fa3762939cda295bb0ce...,https://api.api-ninjas.com/v1/earningstranscri...,"{'date': '2025-08-04', 'year': '2025', 'ticker...",ff4b86364033fc1ba2cd282e5271fe49702196d5a97f6a...,2025-10-27 07:39:49.033030+00:00
14,3b64b35a-f83f-4610-b42d-0f5f5df7b5c0,PLTR,2025,1,2025-05-05,Ana Soro: Good afternoon. I'm Ana Soro from Pa...,24ff3622cf379bd87c1ba73197cfc2d1416e40f95ce9f0...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '1321655', 'date': '2025-05-05', 'year...",3d4d09a2735670f7dc4670482cde619656e293c10ca8d7...,2025-10-27 07:39:49.033030+00:00
15,12e115db-8c79-40ca-a101-0efe3a87b559,SOFI,2025,2,2025-07-29,"Operator: Good morning or good afternoon all, ...",b7f1996f9fbdc79881b43381258fd09f635878d45ba430...,https://api.api-ninjas.com/v1/earningstranscri...,"{'date': '2025-07-29', 'year': '2025', 'ticker...",0ba89c53d69ea16074bf7aee9b0bf7d2efa91a16a9ad47...,2025-10-27 07:39:49.033030+00:00
16,9362e422-30e1-4801-9b58-f4dc614263ba,SOFI,2025,1,2025-04-29,"Operator: Good morning. My name is Adam, and I...",954619899a34c062710c2ff8bc34ad3f1412b693a9b0a4...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '1818874', 'date': '2025-04-29', 'year...",dcffb991bd51df03115e64c93813512b327b600e0412f4...,2025-10-27 07:39:49.033030+00:00
17,945c3048-35ba-4144-9a7b-25629d645089,TSLA,2025,3,2025-10-22,"Travis Axelrod: Good afternoon, everyone, and ...",fdd5600624518a71ac1c408ca2344d12586840e34f0a3d...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '1318605', 'date': '2025-10-22', 'year...",6e1e4491a9a5d2be7fd7244a813d18f55bc025613daba1...,2025-10-27 07:39:49.033030+00:00
18,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,TSLA,2025,2,2025-07-23,"Travis Axelrod: Good afternoon, everyone, and ...",9b659eb82fbd6032afe1c94c99373719ea1955cef27327...,https://api.api-ninjas.com/v1/earningstranscri...,"{'date': '2025-07-23', 'year': '2025', 'ticker...",a6e606af7e08937809acd5994ca89a331dcff9da12d9ec...,2025-10-27 07:39:49.033030+00:00
19,d8af0db7-2166-48a4-914f-2bb695d65978,TSLA,2025,1,2025-04-22,"Operator: Good afternoon, everyone, and welcom...",c9a7c36c936de533c2abf98f88539e675ac91a65c710cc...,https://api.api-ninjas.com/v1/earningstranscri...,"{'cik': '1318605', 'date': '2025-04-22', 'year...",bbf4c0099835cd11cf4644c0bea2fdc2f38d9affb98c6f...,2025-10-27 07:39:49.033030+00:00

In [ ]:
# Query the `earnings_transcript_chunks` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.earnings_transcript_chunks;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
# Query the `earnings_transcript_embeddings` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.earnings_transcript_embeddings;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [127]:
# Query the `earnings_transcript_analysis` table
conn = connect_to_db()
# display all columns
pd.set_option('display.max_columns', None)
if conn:
    query = "SELECT * FROM core.earnings_transcript_analysis;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/2698143443.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,inference_id,event_id,tic,calendar_year,calendar_quarter,sentiment,durability,performance_factors,past_summary,guidance_direction,revenue_outlook,margin_outlook,earnings_outlook,cashflow_outlook,growth_acceleration,future_outlook_sentiment,growth_drivers,future_summary,risk_mentioned,risk_impact,risk_time_horizon,risk_factors,risk_summary,mitigation_mentioned,mitigation_effectiveness,mitigation_time_horizon,mitigation_actions,mitigation_summary,transcript_sha256,updated_at
0,3128ce30-713d-427f-b3a0-46aade306c5f,a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f,AAPL,2025,2,1,2,"[record revenue, strong services growth, high customer satisfaction, tariff-related costs, increased shareholder returns]","Apple reported a strong June quarter with record revenue of $94 billion, up 10% year-over-year. The company highlighted, ""We're really proud of our results for the June quarter,"" and noted that services revenue reached an all-time high of $27.4 billion, up 13% year-over-year.",1,1,0,0,0,0,None,"[AI-related investments, expansion of Services, enterprise product deployment]","Management expects total company revenue to grow mid- to high single digits year-over-year for the September quarter. They stated, 'We expect Services revenue to grow at a year-over-year rate similar to what we reported in the June quarter.'",1,1,1,"[tariff rates, supply chain strategy]","Management highlighted significant uncertainties regarding tariff rates, stating, ""I would be careful about projecting based on the numbers from Q2 and Q3 because, one, we're uncertain of what the rates will be."" Additionally, they mentioned the impact of supply chain strategies on future performance, indicating potential headwinds.",1,1,2,"[investment in U.S. manufacturing, supply chain diversification]","Apple is actively addressing tariff-related costs by investing $500 billion in U.S. manufacturing and supply chain strategies. Tim Cook stated, ""we're always looking to do more"" and highlighted the commitment to strengthen the supply of vital materials and support American industry, which is part of their long-term strategy.",3dbd9b4e2d9b271c169d08896e655157680e8276bd401429d48d91331f9d11f8,2025-10-27 08:29:36.025933+00:00
1,a62f21db-65d8-4dec-aae1-181de1bb0058,11cd1449-ba38-4626-b62f-65a1c512c7f4,AAPL,2025,1,0,2,"[foreign exchange headwinds, strong Mac performance, record services revenue, high customer satisfaction, increased shareholder returns]","Apple reported a revenue of $95.4 billion, up 5% year-over-year, despite foreign exchange headwinds. Tim Cook noted, 'I'm quite pleased with the results from Q2,' highlighting strong performance in services and customer satisfaction.",1,1,0,0,0,0,None,"[enterprise product investment, Vision Pro integration, R&D investment growth, share repurchase program, dividend increase]","Management expects total company revenue to grow low to mid-single digits year-over-year in the June quarter. They stated, 'Given the continued confidence we have in our business now and into the future,' indicating an optimistic outlook.",1,1,1,"[tariff-related costs, supply chain risk, legal cases]","Management highlighted significant risks related to 'tariff-related costs' amounting to $900 million and ongoing 'legal cases' that could impact the Services business. Tim Cook noted, 'There's always risk in the supply chain,' emphasizing the complexities and uncertainties that could affect operations in the near term.",1,1,1,"[optimizing supply chain, engaging in tariff discussions, diversifying supply sources]","Management is actively addressing tariff-related costs by optimizing the supply chain and engaging in discussions regarding tariffs. Tim Cook stated, 'the operational team has done an incredible job around optimizing the supply chain and the inventory,' indicating a strong commitment to mitigating risks associated with tariffs and supply chain complexities.",8dee5e77fbc239c31063645f176cb6a03541331e0373e265a9019c2c7a9394de,2025-10-27 08:29:36.025933+00:00
2,1a0b860c-184c-40b7-a2f0-71e7bbed3246,1ee975fb-a5f5-4fa2-8fd8-45c1052493fd,NVDA,2025,2,1,2,"[record revenue, strong gaming sales, data center growth, automotive revenue increase, operating expense rise]","NVIDIA delivered a record quarter with total revenue of $46.7 billion, exceeding expectations. Key drivers included a 14% sequential increase in gaming revenue and a 56% year-over-year growth in data center revenue. Colette Kress stated, 'We delivered another record quarter while navigating what continues to be a dynamic external environment.'",1,1,1,1,1,1,None,"[data center infrastructure spend, Blackwell performance improvements, AI capability enhancements, annual rhythm for data centers, record-breaking year expectations]","NVIDIA expects significant growth in revenue and earnings, with total revenue projected at $54 billion for the next quarter. Jensen Huang stated, 'I expect next year to be a record-breaking year.'",1,1,1,"[geopolitical issues, supply chain uncertainties]","Management highlighted uncertainties regarding the shipment of H20s due to ongoing geopolitical issues, stating, ""we are still waiting on several of the geopolitical issues going back and forth between the governments and the companies."" This presents a major risk to revenue expectations in the near term.",1,1,2,"[expanding AI infrastructure, developing new AI products, navigating geopolitical issues]","Management is actively expanding its AI infrastructure and product offerings to mitigate risks associated with geopolitical uncertainties and supply chain challenges. Jensen Huang noted, ""we are really an AI infrastructure company and we are hoping to continue to contribute to growing this industry,"" emphasizing their commitment to innovation and growth despite external pressures.",389f300f6683c7c63d35c577bdf7d4167259fd665c1f049b778abdc96caaac2b,2025-10-27 08:29:36.025933+00:00
3,841dee65-1711-4506-91d9-e9ce8dc79b8f,80a35412-4e34-40bf-bc72-eb42088fac26,NVDA,2025,1,-1,0,"[export controls, inventory write-down, data center revenue growth, operating environment challenges, Blackwell ramp]","NVIDIA faced significant challenges this quarter, primarily due to new export controls impacting H20 revenue, resulting in a $4.5 billion charge. Despite a 69% year-over-year revenue increase, management noted, ""the new export controls on H20 did not provide a grace period to allow us to sell through our inventory.""",1,1,1,0,0,1,None,"[AI solutions expansion, Blackwell ramp-up, capital return program, infrastructure capabilities investment]","NVIDIA expects total revenue of $45 billion for Q2, with modest sequential growth across all platforms. Colette Kress stated, 'We expect better Blackwell profitability to drive modest sequential improvement in gross margins.'",1,1,1,"[export controls, China market limitations, inventory write-down]","NVIDIA faces significant risks due to stringent export controls impacting their ability to serve the Chinese market. Colette Kress noted, ""it's a bigger issue regarding the amount of the market that we will not be able to serve,"" indicating a major long-term challenge.",1,0,1,"[exploring limited ways to compete, evaluating options to supply compliant products, long-term purchase commitments for onshore manufacturing]","NVIDIA is actively exploring limited ways to compete in the Chinese market despite stringent export controls, with Jensen Huang stating, ""we are considering it. We're thinking about it."" Additionally, the company is evaluating options to supply data center products compliant with new regulations, indicating a moderate effectiveness in their mitigation strategy.",a1fadba73eb8d252dd28b16b3b4e6d1f4f14403d59da2d775609cc40d5b27f7d,2025-10-27 08:29:36.025933+00:00
4,65e03e56-b006-4152-9b0a-d3e53844246c,03b75b38-db37-43f1-9c74-2dc181b770d5,AAPL,2024,4,1,2,"[record revenue, strong demand, paid subscriptions growth, favorable mix, operating cash flow]","Management expressed a positive tone regarding past performance, highlighting an all-time high for revenue and strong growth in paid subscriptions. Kevan Parekh noted, 'We are very pleased to report an all-time high for revenue with December quarter revenue of $124.3 billion, up 4% year-over-year.'",0,1,0,0,0,0,None,"[services revenue growth, expansion in emerging markets, new product launches, enterprise deployments, favorable commodity environment]","Management expects total company revenue to grow low to mid-single-digits year-over-year, with services revenue anticipated to grow low-double-digits. Kevan Parekh stated, 'Despite that headwind, we expect our March quarter total company revenue to grow low to mid-single-digits year-over-year.'",1,1,0,"[regulatory burdens, China headwinds, foreign exchange headwinds]","Management highlighted significant risks including 'regulatory burdens on the business globally' and 'China headwinds' affecting performance. Additionally, they noted that 'as the dollar is strengthened significantly, we expect foreign exchange to be a headwind' impacting revenue.",1,1,1,"[expanding services offerings, capital return program, leveraging hybrid model for efficiency]","Management is actively expanding their services offerings, which includes new features and programs to enhance user experience, as seen with 'new games on Apple Arcade' and 'exciting new programming on Fitness Plus.' They also emphasized a prudent capital return program, returning over $30 billion to shareholders, and leveraging a hybrid model to drive efficiency, stating, 'innovation that drives efficiency is a good thing.'",abba2130960470fb89ec6dd28ea23fbeb60cff51be765477df987655a78d7aa5,2025-10-27 08:29:36.025933+00:00
5,50297efa-e9b6-40ba-8955-a98069cbd0b4,f8de490f-4457-4254-b605-50771fdd3229,NVDA,2024,4,-1,1,"[gross margin decline, higher operating expenses, Blackwell architecture ramp, strong automotive growth, record revenue in professional visualization]","NVIDIA experienced a challenging quarter with gross margins declining to 73%, attributed to the ramp of the Blackwell architecture and increased operating expenses. Colette Kress noted, 'As Blackwell ramps, we expect gross margins to be in the low seventies,' indicating concerns about current performance.",1,1,1,0,0,1,None,"[Blackwell architecture ramp, data center growth, gaming growth, AI software expansion, capital investment in data centers]","Management expects total revenue for Q1 to be around $43 billion, driven by strong demand and a significant ramp of Blackwell. Colette Kress stated, 'We expect sequential growth in both data center and gaming.'",1,1,1,[tariffs uncertainty],"Management highlighted the uncertainty surrounding tariffs, stating, 'Tariffs, at this point, it's a little bit of an unknown.' This uncertainty poses a major risk as it could impact broader semiconductor operations and costs in the mid-term.",1,1,1,"[increasing supply of Blackwell architecture, complying with export controls, improving gross margins through various configurations]","Management is actively increasing the supply of the Blackwell architecture to meet strong demand, stating, 'Blackwell production is in full gear across multiple configurations, and we are increasing supply quickly.' They are also committed to complying with export controls and are exploring ways to improve gross margins over time, indicating, 'We have many different configurations as well on Blackwell that will be able to help us do that.'",2b1dbb5ba288230b9398f67a47e3a56fab3a01a3bb0d260fc497942f26e91f95,2025-10-27 08:29:36.025933+00:00
6,4a62b355-9067-45dc-b90d-53f1d5b602a5,2d7f3557-ea2e-467c-8a6f-1760b0b6aa79,NVDA,2024,3,1,2,"[record quarter, strong demand, gaming revenue growth, data center revenue increase, supply constraints]","NVIDIA reported a strong Q3 with revenue of $35.1 billion, up 17% sequentially and 94% year-on-year, driven by exceptional demand in data centers and gaming. Colette Kress stated, 'Q3 was another record quarter. We continued to deliver incredible growth.'",1,1,1,0,0,1,None,"[Blackwell product ramp, Hopper architecture demand, data center expansion, AI infrastructure development]","NVIDIA expects total revenue for Q4 to be approximately $37.5 billion, driven by strong demand for Blackwell products. Colette Kress stated, 'we are on track to exceed our previous Blackwell revenue estimate of several billion dollars as our visibility into supply continues to increase.'",1,1,0,"[supply constraints, China business uncertainty]","Management highlighted significant supply constraints impacting revenue, stating, 'demand is greatly exceed supply.' Additionally, there are uncertainties regarding the China business due to potential tariff changes, with Jensen noting, 'have you gotten any sense, or any conversations about tariffs, or anything with regard to your China business?'",1,1,1,"[compliance with export controls, building AI factories in India, partnerships with major companies for AI initiatives]","Management is actively addressing risks related to export controls and competition in China by ensuring compliance while expanding operations in other regions. Colette Kress stated, 'We will continue to comply with export controls while serving our customers,' and highlighted partnerships with companies like Tata Communications and SoftBank to enhance AI capabilities in India and Japan.",a8c6d85f9197127b9b61dab448eadae8d9e2ce6f9734fcdf34bdb9be544ee791,2025-10-27 08:29:36.025933+00:00
7,a4996496-3bb1-4860-aa67-8cb46831654c,12e115db-8c79-40ca-a101-0efe3a87b559,SOFI,2025,2,1,2,"[record revenue growth, strong member growth, increased fee-based revenue, capital-light nonlending, record contribution profit]","SoFi had an excellent second quarter, achieving a record revenue of $858 million, up 44% year-over-year. Key drivers included 'strong member growth' and 'increased fee-based revenue,' with management noting, 'We added a record 850,000 new members in Q2.'",1,1,1,1,1,1,None,"[increased member growth, adjusted net revenue growth, investment in engineering and product design, expansion of Invest business, capital-light nonlending revenue]","Management raised their 2025 guidance, expecting over 30% year-over-year growth in adjusted net revenue and confident in achieving a compounded annual revenue growth of 25% from 2023 to 2026. Christopher Lapointe stated, 'We feel really good about it' and 'we remain even more confident in the aggregate outlook.'",1,1,1,"[interest rates, regulatory climate]","Management highlighted that there are uncontrollable factors affecting the business, specifically mentioning 'interest rates' as a significant challenge. Additionally, they noted that 'the implications for large banks and their tech decisions based on recent regulatory climate' could impact their outlook.",1,1,1,"[launching new personal loan products, refinancing solutions for student loans, home equity loan offerings, investments in technology and innovation]","Management is actively addressing risks associated with interest rates and market conditions by launching new products such as personal loans for prime credit card customers and refinancing solutions for student loans. They noted, 'Our home equity business... is obviously benefiting from rates being high,' indicating a strategic focus on adapting to the current environment. Additionally, they are investing in technology to enhance operational efficiency and customer experience.",b7f1996f9fbdc79881b43381258fd09f635878d45ba430b34bc80695ab181c85,2025-10-27 08:29:36.025933+00:00
8,dfa2ac06-0b10-47f8-8dd7-9aa20c5fa5ec,945c3048-35ba-4144-9a7b-25629d645089,TSLA,2025,3,1,2,"[record deliveries, strong financial metrics, improvements in margins, increased competition, tariff impacts]","Q3 was a strong quarter with record deliveries and financial metrics, driven by customer confidence and operational improvements. As Vaibhav Taneja stated, 'We set new records not just for deliveries and deployments, but also around a range of financial metrics.'",1,1,1,1,1,1,None,"[AI initiatives, robotaxi expansion, increased production capacity, new Model Y variants, energy storage deployments]","Management expresses optimism about future growth, highlighting plans for AI initiatives and robotaxi expansion. They stated, 'we are on pace to continue expanding further' and 'we expect to shift in as we change the way transportation is considered.'",1,1,1,"[tariff impacts, increased competition]","Management highlighted significant headwinds due to 'the increase in competition and tariffs,' with total tariff impacts exceeding $400 million for Q3. This poses a major risk to the business, particularly as they rely on sales procured from China.",1,1,1,"[ramping up production at the Shanghai factory, improving cost efficiency through restructuring, expanding robotaxi operations]","Management is actively addressing tariff impacts by ramping up production at the Shanghai factory to supply non-US demand, which helps mitigate tariff costs. Vaibhav Taneja noted, 'as the ramp of mega factory Shanghai is happening, this is helping us avoid tariffs.' Additionally, they are restructuring to improve efficiency and reduce costs, stating, 'the largest increase included in restructuring and other related to certain actions undertaken to reduce cost and improve efficiency.'",fdd5600624518a71ac1c408ca2344d12586840e34f0a3d7f33d92bf53e953276,2025-10-27 08:29:36.025933+00:00
9,e09d6797-fbcb-4701-bb89-3d6d347593b3,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,TSLA,2025,2,-1,0,"[tariff impacts, operating expenses growth, improved automotive revenue, FSD adoption increase, challenges in storage business]","Tesla faced significant challenges in Q2, particularly from tariff impacts and increased operating expenses. Despite a 19% sequential increase in automotive revenue, management noted, ""we will see shifts in demand and profitability"" due to external pressures.",-1,0,0,0,0,0,None,"[AI investments, new affordable models, energy storage deployment, U.S. manufacturing expansion, FSD adoption increase]","Management expressed caution regarding potential challenges in the upcoming quarters due to tariff impacts and the loss of incentives. Elon Musk noted, 'we could have a few rough quarters,' but emphasized a strong future vision for Tesla.",1,1,1,"[tariff impacts, negative impacts of the bill]",Tesla is facing significant challenges due to 'the negative impacts of the bill and tariffs.' The management noted that these factors will lead to 'shifts in demand and profitability' in the near term.,1,0,1,"[pricing adjustments, investment in AI and robotics, production ramp-up of new models]","Tesla is addressing the challenges posed by tariffs and the expiration of EV credits through pricing adjustments and ramping up production of new models. Vaibhav Taneja stated, 'we are doing our best to try and manage through this,' indicating a moderate approach to mitigating these impacts in the near term.",9b659eb82fbd6032afe1c94c99373719ea1955cef2732743ac26d95efa050b01,2025-10-27 08:29:36.025933+00:00

In [9]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.news_analysis;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_51229/3960197957.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,inference_id,event_id,tic,url,title,content,publisher,published_at,category,event_type,time_horizon,duration,impact_magnitude,affected_dimensions,sentiment,raw_json_sha256,updated_at
0,2356ab42-7745-4724-afb6-5804a2c3ef82,12c723fc-8da1-450f-ad0f-4ba80edbf362,NVDA,https://www.youtube.com/shorts/8u_JN1K_AkQ,Nvidia CEO Outing Heats Up Korea's Fried Chick...,A viral moment of Nvidia's Jensen Huang having...,Bloomberg Markets and Finance,2025-11-01 04:09:50,noise,irrelevant,NaN,None,NaN,None,NaN,0c700932d93500cac096be90fee3ef10d4d142a3f19708...,2025-11-01 09:26:28.073198+00:00
1,df53ffea-7a15-4df8-8ba8-c01eaf262119,313af986-5ee4-4abe-8ccb-c69971d61f82,NVDA,https://venturebeat.com/security/crowdstrike-n...,CrowdStrike & NVIDIA's open source AI gives en...,Every SOC leader knows the feeling: drowning i...,VentureBeat,2025-10-31 18:49:49,noise,irrelevant,NaN,None,NaN,None,NaN,013b29b27b28d53dafad8e480a5430ba7316e7e2d0846c...,2025-11-01 09:26:28.073198+00:00
2,cfeb3359-6e47-4417-821a-f7369b9f42bc,fdb94cac-9d2c-49d0-bc58-1720bd986a70,NVDA,https://www.wsj.com/finance/stocks/the-score-c...,"The Score: Caterpillar, Nvidia, Meta and More ...",Here are some of the major companies whose sto...,WSJ,2025-10-31 17:17:00,noise,irrelevant,NaN,None,NaN,None,NaN,a25f003323d0c183c40445dfc2f0ab4c2c64d6d88f7d88...,2025-11-01 09:26:28.073198+00:00
3,427479bc-2c3c-4c18-ba48-f990bead1c7c,fd0ae3b4-f533-4769-89fe-fdc7bd904ac7,NVDA,https://www.youtube.com/watch?v=gVSBhK5cvYM,"Friday's Final Takeaways: NVDA's Big Week, Gol...",On the final day of the trading week and Octob...,Schwab Network,2025-10-31 17:00:57,market_perception,media_narrative,0.0,1 week,0.0,[sentiment],0.0,ba57e0da8768ed3c040a94bf5cbcfbcc2739cf267fa556...,2025-11-01 09:26:28.073198+00:00
4,5caae53b-1ff6-4250-8b86-d94089e339c0,1bee64bb-65b6-4f6e-b688-61ab7e04ec6a,NVDA,https://www.youtube.com/watch?v=N5cPFfufV6o,Nvidia's China Future Remains Unclear,"Amy Webb, CEO of Future Today Strategy Group, ...",Bloomberg Technology,2025-10-31 15:29:59,market_perception,media_narrative,0.0,1 week,-1.0,[sentiment],-1.0,8cb7912625f57c208d36c8c85d7a6dda353a1b53af6776...,2025-11-01 09:26:28.073198+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
694,ea94fcb0-7307-4e06-bcf0-9baf8e8b853e,894de7e4-faea-4dfb-aef6-0a42ff78bf78,HOOD,https://invezz.com/news/2025/09/25/robinhood-s...,Robinhood stock price has surged: time to buy ...,Robinhood stock price has been in a strong upt...,Invezz,2025-09-25 12:03:00,technical,price_movement,0.0,1 week,0.0,[sentiment],1.0,f57d656967c584f6c7ab9d3ac9e9682478589d14425d1f...,2025-11-01 09:26:28.073198+00:00
695,e89c3276-386c-4c5f-9980-1ac1468dc8a1,6e14d309-0538-49c3-b540-0fa3dc066780,HOOD,https://www.zacks.com/stock/news/2756951/is-it...,Is It Worth Investing in Robinhood Markets (HO...,Investors often turn to recommendations made b...,Zacks Investment Research,2025-09-25 10:31:22,market_perception,media_narrative,0.0,1 week,-1.0,[sentiment],0.0,b26808b28481ffa5b9e4b686917013095762d06fc8362d...,2025-11-01 09:26:28.073198+00:00
696,1c502cae-8759-4bee-bd6c-4313c0019b00,90b64875-6bbe-4d32-8a9d-be1a7f98c45b,HOOD,https://www.zacks.com/stock/news/2756599/hood-...,"HOOD Launches ""Asset Match"" Through TradePMR: ...","Robinhood rolls out ""Asset Match"" via TradePMR...",Zacks Investment Research,2025-09-24 13:31:05,fundamental,other,1.0,3 months,0.0,"[revenue, sentiment]",0.0,edb94611205f6482ace387e2972550f6a78ee82bdeb8be...,2025-11-01 09:26:28.073198+00:00
697,a40b84fc-a6e3-4f0d-afa6-b126114295b8,4c1f5a1b-21b8-47ae-a204-3eb1e94b2ad5,HOOD,https://www.cnbc.com/2025/09/24/day-trading-is...,Day trading is about to get easier for smaller...,Regulators are moving to dismantle one of the ...,CNBC,2025-09-24 13:21:20,fundamental,regulatory_legal,1.0,3 months,1.0,"[revenue, sentiment]",1.0,2db2ed702821fb52ccac1da1de05092199cb59ee5c2bdc...,2025-11-01 09:26:28.073198+00:00
698,156bc856-a306-42f0-8684-c76e082277e8,0bebbb34-613a-483a-ba70-d63ad753731f,HOOD,https://www.zacks.com/stock/news/2756228/inves...,"Investors Heavily Search Robinhood Markets, In...",Robinhood Markets (HOOD) has been one of the s...,Zacks Investment Research,2025-09-24 10:01:01,market_perception,media_narrative,0.0,1 week,0.0,[sentiment],0.0,a34c3d786f2da99beda825734ee700e4d93142ff25734c...,2025-11-01 09:26:28.073198+00:00

In [12]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.news_analysis WHERE tic = 'TSLA' ORDER BY updated_at desc LIMIT 5;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_51229/1035885731.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,inference_id,event_id,tic,url,title,content,publisher,published_at,category,event_type,time_horizon,duration,impact_magnitude,affected_dimensions,sentiment,raw_json_sha256,updated_at
0,047bc5e4-3a15-411e-af17-64362492b3a6,f0b0a3ba-29eb-447e-bbe6-e86a4e188b96,TSLA,https://www.investors.com/news/tesla-stock-ai-...,"Tesla, AI Plays Lead Five Stocks Near Buy Poin...","Tesla leads five stocks near buy points, inclu...",Investors Business Daily,2025-10-25 08:00:56,market_perception,media_narrative,0,1 week,0,[sentiment],1,ed68a640248db152f42079a7653a7229f88720b6962e4f...,2025-11-01 09:26:28.073198+00:00
1,296b4418-f04f-4483-9227-9d23934e80c5,329d5562-8888-49a5-b2d3-a13966b2ff39,TSLA,https://247wallst.com/investing/2025/10/30/tes...,Tesla Is Worth 28 Times Ford,Ford Motor Co. (NYSE: F) posted a strong quart...,24/7 Wall Street,2025-10-30 09:15:55,market_perception,media_narrative,0,1 week,-1,[sentiment],0,1af6ecb78f7e1de29e3a694f340e8661c89c9212cb4ef8...,2025-11-01 09:26:28.073198+00:00
2,ba46980c-983b-4674-8779-1d6520bc03ff,0c30d0e7-17ed-4c85-8a31-ea0b9d598d73,TSLA,https://seekingalpha.com/article/4836517-tesla...,Tesla: Musk's Potential Trillion-Dollar Pay Pa...,Musk's $1T performance award aligns execution ...,Seeking Alpha,2025-10-31 15:43:05,market_perception,media_narrative,2,long_term,0,[sentiment],1,ef3711cac26744064d66c782e1135bddd33d4b2557e470...,2025-11-01 09:26:28.073198+00:00
3,540e81f1-f439-44b7-90b4-1645d0e7302d,ed75e7a1-68be-4c26-94a1-ce44872ccc85,TSLA,https://www.fool.com/investing/2025/11/01/5-th...,5 Things Investors Need to Know After Tesla's ...,Tesla posted its first quarter of sales growth...,The Motley Fool,2025-11-01 03:41:00,fundamental,earnings_guidance,1,3 months,0,"[revenue, profit]",0,b99b902bbfd85825dd53db0e9eb2bd6d8703883d16e6cb...,2025-11-01 09:26:28.073198+00:00
4,5f7dc49f-8e56-4f3d-b7b7-7b6aa3f970d8,44306a3b-5406-45c1-9c71-629af8dfedf0,TSLA,https://247wallst.com/investing/2025/10/27/tes...,Tesla's Next Huge Challenge,Tesla Inc. (NASDAQ: TSLA) CEO Elon Musk likes ...,24/7 Wall Street,2025-10-27 09:05:32,market_perception,media_narrative,0,1 week,-1,[sentiment],0,a9dba68d1298ba6ec4f906b86a26cb5f125a0e9a40712a...,2025-11-01 09:26:28.073198+00:00

In [ ]:
# Display the max width columns for better readability
pd.set_option('display.max_colwidth', None)
len(df[df['impact_magnitude']==0][['tic', 'published_at', 'title', 'content','impact_magnitude', 'category', 'event_type', 'sentiment']])

In [ ]:
len(df)

In [ ]:
# Query the `news` table
conn = connect_to_db()
if conn:
    query = """
        WITH news_summary AS (
        SELECT
            n.tic,
            EXTRACT(YEAR FROM n.published_at)::INT AS year,
            EXTRACT(MONTH FROM n.published_at)::INT AS month,
            COUNT(*) AS record_count
        FROM core.news n
        GROUP BY n.tic, year, month
        )
        SELECT n.tic, n.year, n.month, n.record_count,
            sp.name, sp.sector, sp.industry, sp.short_summary
        FROM news_summary n
        JOIN core.stock_profiles AS sp
            ON n.tic = sp.tic
        ORDER BY n.tic, n.year, n.month;
        """
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = "SELECT tic, title, content, " \
    "       time_horizon, impact_magnitude, sentiment FROM core.news_analysis;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [116]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.catalyst_master;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/1130310606.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,catalyst_id,tic,date,catalyst_type,title,summary,state,sentiment,time_horizon,impact_magnitude,certainty,impact_area,mention_count,event_ids,created_at,updated_at
0,9191f310-c7a6-4caa-bb1d-63d4117a4de1,AAPL,2025-01-30,guidance_outlook,Apple FX headwind lowers revenue outlook,"Management flags a stronger dollar as a headwind, estimating a 2.5 percentage point drag to revenue year-over-year and refining the upcoming quarter's guidance.",updated,-1,1,0,confirmed,revenue,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-03 07:41:46.184009+00:00,2025-12-03 07:41:46.214289+00:00

In [72]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.catalyst_master WHERE tic = 'TSLA' ORDER BY date desc, updated_at desc;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/552265995.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

Empty DataFrame
Columns: [catalyst_id, tic, date, catalyst_type, title, summary, state, sentiment, time_horizon, impact_magnitude, certainty, impact_area, mention_count, event_ids, created_at, updated_at]
Index: []

In [123]:
# Query the `news_analysis` table
conn = connect_to_db()
# display max width columns for better readability
pd.set_option('display.max_colwidth', None)
if conn:
    query = "SELECT * FROM core.catalyst_master;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/2800078175.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,catalyst_id,tic,date,catalyst_type,title,summary,state,sentiment,time_horizon,impact_magnitude,certainty,impact_area,mention_count,event_ids,created_at,updated_at
0,cc16c149-d426-4c35-8bc5-13ed61f94831,AAPL,2025-01-30,guidance_outlook,Apple to update capital return program in March quarter,"Apple indicates it will update its capital return program when it reports results for the March quarter, signaling potential changes to shareholder returns.",announced,0,1.0,0,planned,cashflow,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-03 07:54:15.628423+00:00,2025-12-03 07:54:15.628423+00:00
1,822247e0-dced-4886-83ed-dfcbceffc117,AAPL,2025-01-30,guidance_outlook,Apple reiterates March quarter gross margin 46.5-47.5%,"Management reaffirms the March quarter gross margin guidance of 46.5%-47.5%, indicating that FX headwinds are contemplated within the range.",updated,1,1.0,0,confirmed,margin,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-03 07:54:15.628423+00:00,2025-12-03 07:54:15.651160+00:00
2,8431a64e-fe4e-43ea-8515-b5b71c287183,AAPL,2025-01-30,product_initiative,Apple Announces April Language Rollouts in Q3,"Apple plans a new phase of language feature rollouts in April, aligned with its Q3 timeline. This initiative signals expansion of language capabilities across its platforms.",announced,0,1.0,0,planned,technology,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-03 07:56:46.573825+00:00,2025-12-03 07:56:46.573825+00:00
3,7cd96eea-2df8-4cfd-b159-0f799acb4ab1,AAPL,2025-01-30,product_initiative,"Apple Expands UAE Stores, Launches Saudi Online Store",Apple plans geographic expansion by adding a fifth UAE store and launching an online store in Saudi Arabia this summer.,announced,1,1.0,1,planned,market_expansion,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-03 07:56:46.573825+00:00,2025-12-03 07:56:46.573825+00:00
4,6862497a-70da-4a67-be86-d76b3fe42c8c,AAPL,2025-01-30,cost_efficiency,Apple guides 46.5%-47.5% gross margin,"Apple issues forward-looking gross margin guidance of 46.5%-47.5%, signaling improved profitability. The margin outlook reflects ongoing cost efficiency efforts.",announced,1,1.0,1,planned,margin,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-03 08:00:30.533664+00:00,2025-12-03 08:00:30.533664+00:00
5,16bbe6d3-354d-4b91-a7f4-00ee28aa19b5,AAPL,2025-01-30,cost_efficiency,Apple eyes further gross margin upside with AI devices,"The snippet asks about potential additional gross margin improvements from the product side, including AI-related devices, implying upside beyond current guidance.",announced,0,NaN,0,None,margin,0,[],2025-12-03 08:00:30.533664+00:00,2025-12-03 08:00:30.533664+00:00
6,6e80027c-1a90-4098-9737-66f6fe556e1a,AAPL,2025-01-30,capital_actions,Apple declares $0.25 per share dividend,"Apple's board declared a cash dividend of $0.25 per share, payable February 13, 2025 to shareholders of record February 10, 2025. This strengthens shareholder returns and reduces cash on payout.",announced,1,1.0,-1,confirmed,shareholder_return,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-03 08:02:57.734982+00:00,2025-12-03 08:02:57.734982+00:00
7,9784224d-5977-463e-a744-c22539e30b17,AAPL,2025-01-30,demand_trends,Apple accounts hit all-time highs; paid users up double-digits,"Apple reported stronger demand signals as both transacting and paid accounts reached new all-time highs. Paid accounts grew double-digit year-over-year, signaling expanding user engagement.",announced,1,1.0,1,confirmed,demand,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-03 08:07:35.420370+00:00,2025-12-03 08:07:35.420370+00:00
8,18e4007f-137d-4683-9821-66ae672db897,AAPL,2025-01-30,demand_trends,China demand stabilizes; QoQ path normalizes into March,A China inventory clearing event suggests a more normal quarter-on-quarter demand progression into the March quarter for Greater China.,updated,0,1.0,0,rumor,region,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-03 08:07:35.420370+00:00,2025-12-03 08:07:35.436184+00:00
9,3cee3639-df98-413b-a675-9d2a5690ce02,AAPL,2025-01-30,risk_event,FX headwind trims Apple revenue by 2.5pp,"Apple reiterates that foreign exchange headwinds will reduce revenue by about 2.5 percentage points year over year, signaling a near-term earnings impact.",updated,-1,NaN,0,planned,earnings,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-03 08:09:51.251997+00:00,2025-12-03 08:09:51.263125+00:00

In [122]:
# Query the `news_analysis` table
conn = connect_to_db()
# display max width columns for better readability
pd.set_option('display.max_colwidth', None)
# display all columns
pd.set_option('display.max_columns', None)
if conn:
    query = "SELECT * FROM core.catalyst_versions;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/4028825008.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,event_id,chunk_id,catalyst_id,tic,date,catalyst_type,title,summary,evidence,state,sentiment,time_horizon,impact_magnitude,certainty,impact_area,is_valid,rejection_reason,ingestion_batch,source_type,source,url,raw_json_sha256,updated_at
0,03b75b38-db37-43f1-9c74-2dc181b770d5,9,822247e0-dced-4886-83ed-dfcbceffc117,AAPL,2025-01-30,guidance_outlook,Apple guides March quarter revenue and margins higher,"Apple provided updated guidance for the March quarter, projecting total revenue to grow low-to-mid single digits year-over-year, services revenue to grow low double digits, and gross margin of 46.5%-47.5%.","""we expect March quarter total company revenue to grow low to mid-single-digits year-over-year. We expect services revenue to grow low-double-digits year-over-year. We expect gross margin to be between 46.5% and 47.5%""",announced,1,1,0,confirmed,revenue,0,Evidence is non-contiguous; quotes non-adjacent sentences from the source.,quarterly,earnings_transcript,https://api.api-ninjas.com/v1/earningstranscript?ticker=AAPL&year=2025&quarter=1,None,97b8dabae79e878d4a52f0e6461169985d73bbcb35225680aac2dd4c2993f853,2025-12-03 07:54:15.628423+00:00
1,03b75b38-db37-43f1-9c74-2dc181b770d5,8,cc16c149-d426-4c35-8bc5-13ed61f94831,AAPL,2025-01-30,guidance_outlook,Apple to update capital return program in March quarter,"Apple indicates it will update its capital return program when it reports results for the March quarter, signaling potential changes to shareholder returns.","As usual, we will provide an update to our capital return program when we report results for the March quarter.",announced,0,1,0,planned,cashflow,1,None,quarterly,earnings_transcript,https://api.api-ninjas.com/v1/earningstranscript?ticker=AAPL&year=2025&quarter=1,None,97b8dabae79e878d4a52f0e6461169985d73bbcb35225680aac2dd4c2993f853,2025-12-03 07:54:15.628423+00:00
2,03b75b38-db37-43f1-9c74-2dc181b770d5,44,822247e0-dced-4886-83ed-dfcbceffc117,AAPL,2025-01-30,guidance_outlook,Apple guides March quarter gross margin 46.5-47.5%,"Management reiterates the March quarter gross margin guidance of 46.5%-47.5%, signaling a strong margin outlook.","""we're guiding to 46.5% to 47.5%... we think it's a very, very strong guide for gross margin.""",updated,1,1,1,confirmed,margin,1,None,quarterly,earnings_transcript,https://api.api-ninjas.com/v1/earningstranscript?ticker=AAPL&year=2025&quarter=1,None,97b8dabae79e878d4a52f0e6461169985d73bbcb35225680aac2dd4c2993f853,2025-12-03 07:54:15.650160+00:00
3,03b75b38-db37-43f1-9c74-2dc181b770d5,73,822247e0-dced-4886-83ed-dfcbceffc117,AAPL,2025-01-30,guidance_outlook,Apple reiterates March quarter gross margin 46.5-47.5%,"Management reaffirms the March quarter gross margin guidance of 46.5%-47.5%, indicating that FX headwinds are contemplated within the range.","""we're going to have a foreign exchange headwind heading into the March quarter, but we figured that's contemplated in the guidance range that we gave, the 46.5% to 47.5%.""",updated,1,1,0,confirmed,margin,1,None,quarterly,earnings_transcript,https://api.api-ninjas.com/v1/earningstranscript?ticker=AAPL&year=2025&quarter=1,None,97b8dabae79e878d4a52f0e6461169985d73bbcb35225680aac2dd4c2993f853,2025-12-03 07:54:15.651160+00:00

In [124]:
# Query the `news_analysis` table
conn = connect_to_db()
# display max width columns for better readability
pd.set_option('display.max_colwidth', None)
# display all columns
pd.set_option('display.max_columns', None)
if conn:
    query = "SELECT * FROM core.catalyst_versions WHERE catalyst_id = '3cee3639-df98-413b-a675-9d2a5690ce02' AND event_id = '03b75b38-db37-43f1-9c74-2dc181b770d5' ;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/3924320952.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,event_id,chunk_id,catalyst_id,tic,date,catalyst_type,title,summary,evidence,state,sentiment,time_horizon,impact_magnitude,certainty,impact_area,is_valid,rejection_reason,ingestion_batch,source_type,source,url,raw_json_sha256,updated_at
0,03b75b38-db37-43f1-9c74-2dc181b770d5,8,3cee3639-df98-413b-a675-9d2a5690ce02,AAPL,2025-01-30,risk_event,FX headwind trims Apple revenue by 2.5pp,"Apple reiterates that foreign exchange headwinds will reduce revenue by about 2.5 percentage points year over year, signaling a near-term earnings impact.","""we expect foreign exchange to be a headwind and to have a negative impact on revenue of about 2.5 percentage points on a year-over-year basis.""",updated,-1,None,0,planned,earnings,1,None,quarterly,earnings_transcript,https://api.api-ninjas.com/v1/earningstranscript?ticker=AAPL&year=2025&quarter=1,None,97b8dabae79e878d4a52f0e6461169985d73bbcb35225680aac2dd4c2993f853,2025-12-03 08:09:51.263125+00:00
1,03b75b38-db37-43f1-9c74-2dc181b770d5,9,3cee3639-df98-413b-a675-9d2a5690ce02,AAPL,2025-01-30,risk_event,FX headwind trims Apple revenue by 2.5pp,"Apple projects a foreign exchange headwind that will reduce revenue about 2.5 percentage points year over year, signaling a near-term earnings impact.","""we expect foreign exchange to be a headwind and to have a negative impact on revenue of about 2.5 percentage points on a year-over-year basis.""",announced,-1,None,0,planned,earnings,1,None,quarterly,earnings_transcript,https://api.api-ninjas.com/v1/earningstranscript?ticker=AAPL&year=2025&quarter=1,None,97b8dabae79e878d4a52f0e6461169985d73bbcb35225680aac2dd4c2993f853,2025-12-03 08:09:51.251997+00:00

In [45]:
# Query the `news_analysis` table
conn = connect_to_db()
# display max width columns for better readability
pd.set_option('display.max_colwidth', None)
if conn:
    query = "SELECT * FROM core.catalyst_master WHERE tic = 'AAPL';"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/2441999067.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,catalyst_id,tic,date,catalyst_type,title,summary,state,sentiment,time_horizon,impact_magnitude,certainty,impact_area,mention_count,event_ids,created_at,updated_at
0,04dded53-27cf-4578-b9ff-ea619b374b62,AAPL,2025-01-30,guidance_outlook,March quarter gross margin guidance updated; FX headwinds,"Updated March quarter guidance; FX headwinds are expected to pressure revenue by about 2.5 percentage points YoY, offset by costs and services mix.",updated,1,1.0,0,planned,margin,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-02 21:24:18.177727+00:00,2025-12-02 21:24:18.205879+00:00
1,164ff695-4c90-4f6c-803e-fd5a10b59e7f,AAPL,2025-01-30,product_initiative,Apple Intelligence Language Rollouts in April,Apple Intelligence language rollouts planned for April (Q3). Early results show markets with prior Apple Intelligence rollouts performed better year-over-year in Q1.,announced,1,1.0,0,confirmed,technology,0,[],2025-12-02 21:26:52.600882+00:00,2025-12-02 21:26:52.600882+00:00
2,ee560e74-4f6c-4975-8371-8f4bb184291b,AAPL,2025-01-30,product_initiative,Airline luggage tracking via Find My Service announced,"Apple announced a Find My Service integration enabling AirTag-equipped luggage location sharing with major airlines, and outlined retail expansion plans including a fifth UAE store and bringing the online store to Saudi Arabia this summer, with flagship stores in Saudi Arabia opening from 2026.",announced,1,1.0,0,confirmed,market_expansion,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-02 21:26:52.600882+00:00,2025-12-02 21:26:52.600882+00:00
3,f57cf57d-af7c-4151-9b93-f623d175f8f0,AAPL,2025-01-30,product_initiative,Q1 Product Launches to Boost Revenue,"Apple indicates multiple product launches are planned for Q1, which should support gross margin through favorable mix and higher volume. The company notes Pro products' appeal and expects FX headwinds in March reflected in guidance.",announced,1,1.0,0,confirmed,revenue,0,[],2025-12-02 21:26:52.600882+00:00,2025-12-02 21:26:52.600882+00:00
4,47b1ce9e-cd02-4bdb-bab9-3d4a89ccfdc6,AAPL,2025-01-30,capital_actions,Dividend Declared: $0.25 per Share,"Apple declared a cash dividend of $0.25 per share, payable Feb 13, 2025.",announced,1,0.0,-1,confirmed,shareholder_return,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-02 21:31:04.974605+00:00,2025-12-02 21:31:04.974605+00:00
5,b1421838-b123-4d6c-9d2f-a0dda2d3bc1d,AAPL,2025-01-30,demand_trends,Apple Services Demand Strengthening,Apple reported new all-time highs in transacting and paid accounts with double-digit YoY growth in paid accounts and subscriptions. Paid subscriptions also grew double-digits.,announced,1,1.0,1,confirmed,demand,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-02 21:34:38.800210+00:00,2025-12-02 21:34:38.800210+00:00
6,bbc82f51-f6bc-44a7-96d1-b214b2056dda,AAPL,2025-01-30,demand_trends,Launch-Driven Product Demand Strengthening,Launch-driven demand uplift from new products and favorable mix is accelerating momentum into the March quarter.,announced,1,1.0,1,confirmed,demand,0,[],2025-12-02 21:34:38.800210+00:00,2025-12-02 21:34:38.800210+00:00
7,9651ec84-fb78-4c81-8aff-ac905efb28e1,AAPL,2025-01-30,demand_trends,Pricing Range Could Boost Demand,The discussion explores price sensitivity and whether a broader pricing range across Apple’s products could unlock demand gains and extend market share.,announced,1,1.0,0,rumor,pricing,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-02 21:34:38.800210+00:00,2025-12-02 21:34:38.800210+00:00
8,f0f49d78-a805-4dd4-9851-066e9463110a,AAPL,2025-01-30,demand_trends,Greater China Demand Improving,China demand is expected to normalize with quarter-on-quarter improvement into the March quarter as channel inventory clears; management will discuss the impact of January subsidies on the next call.,updated,1,1.0,0,confirmed,demand,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-02 21:34:38.800210+00:00,2025-12-02 21:34:38.814462+00:00
9,d55d9d88-4c52-4553-bc51-81b776a1deb5,AAPL,2025-01-30,risk_event,FX Headwind Narrows Apple Revenue by 2.5pp,"Management cites foreign exchange headwinds trimming revenue ~2.5 percentage points YoY; March quarter guidance shows low-to-mid single-digit revenue growth with services growth in the low-double-digits, excluding FX impact.",announced,-1,1.0,0,confirmed,earnings,0,[],2025-12-02 21:36:38.174948+00:00,2025-12-02 21:36:38.174948+00:00
10,a0722b10-5811-49ba-8e49-125003b3f61a,AAPL,2025-01-30,risk_event,Regulatory Headwinds Could Hit Apple Earnings,"Analyst questions whether global regulatory burdens could create top-line or margin headwinds for Apple, with potential improvement if regulation becomes more balanced.",announced,-1,1.0,0,rumor,earnings,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-02 21:36:38.174948+00:00,2025-12-02 21:36:38.174948+00:00
11,f04c9482-18bb-40f3-92a0-a8a161977a5e,AAPL,2025-01-30,macro_policy,China Fiscal Stimulus May Boost Apple Demand,"China’s January national fiscal stimulus covers Apple product categories (phones to wearables); Apple says it will discuss impact on the next call, signaling potential positive demand effects.",announced,1,1.0,0,confirmed,fiscal_policy,1,[03b75b38-db37-43f1-9c74-2dc181b770d5],2025-12-02 21:37:57.888657+00:00,2025-12-02 21:37:57.888657+00:00
12,ee2a32a8-639e-4d66-99dd-17175c117ff1,AAPL,2025-05-01,guidance_outlook,Guidance outlook reaffirmed with unchanged tariffs/macros,Reaffirmed outlook; assumptions on tariffs and macroeconomic trajectory unchanged from today.,updated,0,1.0,0,planned,revenue,1,[11cd1449-ba38-4626-b62f-65a1c512c7f4],2025-12-02 21:40:36.420769+00:00,2025-12-02 21:40:36.434859+00:00
13,397b4c5e-5075-4136-aede-04e2b456283f,AAPL,2025-05-01,product_initiative,Battery-Life Initiative: First Unit Shipped,Apple indicates it has shipped the first unit of a new battery-life focused product initiative and is starting a journey toward improved battery performance.,announced,1,1.0,0,confirmed,technology,1,[11cd1449-ba38-4626-b62f-65a1c512c7f4],2025-12-02 21:42:28.236244+00:00,2025-12-02 21:42:28.236244+00:00
14,42102e4b-d4ef-4459-8a8e-8a09a2f00899,AAPL,2025-05-01,product_initiative,Apple Unveils iPhone 16e Entry Model,"Apple announced the iPhone 16e as a new entry-level addition to the iPhone 16 lineup, powered by the A18 chip and the all-new C1 modem, delivering longer battery life.",announced,1,1.0,0,confirmed,revenue,0,[],2025-12-02 21:42:28.236244+00:00,2025-12-02 21:42:28.236244+00:00
15,9e009472-1996-44d8-942a-05936bff0b99,AAPL,2025-05-01,product_initiative,Apple Expands Capacity with Texas Server Manufacturing,"Apple plans multi-state facility expansions, including a Texas-based advanced server manufacturing setup via a partner, signaling broader capacity expansion across operations.",announced,1,2.0,0,confirmed,capacity,1,[11cd1449-ba38-4626-b62f-65a1c512c7f4],2025-12-02 21:42:28.236244+00:00,2025-12-02 21:42:28.236244+00:00
16,7158ede2-592f-487b-a3db-08a129ac73e8,AAPL,2025-05-01,partnership_deal,Apple Signals Partnerships for Foundation Models and Data Centers,"Tim Cook signals Apple will pursue external partnerships for AI foundation models alongside data-center investments, not gating the effort. Apple has been shipping foundation models for some time, both on-device and in Private Cloud Compute.",announced,1,1.0,1,planned,strategy,0,[],2025-12-02 21:43:48.379019+00:00,2025-12-02 21:43:48.379019+00:00
17,47dfe034-0e89-46ed-8074-9ba18333f19f,AAPL,2025-05-01,capital_actions,Updated: $100B Buyback Authorization and 4% Dividend Increase,"Board authorized an additional $100B for share repurchases and raised the dividend by 4%, expanding the planned capital-return program.",updated,1,0.0,1,confirmed,shareholder_return,2,"[11cd1449-ba38-4626-b62f-65a1c512c7f4, 03b75b38-db37-43f1-9c74-2dc181b770d5]",2025-12-02 21:31:04.974605+00:00,2025-12-02 21:45:45.153290+00:00
18,4b6891f4-329e-4c68-9a73-5458549f6dc7,AAPL,2025-05-01,regulatory_policy,Apple to Appeal Ongoing DOJ Case,"Apple signals it will appeal a regulatory case, stating disagreement with the court's order and ongoing monitoring of related risks.",announced,0,2.0,0,planned,legal,0,[],2025-12-02 21:47:28.463706+00:00,2025-12-02 21:47:28.463706+00:00
19,93783b10-a5d8-4284-a125-a07caf5e5521,AAPL,2025-05-01,regulatory_policy,Rising regulatory risk to Apple Services discussed,"Transcript highlights investor concerns about ongoing high-profile legal cases that could impact Apple's Services business, with questions on mitigation but no concrete actions announced.",announced,0,NaN,0,rumor,legal,0,[],2025-12-02 21:47:28.463706+00:00,2025-12-02 21:47:28.463706+00:00
20,ad858c3b-dbfc-46a4-99d2-0edf8267b6d3,AAPL,2025-05-01,regulatory_policy,Section 232 Tariffs Probe Underway,Apple notes ongoing Section 232 tariff investigation; predictions beyond June are uncertain.,announced,0,1.0,0,confirmed,policy,1,[11cd1449-ba38-4626-b62f-65a1c512c7f4],2025-12-02 21:47:28.463706+00:00,2025-12-02 21:47:28.463706+00:00
21,e7d37b44-015e-4352-8d72-8bad61a3aa47,AAPL,2025-05-01,demand_trends,Tariffs/Export Controls Weigh on June Demand Outlook,"Tariffs and export-control risks are shaping management’s view of the June quarter demand backdrop, adding to FX headwinds affecting revenue guidance.",updated,-1,1.0,1,rumor,demand,1,[11cd1449-ba38-4626-b62f-65a1c512c7f4],2025-12-02 21:50:34.327057+00:00,2025-12-02 21:50:34.344181+00:00
22,ace026e9-11ce-4292-803a-edaca810ba04,AAPL,2025-05-01,risk_event,Tariff Costs Drag Apple Margins,"Apple's June quarter guidance includes tariff-related costs, with gross margin guidance of 45.5–46.5% and OI&E near negative $300 million, implying a potential negative earnings impact.",announced,-1,0.0,0,confirmed,earnings,1,[11cd1449-ba38-4626-b62f-65a1c512c7f4],2025-12-02 21:52:52.024276+00:00,2025-12-02 21:52:52.024276+00:00
23,d4ff428d-12b6-4f77-bff4-cc8ed3e01d7c,AAPL,2025-05-01,risk_event,Apple Broadens Supplier Diversification to Mitigate Supply-Chain Risk,Apple describes ongoing supplier diversification to reduce supply-chain risk and expects this approach to continue.,announced,0,1.0,0,planned,supply_chain,1,[11cd1449-ba38-4626-b62f-65a1c512c7f4],2025-12-02 21:52:52.024276+00:00,2025-12-02 21:52:52.024276+00:00
24,a7c25c93-0a25-4ada-bb4a-10dde0d01b4d,AAPL,2025-07-31,guidance_outlook,Sep quarter revenue growth and margin guidance,"Apple issued guidance for the September quarter, forecasting mid- to high-single-digit revenue growth, Services growth similar to June, and gross margin of 46-47%.",announced,1,1.0,0,planned,revenue,1,[a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f],2025-12-02 21:58:29.593836+00:00,2025-12-02 21:58:29.593836+00:00
25,6ed644f4-87a4-4798-aa43-53cacf987e39,AAPL,2025-07-31,guidance_outlook,AI-driven CapEx growth outlook,"Company plans meaningful CapEx expansion driven by AI investments; ongoing investments in facilities and retail, with hybrid infrastructure.",announced,1,2.0,1,planned,capex,0,[],2025-12-02 21:58:29.593836+00:00,2025-12-02 21:58:29.593836+00:00
26,7984974a-6d91-45e0-8ae7-2681a4a7726b,AAPL,2025-07-31,product_initiative,VisionOS 26 with enterprise APIs launched,"VisionOS 26 introduces enterprise APIs, improved lifelike personas, and spatial widgets, signaling expanded enterprise and developer opportunities.",announced,1,0.0,0,confirmed,technology,1,[a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f],2025-12-02 22:00:33.996184+00:00,2025-12-02 22:00:33.996184+00:00
27,645adacf-eb96-4eb3-966d-c4e8c36b94e4,AAPL,2025-07-31,cost_efficiency,Tariff Headwinds Prompt Updated Margin Levers,"Update to the margin-improvement program; management is evaluating timing and execution of cost-cutting levers to offset tariff headwinds, refining the margin plan tied to US manufacturing initiatives.",updated,1,1.0,1,planned,margin,2,"[a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f, 03b75b38-db37-43f1-9c74-2dc181b770d5]",2025-12-02 21:29:32.414664+00:00,2025-12-02 22:03:04.117177+00:00
28,e41880a6-a27d-4e55-8ec0-58062cf74637,AAPL,2025-07-31,capital_actions,Dividend Declared: $0.26 per Share (Upsized),"Apple declares a cash dividend of $0.26 per share, payable August 14, 2025, to shareholders of record as of August 11, 2025.",announced,1,1.0,0,confirmed,shareholder_return,0,[],2025-12-02 22:04:19.125787+00:00,2025-12-02 22:04:19.125787+00:00
29,6612e290-ac2a-43f4-85b9-c123e85063ac,AAPL,2025-07-31,risk_event,OI&E Headwind Signals Negative Earnings,"Apple guides OI&E around negative $25 million, excluding minority investments MTM, implying a negative earnings impact for the quarter.",announced,-1,1.0,0,confirmed,earnings,1,[a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f],2025-12-02 22:07:43.273884+00:00,2025-12-02 22:07:43.273884+00:00
30,58210382-57e8-4f17-a06d-4a386eb90b24,AAPL,2025-07-31,macro_policy,Tariffs Persist; Costs Rise; Apple Reassesses Offsets,Tariff costs remain a headwind; Apple reiterates ongoing assessment of offset measures as tariff policy evolves. New cost estimates are disclosed for the upcoming quarters.,updated,-1,1.0,1,planned,trade_policy,2,"[a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f, 11cd1449-ba38-4626-b62f-65a1c512c7f4]",2025-12-02 21:55:21.142811+00:00,2025-12-02 22:09:30.942184+00:00

In [49]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.catalyst_versions WHERE catalyst_id = '645adacf-eb96-4eb3-966d-c4e8c36b94e4' AND " \
    "(event_id = '03b75b38-db37-43f1-9c74-2dc181b770d5' OR event_id = 'a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f');"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/865388352.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,event_id,chunk_id,catalyst_id,tic,date,catalyst_type,title,summary,evidence,state,...,certainty,impact_area,is_valid,rejection_reason,ingestion_batch,source_type,source,url,raw_json_sha256,updated_at
0,03b75b38-db37-43f1-9c74-2dc181b770d5,44,645adacf-eb96-4eb3-966d-c4e8c36b94e4,AAPL,2025-01-30,cost_efficiency,Apple Guides 46.5–47.5% Gross Margin on Cost Actions,"Apple provided forward-looking gross-margin guidance of 46.5%–47.5%, citing offsetting cost actions and FX dynamics, with margin support despite product mix shifts.","we're guiding to 46.5% to 47.5%. There's always puts and takes. There are FX headwinds expected to affect margin, but that should be offset by favorable costs and the relative mix of services. As we move from Q1 to Q2, we face some loss of leverage in products, but we feel good about this range for gross margin.",announced,...,planned,margin,1,None,quarterly,earnings_transcript,https://api.api-ninjas.com/v1/earningstranscript?ticker=AAPL&year=2025&quarter=1,None,97b8dabae79e878d4a52f0e6461169985d73bbcb35225680aac2dd4c2993f853,2025-12-02 21:29:32.414664+00:00
1,03b75b38-db37-43f1-9c74-2dc181b770d5,73,645adacf-eb96-4eb3-966d-c4e8c36b94e4,AAPL,2025-01-30,cost_efficiency,Apple Maintains 46.5–47.5% Margin Outlook,"Reaffirmed margin guidance; ongoing cost actions and favorable mix support margin trajectory, offset by FX headwinds.","we're guiding to 46.5% to 47.5%. There's always puts and takes. There are FX headwinds expected to affect margin, but that should be offset by favorable costs and the relative mix of services. As we move from Q1 to Q2, we face some loss of leverage in products, but we feel good about this range for gross margin.",updated,...,planned,margin,1,None,quarterly,earnings_transcript,https://api.api-ninjas.com/v1/earningstranscript?ticker=AAPL&year=2025&quarter=1,None,97b8dabae79e878d4a52f0e6461169985d73bbcb35225680aac2dd4c2993f853,2025-12-02 21:29:32.428881+00:00
2,a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f,36,645adacf-eb96-4eb3-966d-c4e8c36b94e4,AAPL,2025-07-31,cost_efficiency,Apple Expands Margin Outlook with US Manufacturing Push,"Reaffirms margin trajectory with ongoing cost actions and expanded US manufacturing investments, including a 4-year, $500B commitment and multi-state chip builds.",We've committed $500 billion investment in the U.S. over the next 4 years. And we're already building chips in Arizona.,updated,...,planned,margin,0,Evidence confirms $500B US investment and Arizona chip builds but does not mention multi-state chip builds or cost actions; margin details not explicit.,quarterly,earnings_transcript,https://api.api-ninjas.com/v1/earningstranscript?ticker=AAPL&year=2025&quarter=3,None,4a9aad7deb9a0c6c393b47303cfbb642861185d37f7bb8b92cfd3a6f77e55613,2025-12-02 22:03:04.116177+00:00
3,a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f,35,645adacf-eb96-4eb3-966d-c4e8c36b94e4,AAPL,2025-07-31,cost_efficiency,Tariff Headwinds Prompt Updated Margin Levers,"Update to the margin-improvement program; management is evaluating timing and execution of cost-cutting levers to offset tariff headwinds, refining the margin plan tied to US manufacturing initiatives.","""tariff assumption of $1.1 billion in the September quarter"" ... ""how do you eventually think about offsetting this headwind to your P&L? And when do you decide to execute on the levers to offset this headwind versus just flowing into your bottom line?""",updated,...,planned,margin,1,None,quarterly,earnings_transcript,https://api.api-ninjas.com/v1/earningstranscript?ticker=AAPL&year=2025&quarter=3,None,4a9aad7deb9a0c6c393b47303cfbb642861185d37f7bb8b92cfd3a6f77e55613,2025-12-02 22:03:04.117177+00:00

In [125]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.earnings_transcript_chunks WHERE " \
    "event_id = '03b75b38-db37-43f1-9c74-2dc181b770d5' AND (chunk_id = 8 OR chunk_id = 9);"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/4008401158.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,calendar_year,calendar_quarter,event_id,chunk_id,chunk,token_count,chunk_sha256,transcript_sha256,updated_at
0,AAPL,2024,4,03b75b38-db37-43f1-9c74-2dc181b770d5,8,"Kevan Parekh: (contd) Both transacting and paid accounts reached new all-time highs, with paid accounts growing double-digits year-over-year. Paid subscriptions also grew double-digits. We have well over 1 billion paid subscriptions across the services on our platform. We remain focused on improving the breadth and quality of our services offerings, from new games on Apple Arcade to exciting new programming on Fitness Plus, and the continued expansion of features like Tap to Pay, now live in 20 markets. Turning to enterprise, we have seen businesses continue to expand their deployments of our products and services. Deutsche Bank launched its Mac as Choice program for the developers and also issued the latest MacBook Air as a standard computer for their entire mortgage lending division. And we're excited to see leading enterprises such as SAP leverage Apple Intelligence in the U.S., with features like writing tools, summarize, and priority notifications to enhance both their employee and customer experiences. We also see strong demand in our emerging markets. For example, Zomato, a leading food ordering and delivery company in India, has deployed 1,000 of Macs across their workforce to foster innovation. In Vision Pro continues to see more use cases in enterprise, with Cisco's new spatial meetings delivering a fully immersive video conferencing experience for remote collaboration and learning. Let me quickly summarize our cash position and capital return program. We ended the quarter with $141 billion in cash and marketable securities. We repaid $1 billion in maturing debt and decreased commercial paper by $8 billion, resulting in $97 billion in total debt. Therefore, net cash at the end of the quarter was $45 billion. During the quarter, we returned over $30 billion to shareholders. This included $3.9 billion in dividends and equivalents and $23.3 billion through open market repurchases of 100 million Apple shares. As usual, we will provide an update to our capital return program when we report results for the March quarter. As we move ahead into the March quarter, I'd like to review our outlook which includes the types of forward-looking information that Suhasini referred to at the beginning of the call. The color we're providing today assumes that the macroeconomic outlook doesn't worsen from what we're projecting today for the current quarter. As the dollar is strengthened significantly, we expect foreign exchange to be a headwind and to have a negative impact on revenue of about 2.5 percentage points on a year-over-year basis.",502,4b0f944b93bb7a8d029e5bfea986cd5e360f372fb138e19466ca10146c75034a,abba2130960470fb89ec6dd28ea23fbeb60cff51be765477df987655a78d7aa5,2025-10-27 07:39:55.638880+00:00
1,AAPL,2024,4,03b75b38-db37-43f1-9c74-2dc181b770d5,9,"Kevan Parekh: (contd) As the dollar is strengthened significantly, we expect foreign exchange to be a headwind and to have a negative impact on revenue of about 2.5 percentage points on a year-over-year basis. Despite that headwind, we expect our March quarter total company revenue to grow low to mid-single-digits year-over-year. We expect services revenue to grow low-double-digits year-over-year. When you remove the negative impact of the foreign exchange headwinds I described earlier, the year-over-year growth rate would be comparable to that of the December quarter. We expect gross margin to be between 46.5% and 47.5%. We expect operating expenses to be between $15.1 billion and $15.3 billion. We expect OI&E to be around negative $300 million, excluding any potential impact from the mark-to-market of minority investments, and our tax rate to be around 16%. Finally, today our Board of Directors has declared a cash dividend of $0.25 per share of common stock payable on February 13, 2025, to shareholders of record as of February 10, 2025. With that, let's open to call the questions.",251,c4947b3bc2c21061c14cc344dfd7cafeb66b79c99bd7348b123ecd2fca8213c0,abba2130960470fb89ec6dd28ea23fbeb60cff51be765477df987655a78d7aa5,2025-10-27 07:39:55.638880+00:00

In [42]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.catalyst_versions WHERE event_id = '1ee975fb-a5f5-4fa2-8fd8-45c1052493fd' LIMIT 1;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/269446423.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

Empty DataFrame
Columns: [event_id, chunk_id, catalyst_id, tic, date, catalyst_type, title, summary, evidence, state, sentiment, time_horizon, impact_magnitude, certainty, impact_area, is_valid, rejection_reason, ingestion_batch, source_type, source, url, raw_json_sha256, updated_at]
Index: []

[0 rows x 23 columns]

In [8]:

# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = \
    """SELECT 
        cv.event_id,
        evidence,
        source_type,
        CASE WHEN source_type = 'earnings_transcript' 
             THEN 'earnings transcript (Q' || calendar_quarter || ' ' || calendar_year || ')'
             ELSE url
        END AS reference,
        calendar_quarter,
        calendar_year
        FROM core.catalyst_versions cv
        LEFT JOIN 
            (SELECT event_id, calendar_quarter, calendar_year 
            FROM core.earnings_transcripts
            WHERE tic = 'TSLA') et
        ON cv.event_id = et.event_id
        WHERE cv.tic = 'TSLA';
    """
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/2273179061.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,event_id,evidence,source_type,reference,calendar_quarter,calendar_year
0,d8af0db7-2166-48a4-914f-2bb695d65978,Our CapEx guidance inclusive of [tariffs] is f...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
1,d8af0db7-2166-48a4-914f-2bb695d65978,"I expect that this year will be, there will pr...",earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
2,d8af0db7-2166-48a4-914f-2bb695d65978,We're still planning to release models this ye...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
3,d8af0db7-2166-48a4-914f-2bb695d65978,We start to large scale installation of all th...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
4,d8af0db7-2166-48a4-914f-2bb695d65978,We continue to mitigate global economic risks ...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
5,d8af0db7-2166-48a4-914f-2bb695d65978,"In California in Q1, Tesla remained the best-s...",earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
6,d8af0db7-2166-48a4-914f-2bb695d65978,We're not getting down one by one... ramp mayb...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
7,d8af0db7-2166-48a4-914f-2bb695d65978,Auto margins declined sequentially primarily d...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
8,d8af0db7-2166-48a4-914f-2bb695d65978,We’re already taking tremendous steps to local...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
9,d8af0db7-2166-48a4-914f-2bb695d65978,The impact of tariffs on the energy business w...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
10,d8af0db7-2166-48a4-914f-2bb695d65978,We’re already taking tremendous steps to local...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
11,d8af0db7-2166-48a4-914f-2bb695d65978,Is Tesla still battery supply constrained as n...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
12,d8af0db7-2166-48a4-914f-2bb695d65978,We continue to mitigate global economic risks ...,earnings_transcript,earnings transcript (Q1 2025),1.0,2025.0
13,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,"Unfortunately, that rolls away, we'll be ready...",earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
14,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,"We'll have prototypes of that in, I don't know...",earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
15,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,We continue to invest heavily in U.S. manufact...,earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
16,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,We started ramping up the production of the ne...,earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
17,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,"You talked about some aspects of this, like 2/...",earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
18,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,You've previously talked about working to driv...,earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
19,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,We've started seeing an uptick in FSD adoption...,earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
20,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,the goal of those products was not to negative...,earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
21,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,"Given the abrupt change, we have limited suppl...",earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
22,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,Tesla has historically said it would use prici...,earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
23,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,I'm curious how you're thinking about pricing ...,earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
24,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,We have near-term challenges in our business d...,earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
25,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,The cost of tariffs increased around $300 mill...,earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
26,908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c,We started seeing the impact of tariffs in our...,earnings_transcript,earnings transcript (Q2 2025),2.0,2025.0
27,945c3048-35ba-4144-9a7b-25629d645089,We're projecting the numbers to increase subst...,earnings_transcript,earnings transcript (Q3 2025),3.0,2025.0
28,945c3048-35ba-4144-9a7b-25629d645089,We received very strong positive customer feed...,earnings_transcript,earnings transcript (Q3 2025),3.0,2025.0
29,945c3048-35ba-4144-9a7b-25629d645089,We are now operating a robotaxi in two markets...,earnings_transcript,earnings transcript (Q3 2025),3.0,2025.0
30,945c3048-35ba-4144-9a7b-25629d645089,"Elon, you talked about expanding production of...",earnings_transcript,earnings transcript (Q3 2025),3.0,2025.0
31,945c3048-35ba-4144-9a7b-25629d645089,The factory is going on schedule. We've comple...,earnings_transcript,earnings transcript (Q3 2025),3.0,2025.0
32,945c3048-35ba-4144-9a7b-25629d645089,We are seeing headwinds in this business given...,earnings_transcript,earnings transcript (Q3 2025),3.0,2025.0
33,945c3048-35ba-4144-9a7b-25629d645089,We'll have a larger build towards the end of t...,earnings_transcript,earnings transcript (Q3 2025),3.0,2025.0
34,945c3048-35ba-4144-9a7b-25629d645089,The strength in deliveries was attributed to s...,earnings_transcript,earnings transcript (Q3 2025),3.0,2025.0
35,945c3048-35ba-4144-9a7b-25629d645089,Demand for Megapack and Powerwall continues to...,earnings_transcript,earnings transcript (Q3 2025),3.0,2025.0
36,945c3048-35ba-4144-9a7b-25629d645089,We are seeing headwinds in this business given...,earnings_transcript,earnings transcript (Q3 2025),3.0,2025.0
37,5f8c91b5-11a3-4e59-ab00-7c74227e4afd,Elon Musk teased an expansion of the robotaxi ...,news,https://www.fool.com/investing/2025/10/25/2-re...,NaN,NaN
38,c9727492-2eb9-4c13-8894-4d9112ebec44,Musk told podcaster Joe Rogan that his company...,news,https://www.cnbc.com/2025/10/31/musk-teases-te...,NaN,NaN
39,3516a746-85e7-4eee-9120-30912f3a7268,Elon Musk did say Cybercab production will sta...,news,https://www.investors.com/news/tesla-earnings-...,NaN,NaN
40,2efc5fab-b177-41cd-b54d-585ed897d65e,Tesla will debut its Cybercab at the China Int...,news,https://www.reuters.com/world/asia-pacific/tes...,NaN,NaN
41,0a37736f-c8c8-44f5-ab6b-02a35b394bdd,TSLA's robotaxi expansion and upcoming Cyberca...,news,https://seekingalpha.com/article/4833751-tesla...,NaN,NaN
42,9ca33dc1-2688-4922-b8c0-d41ecc9f00f7,"After a weak first half of the year, Tesla del...",news,https://www.fool.com/investing/2025/10/25/tesl...,NaN,NaN
43,cb59be08-26b0-4bec-9ba0-131da3a9b993,The end of federal tax credits likely pushed a...,news,https://www.fool.com/investing/2025/10/27/with...,NaN,NaN
44,930ebe0d-af3f-43be-a6a2-4ef9f975f20f,Tesla Issues 10th Recall For Cybertrucks - 5.1...,news,https://www.forbes.com/sites/tylerroush/2025/1...,NaN,NaN
45,792c8a28-08e8-4e1f-9a8e-c5873eb15884,The latest Tesla Cybertruck recall issue invol...,news,https://www.cnet.com/roadshow/news/tesla-issue...,NaN,NaN
46,4ffb8695-b634-44ce-96a4-9305b9aec611,"Tesla is recalling nearly 6,200 Cybertrucks be...",news,https://www.businessinsider.com/tesla-recalls-...,NaN,NaN
47,9abeb830-152b-409b-a98b-ca29b51bb53e,President Trump expressed his optimism for a d...,news,https://www.fool.com/investing/2025/10/27/why-...,NaN,NaN
48,ed75e7a1-68be-4c26-94a1-ce44872ccc85,"Energy storage shined, with sales up nearly 50%.",news,https://www.fool.com/investing/2025/11/01/5-th...,NaN,NaN

In [38]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.catalyst_master WHERE tic = 'TSLA';"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/3515528589.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,catalyst_id,tic,date,catalyst_type,title,summary,evidence,state,sentiment,time_horizon,impact_magnitude,certainty,impact_area,mention_count,event_ids,created_at,updated_at
0,d6f66508-88e7-4adc-aec0-bd1458e73769,TSLA,2025-04-22,guidance_outlook,Optimistic outlook on autonomous vehicle impact,"Elon Musk expressed optimism about Tesla's future, highlighting that the financial impact of autonomous vehicle sales is expected to materialize in the second half of next year, despite some anticipated challenges.","I expect that this year will be, there will probably be some unexpected bumps this year... the real question from financial standpoint is when does it really become material and affect bottom line of the company.",updated,1,1,1,confirmed,revenue,1,[d8af0db7-2166-48a4-914f-2bb695d65978],2025-11-01 13:55:31.585031+00:00,2025-11-01 13:55:31.595645+00:00
1,795e1fae-2bbd-44b6-8004-f48884d0af4f,TSLA,2025-04-22,risk_event,Proactive Supply Chain Localization Efforts,Elon Musk highlighted ongoing initiatives to localize Tesla's supply chain to mitigate risks from geopolitical uncertainties.,We’re already taking tremendous steps to localize our supply chain... to reduce supply chain risk associated with geopolitical uncertainty.,announced,-1,1,0,confirmed,supply_chain,1,[d8af0db7-2166-48a4-914f-2bb695d65978],2025-11-01 13:57:22.485741+00:00,2025-11-01 13:57:22.485741+00:00
2,67b23128-5ac9-48c6-bd72-004fb698c343,TSLA,2025-10-22,cost_efficiency,Cost Efficiency Actions to Improve Operations,"Tesla is implementing restructuring actions to reduce costs and improve efficiency, particularly in response to tariff impacts and competition, while also ramping up AI initiatives.",We are seeing headwinds in this business given the increase in competition and tariffs... actions undertaken to reduce cost and improve efficiency to convergence of our AR AI chip design efforts.,updated,0,1,1,confirmed,operations,3,"[945c3048-35ba-4144-9a7b-25629d645089, 908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c, d8af0db7-2166-48a4-914f-2bb695d65978]",2025-11-01 13:56:18.075855+00:00,2025-11-01 14:01:02.644962+00:00
3,e5ba7326-c543-40f0-bf06-b501ee32546e,TSLA,2025-04-22,macro_policy,Enhanced Localization to Address Geopolitical Risks,"Tesla is accelerating its supply chain localization efforts to mitigate geopolitical risks, enhancing resilience against tariffs and political biases affecting operations.","We continue to mitigate global economic risks like tariffs and political biases by regionalizing part supply factories in North America, Berlin and Shanghai.",updated,1,1,0,confirmed,geopolitical,1,[d8af0db7-2166-48a4-914f-2bb695d65978],2025-11-01 13:57:51.360479+00:00,2025-11-01 13:57:51.371339+00:00
4,c751a257-38fa-45e8-b5df-52cd72e8c467,TSLA,2025-07-23,product_initiative,New Affordable Models Launching in Q4,"Tesla plans to introduce new, more affordable vehicle models in Q4, aiming to maximize production while maintaining revenue and gross margin.","Unfortunately, that rolls away, we'll be ready with new, more affordable models available for everyone in Q4.",announced,1,1,1,confirmed,revenue,1,[908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c],2025-11-01 13:58:26.281677+00:00,2025-11-01 13:58:26.281677+00:00
5,5d87c044-4d55-408a-9533-c76bd209d86e,TSLA,2025-07-23,product_initiative,Optimus 3 Production Ramp Planned,"Tesla plans to start production of the Optimus 3 design in early next year, with prototypes expected in three months. The production ramp may face challenges due to supply chain complexities.","We'll have prototypes of that in, I don't know, 3 months and then start production -- we'll certainly start production on that in the beginning of next year.",announced,1,1,1,confirmed,operations,1,[908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c],2025-11-01 13:58:26.281677+00:00,2025-11-01 13:58:26.281677+00:00
6,32ad7f76-72e4-4bc3-8f50-8da37182f763,TSLA,2025-07-23,product_initiative,New Manufacturing Initiatives and Megafactory Launch,"Tesla is investing in U.S. manufacturing, expecting its first LFP cell manufacturing facility to be operational by year-end and planning to launch a third Megafactory near Houston in 2026, indicating significant capacity expansion.",We continue to invest heavily in U.S. manufacturing... expecting our first LFP cell manufacturing facility to be online by the end of the year and launching our third Megafactory near Houston in 2026.,announced,1,2,1,confirmed,capacity,1,[908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c],2025-11-01 13:58:26.281677+00:00,2025-11-01 13:58:26.281677+00:00
7,1e1ee26a-dac4-4310-a40e-b3ce5e693a7c,TSLA,2025-10-22,risk_event,Ongoing Tariff and Competition Headwinds Impacting Earnings,"Tesla reports continued headwinds from tariffs and increased competition, projecting a significant impact on profitability with tariff costs exceeding $400 million for Q3.",We are seeing headwinds in this business given the increase in competition and tariffs. The total tariff impacts for Q3 for both businesses were in excess of $400 million.,updated,-1,1,0,confirmed,earnings,3,"[945c3048-35ba-4144-9a7b-25629d645089, 908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c, d8af0db7-2166-48a4-914f-2bb695d65978]",2025-11-01 13:57:22.485741+00:00,2025-11-01 14:02:01.944250+00:00
8,fc4a437d-eda9-45df-90bc-6acd934e5695,TSLA,2025-11-01,demand_trends,Strong Demand for Energy Storage Products,"Tesla's energy storage segment is experiencing significant growth, with sales up nearly 50%, indicating a positive demand trend in this area.","Energy storage shined, with sales up nearly 50%.",updated,1,1,1,confirmed,demand,4,"[ed75e7a1-68be-4c26-94a1-ce44872ccc85, 945c3048-35ba-4144-9a7b-25629d645089, 908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c, d8af0db7-2166-48a4-914f-2bb695d65978]",2025-11-01 13:57:07.118317+00:00,2025-11-01 14:17:27.285756+00:00
9,842215e2-5bab-4e3f-af4e-3647219b76c7,TSLA,2025-07-23,risk_event,Potential Pricing Strategy Risks Identified,"Tesla is considering pricing adjustments to drive vehicle growth, raising concerns about future earnings due to the potential loss of IRA tax credits and the impact on free cash flow.",I'm curious how you're thinking about pricing from here as a potential tool to drive increased volumes given where you stand with FSD as well as the fact that the IRA purchase tax credits are poised to go away.,announced,-1,1,0,confirmed,earnings,1,[908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c],2025-11-01 13:59:45.911830+00:00,2025-11-01 13:59:45.911830+00:00
10,c27e4374-c6a6-46c3-8709-94bd75f5d779,TSLA,2025-10-22,guidance_outlook,Projected increase in CapEx for 2026,"Tesla is projecting a substantial increase in capital expenditures for 2026 as it prepares for growth in existing businesses and AI initiatives, indicating a strong commitment to future expansion.",We're projecting the numbers to increase substantially in 2026 as we prepare the company for the next phase of growth.,announced,1,2,1,confirmed,capex,1,[945c3048-35ba-4144-9a7b-25629d645089],2025-11-01 14:00:06.326252+00:00,2025-11-01 14:00:06.326252+00:00
11,6bd6bfaa-8630-4b83-a649-b52749a8760c,TSLA,2025-10-22,product_initiative,New Solar Products and Production Initiatives,"Tesla is set to begin shipping its Mega Block product next year and has started production of residential solar panels in Buffalo, indicating a strong commitment to expanding its solar product offerings.","We received very strong positive customer feedback on our Mega Block product, which will begin shipping next year out of Houston.",announced,1,1,1,confirmed,operations,1,[945c3048-35ba-4144-9a7b-25629d645089],2025-11-01 14:00:40.019796+00:00,2025-11-01 14:00:40.019796+00:00
12,62cae088-dad4-47ee-af24-8eb09c981ddc,TSLA,2025-10-22,product_initiative,Model Y and Robotaxi Service Expansion,"Tesla has expanded its Model Y production and robotaxi service, increasing coverage in Austin and other cities, reflecting ongoing advancements in its product initiatives. The excitement around the Model Y continues to drive demand.","We are now operating a robotaxi in two markets, Austin and most various cities. We have already expanded our coverage area in Austin three times since the initial launch.",updated,1,1,1,confirmed,operations,3,"[945c3048-35ba-4144-9a7b-25629d645089, 908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c, d8af0db7-2166-48a4-914f-2bb695d65978]",2025-11-01 13:55:51.244898+00:00,2025-11-01 14:00:40.031956+00:00
13,cce0a367-7c53-4703-bf1c-b3b64cb0820d,TSLA,2025-10-22,product_initiative,Autonomous Truck Production Plans Progressing,"Production plans for autonomous trucks are on schedule, with equipment installation underway and initial builds expected early next year, ramping up to significant volume by Q2.",The factory is going on schedule. We've completed the building and are installing the equipment now... we'll have a larger build towards the end of this year and then our first online builds in the first part of next year.,updated,1,1,1,confirmed,operations,2,"[945c3048-35ba-4144-9a7b-25629d645089, d8af0db7-2166-48a4-914f-2bb695d65978]",2025-11-01 13:55:51.244898+00:00,2025-11-01 14:00:40.033956+00:00
14,935852a8-2a0b-4d73-9e4c-d1ab8c62b037,TSLA,2025-10-22,demand_trends,Anticipated Growth in Autonomous Truck Production,"Tesla is ramping up production of autonomous trucks, with initial builds expected early next year and significant volume anticipated in the latter half of the year.","We'll have a larger build towards the end of this year and then our first online builds in the first part of next year, ramping into the Q2 timing with real volume coming in the back half of the year.",announced,1,1,1,confirmed,demand,1,[945c3048-35ba-4144-9a7b-25629d645089],2025-11-01 14:01:49.647251+00:00,2025-11-01 14:01:49.647251+00:00
15,8b063313-a146-4b20-8618-0930d2d2e8b0,TSLA,2025-10-25,product_initiative,Robotaxi Fleet Expansion Teased,"Elon Musk's mention of expanding the robotaxi fleet indicates a forward-looking enhancement to Tesla's existing robotaxi initiative, which aims to bolster autonomous vehicle offerings.",Elon Musk teased an expansion of the robotaxi fleet.,updated,1,1,1,confirmed,operations,5,"[5f8c91b5-11a3-4e59-ab00-7c74227e4afd, 0a37736f-c8c8-44f5-ab6b-02a35b394bdd, 2efc5fab-b177-41cd-b54d-585ed897d65e, 3516a746-85e7-4eee-9120-30912f3a7268, c9727492-2eb9-4c13-8894-4d9112ebec44]",2025-11-01 14:15:46.311926+00:00,2025-11-01 14:15:46.325596+00:00
16,e308e491-4e97-48b4-b5df-284d4e238035,TSLA,2025-10-25,demand_trends,Tesla Deliveries Surge in Q3,"Tesla reported a significant increase in deliveries in Q3, indicating a positive demand trend following a weak first half of the year.","After a weak first half of the year, Tesla deliveries roared higher in Q3.",announced,1,1,1,confirmed,demand,1,[9ca33dc1-2688-4922-b8c0-d41ecc9f00f7],2025-11-01 14:16:33.005549+00:00,2025-11-01 14:16:33.005549+00:00
17,2dcf37d4-83a1-4df4-a84b-b228f55c124c,TSLA,2025-10-27,risk_event,Profit Concerns Amid Tax Credit Changes,"Tesla faces near-term uncertainty as profits decline, exacerbated by the end of federal tax credits, which may impact future earnings.","The end of federal tax credits likely pushed auto sales higher, but will now become a headwind.",announced,-1,1,0,confirmed,earnings,1,[cb59be08-26b0-4bec-9ba0-131da3a9b993],2025-11-01 14:16:57.073647+00:00,2025-11-01 14:16:57.073647+00:00
18,cef2a7ed-dab8-4808-8221-ddded989e352,TSLA,2025-10-30,risk_event,Cybertruck Recall Expanded Due to Safety Issues,"Tesla's Cybertruck recall has been expanded to include nearly 6,200 vehicles due to a safety risk involving the light bar, which may detach while driving, compounding existing operational challenges.","Tesla is recalling nearly 6,200 Cybertrucks because it used the wrong type of glue for an off-road light bar.",updated,-1,0,1,confirmed,operations,3,"[4ffb8695-b634-44ce-96a4-9305b9aec611, 792c8a28-08e8-4e1f-9a8e-c5873eb15884, 930ebe0d-af3f-43be-a6a2-4ef9f975f20f]",2025-11-01 14:16:57.073647+00:00,2025-11-01 14:16:57.084421+00:00
19,7a28c8b5-c7bc-41b9-aa5a-c35fd007a1f8,TSLA,2025-10-27,macro_policy,Potential Trade Deal Could Reduce Tariff Costs,"Optimism around upcoming trade talks with China may lead to reduced tariff costs, directly benefiting Tesla's financial performance after reporting $400 million in tariff expenses in Q3.","President Trump expressed his optimism for a deal in upcoming trade talks with China. Tesla reported $400 million in tariff costs during Q3, making any trade deal directly beneficial to the company's bottom line.",updated,1,1,0,confirmed,trade_policy,3,"[9abeb830-152b-409b-a98b-ca29b51bb53e, 908abe6e-9f43-4dc6-8b4e-9ca93ecf9b1c, d8af0db7-2166-48a4-914f-2bb695d65978]",2025-11-01 13:57:51.360479+00:00,2025-11-01 14:17:07.210417+00:00

In [53]:

# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = \
    """
        WITH catalyst_events AS (
            SELECT
                cv.event_id,
                cv.catalyst_id,
                cv.evidence,
                COALESCE(
                    CASE
                        WHEN cv.source_type = 'earnings_transcript'
                            THEN 'earnings transcript (Q' || et.calendar_quarter || ' ' || et.calendar_year || ')'
                        ELSE 'news article'
                    END
                ) AS source_type,
                cv.url
            FROM core.catalyst_versions AS cv
            LEFT JOIN (
                SELECT event_id, calendar_quarter, calendar_year
                FROM core.earnings_transcripts
                WHERE tic = 'AAPL'
            ) AS et
                ON cv.event_id = et.event_id
            WHERE cv.tic = 'AAPL' AND cv.is_valid = 1
        )
        SELECT
            cm.*,
            COALESCE(ev.source_types, ARRAY[]::text[])   AS source_types,
            COALESCE(ev.evidences, ARRAY[]::text[])      AS evidences,
            COALESCE(ev.urls, ARRAY[]::text[])     AS urls
        FROM core.catalyst_master AS cm
        LEFT JOIN LATERAL (
            SELECT
                array_agg(ce.source_type ORDER BY ce.event_id) AS source_types,
                array_agg(ce.evidence ORDER BY ce.event_id)    AS evidences,
                array_agg(ce.url ORDER BY ce.event_id)   AS urls
            FROM catalyst_events AS ce
            WHERE ce.catalyst_id = cm.catalyst_id AND ce.event_id::text = ANY(cm.event_ids)
        ) AS ev ON TRUE
        WHERE cm.mention_count > 0 AND cm.tic = 'AAPL' AND cm.catalyst_id = '645adacf-eb96-4eb3-966d-c4e8c36b94e4'
        ORDER BY cm.date DESC, cm.updated_at DESC
        LIMIT 2;
    """
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_17645/1411687734.py:46: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,catalyst_id,tic,date,catalyst_type,title,summary,state,sentiment,time_horizon,impact_magnitude,certainty,impact_area,mention_count,event_ids,created_at,updated_at,source_types,evidences,urls
0,645adacf-eb96-4eb3-966d-c4e8c36b94e4,AAPL,2025-07-31,cost_efficiency,Tariff Headwinds Prompt Updated Margin Levers,"Update to the margin-improvement program; management is evaluating timing and execution of cost-cutting levers to offset tariff headwinds, refining the margin plan tied to US manufacturing initiatives.",updated,1,1,1,planned,margin,2,"[a1e2bb8c-0ef3-45d7-b82d-64ba0b7a9c3f, 03b75b38-db37-43f1-9c74-2dc181b770d5]",2025-12-02 21:29:32.414664+00:00,2025-12-02 22:03:04.117177+00:00,"[earnings transcript (Q4 2024), earnings transcript (Q4 2024), earnings transcript (Q2 2025)]","[we're guiding to 46.5% to 47.5%. There's always puts and takes. There are FX headwinds expected to affect margin, but that should be offset by favorable costs and the relative mix of services. As we move from Q1 to Q2, we face some loss of leverage in products, but we feel good about this range for gross margin., we're guiding to 46.5% to 47.5%. There's always puts and takes. There are FX headwinds expected to affect margin, but that should be offset by favorable costs and the relative mix of services. As we move from Q1 to Q2, we face some loss of leverage in products, but we feel good about this range for gross margin., ""tariff assumption of $1.1 billion in the September quarter"" ... ""how do you eventually think about offsetting this headwind to your P&L? And when do you decide to execute on the levers to offset this headwind versus just flowing into your bottom line?""]","[None, None, None]"

In [ ]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.catalyst_versions;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [6]:
# Query the `news_analysis` table
conn = connect_to_db()
if conn:
    # distinct count of event_id
    query = "SELECT catalyst_id, COUNT(DISTINCT event_id) AS distinct_event_count, COUNT(*) AS count FROM core.catalyst_versions GROUP BY catalyst_id ORDER BY count DESC, distinct_event_count DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_51229/3571054423.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

                              catalyst_id  distinct_event_count  count
0    2dc22851-4b45-44d1-a3b9-a20ac290a6c8                     6     17
1    834cc9f7-aa7f-4e66-a36e-c09536114bf0                     6     13
2    9659fdff-33eb-4d19-a6f8-7c36360fa7e8                     5      9
3    fc4a437d-eda9-45df-90bc-6acd934e5695                     4      9
4    642764bf-163a-492a-892a-32646fc2aa4d                     7      8
..                                    ...                   ...    ...
160  ad3d223f-cc4f-4387-9b75-372a1525da13                     1      1
161  ad6a515c-adca-4976-9aea-cfeda2f8a434                     1      1
162  afe90129-00b3-4952-b4e0-3b1f325267a2                     1      1
163  b877981b-a9f3-483d-bd58-9e5f00bae965                     1      1
164  bdd7fbce-7954-421f-9f6a-d1603b3e12c4                     1      1

[165 rows x 3 columns]

In [ ]:
# convert sentiment to text
# sentiment 1: positive
# sentiment 0: neutral
# sentiment -1: negative

df['sentiment'] = df['sentiment'].map({1: 'positive', 0: 'neutral', -1: 'negative'})

# convert impact_magnitude to text
# impact_magnitude 1: major
# impact_magnitude 0: moderate
# impact_magnitude -1: minor
df['impact_magnitude'] = df['impact_magnitude'].map({1: 'major', 0: 'moderate', -1: 'minor'})

# convert time_horizon to text
# time_horizon 0: short-term
# time_horizon 1: medium-term
# time_horizon 2 long-term
df['time_horizon'] = df['time_horizon'].map({0: 'short-term', 1: 'medium-term', 2: 'long-term'})

In [ ]:
# display all records in the DataFrame
# pd.set_option('display.max_rows', None)
# display all the content in each column
# pd.set_option('display.max_colwidth', None)
# display(df)

In [ ]:
# Query the `analyst_grade_mapping` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM ref.analyst_grade_mapping;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
# Query the `analyst_grade_mapping` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.analyst_rating_monthly_summary;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
df[pd.to_datetime(df['start_date'])==pd.to_datetime("2023-11-04")]

In [ ]:
# Query the `earnings_analysis` table
conn = connect_to_db()

# display all columns
# pd.set_option('display.max_columns', None)

if conn:
    query = "SELECT * FROM core.earnings_analysis ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
# Query the `earnings` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.earnings_calendar ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
df[(df['tic']=='AAPL') & (pd.to_datetime(df['earnings_date']) == pd.to_datetime('1999-12-22'))]

In [ ]:
df[(df['tic']=='AAPL')].iloc[-70:-50]

In [ ]:
# Query the `income_statements` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.balance_sheets ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
# Query the `balance_sheets` table
conn = connect_to_db()
# display all rows
pd.set_option('display.max_rows', None)
if conn:
    query = "SELECT * FROM core.balance_sheets ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
# Query the `earnings` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.analyst_rating_monthly_summary ORDER BY tic, start_date DESC, end_date DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
# Query the `earnings` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.analyst_rating_quarterly_summary ORDER BY tic, start_date DESC, end_date DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
# Query the `earnings` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.analyst_rating_monthly_summary ORDER BY tic, start_date DESC, end_date DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
# Query the `news` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.news ORDER BY tic, published_at DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
import tiktoken

enc = tiktoken.get_encoding("cl100k_base")

# Function to chunk text
def tok_len(s: str) -> int:
    return len(enc.encode(s))

for index, row in df.iterrows(): 
    # count the number of words in the title+content column
    num_words = tok_len(str(row['title'])) + tok_len(str(row['content']))
    print(f"Row {index}: {num_words} words")    
    # if num_words > 200:
    #     print(f"Tic: {row['tic']}\nTitle: {row['title']}\nContent: {row['content']}\n")

In [4]:
# Query the `earnings` table
# display all records
pd.set_option('display.max_rows', None)
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.earnings_calendar ORDER BY tic, earnings_date DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_63723/551479965.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,calendar_year,calendar_quarter,earnings_date,fiscal_year,fiscal_quarter,fiscal_date,session,updated_at
0,AAPL,2026,1,2026-04-26,NaN,NaN,2026-03-29,amc,2025-10-27 07:34:06.573849+00:00
1,AAPL,2025,4,2026-01-28,NaN,NaN,2025-12-28,amc,2025-10-27 07:34:06.573849+00:00
2,AAPL,2025,3,2025-10-30,NaN,NaN,None,None,2025-10-27 07:34:06.573849+00:00
3,AAPL,2025,2,2025-07-31,2025.0,3.0,2025-06-28,amc,2025-10-27 07:34:06.573849+00:00
4,AAPL,2025,1,2025-05-01,2025.0,2.0,2025-03-29,amc,2025-10-27 07:34:06.573849+00:00
5,AAPL,2024,4,2025-01-30,2025.0,1.0,2024-12-28,amc,2025-10-27 07:34:06.573849+00:00
6,AAPL,2024,3,2024-10-31,2024.0,4.0,2024-09-28,amc,2025-10-27 07:34:06.573849+00:00
7,AAPL,2024,2,2024-08-01,2024.0,3.0,2024-06-29,amc,2025-10-27 07:34:06.573849+00:00
8,AAPL,2024,1,2024-05-02,2024.0,2.0,2024-03-30,amc,2025-10-27 07:34:06.573849+00:00
9,AAPL,2023,4,2024-02-01,2024.0,1.0,2023-12-30,amc,2025-10-27 07:34:06.573849+00:00
10,AAPL,2023,3,2023-11-02,2023.0,4.0,2023-09-30,amc,2025-10-27 07:34:06.573849+00:00
11,AAPL,2023,2,2023-08-03,2023.0,3.0,2023-07-01,amc,2025-10-27 07:34:06.573849+00:00
12,AAPL,2023,1,2023-05-04,2023.0,2.0,2023-04-01,amc,2025-10-27 07:34:06.573849+00:00
13,AAPL,2022,4,2023-02-02,2023.0,1.0,2022-12-31,amc,2025-10-27 07:34:06.573849+00:00
14,AAPL,2022,3,2022-10-27,2022.0,4.0,2022-09-24,amc,2025-10-27 07:34:06.573849+00:00
15,AAPL,2022,2,2022-07-28,2022.0,3.0,2022-06-25,amc,2025-10-27 07:34:06.573849+00:00
16,AAPL,2022,1,2022-04-28,2022.0,2.0,2022-03-26,amc,2025-10-27 07:34:06.573849+00:00
17,AAPL,2021,4,2022-01-27,2022.0,1.0,2021-12-25,amc,2025-10-27 07:34:06.573849+00:00
18,AAPL,2021,3,2021-10-28,2021.0,4.0,2021-09-25,amc,2025-10-27 07:34:06.573849+00:00
19,AAPL,2021,2,2021-07-27,2021.0,3.0,2021-06-26,amc,2025-10-27 07:34:06.573849+00:00
20,AAPL,2021,1,2021-04-28,2021.0,2.0,2021-03-27,amc,2025-10-27 07:34:06.573849+00:00
21,AAPL,2020,4,2021-01-27,2021.0,1.0,2020-12-26,amc,2025-10-27 07:34:06.573849+00:00
22,AAPL,2020,3,2020-10-29,2020.0,4.0,2020-09-26,amc,2025-10-27 07:34:06.573849+00:00
23,AAPL,2020,2,2020-07-30,NaN,NaN,2020-06-26,amc,2025-10-27 07:34:06.573849+00:00
24,AAPL,2020,1,2020-04-30,NaN,NaN,2020-03-27,amc,2025-10-27 07:34:06.573849+00:00
25,AAPL,2019,4,2020-01-28,NaN,NaN,2019-12-27,amc,2025-10-27 07:34:06.573849+00:00
26,AAPL,2019,3,2019-10-30,2020.0,0.0,2020-09-26,amc,2025-10-27 07:34:06.573849+00:00
27,AAPL,2019,2,2019-07-30,NaN,NaN,2019-06-28,amc,2025-10-27 07:34:06.573849+00:00
28,AAPL,2019,1,2019-04-30,NaN,NaN,2019-03-29,amc,2025-10-27 07:34:06.573849+00:00
29,AAPL,2018,4,2019-01-29,NaN,NaN,2018-12-28,amc,2025-10-27 07:34:06.573849+00:00
30,AAPL,2018,3,2018-11-01,NaN,NaN,2018-09-28,amc,2025-10-27 07:34:06.573849+00:00
31,AAPL,2018,2,2018-07-31,NaN,NaN,2018-06-29,amc,2025-10-27 07:34:06.573849+00:00
32,AAPL,2018,1,2018-05-01,NaN,NaN,2018-03-30,amc,2025-10-27 07:34:06.573849+00:00
33,AAPL,2017,4,2018-02-01,NaN,NaN,2017-12-29,amc,2025-10-27 07:34:06.573849+00:00
34,AAPL,2017,3,2017-11-02,NaN,NaN,2017-09-29,amc,2025-10-27 07:34:06.573849+00:00
35,AAPL,2017,2,2017-08-01,NaN,NaN,2017-06-30,amc,2025-10-27 07:34:06.573849+00:00
36,AAPL,2017,1,2017-05-02,NaN,NaN,2017-03-31,amc,2025-10-27 07:34:06.573849+00:00
37,AAPL,2016,4,2017-01-31,NaN,NaN,2016-12-30,amc,2025-10-27 07:34:06.573849+00:00
38,AAPL,2016,3,2016-10-25,NaN,NaN,2016-09-23,amc,2025-10-27 07:34:06.573849+00:00
39,AAPL,2016,2,2016-07-26,NaN,NaN,2016-06-24,amc,2025-10-27 07:34:06.573849+00:00
40,AAPL,2016,1,2016-04-26,NaN,NaN,2016-03-25,amc,2025-10-27 07:34:06.573849+00:00
41,AAPL,2015,4,2016-01-26,NaN,NaN,2015-12-25,amc,2025-10-27 07:34:06.573849+00:00
42,AAPL,2015,3,2015-10-27,NaN,NaN,2015-09-25,amc,2025-10-27 07:34:06.573849+00:00
43,AAPL,2015,2,2015-07-21,NaN,NaN,2015-06-26,amc,2025-10-27 07:34:06.573849+00:00
44,AAPL,2015,1,2015-04-27,NaN,NaN,2015-03-27,amc,2025-10-27 07:34:06.573849+00:00
45,AAPL,2014,4,2015-01-27,NaN,NaN,2014-12-26,amc,2025-10-27 07:34:06.573849+00:00
46,AAPL,2014,3,2014-10-20,NaN,NaN,2014-09-26,amc,2025-10-27 07:34:06.573849+00:00
47,AAPL,2014,2,2014-07-22,NaN,NaN,2014-06-27,amc,2025-10-27 07:34:06.573849+00:00
48,AAPL,2014,1,2014-04-23,NaN,NaN,2014-03-28,amc,2025-10-27 07:34:06.573849+00:00
49,AAPL,2013,4,2014-01-27,NaN,NaN,2013-12-27,amc,2025-10-27 07:34:06.573849+00:00
50,AAPL,2013,3,2013-10-28,NaN,NaN,2013-09-27,amc,2025-10-27 07:34:06.573849+00:00
51,AAPL,2013,2,2013-07-23,NaN,NaN,2013-06-28,amc,2025-10-27 07:34:06.573849+00:00
52,AAPL,2013,1,2013-04-23,NaN,NaN,None,None,2025-10-27 07:34:06.573849+00:00
53,AAPL,2012,4,2013-01-23,NaN,NaN,2012-12-28,amc,2025-10-27 07:34:06.573849+00:00
54,AAPL,2012,3,2012-10-25,NaN,NaN,2012-09-28,amc,2025-10-27 07:34:06.573849+00:00
55,AAPL,2012,2,2012-07-24,NaN,NaN,2012-06-29,amc,2025-10-27 07:34:06.573849+00:00
56,AAPL,2012,1,2012-04-24,NaN,NaN,2012-03-30,amc,2025-10-27 07:34:06.573849+00:00
57,AAPL,2011,4,2012-01-24,NaN,NaN,2011-12-30,amc,2025-10-27 07:34:06.573849+00:00
58,AAPL,2011,3,2011-10-18,NaN,NaN,None,None,2025-10-27 07:34:06.573849+00:00
59,AAPL,2011,2,2011-07-19,NaN,NaN,2011-06-24,amc,2025-10-27 07:34:06.573849+00:00
60,AAPL,2011,1,2011-04-20,NaN,NaN,2011-03-25,amc,2025-10-27 07:34:06.573849+00:00
61,AAPL,2010,4,2011-01-18,NaN,NaN,2010-12-24,amc,2025-10-27 07:34:06.573849+00:00
62,AAPL,2010,3,2010-10-18,NaN,NaN,2010-09-24,amc,2025-10-27 07:34:06.573849+00:00
63,AAPL,2010,2,2010-07-20,NaN,NaN,2010-06-25,amc,2025-10-27 07:34:06.573849+00:00
64,AAPL,2010,1,2010-04-20,NaN,NaN,2010-03-26,amc,2025-10-27 07:34:06.573849+00:00
65,AAPL,2009,4,2010-01-25,NaN,NaN,2009-12-25,amc,2025-10-27 07:34:06.573849+00:00
66,AAPL,2009,3,2009-10-19,NaN,NaN,2009-09-25,amc,2025-10-27 07:34:06.573849+00:00
67,AAPL,2009,2,2009-07-21,NaN,NaN,2009-06-26,amc,2025-10-27 07:34:06.573849+00:00
68,AAPL,2009,1,2009-04-22,NaN,NaN,2009-03-27,amc,2025-10-27 07:34:06.573849+00:00
69,AAPL,2008,4,2009-01-21,NaN,NaN,2008-12-26,amc,2025-10-27 07:34:06.573849+00:00
70,AAPL,2008,3,2008-10-21,NaN,NaN,2008-09-26,amc,2025-10-27 07:34:06.573849+00:00
71,AAPL,2008,2,2008-07-21,NaN,NaN,2008-06-27,amc,2025-10-27 07:34:06.573849+00:00
72,AAPL,2008,1,2008-04-23,NaN,NaN,2008-03-28,amc,2025-10-27 07:34:06.573849+00:00
73,AAPL,2007,4,2008-01-22,NaN,NaN,2007-12-28,amc,2025-10-27 07:34:06.573849+00:00
74,AAPL,2007,3,2007-10-22,NaN,NaN,2007-09-28,amc,2025-10-27 07:34:06.573849+00:00
75,AAPL,2007,2,2007-07-25,NaN,NaN,2007-06-29,amc,2025-10-27 07:34:06.573849+00:00
76,AAPL,2007,1,2007-04-25,NaN,NaN,2007-03-30,amc,2025-10-27 07:34:06.573849+00:00
77,AAPL,2006,4,2007-01-17,NaN,NaN,2006-12-29,amc,2025-10-27 07:34:06.573849+00:00
78,AMZN,2026,1,2026-04-29,NaN,NaN,2026-03-30,amc,2025-10-27 07:34:06.667020+00:00
79,AMZN,2025,4,2026-02-04,NaN,NaN,2025-12-30,amc,2025-10-27 07:34:06.667020+00:00
80,AMZN,2025,3,2025-10-30,NaN,NaN,None,None,2025-10-27 07:34:06.667020+00:00
81,AMZN,2025,2,2025-07-31,2025.0,2.0,2025-06-30,amc,2025-10-27 07:34:06.667020+00:00
82,AMZN,2025,1,2025-05-01,2025.0,1.0,2025-03-31,amc,2025-10-27 07:34:06.667020+00:00
83,AMZN,2024,4,2025-02-06,2024.0,4.0,2024-12-31,amc,2025-10-27 07:34:06.667020+00:00
84,AMZN,2024,3,2024-10-31,2024.0,3.0,2024-09-30,amc,2025-10-27 07:34:06.667020+00:00
85,AMZN,2024,2,2024-08-01,2024.0,2.0,2024-06-30,amc,2025-10-27 07:34:06.667020+00:00
86,AMZN,2024,1,2024-04-30,2024.0,1.0,2024-03-31,amc,2025-10-27 07:34:06.667020+00:00
87,AMZN,2023,4,2024-02-01,2023.0,4.0,2023-12-31,amc,2025-10-27 07:34:06.667020+00:00
88,AMZN,2023,3,2023-10-26,2023.0,3.0,2023-09-30,amc,2025-10-27 07:34:06.667020+00:00
89,AMZN,2023,2,2023-08-03,2023.0,2.0,2023-06-30,amc,2025-10-27 07:34:06.667020+00:00
90,AMZN,2023,1,2023-04-27,2023.0,1.0,2023-03-31,amc,2025-10-27 07:34:06.667020+00:00
91,AMZN,2022,4,2023-02-02,2022.0,4.0,2022-12-31,amc,2025-10-27 07:34:06.667020+00:00
92,AMZN,2022,3,2022-10-27,2022.0,3.0,2022-09-30,amc,2025-10-27 07:34:06.667020+00:00
93,AMZN,2022,2,2022-07-28,2022.0,2.0,2022-06-30,amc,2025-10-27 07:34:06.667020+00:00
94,AMZN,2022,1,2022-04-28,2022.0,1.0,2022-03-31,amc,2025-10-27 07:34:06.667020+00:00
95,AMZN,2021,4,2022-02-03,2021.0,4.0,2021-12-31,amc,2025-10-27 07:34:06.667020+00:00
96,AMZN,2021,3,2021-10-28,2021.0,3.0,2021-09-30,amc,2025-10-27 07:34:06.667020+00:00
97,AMZN,2021,2,2021-07-29,2021.0,2.0,2021-06-30,amc,2025-10-27 07:34:06.667020+00:00
98,AMZN,2021,1,2021-04-29,2021.0,1.0,2021-03-31,amc,2025-10-27 07:34:06.667020+00:00
99,AMZN,2020,4,2021-02-02,2020.0,4.0,2020-12-31,amc,2025-10-27 07:34:06.667020+00:00
100,AMZN,2020,3,2020-10-29,2020.0,3.0,2020-09-30,amc,2025-10-27 07:34:06.667020+00:00
101,AMZN,2020,2,2020-07-30,NaN,NaN,2020-06-29,amc,2025-10-27 07:34:06.667020+00:00
102,AMZN,2020,1,2020-04-30,NaN,NaN,2020-03-30,amc,2025-10-27 07:34:06.667020+00:00
103,AMZN,2019,4,2020-01-30,2020.0,0.0,2020-12-31,amc,2025-10-27 07:34:06.667020+00:00
104,AMZN,2019,3,2019-10-24,NaN,NaN,2019-09-29,amc,2025-10-27 07:34:06.667020+00:00
105,AMZN,2019,2,2019-07-25,NaN,NaN,2019-06-29,amc,2025-10-27 07:34:06.667020+00:00
106,AMZN,2019,1,2019-04-25,NaN,NaN,2019-03-30,amc,2025-10-27 07:34:06.667020+00:00
107,AMZN,2018,4,2019-01-31,NaN,NaN,2018-12-30,amc,2025-10-27 07:34:06.667020+00:00
108,AMZN,2018,3,2018-10-25,NaN,NaN,2018-09-29,amc,2025-10-27 07:34:06.667020+00:00
109,AMZN,2018,2,2018-07-26,NaN,NaN,2018-06-29,amc,2025-10-27 07:34:06.667020+00:00
110,AMZN,2018,1,2018-04-26,NaN,NaN,2018-03-30,amc,2025-10-27 07:34:06.667020+00:00
111,AMZN,2017,4,2018-02-01,NaN,NaN,2017-12-30,amc,2025-10-27 07:34:06.667020+00:00
112,AMZN,2017,3,2017-10-26,NaN,NaN,2017-09-29,amc,2025-10-27 07:34:06.667020+00:00
113,AMZN,2017,2,2017-07-27,NaN,NaN,2017-06-29,amc,2025-10-27 07:34:06.667020+00:00
114,AMZN,2017,1,2017-04-27,NaN,NaN,2017-03-30,amc,2025-10-27 07:34:06.667020+00:00
115,AMZN,2016,4,2017-02-02,NaN,NaN,2016-12-30,amc,2025-10-27 07:34:06.667020+00:00
116,AMZN,2016,3,2016-10-27,NaN,NaN,2016-09-29,amc,2025-10-27 07:34:06.667020+00:00
117,AMZN,2016,2,2016-07-28,NaN,NaN,2016-06-29,amc,2025-10-27 07:34:06.667020+00:00
118,AMZN,2016,1,2016-04-28,NaN,NaN,2016-03-30,amc,2025-10-27 07:34:06.667020+00:00
119,AMZN,2015,4,2016-01-28,NaN,NaN,2015-12-30,amc,2025-10-27 07:34:06.667020+00:00
120,AMZN,2015,3,2015-10-22,NaN,NaN,2015-09-29,amc,2025-10-27 07:34:06.667020+00:00
121,AMZN,2015,2,2015-07-23,NaN,NaN,2015-06-29,amc,2025-10-27 07:34:06.667020+00:00
122,AMZN,2015,1,2015-04-23,NaN,NaN,2015-03-30,amc,2025-10-27 07:34:06.667020+00:00
123,AMZN,2014,4,2015-01-29,NaN,NaN,2014-12-30,amc,2025-10-27 07:34:06.667020+00:00
124,AMZN,2014,3,2014-10-23,NaN,NaN,2014-09-29,amc,2025-10-27 07:34:06.667020+00:00
125,AMZN,2014,2,2014-07-24,NaN,NaN,2014-06-29,amc,2025-10-27 07:34:06.667020+00:00
126,AMZN,2014,1,2014-04-24,NaN,NaN,2014-03-30,amc,2025-10-27 07:34:06.667020+00:00
127,AMZN,2013,4,2014-01-30,NaN,NaN,2013-12-30,amc,2025-10-27 07:34:06.667020+00:00
128,AMZN,2013,3,2013-10-24,NaN,NaN,2013-09-29,amc,2025-10-27 07:34:06.667020+00:00
129,AMZN,2013,2,2013-07-25,NaN,NaN,None,None,2025-10-27 07:34:06.667020+00:00
130,AMZN,2013,1,2013-04-25,NaN,NaN,2013-03-30,amc,2025-10-27 07:34:06.667020+00:00
131,AMZN,2012,4,2013-01-29,NaN,NaN,2012-12-30,amc,2025-10-27 07:34:06.667020+00:00
132,AMZN,2012,3,2012-10-25,NaN,NaN,2012-09-29,amc,2025-10-27 07:34:06.667020+00:00
133,AMZN,2012,2,2012-07-26,NaN,NaN,2012-06-29,amc,2025-10-27 07:34:06.667020+00:00
134,AMZN,2012,1,2012-04-26,NaN,NaN,2012-03-30,amc,2025-10-27 07:34:06.667020+00:00
135,AMZN,2011,4,2012-01-31,NaN,NaN,2011-12-30,amc,2025-10-27 07:34:06.667020+00:00
136,AMZN,2011,3,2011-10-25,NaN,NaN,2011-09-29,amc,2025-10-27 07:34:06.667020+00:00
137,AMZN,2011,2,2011-07-26,NaN,NaN,2011-06-29,amc,2025-10-27 07:34:06.667020+00:00
138,AMZN,2011,1,2011-04-26,NaN,NaN,2011-03-30,amc,2025-10-27 07:34:06.667020+00:00
139,AMZN,2010,4,2011-01-27,NaN,NaN,2010-12-30,amc,2025-10-27 07:34:06.667020+00:00
140,AMZN,2010,3,2010-10-21,NaN,NaN,2010-09-29,amc,2025-10-27 07:34:06.667020+00:00
141,AMZN,2010,2,2010-07-22,NaN,NaN,2010-06-29,amc,2025-10-27 07:34:06.667020+00:00
142,AMZN,2010,1,2010-04-22,NaN,NaN,2010-03-30,amc,2025-10-27 07:34:06.667020+00:00
143,AMZN,2009,4,2010-01-28,NaN,NaN,2009-12-30,amc,2025-10-27 07:34:06.667020+00:00
144,AMZN,2009,3,2009-10-22,NaN,NaN,2009-09-29,amc,2025-10-27 07:34:06.667020+00:00
145,AMZN,2009,2,2009-07-23,NaN,NaN,2009-06-29,amc,2025-10-27 07:34:06.667020+00:00
146,AMZN,2009,1,2009-04-23,NaN,NaN,2009-03-30,amc,2025-10-27 07:34:06.667020+00:00
147,AMZN,2008,4,2009-01-29,NaN,NaN,2008-12-30,amc,2025-10-27 07:34:06.667020+00:00
148,AMZN,2008,3,2008-10-22,NaN,NaN,2008-09-29,amc,2025-10-27 07:34:06.667020+00:00
149,AMZN,2008,2,2008-07-23,NaN,NaN,2008-06-29,amc,2025-10-27 07:34:06.667020+00:00
150,AMZN,2008,1,2008-04-23,NaN,NaN,2008-03-30,amc,2025-10-27 07:34:06.667020+00:00
151,AMZN,2007,4,2008-01-30,NaN,NaN,2007-12-30,amc,2025-10-27 07:34:06.667020+00:00
152,AMZN,2007,3,2007-10-23,NaN,NaN,2007-09-29,amc,2025-10-27 07:34:06.667020+00:00
153,AMZN,2007,2,2007-07-24,NaN,NaN,2007-06-29,amc,2025-10-27 07:34:06.667020+00:00
154,AMZN,2007,1,2007-04-24,NaN,NaN,2007-03-30,amc,2025-10-27 07:34:06.667020+00:00
155,AMZN,2006,4,2007-02-01,NaN,NaN,2006-12-30,bmo,2025-10-27 07:34:06.667020+00:00
156,AMZN,2006,3,2006-10-24,NaN,NaN,2006-09-29,amc,2025-10-27 07:34:06.667020+00:00
157,AMZN,2006,2,2006-07-25,NaN,NaN,2006-06-29,amc,2025-10-27 07:34:06.667020+00:00
158,AMZN,2006,1,2006-04-25,NaN,NaN,2006-03-30,amc,2025-10-27 07:34:06.667020+00:00
159,AMZN,2005,4,2006-02-02,NaN,NaN,2005-12-30,amc,2025-10-27 07:34:06.667020+00:00
160,AMZN,2005,3,2005-10-25,NaN,NaN,2005-09-29,amc,2025-10-27 07:34:06.667020+00:00
161,AMZN,2005,2,2005-07-26,NaN,NaN,2005-06-29,amc,2025-10-27 07:34:06.667020+00:00
162,AMZN,2005,1,2005-04-26,NaN,NaN,2005-03-30,amc,2025-10-27 07:34:06.667020+00:00
163,AMZN,2004,4,2005-02-02,NaN,NaN,2004-12-30,amc,2025-10-27 07:34:06.667020+00:00
164,AMZN,2004,3,2004-10-21,NaN,NaN,2004-09-29,amc,2025-10-27 07:34:06.667020+00:00
165,AMZN,2004,2,2004-07-22,NaN,NaN,2004-06-29,amc,2025-10-27 07:34:06.667020+00:00
166,AMZN,2004,1,2004-04-22,NaN,NaN,2004-03-30,amc,2025-10-27 07:34:06.667020+00:00
167,AMZN,2003,4,2004-01-27,NaN,NaN,2003-12-30,amc,2025-10-27 07:34:06.667020+00:00
168,AMZN,2003,3,2003-10-21,NaN,NaN,2003-09-29,amc,2025-10-27 07:34:06.667020+00:00
169,AMZN,2003,2,2003-07-22,NaN,NaN,2003-06-29,amc,2025-10-27 07:34:06.667020+00:00
170,AMZN,2003,1,2003-04-24,NaN,NaN,2003-03-30,amc,2025-10-27 07:34:06.667020+00:00
171,AMZN,2002,4,2003-01-23,NaN,NaN,2002-12-30,amc,2025-10-27 07:34:06.667020+00:00
172,AMZN,2002,3,2002-10-24,NaN,NaN,2002-09-29,amc,2025-10-27 07:34:06.667020+00:00
173,AMZN,2002,2,2002-07-23,NaN,NaN,2002-06-29,amc,2025-10-27 07:34:06.667020+00:00
174,AMZN,2002,1,2002-04-23,NaN,NaN,2002-03-30,amc,2025-10-27 07:34:06.667020+00:00
175,AMZN,2001,4,2002-01-22,NaN,NaN,2001-12-30,bmo,2025-10-27 07:34:06.667020+00:00
176,AMZN,2001,3,2001-10-23,NaN,NaN,2001-09-29,bmo,2025-10-27 07:34:06.667020+00:00
177,AMZN,2001,2,2001-07-23,NaN,NaN,2001-06-29,bmo,2025-10-27 07:34:06.667020+00:00
178,AMZN,2001,1,2001-04-24,NaN,NaN,2001-03-30,bmo,2025-10-27 07:34:06.667020+00:00
179,AMZN,2000,4,2001-01-30,NaN,NaN,2000-12-30,bmo,2025-10-27 07:34:06.667020+00:00
180,AMZN,2000,3,2000-10-24,NaN,NaN,2000-09-29,bmo,2025-10-27 07:34:06.667020+00:00
181,AMZN,2000,2,2000-07-26,NaN,NaN,2000-06-29,bmo,2025-10-27 07:34:06.667020+00:00
182,AMZN,2000,1,2000-04-26,NaN,NaN,2000-03-30,bmo,2025-10-27 07:34:06.667020+00:00
183,AMZN,1999,4,2000-02-02,NaN,NaN,1999-12-30,bmo,2025-10-27 07:34:06.667020+00:00
184,AMZN,1999,3,1999-10-27,NaN,NaN,1999-09-29,bmo,2025-10-27 07:34:06.667020+00:00
185,AMZN,1999,2,1999-07-21,NaN,NaN,1999-06-29,bmo,2025-10-27 07:34:06.667020+00:00
186,AMZN,1999,1,1999-04-28,NaN,NaN,1999-03-30,bmo,2025-10-27 07:34:06.667020+00:00
187,AMZN,1998,4,1999-01-26,NaN,NaN,1998-12-30,bmo,2025-10-27 07:34:06.667020+00:00
188,AMZN,1998,3,1998-10-28,NaN,NaN,1998-09-29,bmo,2025-10-27 07:34:06.667020+00:00
189,AMZN,1998,2,1998-07-22,NaN,NaN,1998-06-29,bmo,2025-10-27 07:34:06.667020+00:00
190,AMZN,1998,1,1998-04-27,NaN,NaN,1998-03-30,bmo,2025-10-27 07:34:06.667020+00:00
191,AMZN,1997,4,1998-01-22,NaN,NaN,1997-12-30,bmo,2025-10-27 07:34:06.667020+00:00
192,AMZN,1997,3,1997-10-27,NaN,NaN,1997-09-29,bmo,2025-10-27 07:34:06.667020+00:00
193,AMZN,1997,2,1997-08-14,NaN,NaN,None,None,2025-10-27 07:34:06.667020+00:00
194,HOOD,2026,1,2026-04-28,NaN,NaN,2026-03-30,amc,2025-10-27 07:34:06.715252+00:00
195,HOOD,2025,4,2026-02-10,NaN,NaN,2025-12-30,amc,2025-10-27 07:34:06.715252+00:00
196,HOOD,2025,3,2025-11-05,NaN,NaN,2025-09-30,amc,2025-10-27 07:34:06.715252+00:00
197,HOOD,2025,2,2025-07-30,2025.0,2.0,2025-06-30,amc,2025-10-27 07:34:06.715252+00:00
198,HOOD,2025,1,2025-04-30,2025.0,1.0,2025-03-31,amc,2025-10-27 07:34:06.715252+00:00
199,HOOD,2024,4,2025-02-12,2024.0,4.0,2024-12-31,amc,2025-10-27 07:34:06.715252+00:00
200,HOOD,2024,3,2024-10-30,2024.0,3.0,2024-09-30,amc,2025-10-27 07:34:06.715252+00:00
201,HOOD,2024,2,2024-08-07,2024.0,2.0,2024-06-30,amc,2025-10-27 07:34:06.715252+00:00
202,HOOD,2024,1,2024-05-08,2024.0,1.0,2024-03-31,amc,2025-10-27 07:34:06.715252+00:00
203,HOOD,2023,4,2024-02-13,2023.0,4.0,2023-12-31,amc,2025-10-27 07:34:06.715252+00:00
204,HOOD,2023,3,2023-11-07,2023.0,3.0,2023-09-30,amc,2025-10-27 07:34:06.715252+00:00
205,HOOD,2023,2,2023-08-02,2023.0,2.0,2023-06-30,amc,2025-10-27 07:34:06.715252+00:00
206,HOOD,2023,1,2023-05-10,2023.0,1.0,2023-03-31,amc,2025-10-27 07:34:06.715252+00:00
207,HOOD,2022,4,2023-02-08,2022.0,4.0,2022-12-31,amc,2025-10-27 07:34:06.715252+00:00
208,HOOD,2022,3,2022-11-02,2022.0,3.0,2022-09-30,amc,2025-10-27 07:34:06.715252+00:00
209,HOOD,2022,2,2022-08-02,2022.0,2.0,2022-06-30,amc,2025-10-27 07:34:06.715252+00:00
210,HOOD,2022,1,2022-04-28,2022.0,1.0,2022-03-31,amc,2025-10-27 07:34:06.715252+00:00
211,HOOD,2021,4,2022-01-27,2021.0,4.0,2021-12-31,amc,2025-10-27 07:34:06.715252+00:00
212,HOOD,2021,3,2021-10-26,2021.0,3.0,2021-09-30,amc,2025-10-27 07:34:06.715252+00:00
213,HOOD,2021,2,2021-08-18,2021.0,2.0,2021-06-30,amc,2025-10-27 07:34:06.715252+00:00
214,NVDA,2026,1,2026-05-26,NaN,NaN,None,None,2025-10-27 07:34:06.532772+00:00
215,NVDA,2025,4,2026-02-24,NaN,NaN,2026-01-27,amc,2025-10-27 07:34:06.532772+00:00
216,NVDA,2025,3,2025-11-19,NaN,NaN,2025-10-27,bmo,2025-10-27 07:34:06.532772+00:00
217,NVDA,2025,2,2025-08-27,2026.0,2.0,2025-07-27,amc,2025-10-27 07:34:06.532772+00:00
218,NVDA,2025,1,2025-05-28,2026.0,1.0,2025-04-27,amc,2025-10-27 07:34:06.532772+00:00
219,NVDA,2024,4,2025-02-26,2025.0,0.0,2025-01-31,amc,2025-10-27 07:34:06.532772+00:00
220,NVDA,2024,3,2024-11-20,2025.0,3.0,2024-10-27,amc,2025-10-27 07:34:06.532772+00:00
221,NVDA,2024,2,2024-08-28,2025.0,2.0,2024-07-28,amc,2025-10-27 07:34:06.532772+00:00
222,NVDA,2024,1,2024-05-22,2025.0,1.0,2024-04-28,None,2025-10-27 07:34:06.532772+00:00
223,NVDA,2023,4,2024-02-21,2024.0,0.0,2024-01-31,amc,2025-10-27 07:34:06.532772+00:00
224,NVDA,2023,3,2023-11-21,2024.0,3.0,2023-10-29,amc,2025-10-27 07:34:06.532772+00:00
225,NVDA,2023,2,2023-08-23,2024.0,2.0,2023-07-30,amc,2025-10-27 07:34:06.532772+00:00
226,NVDA,2023,1,2023-05-24,2024.0,1.0,2023-04-30,amc,2025-10-27 07:34:06.532772+00:00
227,NVDA,2022,4,2023-02-22,2023.0,0.0,2023-01-31,amc,2025-10-27 07:34:06.532772+00:00
228,NVDA,2022,3,2022-11-16,2023.0,3.0,2022-10-30,amc,2025-10-27 07:34:06.532772+00:00
229,NVDA,2022,2,2022-08-24,2023.0,2.0,2022-07-31,amc,2025-10-27 07:34:06.532772+00:00
230,NVDA,2022,1,2022-05-25,2023.0,1.0,2022-05-01,amc,2025-10-27 07:34:06.532772+00:00
231,NVDA,2021,4,2022-02-16,2022.0,0.0,2022-01-31,amc,2025-10-27 07:34:06.532772+00:00
232,NVDA,2021,3,2021-11-17,2022.0,3.0,2021-10-31,amc,2025-10-27 07:34:06.532772+00:00
233,NVDA,2021,2,2021-08-18,2022.0,2.0,2021-08-01,amc,2025-10-27 07:34:06.532772+00:00
234,NVDA,2021,1,2021-05-26,2022.0,1.0,2021-05-02,None,2025-10-27 07:34:06.532772+00:00
235,NVDA,2020,4,2021-02-24,2021.0,4.0,2021-01-31,amc,2025-10-27 07:34:06.532772+00:00
236,NVDA,2020,3,2020-11-18,2021.0,3.0,2020-10-25,amc,2025-10-27 07:34:06.532772+00:00
237,NVDA,2020,2,2020-08-19,NaN,NaN,2020-07-25,amc,2025-10-27 07:34:06.532772+00:00

In [7]:
# Query the `earnings` table
# display all records
pd.set_option('display.max_rows', None)
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.earnings_calendar ORDER BY tic, earnings_date DESC;"
    _df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(_df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_63723/1376497076.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _df = pd.read_sql_query(query, conn)

,tic,calendar_year,calendar_quarter,earnings_date,fiscal_year,fiscal_quarter,fiscal_date,session,updated_at
0,AAPL,2026,1,2026-04-26,NaN,NaN,2026-03-29,amc,2025-11-02 12:01:05.272578+00:00
1,AAPL,2025,4,2026-01-28,NaN,NaN,2025-12-28,amc,2025-11-02 12:01:05.272578+00:00
2,AAPL,2025,3,2025-10-30,NaN,NaN,None,None,2025-11-02 12:01:05.272578+00:00
3,AAPL,2025,2,2025-07-31,2025.0,3.0,2025-06-28,amc,2025-11-02 12:01:05.272578+00:00
4,AAPL,2025,1,2025-05-01,2025.0,2.0,2025-03-29,amc,2025-11-02 12:01:05.272578+00:00
5,AAPL,2024,4,2025-01-30,2025.0,1.0,2024-12-28,amc,2025-11-02 12:01:05.272578+00:00
6,AAPL,2024,3,2024-10-31,2024.0,4.0,2024-09-28,amc,2025-11-02 12:01:05.272578+00:00
7,AAPL,2024,2,2024-08-01,2024.0,3.0,2024-06-29,amc,2025-11-02 12:01:05.272578+00:00
8,AAPL,2024,1,2024-05-02,2024.0,2.0,2024-03-30,amc,2025-11-02 12:01:05.272578+00:00
9,AAPL,2023,4,2024-02-01,2024.0,1.0,2023-12-30,amc,2025-11-02 12:01:05.272578+00:00
10,AAPL,2023,3,2023-11-02,2023.0,4.0,2023-09-30,amc,2025-11-02 12:01:05.272578+00:00
11,AAPL,2023,2,2023-08-03,2023.0,3.0,2023-07-01,amc,2025-11-02 12:01:05.272578+00:00
12,AAPL,2023,1,2023-05-04,2023.0,2.0,2023-04-01,amc,2025-11-02 12:01:05.272578+00:00
13,AAPL,2022,4,2023-02-02,2023.0,1.0,2022-12-31,amc,2025-11-02 12:01:05.272578+00:00
14,AAPL,2022,3,2022-10-27,2022.0,4.0,2022-09-24,amc,2025-11-02 12:01:05.272578+00:00
15,AAPL,2022,2,2022-07-28,2022.0,3.0,2022-06-25,amc,2025-11-02 12:01:05.272578+00:00
16,AAPL,2022,1,2022-04-28,2022.0,2.0,2022-03-26,amc,2025-11-02 12:01:05.272578+00:00
17,AAPL,2021,4,2022-01-27,2022.0,1.0,2021-12-25,amc,2025-11-02 12:01:05.272578+00:00
18,AAPL,2021,3,2021-10-28,2021.0,4.0,2021-09-25,amc,2025-11-02 12:01:05.272578+00:00
19,AAPL,2021,2,2021-07-27,2021.0,3.0,2021-06-26,amc,2025-11-02 12:01:05.272578+00:00
20,AAPL,2021,1,2021-04-28,2021.0,2.0,2021-03-27,amc,2025-11-02 12:01:05.272578+00:00
21,AAPL,2020,4,2021-01-27,2021.0,1.0,2020-12-26,amc,2025-11-02 12:01:05.272578+00:00
22,AAPL,2020,3,2020-10-29,2020.0,4.0,2020-09-26,amc,2025-11-02 12:01:05.272578+00:00
23,AAPL,2020,2,2020-07-30,NaN,NaN,2020-06-26,amc,2025-11-02 12:01:05.272578+00:00
24,AAPL,2020,1,2020-04-30,NaN,NaN,2020-03-27,amc,2025-11-02 12:01:05.272578+00:00
25,AAPL,2019,4,2020-01-28,NaN,NaN,2019-12-27,amc,2025-11-02 12:01:05.272578+00:00
26,AAPL,2019,3,2019-10-30,NaN,NaN,2019-09-27,amc,2025-11-02 12:01:05.272578+00:00
27,AAPL,2019,2,2019-07-30,NaN,NaN,2019-06-28,amc,2025-11-02 12:01:05.272578+00:00
28,AAPL,2019,1,2019-04-30,NaN,NaN,2019-03-29,amc,2025-11-02 12:01:05.272578+00:00
29,AAPL,2018,4,2019-01-29,NaN,NaN,2018-12-28,amc,2025-11-02 12:01:05.272578+00:00
30,AAPL,2018,3,2018-11-01,NaN,NaN,2018-09-28,amc,2025-11-02 12:01:05.272578+00:00
31,AAPL,2018,2,2018-07-31,NaN,NaN,2018-06-29,amc,2025-11-02 12:01:05.272578+00:00
32,AAPL,2018,1,2018-05-01,NaN,NaN,2018-03-30,amc,2025-11-02 12:01:05.272578+00:00
33,AAPL,2017,4,2018-02-01,NaN,NaN,2017-12-29,amc,2025-11-02 12:01:05.272578+00:00
34,AAPL,2017,3,2017-11-02,NaN,NaN,2017-09-29,amc,2025-11-02 12:01:05.272578+00:00
35,AAPL,2017,2,2017-08-01,NaN,NaN,2017-06-30,amc,2025-11-02 12:01:05.272578+00:00
36,AAPL,2017,1,2017-05-02,NaN,NaN,2017-03-31,amc,2025-11-02 12:01:05.272578+00:00
37,AAPL,2016,4,2017-01-31,NaN,NaN,2016-12-30,amc,2025-11-02 12:01:05.272578+00:00
38,AAPL,2016,3,2016-10-25,NaN,NaN,2016-09-23,amc,2025-11-02 12:01:05.272578+00:00
39,AAPL,2016,2,2016-07-26,NaN,NaN,2016-06-24,amc,2025-11-02 12:01:05.272578+00:00
40,AAPL,2016,1,2016-04-26,NaN,NaN,2016-03-25,amc,2025-11-02 12:01:05.272578+00:00
41,AAPL,2015,4,2016-01-26,NaN,NaN,2015-12-25,amc,2025-11-02 12:01:05.272578+00:00
42,AAPL,2015,3,2015-10-27,NaN,NaN,2015-09-25,amc,2025-11-02 12:01:05.272578+00:00
43,AAPL,2015,2,2015-07-21,NaN,NaN,2015-06-26,amc,2025-11-02 12:01:05.272578+00:00
44,AAPL,2015,1,2015-04-27,NaN,NaN,2015-03-27,amc,2025-11-02 12:01:05.272578+00:00
45,AAPL,2014,4,2015-01-27,NaN,NaN,2014-12-26,amc,2025-11-02 12:01:05.272578+00:00
46,AAPL,2014,3,2014-10-20,NaN,NaN,2014-09-26,amc,2025-11-02 12:01:05.272578+00:00
47,AAPL,2014,2,2014-07-22,NaN,NaN,2014-06-27,amc,2025-11-02 12:01:05.272578+00:00
48,AAPL,2014,1,2014-04-23,NaN,NaN,2014-03-28,amc,2025-11-02 12:01:05.272578+00:00
49,AAPL,2013,4,2014-01-27,NaN,NaN,2013-12-27,amc,2025-11-02 12:01:05.272578+00:00
50,AAPL,2013,3,2013-10-28,NaN,NaN,2013-09-27,amc,2025-11-02 12:01:05.272578+00:00
51,AAPL,2013,2,2013-07-23,NaN,NaN,2013-06-28,amc,2025-11-02 12:01:05.272578+00:00
52,AAPL,2013,1,2013-04-23,NaN,NaN,None,None,2025-11-02 12:01:05.272578+00:00
53,AAPL,2012,4,2013-01-23,NaN,NaN,2012-12-28,amc,2025-11-02 12:01:05.272578+00:00
54,AAPL,2012,3,2012-10-25,NaN,NaN,2012-09-28,amc,2025-11-02 12:01:05.272578+00:00
55,AAPL,2012,2,2012-07-24,NaN,NaN,2012-06-29,amc,2025-11-02 12:01:05.272578+00:00
56,AAPL,2012,1,2012-04-24,NaN,NaN,2012-03-30,amc,2025-11-02 12:01:05.272578+00:00
57,AAPL,2011,4,2012-01-24,NaN,NaN,2011-12-30,amc,2025-11-02 12:01:05.272578+00:00
58,AAPL,2011,3,2011-10-18,NaN,NaN,None,None,2025-11-02 12:01:05.272578+00:00
59,AAPL,2011,2,2011-07-19,NaN,NaN,2011-06-24,amc,2025-11-02 12:01:05.272578+00:00
60,AAPL,2011,1,2011-04-20,NaN,NaN,2011-03-25,amc,2025-11-02 12:01:05.272578+00:00
61,AAPL,2010,4,2011-01-18,NaN,NaN,2010-12-24,amc,2025-11-02 12:01:05.272578+00:00
62,AAPL,2010,3,2010-10-18,NaN,NaN,2010-09-24,amc,2025-11-02 12:01:05.272578+00:00
63,AAPL,2010,2,2010-07-20,NaN,NaN,2010-06-25,amc,2025-11-02 12:01:05.272578+00:00
64,AAPL,2010,1,2010-04-20,NaN,NaN,2010-03-26,amc,2025-11-02 12:01:05.272578+00:00
65,AAPL,2009,4,2010-01-25,NaN,NaN,2009-12-25,amc,2025-11-02 12:01:05.272578+00:00
66,AAPL,2009,3,2009-10-19,NaN,NaN,2009-09-25,amc,2025-11-02 12:01:05.272578+00:00
67,AAPL,2009,2,2009-07-21,NaN,NaN,2009-06-26,amc,2025-11-02 12:01:05.272578+00:00
68,AAPL,2009,1,2009-04-22,NaN,NaN,2009-03-27,amc,2025-11-02 12:01:05.272578+00:00
69,AAPL,2008,4,2009-01-21,NaN,NaN,2008-12-26,amc,2025-11-02 12:01:05.272578+00:00
70,AAPL,2008,3,2008-10-21,NaN,NaN,2008-09-26,amc,2025-11-02 12:01:05.272578+00:00
71,AAPL,2008,2,2008-07-21,NaN,NaN,2008-06-27,amc,2025-11-02 12:01:05.272578+00:00
72,AAPL,2008,1,2008-04-23,NaN,NaN,2008-03-28,amc,2025-11-02 12:01:05.272578+00:00
73,AAPL,2007,4,2008-01-22,NaN,NaN,2007-12-28,amc,2025-11-02 12:01:05.272578+00:00
74,AAPL,2007,3,2007-10-22,NaN,NaN,2007-09-28,amc,2025-11-02 12:01:05.272578+00:00
75,AAPL,2007,2,2007-07-25,NaN,NaN,2007-06-29,amc,2025-11-02 12:01:05.272578+00:00
76,AAPL,2007,1,2007-04-25,NaN,NaN,2007-03-30,amc,2025-11-02 12:01:05.272578+00:00
77,AAPL,2006,4,2007-01-17,NaN,NaN,2006-12-29,amc,2025-11-02 12:01:05.272578+00:00
78,AMZN,2026,1,2026-04-29,NaN,NaN,2026-03-30,amc,2025-11-02 12:01:05.363736+00:00
79,AMZN,2025,4,2026-02-04,NaN,NaN,2025-12-30,amc,2025-11-02 12:01:05.363736+00:00
80,AMZN,2025,3,2025-10-30,NaN,NaN,None,None,2025-11-02 12:01:05.363736+00:00
81,AMZN,2025,2,2025-07-31,2025.0,2.0,2025-06-30,amc,2025-11-02 12:01:05.363736+00:00
82,AMZN,2025,1,2025-05-01,2025.0,1.0,2025-03-31,amc,2025-11-02 12:01:05.363736+00:00
83,AMZN,2024,4,2025-02-06,2024.0,4.0,2024-12-31,amc,2025-11-02 12:01:05.363736+00:00
84,AMZN,2024,3,2024-10-31,2024.0,3.0,2024-09-30,amc,2025-11-02 12:01:05.363736+00:00
85,AMZN,2024,2,2024-08-01,2024.0,2.0,2024-06-30,amc,2025-11-02 12:01:05.363736+00:00
86,AMZN,2024,1,2024-04-30,2024.0,1.0,2024-03-31,amc,2025-11-02 12:01:05.363736+00:00
87,AMZN,2023,4,2024-02-01,2023.0,4.0,2023-12-31,amc,2025-11-02 12:01:05.363736+00:00
88,AMZN,2023,3,2023-10-26,2023.0,3.0,2023-09-30,amc,2025-11-02 12:01:05.363736+00:00
89,AMZN,2023,2,2023-08-03,2023.0,2.0,2023-06-30,amc,2025-11-02 12:01:05.363736+00:00
90,AMZN,2023,1,2023-04-27,2023.0,1.0,2023-03-31,amc,2025-11-02 12:01:05.363736+00:00
91,AMZN,2022,4,2023-02-02,2022.0,4.0,2022-12-31,amc,2025-11-02 12:01:05.363736+00:00
92,AMZN,2022,3,2022-10-27,2022.0,3.0,2022-09-30,amc,2025-11-02 12:01:05.363736+00:00
93,AMZN,2022,2,2022-07-28,2022.0,2.0,2022-06-30,amc,2025-11-02 12:01:05.363736+00:00
94,AMZN,2022,1,2022-04-28,2022.0,1.0,2022-03-31,amc,2025-11-02 12:01:05.363736+00:00
95,AMZN,2021,4,2022-02-03,2021.0,4.0,2021-12-31,amc,2025-11-02 12:01:05.363736+00:00
96,AMZN,2021,3,2021-10-28,2021.0,3.0,2021-09-30,amc,2025-11-02 12:01:05.363736+00:00
97,AMZN,2021,2,2021-07-29,2021.0,2.0,2021-06-30,amc,2025-11-02 12:01:05.363736+00:00
98,AMZN,2021,1,2021-04-29,2021.0,1.0,2021-03-31,amc,2025-11-02 12:01:05.363736+00:00
99,AMZN,2020,4,2021-02-02,2020.0,4.0,2020-12-31,amc,2025-11-02 12:01:05.363736+00:00
100,AMZN,2020,3,2020-10-29,2020.0,3.0,2020-09-30,amc,2025-11-02 12:01:05.363736+00:00
101,AMZN,2020,2,2020-07-30,NaN,NaN,2020-06-29,amc,2025-11-02 12:01:05.363736+00:00
102,AMZN,2020,1,2020-04-30,NaN,NaN,2020-03-30,amc,2025-11-02 12:01:05.363736+00:00
103,AMZN,2019,4,2020-01-30,NaN,NaN,2019-12-30,amc,2025-11-02 12:01:05.363736+00:00
104,AMZN,2019,3,2019-10-24,NaN,NaN,2019-09-29,amc,2025-11-02 12:01:05.363736+00:00
105,AMZN,2019,2,2019-07-25,NaN,NaN,2019-06-29,amc,2025-11-02 12:01:05.363736+00:00
106,AMZN,2019,1,2019-04-25,NaN,NaN,2019-03-30,amc,2025-11-02 12:01:05.363736+00:00
107,AMZN,2018,4,2019-01-31,NaN,NaN,2018-12-30,amc,2025-11-02 12:01:05.363736+00:00
108,AMZN,2018,3,2018-10-25,NaN,NaN,2018-09-29,amc,2025-11-02 12:01:05.363736+00:00
109,AMZN,2018,2,2018-07-26,NaN,NaN,2018-06-29,amc,2025-11-02 12:01:05.363736+00:00
110,AMZN,2018,1,2018-04-26,NaN,NaN,2018-03-30,amc,2025-11-02 12:01:05.363736+00:00
111,AMZN,2017,4,2018-02-01,NaN,NaN,2017-12-30,amc,2025-11-02 12:01:05.363736+00:00
112,AMZN,2017,3,2017-10-26,NaN,NaN,2017-09-29,amc,2025-11-02 12:01:05.363736+00:00
113,AMZN,2017,2,2017-07-27,NaN,NaN,2017-06-29,amc,2025-11-02 12:01:05.363736+00:00
114,AMZN,2017,1,2017-04-27,NaN,NaN,2017-03-30,amc,2025-11-02 12:01:05.363736+00:00
115,AMZN,2016,4,2017-02-02,NaN,NaN,2016-12-30,amc,2025-11-02 12:01:05.363736+00:00
116,AMZN,2016,3,2016-10-27,NaN,NaN,2016-09-29,amc,2025-11-02 12:01:05.363736+00:00
117,AMZN,2016,2,2016-07-28,NaN,NaN,2016-06-29,amc,2025-11-02 12:01:05.363736+00:00
118,AMZN,2016,1,2016-04-28,NaN,NaN,2016-03-30,amc,2025-11-02 12:01:05.363736+00:00
119,AMZN,2015,4,2016-01-28,NaN,NaN,2015-12-30,amc,2025-11-02 12:01:05.363736+00:00
120,AMZN,2015,3,2015-10-22,NaN,NaN,2015-09-29,amc,2025-11-02 12:01:05.363736+00:00
121,AMZN,2015,2,2015-07-23,NaN,NaN,2015-06-29,amc,2025-11-02 12:01:05.363736+00:00
122,AMZN,2015,1,2015-04-23,NaN,NaN,2015-03-30,amc,2025-11-02 12:01:05.363736+00:00
123,AMZN,2014,4,2015-01-29,NaN,NaN,2014-12-30,amc,2025-11-02 12:01:05.363736+00:00
124,AMZN,2014,3,2014-10-23,NaN,NaN,2014-09-29,amc,2025-11-02 12:01:05.363736+00:00
125,AMZN,2014,2,2014-07-24,NaN,NaN,2014-06-29,amc,2025-11-02 12:01:05.363736+00:00
126,AMZN,2014,1,2014-04-24,NaN,NaN,2014-03-30,amc,2025-11-02 12:01:05.363736+00:00
127,AMZN,2013,4,2014-01-30,NaN,NaN,2013-12-30,amc,2025-11-02 12:01:05.363736+00:00
128,AMZN,2013,3,2013-10-24,NaN,NaN,2013-09-29,amc,2025-11-02 12:01:05.363736+00:00
129,AMZN,2013,2,2013-07-25,NaN,NaN,None,None,2025-11-02 12:01:05.363736+00:00
130,AMZN,2013,1,2013-04-25,NaN,NaN,2013-03-30,amc,2025-11-02 12:01:05.363736+00:00
131,AMZN,2012,4,2013-01-29,NaN,NaN,2012-12-30,amc,2025-11-02 12:01:05.363736+00:00
132,AMZN,2012,3,2012-10-25,NaN,NaN,2012-09-29,amc,2025-11-02 12:01:05.363736+00:00
133,AMZN,2012,2,2012-07-26,NaN,NaN,2012-06-29,amc,2025-11-02 12:01:05.363736+00:00
134,AMZN,2012,1,2012-04-26,NaN,NaN,2012-03-30,amc,2025-11-02 12:01:05.363736+00:00
135,AMZN,2011,4,2012-01-31,NaN,NaN,2011-12-30,amc,2025-11-02 12:01:05.363736+00:00
136,AMZN,2011,3,2011-10-25,NaN,NaN,2011-09-29,amc,2025-11-02 12:01:05.363736+00:00
137,AMZN,2011,2,2011-07-26,NaN,NaN,2011-06-29,amc,2025-11-02 12:01:05.363736+00:00
138,AMZN,2011,1,2011-04-26,NaN,NaN,2011-03-30,amc,2025-11-02 12:01:05.363736+00:00
139,AMZN,2010,4,2011-01-27,NaN,NaN,2010-12-30,amc,2025-11-02 12:01:05.363736+00:00
140,AMZN,2010,3,2010-10-21,NaN,NaN,2010-09-29,amc,2025-11-02 12:01:05.363736+00:00
141,AMZN,2010,2,2010-07-22,NaN,NaN,2010-06-29,amc,2025-11-02 12:01:05.363736+00:00
142,AMZN,2010,1,2010-04-22,NaN,NaN,2010-03-30,amc,2025-11-02 12:01:05.363736+00:00
143,AMZN,2009,4,2010-01-28,NaN,NaN,2009-12-30,amc,2025-11-02 12:01:05.363736+00:00
144,AMZN,2009,3,2009-10-22,NaN,NaN,2009-09-29,amc,2025-11-02 12:01:05.363736+00:00
145,AMZN,2009,2,2009-07-23,NaN,NaN,2009-06-29,amc,2025-11-02 12:01:05.363736+00:00
146,AMZN,2009,1,2009-04-23,NaN,NaN,2009-03-30,amc,2025-11-02 12:01:05.363736+00:00
147,AMZN,2008,4,2009-01-29,NaN,NaN,2008-12-30,amc,2025-11-02 12:01:05.363736+00:00
148,AMZN,2008,3,2008-10-22,NaN,NaN,2008-09-29,amc,2025-11-02 12:01:05.363736+00:00
149,AMZN,2008,2,2008-07-23,NaN,NaN,2008-06-29,amc,2025-11-02 12:01:05.363736+00:00
150,AMZN,2008,1,2008-04-23,NaN,NaN,2008-03-30,amc,2025-11-02 12:01:05.363736+00:00
151,AMZN,2007,4,2008-01-30,NaN,NaN,2007-12-30,amc,2025-11-02 12:01:05.363736+00:00
152,AMZN,2007,3,2007-10-23,NaN,NaN,2007-09-29,amc,2025-11-02 12:01:05.363736+00:00
153,AMZN,2007,2,2007-07-24,NaN,NaN,2007-06-29,amc,2025-11-02 12:01:05.363736+00:00
154,AMZN,2007,1,2007-04-24,NaN,NaN,2007-03-30,amc,2025-11-02 12:01:05.363736+00:00
155,AMZN,2006,4,2007-02-01,NaN,NaN,2006-12-30,bmo,2025-11-02 12:01:05.363736+00:00
156,AMZN,2006,3,2006-10-24,NaN,NaN,2006-09-29,amc,2025-11-02 12:01:05.363736+00:00
157,AMZN,2006,2,2006-07-25,NaN,NaN,2006-06-29,amc,2025-11-02 12:01:05.363736+00:00
158,AMZN,2006,1,2006-04-25,NaN,NaN,2006-03-30,amc,2025-11-02 12:01:05.363736+00:00
159,AMZN,2005,4,2006-02-02,NaN,NaN,2005-12-30,amc,2025-11-02 12:01:05.363736+00:00
160,AMZN,2005,3,2005-10-25,NaN,NaN,2005-09-29,amc,2025-11-02 12:01:05.363736+00:00
161,AMZN,2005,2,2005-07-26,NaN,NaN,2005-06-29,amc,2025-11-02 12:01:05.363736+00:00
162,AMZN,2005,1,2005-04-26,NaN,NaN,2005-03-30,amc,2025-11-02 12:01:05.363736+00:00
163,AMZN,2004,4,2005-02-02,NaN,NaN,2004-12-30,amc,2025-11-02 12:01:05.363736+00:00
164,AMZN,2004,3,2004-10-21,NaN,NaN,2004-09-29,amc,2025-11-02 12:01:05.363736+00:00
165,AMZN,2004,2,2004-07-22,NaN,NaN,2004-06-29,amc,2025-11-02 12:01:05.363736+00:00
166,AMZN,2004,1,2004-04-22,NaN,NaN,2004-03-30,amc,2025-11-02 12:01:05.363736+00:00
167,AMZN,2003,4,2004-01-27,NaN,NaN,2003-12-30,amc,2025-11-02 12:01:05.363736+00:00
168,AMZN,2003,3,2003-10-21,NaN,NaN,2003-09-29,amc,2025-11-02 12:01:05.363736+00:00
169,AMZN,2003,2,2003-07-22,NaN,NaN,2003-06-29,amc,2025-11-02 12:01:05.363736+00:00
170,AMZN,2003,1,2003-04-24,NaN,NaN,2003-03-30,amc,2025-11-02 12:01:05.363736+00:00
171,AMZN,2002,4,2003-01-23,NaN,NaN,2002-12-30,amc,2025-11-02 12:01:05.363736+00:00
172,AMZN,2002,3,2002-10-24,NaN,NaN,2002-09-29,amc,2025-11-02 12:01:05.363736+00:00
173,AMZN,2002,2,2002-07-23,NaN,NaN,2002-06-29,amc,2025-11-02 12:01:05.363736+00:00
174,AMZN,2002,1,2002-04-23,NaN,NaN,2002-03-30,amc,2025-11-02 12:01:05.363736+00:00
175,AMZN,2001,4,2002-01-22,NaN,NaN,2001-12-30,bmo,2025-11-02 12:01:05.363736+00:00
176,AMZN,2001,3,2001-10-23,NaN,NaN,2001-09-29,bmo,2025-11-02 12:01:05.363736+00:00
177,AMZN,2001,2,2001-07-23,NaN,NaN,2001-06-29,bmo,2025-11-02 12:01:05.363736+00:00
178,AMZN,2001,1,2001-04-24,NaN,NaN,2001-03-30,bmo,2025-11-02 12:01:05.363736+00:00
179,AMZN,2000,4,2001-01-30,NaN,NaN,2000-12-30,bmo,2025-11-02 12:01:05.363736+00:00
180,AMZN,2000,3,2000-10-24,NaN,NaN,2000-09-29,bmo,2025-11-02 12:01:05.363736+00:00
181,AMZN,2000,2,2000-07-26,NaN,NaN,2000-06-29,bmo,2025-11-02 12:01:05.363736+00:00
182,AMZN,2000,1,2000-04-26,NaN,NaN,2000-03-30,bmo,2025-11-02 12:01:05.363736+00:00
183,AMZN,1999,4,2000-02-02,NaN,NaN,1999-12-30,bmo,2025-11-02 12:01:05.363736+00:00
184,AMZN,1999,3,1999-10-27,NaN,NaN,1999-09-29,bmo,2025-11-02 12:01:05.363736+00:00
185,AMZN,1999,2,1999-07-21,NaN,NaN,1999-06-29,bmo,2025-11-02 12:01:05.363736+00:00
186,AMZN,1999,1,1999-04-28,NaN,NaN,1999-03-30,bmo,2025-11-02 12:01:05.363736+00:00
187,AMZN,1998,4,1999-01-26,NaN,NaN,1998-12-30,bmo,2025-11-02 12:01:05.363736+00:00
188,AMZN,1998,3,1998-10-28,NaN,NaN,1998-09-29,bmo,2025-11-02 12:01:05.363736+00:00
189,AMZN,1998,2,1998-07-22,NaN,NaN,1998-06-29,bmo,2025-11-02 12:01:05.363736+00:00
190,AMZN,1998,1,1998-04-27,NaN,NaN,1998-03-30,bmo,2025-11-02 12:01:05.363736+00:00
191,AMZN,1997,4,1998-01-22,NaN,NaN,1997-12-30,bmo,2025-11-02 12:01:05.363736+00:00
192,HOOD,2026,1,2026-04-28,NaN,NaN,2026-03-30,amc,2025-11-02 12:01:05.415796+00:00
193,HOOD,2025,4,2026-02-10,NaN,NaN,2025-12-30,amc,2025-11-02 12:01:05.415796+00:00
194,HOOD,2025,3,2025-11-05,NaN,NaN,2025-09-30,amc,2025-11-02 12:01:05.415796+00:00
195,HOOD,2025,2,2025-07-30,2025.0,2.0,2025-06-30,amc,2025-11-02 12:01:05.415796+00:00
196,HOOD,2025,1,2025-04-30,2025.0,1.0,2025-03-31,amc,2025-11-02 12:01:05.415796+00:00
197,HOOD,2024,4,2025-02-12,2024.0,4.0,2024-12-31,amc,2025-11-02 12:01:05.415796+00:00
198,HOOD,2024,3,2024-10-30,2024.0,3.0,2024-09-30,amc,2025-11-02 12:01:05.415796+00:00
199,HOOD,2024,2,2024-08-07,2024.0,2.0,2024-06-30,amc,2025-11-02 12:01:05.415796+00:00
200,HOOD,2024,1,2024-05-08,2024.0,1.0,2024-03-31,amc,2025-11-02 12:01:05.415796+00:00
201,HOOD,2023,4,2024-02-13,2023.0,4.0,2023-12-31,amc,2025-11-02 12:01:05.415796+00:00
202,HOOD,2023,3,2023-11-07,2023.0,3.0,2023-09-30,amc,2025-11-02 12:01:05.415796+00:00
203,HOOD,2023,2,2023-08-02,2023.0,2.0,2023-06-30,amc,2025-11-02 12:01:05.415796+00:00
204,HOOD,2023,1,2023-05-10,2023.0,1.0,2023-03-31,amc,2025-11-02 12:01:05.415796+00:00
205,HOOD,2022,4,2023-02-08,2022.0,4.0,2022-12-31,amc,2025-11-02 12:01:05.415796+00:00
206,HOOD,2022,3,2022-11-02,2022.0,3.0,2022-09-30,amc,2025-11-02 12:01:05.415796+00:00
207,HOOD,2022,2,2022-08-02,2022.0,2.0,2022-06-30,amc,2025-11-02 12:01:05.415796+00:00
208,HOOD,2022,1,2022-04-28,2022.0,1.0,2022-03-31,amc,2025-11-02 12:01:05.415796+00:00
209,HOOD,2021,4,2022-01-27,2021.0,4.0,2021-12-31,amc,2025-11-02 12:01:05.415796+00:00
210,NVDA,2026,1,2026-05-26,NaN,NaN,None,None,2025-11-02 12:01:05.235201+00:00
211,NVDA,2025,4,2026-02-24,NaN,NaN,2026-01-27,amc,2025-11-02 12:01:05.235201+00:00
212,NVDA,2025,3,2025-11-19,NaN,NaN,2025-10-27,bmo,2025-11-02 12:01:05.235201+00:00
213,NVDA,2025,2,2025-08-27,2026.0,2.0,2025-07-27,amc,2025-11-02 12:01:05.235201+00:00
214,NVDA,2025,1,2025-05-28,2026.0,1.0,2025-04-27,amc,2025-11-02 12:01:05.235201+00:00
215,NVDA,2024,4,2025-02-26,2025.0,4.0,2025-01-31,amc,2025-11-02 12:01:05.235201+00:00
216,NVDA,2024,3,2024-11-20,2025.0,3.0,2024-10-27,amc,2025-11-02 12:01:05.235201+00:00
217,NVDA,2024,2,2024-08-28,2025.0,2.0,2024-07-28,amc,2025-11-02 12:01:05.235201+00:00
218,NVDA,2024,1,2024-05-22,2025.0,1.0,2024-04-28,None,2025-11-02 12:01:05.235201+00:00
219,NVDA,2023,4,2024-02-21,2024.0,4.0,2024-01-31,amc,2025-11-02 12:01:05.235201+00:00
220,NVDA,2023,3,2023-11-21,2024.0,3.0,2023-10-29,amc,2025-11-02 12:01:05.235201+00:00
221,NVDA,2023,2,2023-08-23,2024.0,2.0,2023-07-30,amc,2025-11-02 12:01:05.235201+00:00
222,NVDA,2023,1,2023-05-24,2024.0,1.0,2023-04-30,amc,2025-11-02 12:01:05.235201+00:00
223,NVDA,2022,4,2023-02-22,2023.0,4.0,2023-01-31,amc,2025-11-02 12:01:05.235201+00:00
224,NVDA,2022,3,2022-11-16,2023.0,3.0,2022-10-30,amc,2025-11-02 12:01:05.235201+00:00
225,NVDA,2022,2,2022-08-24,2023.0,2.0,2022-07-31,amc,2025-11-02 12:01:05.235201+00:00
226,NVDA,2022,1,2022-05-25,2023.0,1.0,2022-05-01,amc,2025-11-02 12:01:05.235201+00:00
227,NVDA,2021,4,2022-02-16,2022.0,4.0,2022-01-31,amc,2025-11-02 12:01:05.235201+00:00
228,NVDA,2021,3,2021-11-17,2022.0,3.0,2021-10-31,amc,2025-11-02 12:01:05.235201+00:00
229,NVDA,2021,2,2021-08-18,2022.0,2.0,2021-08-01,amc,2025-11-02 12:01:05.235201+00:00
230,NVDA,2021,1,2021-05-26,2022.0,1.0,2021-05-02,None,2025-11-02 12:01:05.235201+00:00
231,NVDA,2020,4,2021-02-24,2021.0,4.0,2021-01-31,amc,2025-11-02 12:01:05.235201+00:00
232,NVDA,2020,3,2020-11-18,2021.0,3.0,2020-10-25,amc,2025-11-02 12:01:05.235201+00:00
233,NVDA,2020,2,2020-08-19,NaN,NaN,2020-07-25,amc,2025-11-02 12:01:05.235201+00:00
234,NVDA,2020,1,2020-05-21,NaN,NaN,None,None,2025-11-02 12:01:05.235201+00:00
235,NVDA,2019,4,2020-02-13,NaN,NaN,2020-01-25,amc,2025-11-02 12:01:05.235201+00:00
236,NVDA,2019,3,2019-11-14,NaN,NaN,2019-10-26,amc,2025-11-02 12:01:05.235201+00:00
237,NVDA,2019,2,2019-08-15,NaN,NaN,2019-07-27,amc,2025-11-02 12:01:05.235201+00:00