# Database Queries and Analysis
This notebook contains queries for various database tables, identifies potential data issues, and provides insights for further analysis.

In [1]:
# Import required libraries
import pandas as pd
import os
from utils import connect_to_db

In [134]:
# Query the `stock_metadata` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM core.net_debt_to_ebitda_metrics ORDER BY tic, calendar_year, calendar_quarter;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_50496/3814398564.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,calendar_year,calendar_quarter,net_debt_to_ebitda,net_debt_to_ebitda_ttm,net_debt_to_ebitda_qoq_growth_pct,net_debt_to_ebitda_qoq_positive_flag,net_debt_to_ebitda_qoq_count_4q,net_debt_to_ebitda_qoq_streak_length,net_debt_to_ebitda_qoq_growth_class,net_debt_to_ebitda_qoq_growth_regime,net_debt_to_ebitda_qoq_volatility_4q,net_debt_to_ebitda_qoq_volatility_flag,net_debt_to_ebitda_qoq_growth_drift,net_debt_to_ebitda_qoq_outlier_flag,net_debt_to_ebitda_qoq_stability_regime,net_debt_to_ebitda_qoq_accel,net_debt_to_ebitda_qoq_accel_count_4q,net_debt_to_ebitda_qoq_accel_positive_flag,net_debt_to_ebitda_qoq_accel_streak_length,net_debt_to_ebitda_qoq_accel_regime,net_debt_to_ebitda_yoy_growth_pct,net_debt_to_ebitda_yoy_positive_flag,net_debt_to_ebitda_yoy_count_4q,net_debt_to_ebitda_yoy_streak_length,net_debt_to_ebitda_yoy_growth_class,net_debt_to_ebitda_yoy_growth_regime,net_debt_to_ebitda_yoy_volatility_4q,net_debt_to_ebitda_yoy_volatility_flag,net_debt_to_ebitda_yoy_growth_drift,net_debt_to_ebitda_yoy_outlier_flag,net_debt_to_ebitda_yoy_stability_regime,net_debt_to_ebitda_yoy_accel,net_debt_to_ebitda_yoy_accel_count_4q,net_debt_to_ebitda_yoy_accel_positive_flag,net_debt_to_ebitda_yoy_accel_streak_length,net_debt_to_ebitda_yoy_accel_regime,net_debt_to_ebitda_ttm_growth_pct,net_debt_to_ebitda_ttm_positive_flag,net_debt_to_ebitda_ttm_count_4q,net_debt_to_ebitda_ttm_streak_length,net_debt_to_ebitda_ttm_growth_class,net_debt_to_ebitda_ttm_growth_regime,net_debt_to_ebitda_ttm_volatility_4q,net_debt_to_ebitda_ttm_volatility_flag,net_debt_to_ebitda_ttm_growth_drift,net_debt_to_ebitda_ttm_outlier_flag,net_debt_to_ebitda_ttm_stability_regime,net_debt_to_ebitda_ttm_accel,net_debt_to_ebitda_ttm_accel_count_4q,net_debt_to_ebitda_ttm_accel_positive_flag,net_debt_to_ebitda_ttm_accel_streak_length,net_debt_to_ebitda_ttm_accel_regime,raw_json_sha256,updated_at
0,AAPL,2020,3,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,64e28357f89c3e40fead8eacf089727d5b88066bcde5ef...,2025-10-24 09:35:39.858852+00:00
1,AAPL,2020,4,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,5fa0849a9f49751b923fd5754181609de9b0754786d926...,2025-10-24 09:35:39.858852+00:00
2,AAPL,2021,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,461796007dae8834585bb199336b0bccd4619ecf1a7b04...,2025-10-24 09:35:39.858852+00:00
3,AAPL,2021,2,0.525012,0.368273,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,d4e2683a4d2043c3ed1194a02a477f441125ae96341453...,2025-10-24 09:35:39.858852+00:00
4,AAPL,2021,3,0.504158,0.424740,-0.039721,0.0,NaN,0.0,Mild contraction,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,6b918ab483e5e0d1267e438a474f236f36be19032461bb...,2025-10-24 09:35:39.858852+00:00
5,AAPL,2021,4,0.449899,0.444801,-0.107623,0.0,NaN,0.0,Deep contraction,None,NaN,1.0,NaN,0.0,None,-0.067902,0.0,0.0,0.0,Deceleration,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,523dbf0791d60b03f96cdff47b36d30401a9e9a70b1437...,2025-10-24 09:35:39.858852+00:00
6,AAPL,2022,1,0.514913,0.469133,0.144508,1.0,NaN,1.0,Strong growth,None,NaN,1.0,NaN,0.0,None,0.252131,1.0,1.0,1.0,Unstable Momentum,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,122a45fccd2ab8acb679ccc9e57566098fa14b330b80a4...,2025-10-24 09:35:39.858852+00:00
7,AAPL,2022,2,0.542605,0.495252,0.053781,1.0,2.0,2.0,Strong growth,Volatile Transition,NaN,1.0,NaN,0.0,None,-0.090727,1.0,0.0,0.0,Deceleration,0.033509,1.0,NaN,1.0,Moderate growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,0.344797,1.0,NaN,1.0,Very strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,d9fe15d262b6250a78edf55a72f95fd1e080d0324b95f6...,2025-10-24 09:35:39.858852+00:00
8,AAPL,2022,3,0.539027,0.508082,-0.006594,0.0,2.0,0.0,Mild contraction,Volatile Transition,0.109980,1.0,0.012736,0.0,Volatile,-0.060375,1.0,0.0,0.0,Deceleration,0.069163,1.0,NaN,2.0,Strong growth,None,NaN,1.0,NaN,0.0,None,0.035654,1.0,1.0,1.0,Unstable Momentum,0.196219,1.0,NaN,2.0,Strong growth,None,NaN,1.0,NaN,0.0,None,-0.148578,0.0,0.0,0.0,Deceleration,0df22347bd6dc77b109ea6a71ea3b9f3eebc031aefe3a2...,2025-10-24 09:35:39.858852+00:00
9,AAPL,2022,4,0.468895,0.532514,-0.130109,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.105884,1.0,0.021018,0.0,Volatile,-0.123516,1.0,0.0,0.0,Deceleration,0.042223,1.0,NaN,3.0,Moderate growth,None,NaN,1.0,NaN,0.0,None,-0.026941,1.0,0.0,0.0,Deceleration,0.197196,1.0,NaN,3.0,Strong growth,None,NaN,1.0,NaN,0.0,None,0.000977,1.0,1.0,1.0,Unstable Momentum,87181cfe58fb765509f4aea01e642d1efc60a42944c50c...,2025-10-24 09:35:39.858852+00:00
10,AAPL,2023,1,0.429645,0.513089,-0.083707,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.115179,1.0,0.015396,0.0,Volatile,0.046403,1.0,1.0,1.0,Unstable Momentum,-0.165596,0.0,3.0,0.0,Deep contraction,Break the Streak,NaN,1.0,NaN,0.0,None,-0.207819,1.0,0.0,0.0,Deceleration,0.093696,1.0,4.0,4.0,Strong growth,Sustained Expansion,NaN,1.0,NaN,0.0,None,-0.103500,1.0,0.0,0.0,Deceleration,ce1285cb40e38e4bc28f2e6fc6e8fb5a707428c0952d3d...,2025-10-24 09:35:39.858852+00:00
11,AAPL,2023,2,0.375746,0.465810,-0.125451,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.081506,0.0,-0.041657,0.0,Structurally Deteriorating,-0.041744,1.0,0.0,0.0,Deceleration,-0.307515,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.108019,1.0,-0.005175,0.0,Volatile,-0.141919,1.0,0.0,0.0,Deceleration,-0.059449,0.0,3.0,0.0,Deep contraction,Break the Streak,0.103335,1.0,0.207977,1.0,Volatile,-0.153145,1.0,0.0,0.0,Deceleration,2b0070738c8e64af41e51ecd6a1d820830d55159ea4822...,2025-10-24 09:35:39.858852+00:00
12,AAPL,2023,3,0.390482,0.413534,0.039218,1.0,1.0,1.0,Moderate growth,Tentative Turnaround,0.057189,0.0,-0.086465,1.0,Stable but Disturbed,0.164669,2.0,1.0,1.0,Unstable Momentum,-0.275581,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.178739,1.0,-0.090431,0.0,Volatile,0.031935,1.0,1.0,1.0,Unstable Momentum,-0.186087,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.121075,1.0,0.106916,0.0,Volatile,-0.126638,1.0,0.0,0.0,Deceleration,e43e4902ee92a8533319afc19be4c3a61dfcdd8f2ab130...,2025-10-24 09:35:39.858852+00:00
13,AAPL,2023,4,0.266433,0.352703,-0.317682,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.078960,0.0,-0.075012,0.0,Structurally Deteriorating,-0.356900,2.0,0.0,0.0,Unstable Momentum,-0.431785,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.158051,1.0,-0.176617,0.0,Volatile,-0.156205,1.0,0.0,0.0,Deceleration,-0.337664,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.168635,1.0,0.011339,0.0,Volatile,-0.151577,0.0,0.0,0.0,Deceleration,398a2afea4e6d574f18bd70befb831f40e70b78ff71ee1...,2025-10-24 09:35:39.858852+00:00
14,AAPL,2024,1,0.286545,0.322805,0.075488,1.0,2.0,1.0,Strong growth,Volatile Transition,0.148055,1.0,-0.121905,0.0,Volatile,0.393169,2.0,1.0,1.0,Unstable Momentum,-0.333065,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.109528,1.0,-0.295119,1.0,Volatile,0.098720,2.0,1.0,1.0,Unstable Momentum,-0.370859,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.183535,1.0,-0.122376,0.0,Volatile,-0.033195,0.0,0.0,0.0,Deceleration,847b3f730f56643940df68e4783b983ce3684386ad6549...,2025-10-24 09:35:39.858852+00:00
15,AAPL,2024,2,0.297435,0.303843,0.038005,1.0,3.0,2.0,Moderate growth,Developing Expansion,0.179750,1.0,-0.082107,0.0,Volatile,-0.037482,2.0,0.0,0.0,Unstable Momentum,-0.208413,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.067433,0.0,-0.336987,1.0,Stable but Disturbed,0.124652,3.0,1.0,2.0,Sustained Acceleration,-0.347711,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.143943,1.0,-0.238515,1.0,Volatile,0.023148,1.0,1.0,1.0,Unstable Momentum,e0a8848fd9173ec8b4f289a862e846d1b7fd786a80075f...,2025-10-24 09:35:39.858852+00:00
16,AAPL,2024,3,0.307869,0.284680,0.035080,1.0,3.0,3.0,Moderate growth,Sustained Expansion,0.185111,1.0,-0.041243,0.0,Volatile,-0.002926,1.0,0.0,0.0,Deceleration,-0.211565,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.094602,0.0,-0.312211,1.0,Stable but Disturbed,-0.003152,2.0,0.0,0.0,Unstable Momentum,-0.311594,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.084151,1.0,-0.310580,1.0,Volatile,0.036117,2.0,1.0,2.0,Emerging Acceleration,b0185d95348a604673495548425a8a043966dd788248af...,2025-10-24 09:35:39.858852+00:00
17,AAPL,2024,4,0.313239,0.293816,0.017441,1.0,4.0,4.0,Moderate growth,Sustained Expansion,0.184522,1.0,-0.042277,0.0,Volatile,-0.017638,1.0,0.0,0.0,Deceleration,0.175677,1.0,1.0,1.0,Strong growth,Tentative Turnaround,0.107412,1.0,-0.296207,1.0,Volatile,0.387242,3.0,1.0,1.0,Choppy Acceleration,-0.166959,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.024555,0.0,-0.341957,1.0,Stable but Disturbed,0.144635,3.0,1.0,3.0,Sustained Acceleration,94fc90b0a15641e2b41ab797d1993b0f364abee769775a...,2025-10-24 09:35:39.858852+00:00
18,AAPL,2025,1,0.357813,0.312663,0.142299,1.0,4.0,5.0,Strong growth,Sustained Expansion,0.024409,0.0,0.041503,1.0,Stable but Disturbed,0.124858,1.0,1.0,1.0,Unstable Momentum,0.248712,1.0,2.0,2.0,Very strong growth,Volatile Transition,0.221098,1.0,-0.144341,0.0,Volatile,0.073035,3.0,1.0,2.0,Sustained Acceleration,-0.031420,0.0,0.0,0.0,Mild contraction,Persistent Contraction,0.091523,1.0,-0.299280,1.0,Volatile,0.135539,4.0,1.0,4.0,Sustained Acceleration,969d6aad722105b7e4e289d50a4924170875f4b6c782dc...,2025-10-24 09:35:39.858852+00:00
19,AAPL,2025,2,0.326939,0.318456,-0.086283,0.0,3.0,0.0,Deep contraction,Break the Streak,0.056793,0.0,0.058206,0.0,Stable,-0.228582,1.0,0.0,0.0,Deceleration,0.099194,1.0,3.0,3.0,Strong growth,Sustained Expansion,0.245568,1.0,0.001103,0.0,Volatile,-0.149518,2.0,0.0,0.0,Unstable Momentum,0.048095,1.0,1.0,1.0,Moderate growth,Tentative Turnaround,0.144857,1.0,-0.214421,0.0,Volatile,0.079515,4.0,1.0,5.0,Sustained Acceleration,a60e5072e0aa5cb9de466c7f16ea1fa0fdc7656b8db169...,2025-10-24 09:35:39.858852+00:00
20,NVDA,2020,3,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,cf96be553f504ec7be577579c9e600392497e4540dd79c...,2025-10-24 09:35:39.822455+00:00
21,NVDA,2020,4,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,334fba20f78ffa5ae951821abe2cafe498d816d01929c9...,2025-10-24 09:35:39.822455+00:00
22,NVDA,2021,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,79a8c3fdea06f3e0693fc52bc4ce54045c8d9e8a944b1c...,2025-10-24 09:35:39.822455+00:00
23,NVDA,2021,2,-0.893615,-0.613947,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,5502e27b8177c46726b6525fbb85783d04f1ea077af2a1...,2025-10-24 09:35:39.822455+00:00
24,NVDA,2021,3,-0.841543,-0.664022,0.058270,1.0,NaN,1.0,Strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,175edaec3242a6891cfd3715e7bfea29b40b7c4c3e2255...,2025-10-24 09:35:39.822455+00:00
25,NVDA,2021,4,-0.904061,-0.705466,-0.074290,0.0,NaN,0.0,Deep contraction,None,NaN,1.0,NaN,0.0,None,-0.132560,0.0,0.0,0.0,Deceleration,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,42c0b182aeec9bc27a3a66cd30872c16a000787a8c3736...,2025-10-24 09:35:39.822455+00:00
26,NVDA,2022,1,-0.839982,-0.798703,0.070879,1.0,NaN,1.0,Strong growth,None,NaN,1.0,NaN,0.0,None,0.145169,1.0,1.0,1.0,Unstable Momentum,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,f70e2ca5474a73f71a11356aa4bc1a5ddb3385e106a003...,2025-10-24 09:35:39.822455+00:00
27,NVDA,2022,2,-0.650566,-0.910852,0.225500,1.0,3.0,2.0,Very strong growth,Developing Expansion,NaN,1.0,NaN,0.0,None,0.154620,2.0,1.0,2.0,Emerging Acceleration,0.271983,1.0,NaN,1.0,Very strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,-0.483599,0.0,NaN,0.0,Deep contraction,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,6b1ecfad62dc6d751fa69d5cfac7bd3186a52697495b52...,2025-10-24 09:35:39.822455+00:00
28,NVDA,2022,3,-0.294600,-0.938138,0.547164,1.0,3.0,3.0,Very strong growth,Sustained Expansion,0.122662,1.0,0.070090,0.0,Volatile,0.321665,3.0,1.0,3.0,Sustained Acceleration,0.649929,1.0,NaN,2.0,Very strong growth,None,NaN,1.0,NaN,0.0,None,0.377946,1.0,1.0,1.0,Unstable Momentum,-0.412811,0.0,NaN,0.0,Deep contraction,None,NaN,1.0,NaN,0.0,None,0.070788,1.0,1.0,1.0,Unstable Momentum,e694878273d542e21cc33d9054f7d5753a1f96fb0bb563...,2025-10-24 09:35:39.822455+00:00
29,NVDA,2022,4,-0.391348,-0.835769,-0.328406,0.0,3.0,0.0,Deep contraction,Break the Streak,0.266361,1.0,0.192313,0.0,Volatile,-0.875570,3.0,0.0,0.0,Break the Streak,0.567122,1.0,NaN,3.0,Very strong growth,None,NaN,1.0,NaN,0.0,None,-0.082807,1.0,0.0,0.0,Deceleration,-0.184704,0.0,NaN,0.0,Deep contraction,None,NaN,1.0,NaN,0.0,None,0.228107,2.0,1.0,2.0,Emerging Acceleration,d098f1089272f0e6c2c4c6a01a96513fdd1a922b6bb4ff...,2025-10-24 09:35:39.822455+00:00
30,NVDA,2023,1,-0.678056,-0.582000,-0.732616,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.363672,1.0,0.128784,0.0,Volatile,-0.404210,2.0,0.0,0.0,Unstable Momentum,0.192774,1.0,4.0,4.0,Strong growth,Sustained Expansion,NaN,1.0,NaN,0.0,None,-0.374349,1.0,0.0,0.0,Deceleration,0.271318,1.0,1.0,1.0,Very strong growth,Tentative Turnaround,NaN,1.0,NaN,0.0,None,0.456023,3.0,1.0,3.0,Sustained Acceleration,fcd42a1f32e10b58931bf506c72d397a79a602bb487f6f...,2025-10-24 09:35:39.822455+00:00
31,NVDA,2023,2,-0.488556,-0.294231,0.279476,1.0,2.0,1.0,Very strong growth,Volatile Transition,0.569803,1.0,-0.072089,0.0,Volatile,1.012092,2.0,1.0,1.0,Unstable Momentum,0.249030,1.0,4.0,5.0,Very strong growth,Sustained Expansion,0.222150,1.0,0.420452,1.0,Volatile,0.056257,2.0,1.0,1.0,Unstable Momentum,0.676971,1.0,2.0,2.0,Very strong growth,Volatile Transition,0.340621,1.0,-0.202449,0.0,Volatile,0.405653,4.0,1.0,4.0,Sustained Acceleration,1a1d4b7b9cfd6831c8999f5ae293c5e1129042beec450a...,2025-10-24 09:35:39.822455+00:00
32,NVDA,2023,3,-0.376014,-0.236812,0.230356,1.0,2.0,2.0,Very strong growth,Volatile Transition,0.579752,1.0,-0.058595,0.0,Volatile,-0.049120,1.0,0.0,0.0,Deceleration,-0.276356,0.0,3.0,0.0,Deep contraction,Break the Streak,0.227496,1.0,0.414714,1.0,Volatile,-0.525386,1.0,0.0,0.0,Deceleration,0.747572,1.0,3.0,3.0,Very strong growth,Sustained Expansion,0.484999,1.0,0.087694,0.0,Volatile,0.070601,4.0,1.0,5.0,Sustained Acceleration,d36f4951141730c1ab1cbe078d569d8ea8ca3e4aece550...,2025-10-24 09:35:39.822455+00:00
33,NVDA,2023,4,-0.457381,-0.249656,-0.216394,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.482975,1.0,-0.137798,0.0,Volatile,-0.446750,1.0,0.0,0.0,Deceleration,-0.168733,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.347857,1.0,0.183143,0.0,Volatile,0.107623,2.0,1.0,1.0,Unstable Momentum,0.701286,1.0,4.0,4.0,Very strong growth,Sustained Expansion,0.429723,1.0,0.377789,0.0,Volatile,-0.046286,3.0,0.0,0.0,Break the Streak,151f2c6163fc84c16b3c5dff1be64936641f50b45910c5...,2025-10-24 09:35:39.822455+00:00
34,NVDA,2024,1,-0.428755,-0.260947,0.062588,1.0,3.0,1.0,Strong growth,Developing Expansion,0.471347,1.0,-0.109795,0.0,Volatile,0.278983,2.0,1.0,1.0,Unstable Momentum,0.367670,1.0,2.0,1.0,Very strong growth,Volatile Transition,0.260780,1.0,-0.000821,0.0,Volatile,0.536404,3.0,1.0,2.0,Sustained Acceleration,0.551638,1.0,4.0,5.0,Very strong growth,Sustained Expansion,0.220598,1.0,0.599287,1.0,Volatile,-0.149648,2.0,0.0,0.0,Unstable Momentum,a297dbf2fe510b647493d6d839fd88518584c86d4f84c8...,2025-10-24 09:35:39.822455+00:00
35,NVDA,2024,2,-0.418252,-0.289473,0.024496,1.0,3.0,2.0,Moderate growth,Developing Expansion,0.223775,1.0,0.089006,0.0,Volatile,-0.038092,1.0,0.0,0.0,Deceleration,0.143901,1.0,2.0,2.0,Strong growth,Volatile Transition,0.313411,1.0,0.042903,0.0,Volatile,-0.223770,2.0,0.0,0.0,Unstable Momentum,0.016173,1.0,4.0,6.0,Moderate growth,Sustained Expansion,0.083771,1.0,0.669367,1.0,Volatile,-0.535465,1.0,0.0,0.0,Deceleration,f17cd4cce1a241c773f57e142714bb48bb9a38fab925e4...,2025-10-24 09:35:39.822455+00:00
36,NVDA,2024,3,-0.401018,-0.315094,0.041205,1.0,3.0,3.0,Moderate growth,Sustained Expansion,0.184260,1.0,0.025261,0.0,Volatile,0.016710,2.0,1.0,1.0,Unstable Momentum,-0.066497,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.294181,1.0,0.016621,0.0,Volatile,-0.210398,2.0,0.0,0.0,Unstable Momentum,-0.330567,0.0,3.0,0.0,Deep contraction,Break the Streak,0.335903,1.0,0.504167,1.0,Volatile,-0.346741,0.0,0.0,0.0,Deceleration,27682ecca6c2631cb8d7039f22507c0f5099bf67dcf251...,2025-10-24 09:35:39.822455+00:00
37,NVDA,2024,4,-0.403392,-0.327499,-0.005921,0.0,3.0,0.0,Mild contraction,Break the Streak,0.130513,1.0,-0.022026,0.0,Volatile,-0.047127,2.0,0.0,0.0,Unstable Momentum,0.118039,1.0,3.0,1.0,Strong growth,Developing Expansion,0.237831,1.0,0.069085,0.0,Volatile,0.184536,2.0,1.0,1.0,Unstable Momentum,-0.311801,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.477994,1.0,0.234633,0.0,Volatile,0.018766,1.0,1.0,1.0,Unstable Momentum,13178eb9939454da84ca102985b5be68feccffe6d634e9...,2025-10-24 09:35:39.822455+00:00
38,NVDA,2025,1,-0.486182,-0.371938,-0.205234,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.028907,0.0,0.030592,0.0,Stable,-0.199312,1.0,0.0,0.0,Deceleration,-0.133940,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.177923,1.0,0.140778,0.0,Volatile,-0.251979,1.0,0.0,0.0,Deceleration,-0.425342,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.412178,1.0,-0.018639,0.0,Volatile,-0.113541,1.0,0.0,0.0,Deceleration,6407253cff1b9b750af9fd49c67d2f9258b315f50e09bf...,2025-10-24 09:35:39.822455+00:00
39,NVDA,2025,2,-0.484704,-0.394493,0.003040,1.0,2.0,1.0,Moderate growth,Volatile Transition,0.114258,1.0,-0.036363,0.0,Volatile,0.208273,2.0,1.0,1.0,Unstable Momentum,-0.158881,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.136695,1.0,0.015376,0.0,Volatile,-0.024941,1.0,0.0,0.0,Deceleration,-0.362801,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.192561,1.0,-0.262884,0.0,Volatile,0.062542,2.0,1.0,1.0,Unstable Momentum,de9ec5572a800201a84897ea11ee7fb06266dfc2baed65...,2025-10-24 09:35:39.822455+00:00
40,TSLA,2020,3,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,89d579d9204d572bb32ffebef744c459ca7339f00c5ba2...,2025-10-24 09:35:39.879763+00:00

In [135]:
# show all columns
pd.set_option('display.max_columns', None)
df[df['tic'] == 'AAPL'].iloc[-20:]

,tic,calendar_year,calendar_quarter,net_debt_to_ebitda,net_debt_to_ebitda_ttm,net_debt_to_ebitda_qoq_growth_pct,net_debt_to_ebitda_qoq_positive_flag,net_debt_to_ebitda_qoq_count_4q,net_debt_to_ebitda_qoq_streak_length,net_debt_to_ebitda_qoq_growth_class,net_debt_to_ebitda_qoq_growth_regime,net_debt_to_ebitda_qoq_volatility_4q,net_debt_to_ebitda_qoq_volatility_flag,net_debt_to_ebitda_qoq_growth_drift,net_debt_to_ebitda_qoq_outlier_flag,net_debt_to_ebitda_qoq_stability_regime,net_debt_to_ebitda_qoq_accel,net_debt_to_ebitda_qoq_accel_count_4q,net_debt_to_ebitda_qoq_accel_positive_flag,net_debt_to_ebitda_qoq_accel_streak_length,net_debt_to_ebitda_qoq_accel_regime,net_debt_to_ebitda_yoy_growth_pct,net_debt_to_ebitda_yoy_positive_flag,net_debt_to_ebitda_yoy_count_4q,net_debt_to_ebitda_yoy_streak_length,net_debt_to_ebitda_yoy_growth_class,net_debt_to_ebitda_yoy_growth_regime,net_debt_to_ebitda_yoy_volatility_4q,net_debt_to_ebitda_yoy_volatility_flag,net_debt_to_ebitda_yoy_growth_drift,net_debt_to_ebitda_yoy_outlier_flag,net_debt_to_ebitda_yoy_stability_regime,net_debt_to_ebitda_yoy_accel,net_debt_to_ebitda_yoy_accel_count_4q,net_debt_to_ebitda_yoy_accel_positive_flag,net_debt_to_ebitda_yoy_accel_streak_length,net_debt_to_ebitda_yoy_accel_regime,net_debt_to_ebitda_ttm_growth_pct,net_debt_to_ebitda_ttm_positive_flag,net_debt_to_ebitda_ttm_count_4q,net_debt_to_ebitda_ttm_streak_length,net_debt_to_ebitda_ttm_growth_class,net_debt_to_ebitda_ttm_growth_regime,net_debt_to_ebitda_ttm_volatility_4q,net_debt_to_ebitda_ttm_volatility_flag,net_debt_to_ebitda_ttm_growth_drift,net_debt_to_ebitda_ttm_outlier_flag,net_debt_to_ebitda_ttm_stability_regime,net_debt_to_ebitda_ttm_accel,net_debt_to_ebitda_ttm_accel_count_4q,net_debt_to_ebitda_ttm_accel_positive_flag,net_debt_to_ebitda_ttm_accel_streak_length,net_debt_to_ebitda_ttm_accel_regime,raw_json_sha256,updated_at
0,AAPL,2020,3,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,64e28357f89c3e40fead8eacf089727d5b88066bcde5ef...,2025-10-24 09:35:39.858852+00:00
1,AAPL,2020,4,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,5fa0849a9f49751b923fd5754181609de9b0754786d926...,2025-10-24 09:35:39.858852+00:00
2,AAPL,2021,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,461796007dae8834585bb199336b0bccd4619ecf1a7b04...,2025-10-24 09:35:39.858852+00:00
3,AAPL,2021,2,0.525012,0.368273,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,d4e2683a4d2043c3ed1194a02a477f441125ae96341453...,2025-10-24 09:35:39.858852+00:00
4,AAPL,2021,3,0.504158,0.424740,-0.039721,0.0,NaN,0.0,Mild contraction,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,6b918ab483e5e0d1267e438a474f236f36be19032461bb...,2025-10-24 09:35:39.858852+00:00
5,AAPL,2021,4,0.449899,0.444801,-0.107623,0.0,NaN,0.0,Deep contraction,None,NaN,1.0,NaN,0.0,None,-0.067902,0.0,0.0,0.0,Deceleration,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,523dbf0791d60b03f96cdff47b36d30401a9e9a70b1437...,2025-10-24 09:35:39.858852+00:00
6,AAPL,2022,1,0.514913,0.469133,0.144508,1.0,NaN,1.0,Strong growth,None,NaN,1.0,NaN,0.0,None,0.252131,1.0,1.0,1.0,Unstable Momentum,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,122a45fccd2ab8acb679ccc9e57566098fa14b330b80a4...,2025-10-24 09:35:39.858852+00:00
7,AAPL,2022,2,0.542605,0.495252,0.053781,1.0,2.0,2.0,Strong growth,Volatile Transition,NaN,1.0,NaN,0.0,None,-0.090727,1.0,0.0,0.0,Deceleration,0.033509,1.0,NaN,1.0,Moderate growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,0.344797,1.0,NaN,1.0,Very strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,d9fe15d262b6250a78edf55a72f95fd1e080d0324b95f6...,2025-10-24 09:35:39.858852+00:00
8,AAPL,2022,3,0.539027,0.508082,-0.006594,0.0,2.0,0.0,Mild contraction,Volatile Transition,0.109980,1.0,0.012736,0.0,Volatile,-0.060375,1.0,0.0,0.0,Deceleration,0.069163,1.0,NaN,2.0,Strong growth,None,NaN,1.0,NaN,0.0,None,0.035654,1.0,1.0,1.0,Unstable Momentum,0.196219,1.0,NaN,2.0,Strong growth,None,NaN,1.0,NaN,0.0,None,-0.148578,0.0,0.0,0.0,Deceleration,0df22347bd6dc77b109ea6a71ea3b9f3eebc031aefe3a2...,2025-10-24 09:35:39.858852+00:00
9,AAPL,2022,4,0.468895,0.532514,-0.130109,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.105884,1.0,0.021018,0.0,Volatile,-0.123516,1.0,0.0,0.0,Deceleration,0.042223,1.0,NaN,3.0,Moderate growth,None,NaN,1.0,NaN,0.0,None,-0.026941,1.0,0.0,0.0,Deceleration,0.197196,1.0,NaN,3.0,Strong growth,None,NaN,1.0,NaN,0.0,None,0.000977,1.0,1.0,1.0,Unstable Momentum,87181cfe58fb765509f4aea01e642d1efc60a42944c50c...,2025-10-24 09:35:39.858852+00:00
10,AAPL,2023,1,0.429645,0.513089,-0.083707,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.115179,1.0,0.015396,0.0,Volatile,0.046403,1.0,1.0,1.0,Unstable Momentum,-0.165596,0.0,3.0,0.0,Deep contraction,Break the Streak,NaN,1.0,NaN,0.0,None,-0.207819,1.0,0.0,0.0,Deceleration,0.093696,1.0,4.0,4.0,Strong growth,Sustained Expansion,NaN,1.0,NaN,0.0,None,-0.103500,1.0,0.0,0.0,Deceleration,ce1285cb40e38e4bc28f2e6fc6e8fb5a707428c0952d3d...,2025-10-24 09:35:39.858852+00:00
11,AAPL,2023,2,0.375746,0.465810,-0.125451,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.081506,0.0,-0.041657,0.0,Structurally Deteriorating,-0.041744,1.0,0.0,0.0,Deceleration,-0.307515,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.108019,1.0,-0.005175,0.0,Volatile,-0.141919,1.0,0.0,0.0,Deceleration,-0.059449,0.0,3.0,0.0,Deep contraction,Break the Streak,0.103335,1.0,0.207977,1.0,Volatile,-0.153145,1.0,0.0,0.0,Deceleration,2b0070738c8e64af41e51ecd6a1d820830d55159ea4822...,2025-10-24 09:35:39.858852+00:00
12,AAPL,2023,3,0.390482,0.413534,0.039218,1.0,1.0,1.0,Moderate growth,Tentative Turnaround,0.057189,0.0,-0.086465,1.0,Stable but Disturbed,0.164669,2.0,1.0,1.0,Unstable Momentum,-0.275581,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.178739,1.0,-0.090431,0.0,Volatile,0.031935,1.0,1.0,1.0,Unstable Momentum,-0.186087,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.121075,1.0,0.106916,0.0,Volatile,-0.126638,1.0,0.0,0.0,Deceleration,e43e4902ee92a8533319afc19be4c3a61dfcdd8f2ab130...,2025-10-24 09:35:39.858852+00:00
13,AAPL,2023,4,0.266433,0.352703,-0.317682,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.078960,0.0,-0.075012,0.0,Structurally Deteriorating,-0.356900,2.0,0.0,0.0,Unstable Momentum,-0.431785,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.158051,1.0,-0.176617,0.0,Volatile,-0.156205,1.0,0.0,0.0,Deceleration,-0.337664,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.168635,1.0,0.011339,0.0,Volatile,-0.151577,0.0,0.0,0.0,Deceleration,398a2afea4e6d574f18bd70befb831f40e70b78ff71ee1...,2025-10-24 09:35:39.858852+00:00
14,AAPL,2024,1,0.286545,0.322805,0.075488,1.0,2.0,1.0,Strong growth,Volatile Transition,0.148055,1.0,-0.121905,0.0,Volatile,0.393169,2.0,1.0,1.0,Unstable Momentum,-0.333065,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.109528,1.0,-0.295119,1.0,Volatile,0.098720,2.0,1.0,1.0,Unstable Momentum,-0.370859,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.183535,1.0,-0.122376,0.0,Volatile,-0.033195,0.0,0.0,0.0,Deceleration,847b3f730f56643940df68e4783b983ce3684386ad6549...,2025-10-24 09:35:39.858852+00:00
15,AAPL,2024,2,0.297435,0.303843,0.038005,1.0,3.0,2.0,Moderate growth,Developing Expansion,0.179750,1.0,-0.082107,0.0,Volatile,-0.037482,2.0,0.0,0.0,Unstable Momentum,-0.208413,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.067433,0.0,-0.336987,1.0,Stable but Disturbed,0.124652,3.0,1.0,2.0,Sustained Acceleration,-0.347711,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.143943,1.0,-0.238515,1.0,Volatile,0.023148,1.0,1.0,1.0,Unstable Momentum,e0a8848fd9173ec8b4f289a862e846d1b7fd786a80075f...,2025-10-24 09:35:39.858852+00:00
16,AAPL,2024,3,0.307869,0.284680,0.035080,1.0,3.0,3.0,Moderate growth,Sustained Expansion,0.185111,1.0,-0.041243,0.0,Volatile,-0.002926,1.0,0.0,0.0,Deceleration,-0.211565,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.094602,0.0,-0.312211,1.0,Stable but Disturbed,-0.003152,2.0,0.0,0.0,Unstable Momentum,-0.311594,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.084151,1.0,-0.310580,1.0,Volatile,0.036117,2.0,1.0,2.0,Emerging Acceleration,b0185d95348a604673495548425a8a043966dd788248af...,2025-10-24 09:35:39.858852+00:00
17,AAPL,2024,4,0.313239,0.293816,0.017441,1.0,4.0,4.0,Moderate growth,Sustained Expansion,0.184522,1.0,-0.042277,0.0,Volatile,-0.017638,1.0,0.0,0.0,Deceleration,0.175677,1.0,1.0,1.0,Strong growth,Tentative Turnaround,0.107412,1.0,-0.296207,1.0,Volatile,0.387242,3.0,1.0,1.0,Choppy Acceleration,-0.166959,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.024555,0.0,-0.341957,1.0,Stable but Disturbed,0.144635,3.0,1.0,3.0,Sustained Acceleration,94fc90b0a15641e2b41ab797d1993b0f364abee769775a...,2025-10-24 09:35:39.858852+00:00
18,AAPL,2025,1,0.357813,0.312663,0.142299,1.0,4.0,5.0,Strong growth,Sustained Expansion,0.024409,0.0,0.041503,1.0,Stable but Disturbed,0.124858,1.0,1.0,1.0,Unstable Momentum,0.248712,1.0,2.0,2.0,Very strong growth,Volatile Transition,0.221098,1.0,-0.144341,0.0,Volatile,0.073035,3.0,1.0,2.0,Sustained Acceleration,-0.031420,0.0,0.0,0.0,Mild contraction,Persistent Contraction,0.091523,1.0,-0.299280,1.0,Volatile,0.135539,4.0,1.0,4.0,Sustained Acceleration,969d6aad722105b7e4e289d50a4924170875f4b6c782dc...,2025-10-24 09:35:39.858852+00:00
19,AAPL,2025,2,0.326939,0.318456,-0.086283,0.0,3.0,0.0,Deep contraction,Break the Streak,0.056793,0.0,0.058206,0.0,Stable,-0.228582,1.0,0.0,0.0,Deceleration,0.099194,1.0,3.0,3.0,Strong growth,Sustained Expansion,0.245568,1.0,0.001103,0.0,Volatile,-0.149518,2.0,0.0,0.0,Unstable Momentum,0.048095,1.0,1.0,1.0,Moderate growth,Tentative Turnaround,0.144857,1.0,-0.214421,0.0,Volatile,0.079515,4.0,1.0,5.0,Sustained Acceleration,a60e5072e0aa5cb9de466c7f16ea1fa0fdc7656b8db169...,2025-10-24 09:35:39.858852+00:00

In [136]:
df[df['tic'] == 'TSLA'].iloc[-20:]

,tic,calendar_year,calendar_quarter,net_debt_to_ebitda,net_debt_to_ebitda_ttm,net_debt_to_ebitda_qoq_growth_pct,net_debt_to_ebitda_qoq_positive_flag,net_debt_to_ebitda_qoq_count_4q,net_debt_to_ebitda_qoq_streak_length,net_debt_to_ebitda_qoq_growth_class,net_debt_to_ebitda_qoq_growth_regime,net_debt_to_ebitda_qoq_volatility_4q,net_debt_to_ebitda_qoq_volatility_flag,net_debt_to_ebitda_qoq_growth_drift,net_debt_to_ebitda_qoq_outlier_flag,net_debt_to_ebitda_qoq_stability_regime,net_debt_to_ebitda_qoq_accel,net_debt_to_ebitda_qoq_accel_count_4q,net_debt_to_ebitda_qoq_accel_positive_flag,net_debt_to_ebitda_qoq_accel_streak_length,net_debt_to_ebitda_qoq_accel_regime,net_debt_to_ebitda_yoy_growth_pct,net_debt_to_ebitda_yoy_positive_flag,net_debt_to_ebitda_yoy_count_4q,net_debt_to_ebitda_yoy_streak_length,net_debt_to_ebitda_yoy_growth_class,net_debt_to_ebitda_yoy_growth_regime,net_debt_to_ebitda_yoy_volatility_4q,net_debt_to_ebitda_yoy_volatility_flag,net_debt_to_ebitda_yoy_growth_drift,net_debt_to_ebitda_yoy_outlier_flag,net_debt_to_ebitda_yoy_stability_regime,net_debt_to_ebitda_yoy_accel,net_debt_to_ebitda_yoy_accel_count_4q,net_debt_to_ebitda_yoy_accel_positive_flag,net_debt_to_ebitda_yoy_accel_streak_length,net_debt_to_ebitda_yoy_accel_regime,net_debt_to_ebitda_ttm_growth_pct,net_debt_to_ebitda_ttm_positive_flag,net_debt_to_ebitda_ttm_count_4q,net_debt_to_ebitda_ttm_streak_length,net_debt_to_ebitda_ttm_growth_class,net_debt_to_ebitda_ttm_growth_regime,net_debt_to_ebitda_ttm_volatility_4q,net_debt_to_ebitda_ttm_volatility_flag,net_debt_to_ebitda_ttm_growth_drift,net_debt_to_ebitda_ttm_outlier_flag,net_debt_to_ebitda_ttm_stability_regime,net_debt_to_ebitda_ttm_accel,net_debt_to_ebitda_ttm_accel_count_4q,net_debt_to_ebitda_ttm_accel_positive_flag,net_debt_to_ebitda_ttm_accel_streak_length,net_debt_to_ebitda_ttm_accel_regime,raw_json_sha256,updated_at
40,TSLA,2020,3,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,89d579d9204d572bb32ffebef744c459ca7339f00c5ba2...,2025-10-24 09:35:39.879763+00:00
41,TSLA,2020,4,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,943ac1ea931f2728fc9ce433dcc89c177de3a8936b946e...,2025-10-24 09:35:39.879763+00:00
42,TSLA,2021,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,b758ed2e9daea189b77268094c3475fbc0b98be89a3d4f...,2025-10-24 09:35:39.879763+00:00
43,TSLA,2021,2,-1.414230,-1.170600,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,e62fac5508660c3e835bb3f00a38399c91a2aa67dc29f5...,2025-10-24 09:35:39.879763+00:00
44,TSLA,2021,3,-1.291906,-1.180544,0.086495,1.0,NaN,1.0,Strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,f9e535af8fa7348a23720fe164b89fdbc79d01f299698b...,2025-10-24 09:35:39.879763+00:00
45,TSLA,2021,4,-1.284675,-0.981558,0.005597,1.0,NaN,2.0,Moderate growth,None,NaN,1.0,NaN,0.0,None,-0.080898,0.0,0.0,0.0,Deceleration,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,2c134232da19b8df98104bd8e7c141379c14caa2ee806e...,2025-10-24 09:35:39.879763+00:00
46,TSLA,2022,1,-1.127753,-0.863185,0.122149,1.0,NaN,3.0,Strong growth,None,NaN,1.0,NaN,0.0,None,0.116552,1.0,1.0,1.0,Unstable Momentum,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,1a053d11910c5154b280b77b87920e9047c20b5c39990f...,2025-10-24 09:35:39.879763+00:00
47,TSLA,2022,2,-1.100000,-0.910136,0.024609,1.0,4.0,4.0,Moderate growth,Sustained Expansion,NaN,1.0,NaN,0.0,None,-0.097540,1.0,0.0,0.0,Deceleration,0.222191,1.0,NaN,1.0,Very strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,0.222505,1.0,NaN,1.0,Very strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,1d1788257148f8fed0557c8aa5336c95c1373b5436d80d...,2025-10-24 09:35:39.879763+00:00
48,TSLA,2022,3,-1.154511,-0.947643,-0.049555,0.0,3.0,0.0,Mild contraction,Break the Streak,0.054087,0.0,0.059713,0.0,Stable,-0.074165,1.0,0.0,0.0,Deceleration,0.106351,1.0,NaN,2.0,Strong growth,None,NaN,1.0,NaN,0.0,None,-0.115840,0.0,0.0,0.0,Deceleration,0.197283,1.0,NaN,2.0,Strong growth,None,NaN,1.0,NaN,0.0,None,-0.025222,0.0,0.0,0.0,Deceleration,8265a2cca494c9d9c66c32be120dbaf6dd0bb7f7592678...,2025-10-24 09:35:39.879763+00:00
49,TSLA,2022,4,-1.140624,-0.979852,0.012028,1.0,3.0,1.0,Moderate growth,Developing Expansion,0.071580,0.0,0.025700,0.0,Stable,0.061583,2.0,1.0,1.0,Unstable Momentum,0.112130,1.0,NaN,3.0,Strong growth,None,NaN,1.0,NaN,0.0,None,0.005780,1.0,1.0,1.0,Unstable Momentum,0.001738,1.0,NaN,3.0,Moderate growth,None,NaN,1.0,NaN,0.0,None,-0.195545,0.0,0.0,0.0,Deceleration,ab345e1f58d5551628e000053f87fa072e0b4f85ed40ba...,2025-10-24 09:35:39.879763+00:00
50,TSLA,2023,1,-1.217212,-1.109092,-0.067146,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.071048,0.0,0.027308,0.0,Stable,-0.079174,1.0,0.0,0.0,Deceleration,-0.079325,0.0,3.0,0.0,Deep contraction,Break the Streak,NaN,1.0,NaN,0.0,None,-0.191455,1.0,0.0,0.0,Deceleration,-0.284884,0.0,3.0,0.0,Deep contraction,Break the Streak,NaN,1.0,NaN,0.0,None,-0.286622,0.0,0.0,0.0,Deceleration,f51dfa9349f4fbf1f17274ba7fcc7738eaba39406b16e3...,2025-10-24 09:35:39.879763+00:00
51,TSLA,2023,2,-1.221718,-1.148492,-0.003702,0.0,1.0,0.0,Mild contraction,Persistent Contraction,0.045137,0.0,-0.020016,0.0,Structurally Deteriorating,0.063443,2.0,1.0,1.0,Unstable Momentum,-0.110653,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.125036,1.0,0.090337,0.0,Volatile,-0.031328,1.0,0.0,0.0,Deceleration,-0.261891,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.234466,1.0,0.034161,0.0,Volatile,0.022993,1.0,1.0,1.0,Unstable Momentum,78f7f189a17b6b23f888926a88a17bc3575264983ac689...,2025-10-24 09:35:39.879763+00:00
52,TSLA,2023,3,-1.371147,-1.298017,-0.122310,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.037356,0.0,-0.027094,0.0,Structurally Deteriorating,-0.118608,2.0,0.0,0.0,Unstable Momentum,-0.187643,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.118627,1.0,0.007126,0.0,Volatile,-0.076990,1.0,0.0,0.0,Deceleration,-0.369733,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.229809,1.0,-0.086938,0.0,Volatile,-0.107842,1.0,0.0,0.0,Deceleration,35ab1acde746be6cc2874d82ad509bfa4fb2ebcfe7f84b...,2025-10-24 09:35:39.879763+00:00
53,TSLA,2023,4,-1.651595,-1.504055,-0.204536,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.061711,0.0,-0.045282,0.0,Structurally Deteriorating,-0.082226,1.0,0.0,0.0,Deceleration,-0.447975,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.127408,1.0,-0.066373,0.0,Volatile,-0.260332,0.0,0.0,0.0,Deceleration,-0.534982,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.160468,1.0,-0.228692,0.0,Volatile,-0.165249,1.0,0.0,0.0,Deceleration,1a85c22f2ca47a3355b6af056a4c2d1f2af16658112073...,2025-10-24 09:35:39.879763+00:00
54,TSLA,2024,1,-1.593868,-1.637341,0.034952,1.0,1.0,1.0,Moderate growth,Tentative Turnaround,0.085199,0.0,-0.099423,0.0,Structurally Deteriorating,0.239488,2.0,1.0,1.0,Unstable Momentum,-0.309442,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.167358,1.0,-0.206399,0.0,Volatile,0.138533,1.0,1.0,1.0,Unstable Momentum,-0.476289,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.123758,1.0,-0.362872,1.0,Volatile,0.058693,2.0,1.0,1.0,Unstable Momentum,b34e7e653c24b3a51eb3def50b2447c45229de7d4a81a0...,2025-10-24 09:35:39.879763+00:00
55,TSLA,2024,2,-1.806776,-1.782120,-0.133580,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.109827,1.0,-0.073899,0.0,Volatile,-0.168532,1.0,0.0,0.0,Deceleration,-0.478881,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.147487,1.0,-0.263928,1.0,Volatile,-0.169439,1.0,0.0,0.0,Deceleration,-0.551704,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.120513,1.0,-0.410724,1.0,Volatile,-0.075415,1.0,0.0,0.0,Deceleration,5731c55df78e7a94b73cf67aab147f7b57637e0f9a45ed...,2025-10-24 09:35:39.879763+00:00
56,TSLA,2024,3,-1.898077,-1.735615,-0.050533,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.101000,1.0,-0.106368,0.0,Volatile,0.083047,2.0,1.0,1.0,Unstable Momentum,-0.384299,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.134252,1.0,-0.355985,1.0,Volatile,0.094582,2.0,1.0,1.0,Unstable Momentum,-0.337128,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.082253,1.0,-0.483177,1.0,Volatile,0.214576,2.0,1.0,1.0,Unstable Momentum,f9739fe951b55c45697c3a63443490118120dbc08c984a...,2025-10-24 09:35:39.879763+00:00
57,TSLA,2024,4,-1.950299,-1.704685,-0.027513,0.0,1.0,0.0,Mild contraction,Persistent Contraction,0.103567,1.0,-0.088424,0.0,Volatile,0.023020,3.0,1.0,2.0,Sustained Acceleration,-0.180858,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.074978,0.0,-0.405149,1.0,Stable but Disturbed,0.203441,3.0,1.0,2.0,Sustained Acceleration,-0.133392,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.097454,1.0,-0.475026,1.0,Volatile,0.203735,3.0,1.0,2.0,Sustained Acceleration,c9728c3cc6c95e4897843211020230943551141a4e9a22...,2025-10-24 09:35:39.879763+00:00
58,TSLA,2025,1,-2.131232,-1.935047,-0.092772,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.069695,0.0,-0.044168,0.0,Structurally Deteriorating,-0.065259,2.0,0.0,0.0,Unstable Momentum,-0.337145,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.125830,1.0,-0.338370,1.0,Volatile,-0.156287,2.0,0.0,0.0,Unstable Momentum,-0.181823,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.183750,1.0,-0.374628,1.0,Volatile,-0.048431,2.0,0.0,0.0,Unstable Momentum,efebbecfa45320c7fa13d2d44fb40bec70c7e30a93c48c...,2025-10-24 09:35:39.879763+00:00
59,TSLA,2025,2,-2.164913,-2.078119,-0.015803,0.0,0.0,0.0,Mild contraction,Persistent Contraction,0.046891,0.0,-0.076099,1.0,Stable but Disturbed,0.076969,3.0,1.0,1.0,Choppy Acceleration,-0.198219,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.124462,1.0,-0.345296,1.0,Volatile,0.138926,3.0,1.0,1.0,Choppy Acceleration,-0.166094,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.188373,1.0,-0.301012,1.0,Volatile,0.015729,3.0,1.0,1.0,Choppy Acceleration,eb73dd51497282d57f445a56b5cc535d9660494b5905b1...,2025-10-24 09:35:39.879763+00:00

In [137]:
# show all columns
pd.set_option('display.max_columns', None)
df[df['tic'] == 'NVDA'].iloc[-20:]

,tic,calendar_year,calendar_quarter,net_debt_to_ebitda,net_debt_to_ebitda_ttm,net_debt_to_ebitda_qoq_growth_pct,net_debt_to_ebitda_qoq_positive_flag,net_debt_to_ebitda_qoq_count_4q,net_debt_to_ebitda_qoq_streak_length,net_debt_to_ebitda_qoq_growth_class,net_debt_to_ebitda_qoq_growth_regime,net_debt_to_ebitda_qoq_volatility_4q,net_debt_to_ebitda_qoq_volatility_flag,net_debt_to_ebitda_qoq_growth_drift,net_debt_to_ebitda_qoq_outlier_flag,net_debt_to_ebitda_qoq_stability_regime,net_debt_to_ebitda_qoq_accel,net_debt_to_ebitda_qoq_accel_count_4q,net_debt_to_ebitda_qoq_accel_positive_flag,net_debt_to_ebitda_qoq_accel_streak_length,net_debt_to_ebitda_qoq_accel_regime,net_debt_to_ebitda_yoy_growth_pct,net_debt_to_ebitda_yoy_positive_flag,net_debt_to_ebitda_yoy_count_4q,net_debt_to_ebitda_yoy_streak_length,net_debt_to_ebitda_yoy_growth_class,net_debt_to_ebitda_yoy_growth_regime,net_debt_to_ebitda_yoy_volatility_4q,net_debt_to_ebitda_yoy_volatility_flag,net_debt_to_ebitda_yoy_growth_drift,net_debt_to_ebitda_yoy_outlier_flag,net_debt_to_ebitda_yoy_stability_regime,net_debt_to_ebitda_yoy_accel,net_debt_to_ebitda_yoy_accel_count_4q,net_debt_to_ebitda_yoy_accel_positive_flag,net_debt_to_ebitda_yoy_accel_streak_length,net_debt_to_ebitda_yoy_accel_regime,net_debt_to_ebitda_ttm_growth_pct,net_debt_to_ebitda_ttm_positive_flag,net_debt_to_ebitda_ttm_count_4q,net_debt_to_ebitda_ttm_streak_length,net_debt_to_ebitda_ttm_growth_class,net_debt_to_ebitda_ttm_growth_regime,net_debt_to_ebitda_ttm_volatility_4q,net_debt_to_ebitda_ttm_volatility_flag,net_debt_to_ebitda_ttm_growth_drift,net_debt_to_ebitda_ttm_outlier_flag,net_debt_to_ebitda_ttm_stability_regime,net_debt_to_ebitda_ttm_accel,net_debt_to_ebitda_ttm_accel_count_4q,net_debt_to_ebitda_ttm_accel_positive_flag,net_debt_to_ebitda_ttm_accel_streak_length,net_debt_to_ebitda_ttm_accel_regime,raw_json_sha256,updated_at
20,NVDA,2020,3,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,cf96be553f504ec7be577579c9e600392497e4540dd79c...,2025-10-24 09:35:39.822455+00:00
21,NVDA,2020,4,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,334fba20f78ffa5ae951821abe2cafe498d816d01929c9...,2025-10-24 09:35:39.822455+00:00
22,NVDA,2021,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,79a8c3fdea06f3e0693fc52bc4ce54045c8d9e8a944b1c...,2025-10-24 09:35:39.822455+00:00
23,NVDA,2021,2,-0.893615,-0.613947,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,5502e27b8177c46726b6525fbb85783d04f1ea077af2a1...,2025-10-24 09:35:39.822455+00:00
24,NVDA,2021,3,-0.841543,-0.664022,0.058270,1.0,NaN,1.0,Strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,175edaec3242a6891cfd3715e7bfea29b40b7c4c3e2255...,2025-10-24 09:35:39.822455+00:00
25,NVDA,2021,4,-0.904061,-0.705466,-0.074290,0.0,NaN,0.0,Deep contraction,None,NaN,1.0,NaN,0.0,None,-0.132560,0.0,0.0,0.0,Deceleration,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,42c0b182aeec9bc27a3a66cd30872c16a000787a8c3736...,2025-10-24 09:35:39.822455+00:00
26,NVDA,2022,1,-0.839982,-0.798703,0.070879,1.0,NaN,1.0,Strong growth,None,NaN,1.0,NaN,0.0,None,0.145169,1.0,1.0,1.0,Unstable Momentum,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,f70e2ca5474a73f71a11356aa4bc1a5ddb3385e106a003...,2025-10-24 09:35:39.822455+00:00
27,NVDA,2022,2,-0.650566,-0.910852,0.225500,1.0,3.0,2.0,Very strong growth,Developing Expansion,NaN,1.0,NaN,0.0,None,0.154620,2.0,1.0,2.0,Emerging Acceleration,0.271983,1.0,NaN,1.0,Very strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,-0.483599,0.0,NaN,0.0,Deep contraction,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,6b1ecfad62dc6d751fa69d5cfac7bd3186a52697495b52...,2025-10-24 09:35:39.822455+00:00
28,NVDA,2022,3,-0.294600,-0.938138,0.547164,1.0,3.0,3.0,Very strong growth,Sustained Expansion,0.122662,1.0,0.070090,0.0,Volatile,0.321665,3.0,1.0,3.0,Sustained Acceleration,0.649929,1.0,NaN,2.0,Very strong growth,None,NaN,1.0,NaN,0.0,None,0.377946,1.0,1.0,1.0,Unstable Momentum,-0.412811,0.0,NaN,0.0,Deep contraction,None,NaN,1.0,NaN,0.0,None,0.070788,1.0,1.0,1.0,Unstable Momentum,e694878273d542e21cc33d9054f7d5753a1f96fb0bb563...,2025-10-24 09:35:39.822455+00:00
29,NVDA,2022,4,-0.391348,-0.835769,-0.328406,0.0,3.0,0.0,Deep contraction,Break the Streak,0.266361,1.0,0.192313,0.0,Volatile,-0.875570,3.0,0.0,0.0,Break the Streak,0.567122,1.0,NaN,3.0,Very strong growth,None,NaN,1.0,NaN,0.0,None,-0.082807,1.0,0.0,0.0,Deceleration,-0.184704,0.0,NaN,0.0,Deep contraction,None,NaN,1.0,NaN,0.0,None,0.228107,2.0,1.0,2.0,Emerging Acceleration,d098f1089272f0e6c2c4c6a01a96513fdd1a922b6bb4ff...,2025-10-24 09:35:39.822455+00:00
30,NVDA,2023,1,-0.678056,-0.582000,-0.732616,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.363672,1.0,0.128784,0.0,Volatile,-0.404210,2.0,0.0,0.0,Unstable Momentum,0.192774,1.0,4.0,4.0,Strong growth,Sustained Expansion,NaN,1.0,NaN,0.0,None,-0.374349,1.0,0.0,0.0,Deceleration,0.271318,1.0,1.0,1.0,Very strong growth,Tentative Turnaround,NaN,1.0,NaN,0.0,None,0.456023,3.0,1.0,3.0,Sustained Acceleration,fcd42a1f32e10b58931bf506c72d397a79a602bb487f6f...,2025-10-24 09:35:39.822455+00:00
31,NVDA,2023,2,-0.488556,-0.294231,0.279476,1.0,2.0,1.0,Very strong growth,Volatile Transition,0.569803,1.0,-0.072089,0.0,Volatile,1.012092,2.0,1.0,1.0,Unstable Momentum,0.249030,1.0,4.0,5.0,Very strong growth,Sustained Expansion,0.222150,1.0,0.420452,1.0,Volatile,0.056257,2.0,1.0,1.0,Unstable Momentum,0.676971,1.0,2.0,2.0,Very strong growth,Volatile Transition,0.340621,1.0,-0.202449,0.0,Volatile,0.405653,4.0,1.0,4.0,Sustained Acceleration,1a1d4b7b9cfd6831c8999f5ae293c5e1129042beec450a...,2025-10-24 09:35:39.822455+00:00
32,NVDA,2023,3,-0.376014,-0.236812,0.230356,1.0,2.0,2.0,Very strong growth,Volatile Transition,0.579752,1.0,-0.058595,0.0,Volatile,-0.049120,1.0,0.0,0.0,Deceleration,-0.276356,0.0,3.0,0.0,Deep contraction,Break the Streak,0.227496,1.0,0.414714,1.0,Volatile,-0.525386,1.0,0.0,0.0,Deceleration,0.747572,1.0,3.0,3.0,Very strong growth,Sustained Expansion,0.484999,1.0,0.087694,0.0,Volatile,0.070601,4.0,1.0,5.0,Sustained Acceleration,d36f4951141730c1ab1cbe078d569d8ea8ca3e4aece550...,2025-10-24 09:35:39.822455+00:00
33,NVDA,2023,4,-0.457381,-0.249656,-0.216394,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.482975,1.0,-0.137798,0.0,Volatile,-0.446750,1.0,0.0,0.0,Deceleration,-0.168733,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.347857,1.0,0.183143,0.0,Volatile,0.107623,2.0,1.0,1.0,Unstable Momentum,0.701286,1.0,4.0,4.0,Very strong growth,Sustained Expansion,0.429723,1.0,0.377789,0.0,Volatile,-0.046286,3.0,0.0,0.0,Break the Streak,151f2c6163fc84c16b3c5dff1be64936641f50b45910c5...,2025-10-24 09:35:39.822455+00:00
34,NVDA,2024,1,-0.428755,-0.260947,0.062588,1.0,3.0,1.0,Strong growth,Developing Expansion,0.471347,1.0,-0.109795,0.0,Volatile,0.278983,2.0,1.0,1.0,Unstable Momentum,0.367670,1.0,2.0,1.0,Very strong growth,Volatile Transition,0.260780,1.0,-0.000821,0.0,Volatile,0.536404,3.0,1.0,2.0,Sustained Acceleration,0.551638,1.0,4.0,5.0,Very strong growth,Sustained Expansion,0.220598,1.0,0.599287,1.0,Volatile,-0.149648,2.0,0.0,0.0,Unstable Momentum,a297dbf2fe510b647493d6d839fd88518584c86d4f84c8...,2025-10-24 09:35:39.822455+00:00
35,NVDA,2024,2,-0.418252,-0.289473,0.024496,1.0,3.0,2.0,Moderate growth,Developing Expansion,0.223775,1.0,0.089006,0.0,Volatile,-0.038092,1.0,0.0,0.0,Deceleration,0.143901,1.0,2.0,2.0,Strong growth,Volatile Transition,0.313411,1.0,0.042903,0.0,Volatile,-0.223770,2.0,0.0,0.0,Unstable Momentum,0.016173,1.0,4.0,6.0,Moderate growth,Sustained Expansion,0.083771,1.0,0.669367,1.0,Volatile,-0.535465,1.0,0.0,0.0,Deceleration,f17cd4cce1a241c773f57e142714bb48bb9a38fab925e4...,2025-10-24 09:35:39.822455+00:00
36,NVDA,2024,3,-0.401018,-0.315094,0.041205,1.0,3.0,3.0,Moderate growth,Sustained Expansion,0.184260,1.0,0.025261,0.0,Volatile,0.016710,2.0,1.0,1.0,Unstable Momentum,-0.066497,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.294181,1.0,0.016621,0.0,Volatile,-0.210398,2.0,0.0,0.0,Unstable Momentum,-0.330567,0.0,3.0,0.0,Deep contraction,Break the Streak,0.335903,1.0,0.504167,1.0,Volatile,-0.346741,0.0,0.0,0.0,Deceleration,27682ecca6c2631cb8d7039f22507c0f5099bf67dcf251...,2025-10-24 09:35:39.822455+00:00
37,NVDA,2024,4,-0.403392,-0.327499,-0.005921,0.0,3.0,0.0,Mild contraction,Break the Streak,0.130513,1.0,-0.022026,0.0,Volatile,-0.047127,2.0,0.0,0.0,Unstable Momentum,0.118039,1.0,3.0,1.0,Strong growth,Developing Expansion,0.237831,1.0,0.069085,0.0,Volatile,0.184536,2.0,1.0,1.0,Unstable Momentum,-0.311801,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.477994,1.0,0.234633,0.0,Volatile,0.018766,1.0,1.0,1.0,Unstable Momentum,13178eb9939454da84ca102985b5be68feccffe6d634e9...,2025-10-24 09:35:39.822455+00:00
38,NVDA,2025,1,-0.486182,-0.371938,-0.205234,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.028907,0.0,0.030592,0.0,Stable,-0.199312,1.0,0.0,0.0,Deceleration,-0.133940,0.0,2.0,0.0,Deep contraction,Volatile Transition,0.177923,1.0,0.140778,0.0,Volatile,-0.251979,1.0,0.0,0.0,Deceleration,-0.425342,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.412178,1.0,-0.018639,0.0,Volatile,-0.113541,1.0,0.0,0.0,Deceleration,6407253cff1b9b750af9fd49c67d2f9258b315f50e09bf...,2025-10-24 09:35:39.822455+00:00
39,NVDA,2025,2,-0.484704,-0.394493,0.003040,1.0,2.0,1.0,Moderate growth,Volatile Transition,0.114258,1.0,-0.036363,0.0,Volatile,0.208273,2.0,1.0,1.0,Unstable Momentum,-0.158881,0.0,1.0,0.0,Deep contraction,Persistent Contraction,0.136695,1.0,0.015376,0.0,Volatile,-0.024941,1.0,0.0,0.0,Deceleration,-0.362801,0.0,0.0,0.0,Deep contraction,Persistent Contraction,0.192561,1.0,-0.262884,0.0,Volatile,0.062542,2.0,1.0,1.0,Unstable Momentum,de9ec5572a800201a84897ea11ee7fb06266dfc2baed65...,2025-10-24 09:35:39.822455+00:00

In [ ]:
# Query the `stock_metadata` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM ref.analyst_grade_mapping;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_50496/1276403154.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,grade_original,grade_normalized,grade_value,embedding,embedding_model,updated_at
0,Accumulate,Buy,1,"[0.021994438,-0.010606739,-0.026823653,0.02983...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
1,Buy,Buy,1,"[0.013307652,0.0018098907,-0.016714925,0.02211...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
2,Cautious,Sell,-1,"[0.07097276,0.014074118,-0.03134117,0.03204137...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
3,Conviction Buy,Buy,1,"[0.035139497,-0.009668649,-0.08012893,0.057709...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
4,Equal-Weight,Hold,0,"[0.01411509,-0.001065873,0.0069798343,0.015768...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
5,Hold,Hold,0,"[0.010647982,0.0045143007,-0.0073389737,0.0565...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
6,Market Outperform,Buy,1,"[0.008356333,-0.00037922408,0.0005379851,0.015...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
7,Market Perform,Hold,0,"[0.0059731966,-0.014726226,0.009962985,0.02020...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
8,Mixed,Hold,0,"[0.026912231,-0.016637964,0.016003037,0.022554...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
9,Negative,Sell,-1,"[0.015303398,0.028422648,0.0010292074,0.079606...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
10,Neutral,Hold,0,"[0.008783124,-0.0058232183,-0.017662844,0.0291...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
11,Outperform,Buy,1,"[0.01911879,-0.035348017,-0.016257282,0.038097...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
12,Overweight,Buy,1,"[0.026835654,-0.013410705,-0.01705004,0.022234...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
13,Peer Perform,Hold,0,"[-0.016047036,-0.028197816,-0.002109831,0.0300...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
14,Perform,Hold,0,"[0.017376823,0.032655314,-0.035383146,-0.00039...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
15,Positive,Buy,1,"[0.011372726,-0.015875166,-0.010312497,0.11043...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
16,Strong Buy,Buy,1,"[0.012168606,-0.02478337,-0.036325913,0.030626...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
17,Underperform,Sell,-1,"[-0.004060448,0.009102315,0.00022850819,0.0200...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
18,Underweight,Sell,-1,"[-0.012776745,-0.012667073,-0.026801003,0.0145...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
19,Bullish,Buy,1,"[-0.0009197371,-0.05542714,0.0067347637,0.0734...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
20,Bull,Buy,1,"[0.0031811735,-0.050425023,0.014893592,0.03721...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
21,Bearish,Sell,-1,"[0.016768347,-0.02005301,0.017099574,0.0439703...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
22,Bear,Sell,-1,"[0.054880824,-0.022204472,-0.028076448,0.09549...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
23,Excellent,Buy,1,"[0.009670962,0.0026107144,0.00594137,0.0109995...",text-embedding-3-small,2025-10-16 03:30:54.945472+00:00
24,Reduce,Sell,-1,"[0.0107038105,0.036149397,-0.022418894,0.02009...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
25,Sector Perform,Hold,0,"[0.015174964,-0.02369002,0.007932897,0.0129782...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
26,Sector Weight,Hold,0,"[0.037847746,0.006732391,0.040599246,-0.008957...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00
27,Sell,Sell,-1,"[0.0046439413,-0.004978138,-0.027404128,0.0067...",text-embedding-3-small,2025-10-16 03:14:31.486524+00:00

In [5]:
# Query the `stock_metadata` table
conn = connect_to_db()
# show all columns
pd.set_option('display.max_columns', None)
if conn:
    query = "SELECT * FROM core.earnings_metrics WHERE tic = 'TSLA' ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_47105/1312202028.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,inference_id,event_id,tic,calendar_year,calendar_quarter,eps,eps_estimated,revenue,revenue_estimated,eps_regime,eps_surprise_pct,eps_beat_flag,eps_beat_count_4q,eps_beat_streak_length,eps_surprise_class,eps_surprise_regime,revenue_surprise_pct,revenue_beat_flag,revenue_beat_count_4q,revenue_beat_streak_length,revenue_surprise_class,revenue_surprise_regime,raw_json_sha256,updated_at
0,dbd8c631-de05-4d6a-989e-3e20849b729b,05c32905-2b12-491e-94e0-9c883acd55df,TSLA,2025,3,0.5000,0.5580,2.809500e+10,2.654037e+10,positive growth,-0.103943,0,1,0,major miss,consistent miss,0.058576,1,2,2,moderate beat,emerging beat,663f84ecd07aab576a70697601880a07f4915e33381a7d...,2025-10-27 08:18:49.902736+00:00
1,81537ea2-b785-4752-bd47-fd34f22760f0,cc937b5b-ffe3-46a2-9074-06ed0f184524,TSLA,2025,2,0.4000,0.3972,2.249600e+10,2.227968e+10,positive growth,0.007049,1,2,1,in-line (positive),mixed performance,0.009709,1,1,1,in-line (positive),consistent miss,b0edb44569113fa1a8cc24340f790212af2b9928387157...,2025-10-27 08:18:49.902736+00:00
2,f62de7e0-87da-4dc8-aa7b-83530d730f51,4f6df69f-2dae-4048-998c-f787b28af700,TSLA,2025,1,0.2700,0.4136,1.933500e+10,2.126950e+10,profit decline,-0.347195,0,1,0,major miss,consistent miss,-0.090952,0,1,0,major miss,consistent miss,0092509ab4d1595475a93f9a805084db97f0c53f843154...,2025-10-27 08:18:49.902736+00:00
3,ac8c5899-f223-4636-a569-0fc05572bc49,e80609f5-bf85-4744-ad7e-3e5617319265,TSLA,2024,4,0.7300,0.7740,2.570700e+10,2.725892e+10,positive growth,-0.056848,0,1,0,major miss,consistent miss,-0.056933,0,1,0,major miss,consistent miss,dc231e537902b094383bc63cf81555cba2093e7b09011a...,2025-10-27 08:18:49.902736+00:00
4,16942542-8f03-4083-b5b7-2584df9f2da3,48327f9e-3dec-4f9a-9878-a8d5824ce8be,TSLA,2024,3,0.7200,0.5800,2.518200e+10,2.546837e+10,positive growth,0.241379,1,1,1,major beat,consistent miss,-0.011244,0,1,0,slight miss,consistent miss,3d349970bc8e94dd075fc8afdd9fee5ca0d444b93557df...,2025-10-27 08:18:49.902736+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,3768516f-ef13-4014-9745-6c41035c6eb5,730c5e08-0a8c-45ce-967f-f0cfa482b5c4,TSLA,2011,3,-0.0400,-0.0376,5.766600e+07,6.189636e+07,flat,-0.063830,0,0,0,major miss,consistent miss,-0.068346,0,1,0,major miss,consistent miss,281f591b4cf9ef46ae6d0305d906cf1e420104080251e1...,2025-10-27 08:18:49.902736+00:00
57,bb0e4d77-c7ea-476f-8cd6-0c5cc0a5a109,602d6b34-a4e7-457c-b6c6-e04a7380b428,TSLA,2011,2,-0.0400,-0.0382,5.817100e+07,5.600377e+07,loss widening,-0.047120,0,0,0,slight miss,consistent miss,0.038698,1,1,1,moderate beat,consistent miss,a83a6fb7234e43e680eb34dae90bd2815b41f6ea636ddd...,2025-10-27 08:18:49.902736+00:00
58,a056053f-94ec-4913-9519-ed3a62e01ef4,0e18722f-9e2b-4cff-9437-0577e3898817,TSLA,2011,1,-0.0300,-0.0262,4.903000e+07,5.679545e+07,flat,-0.145038,0,0,0,major miss,consistent miss,-0.136727,0,0,0,major miss,consistent miss,371f975d0c7b150fc4c88f2af18b295333cebb04f9002e...,2025-10-27 08:18:49.902736+00:00
59,5ad9a005-53b1-4cfa-976e-a0cfb5d5a54d,e00edb8f-c4ab-4d12-b4ad-1032a495530a,TSLA,2010,4,-0.0300,-0.0284,3.628600e+07,3.861702e+07,loss widening,-0.056338,0,0,0,major miss,consistent miss,-0.060363,0,0,0,major miss,consistent miss,1f9901f654588898e56a1cc6424faf8d3788eb91f33064...,2025-10-27 08:18:49.902736+00:00
60,9bf451cb-626b-48d6-afc4-af4397e41ae1,cf173b9a-9615-4cbc-91e7-9693ea919366,TSLA,2010,3,-0.0252,NaN,3.124100e+07,NaN,unknown,NaN,0,0,0,unknown,consistent miss,NaN,0,0,0,unknown,consistent miss,6fcbeb42885443297049a77dbb8ecc85178ab0ec4c2bd9...,2025-10-27 08:18:49.902736+00:00

In [7]:
# Query the `stock_metadata` table
conn = connect_to_db()
# show all columns
pd.set_option('display.max_columns', None)
if conn:
    query = "SELECT * FROM core.revenue_metrics WHERE tic = 'TSLA' ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_47105/1037978008.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,inference_id,event_id,tic,calendar_year,calendar_quarter,revenue,revenue_ttm,revenue_qoq_growth_pct,revenue_qoq_positive_flag,revenue_qoq_count_4q,revenue_qoq_streak_length,revenue_qoq_growth_class,revenue_qoq_growth_regime,revenue_qoq_volatility_4q,revenue_qoq_volatility_flag,revenue_qoq_growth_drift,revenue_qoq_outlier_flag,revenue_qoq_stability_regime,revenue_qoq_accel,revenue_qoq_accel_count_4q,revenue_qoq_accel_positive_flag,revenue_qoq_accel_streak_length,revenue_qoq_accel_regime,revenue_yoy_growth_pct,revenue_yoy_positive_flag,revenue_yoy_count_4q,revenue_yoy_streak_length,revenue_yoy_growth_class,revenue_yoy_growth_regime,revenue_yoy_volatility_4q,revenue_yoy_volatility_flag,revenue_yoy_growth_drift,revenue_yoy_outlier_flag,revenue_yoy_stability_regime,revenue_yoy_accel,revenue_yoy_accel_count_4q,revenue_yoy_accel_positive_flag,revenue_yoy_accel_streak_length,revenue_yoy_accel_regime,revenue_ttm_growth_pct,revenue_ttm_positive_flag,revenue_ttm_count_4q,revenue_ttm_streak_length,revenue_ttm_growth_class,revenue_ttm_growth_regime,revenue_ttm_volatility_4q,revenue_ttm_volatility_flag,revenue_ttm_growth_drift,revenue_ttm_outlier_flag,revenue_ttm_stability_regime,revenue_ttm_accel,revenue_ttm_accel_count_4q,revenue_ttm_accel_positive_flag,revenue_ttm_accel_streak_length,revenue_ttm_accel_regime,raw_json_sha256,updated_at
0,4b2531d7-30b8-4050-82db-206b748dde86,dfc5cddf-2c02-4ebc-b082-0a3ab68d3104,TSLA,2026,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,03aa7ad8a5fd4ee8715f2303a7880d4f38e7f1605e1d97...,2025-10-27 08:23:15.776901+00:00
1,bd590600-e168-4eed-8787-1fa308798fd1,dcb60a11-78bc-4c13-9e9a-4433febd2d0e,TSLA,2025,4,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,1207227a76b1f8f48825c3eb7a265d79b69392ef9820a4...,2025-10-27 08:23:15.776901+00:00
2,0906f5a5-9dbc-42ea-8693-66acc4ce2fce,05c32905-2b12-491e-94e0-9c883acd55df,TSLA,2025,3,2.809500e+10,9.563300e+10,0.248889,1.0,3.0,2.0,strong growth,developing expansion,0.170600,1.0,-0.019002,0.0,volatile,0.085403,3.0,1.0,2.0,sustained acceleration,0.115678,1.0,2.0,1.0,strong growth,volatile transition,0.093054,1.0,-0.027546,0.0,volatile,0.233482,1.0,1.0,1.0,unstable momentum,-0.015615,0.0,2.0,0.0,mild contraction,volatile transition,0.019111,0.0,0.001333,0.0,stable,0.011641,2.0,1.0,1.0,unstable momentum,663f84ecd07aab576a70697601880a07f4915e33381a7d...,2025-10-27 08:23:15.776901+00:00
3,bd8296d0-f825-4f3d-ab5d-fbe3fe11ccc1,cc937b5b-ffe3-46a2-9074-06ed0f184524,TSLA,2025,2,2.249600e+10,9.272000e+10,0.163486,1.0,2.0,1.0,strong growth,volatile transition,0.182976,1.0,-0.010591,0.0,volatile,0.411356,2.0,1.0,1.0,unstable momentum,-0.117804,0.0,2.0,0.0,deep contraction,volatile transition,0.071714,1.0,0.007651,0.0,volatile,-0.025508,1.0,0.0,0.0,deceleration,-0.027256,0.0,3.0,0.0,mild contraction,break the streak,0.002000,0.0,0.011577,1.0,stable but disturbed,-0.037589,1.0,0.0,0.0,deceleration,b0edb44569113fa1a8cc24340f790212af2b9928387157...,2025-10-27 08:23:15.776901+00:00
4,730f2c52-4d0a-4c95-811c-8f96130bda1a,4f6df69f-2dae-4048-998c-f787b28af700,TSLA,2025,1,1.933500e+10,9.572400e+10,-0.247870,0.0,2.0,0.0,deep contraction,volatile transition,0.144191,1.0,0.012973,0.0,volatile,-0.268718,2.0,0.0,0.0,unstable momentum,-0.092296,0.0,3.0,0.0,mild contraction,break the streak,0.069229,1.0,0.008993,0.0,volatile,-0.113753,2.0,0.0,0.0,unstable momentum,0.010333,1.0,4.0,50.0,moderate growth,sustained expansion,0.044660,1.0,0.034303,0.0,volatile,0.000857,1.0,1.0,1.0,unstable momentum,0092509ab4d1595475a93f9a805084db97f0c53f843154...,2025-10-27 08:23:15.776901+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,3851fe1a-cd8f-4a36-baa2-7710ba543457,730c5e08-0a8c-45ce-967f-f0cfa482b5c4,TSLA,2011,3,5.766600e+07,2.011530e+08,-0.008681,0.0,3.0,0.0,mild contraction,break the streak,NaN,1.0,NaN,0.0,None,-0.195118,1.0,0.0,0.0,deceleration,0.845844,1.0,NaN,1.0,very strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,281f591b4cf9ef46ae6d0305d906cf1e420104080251e1...,2025-10-27 08:23:15.776901+00:00
59,7ad472f6-c72e-4aa1-af08-735bce261bdb,602d6b34-a4e7-457c-b6c6-e04a7380b428,TSLA,2011,2,5.817100e+07,1.747280e+08,0.186437,1.0,NaN,3.0,strong growth,None,NaN,1.0,NaN,0.0,None,-0.164773,1.0,0.0,0.0,deceleration,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,a83a6fb7234e43e680eb34dae90bd2815b41f6ea636ddd...,2025-10-27 08:23:15.776901+00:00
60,e38f7ae6-ca47-46cb-8977-8d6b08e5b5a1,0e18722f-9e2b-4cff-9437-0577e3898817,TSLA,2011,1,4.903000e+07,NaN,0.351210,1.0,NaN,2.0,very strong growth,None,NaN,1.0,NaN,0.0,None,0.189723,1.0,1.0,1.0,unstable momentum,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,371f975d0c7b150fc4c88f2af18b295333cebb04f9002e...,2025-10-27 08:23:15.776901+00:00
61,9b07e15a-341b-4504-8816-6f8e1c438875,e00edb8f-c4ab-4d12-b4ad-1032a495530a,TSLA,2010,4,3.628600e+07,NaN,0.161487,1.0,NaN,1.0,strong growth,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,1f9901f654588898e56a1cc6424faf8d3788eb91f33064...,2025-10-27 08:23:15.776901+00:00
62,64e31c41-d128-471c-9c93-8f5e6f123923,cf173b9a-9615-4cbc-91e7-9693ea919366,TSLA,2010,3,3.124100e+07,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,6fcbeb42885443297049a77dbb8ecc85178ab0ec4c2bd9...,2025-10-27 08:23:15.776901+00:00

In [9]:
# Query the `stock_metadata` table
conn = connect_to_db()
# show all columns
pd.set_option('display.max_columns', None)
if conn:
    query = "SELECT * FROM core.earnings_metrics WHERE tic = 'TSLA' ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_47105/1312202028.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,inference_id,event_id,tic,calendar_year,calendar_quarter,eps,eps_estimated,revenue,revenue_estimated,eps_regime,eps_surprise_pct,eps_beat_flag,eps_beat_count_4q,eps_beat_streak_length,eps_surprise_class,eps_surprise_regime,revenue_surprise_pct,revenue_beat_flag,revenue_beat_count_4q,revenue_beat_streak_length,revenue_surprise_class,revenue_surprise_regime,raw_json_sha256,updated_at
0,dbd8c631-de05-4d6a-989e-3e20849b729b,05c32905-2b12-491e-94e0-9c883acd55df,TSLA,2025,3,0.5000,0.5580,2.809500e+10,2.654037e+10,positive growth,-0.103943,0,1,0,major miss,consistent miss,0.058576,1,2,2,moderate beat,emerging beat,663f84ecd07aab576a70697601880a07f4915e33381a7d...,2025-10-27 08:18:49.902736+00:00
1,81537ea2-b785-4752-bd47-fd34f22760f0,cc937b5b-ffe3-46a2-9074-06ed0f184524,TSLA,2025,2,0.4000,0.3972,2.249600e+10,2.227968e+10,positive growth,0.007049,1,2,1,in-line (positive),mixed performance,0.009709,1,1,1,in-line (positive),consistent miss,b0edb44569113fa1a8cc24340f790212af2b9928387157...,2025-10-27 08:18:49.902736+00:00
2,f62de7e0-87da-4dc8-aa7b-83530d730f51,4f6df69f-2dae-4048-998c-f787b28af700,TSLA,2025,1,0.2700,0.4136,1.933500e+10,2.126950e+10,profit decline,-0.347195,0,1,0,major miss,consistent miss,-0.090952,0,1,0,major miss,consistent miss,0092509ab4d1595475a93f9a805084db97f0c53f843154...,2025-10-27 08:18:49.902736+00:00
3,ac8c5899-f223-4636-a569-0fc05572bc49,e80609f5-bf85-4744-ad7e-3e5617319265,TSLA,2024,4,0.7300,0.7740,2.570700e+10,2.725892e+10,positive growth,-0.056848,0,1,0,major miss,consistent miss,-0.056933,0,1,0,major miss,consistent miss,dc231e537902b094383bc63cf81555cba2093e7b09011a...,2025-10-27 08:18:49.902736+00:00
4,16942542-8f03-4083-b5b7-2584df9f2da3,48327f9e-3dec-4f9a-9878-a8d5824ce8be,TSLA,2024,3,0.7200,0.5800,2.518200e+10,2.546837e+10,positive growth,0.241379,1,1,1,major beat,consistent miss,-0.011244,0,1,0,slight miss,consistent miss,3d349970bc8e94dd075fc8afdd9fee5ca0d444b93557df...,2025-10-27 08:18:49.902736+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,3768516f-ef13-4014-9745-6c41035c6eb5,730c5e08-0a8c-45ce-967f-f0cfa482b5c4,TSLA,2011,3,-0.0400,-0.0376,5.766600e+07,6.189636e+07,flat,-0.063830,0,0,0,major miss,consistent miss,-0.068346,0,1,0,major miss,consistent miss,281f591b4cf9ef46ae6d0305d906cf1e420104080251e1...,2025-10-27 08:18:49.902736+00:00
57,bb0e4d77-c7ea-476f-8cd6-0c5cc0a5a109,602d6b34-a4e7-457c-b6c6-e04a7380b428,TSLA,2011,2,-0.0400,-0.0382,5.817100e+07,5.600377e+07,loss widening,-0.047120,0,0,0,slight miss,consistent miss,0.038698,1,1,1,moderate beat,consistent miss,a83a6fb7234e43e680eb34dae90bd2815b41f6ea636ddd...,2025-10-27 08:18:49.902736+00:00
58,a056053f-94ec-4913-9519-ed3a62e01ef4,0e18722f-9e2b-4cff-9437-0577e3898817,TSLA,2011,1,-0.0300,-0.0262,4.903000e+07,5.679545e+07,flat,-0.145038,0,0,0,major miss,consistent miss,-0.136727,0,0,0,major miss,consistent miss,371f975d0c7b150fc4c88f2af18b295333cebb04f9002e...,2025-10-27 08:18:49.902736+00:00
59,5ad9a005-53b1-4cfa-976e-a0cfb5d5a54d,e00edb8f-c4ab-4d12-b4ad-1032a495530a,TSLA,2010,4,-0.0300,-0.0284,3.628600e+07,3.861702e+07,loss widening,-0.056338,0,0,0,major miss,consistent miss,-0.060363,0,0,0,major miss,consistent miss,1f9901f654588898e56a1cc6424faf8d3788eb91f33064...,2025-10-27 08:18:49.902736+00:00
60,9bf451cb-626b-48d6-afc4-af4397e41ae1,cf173b9a-9615-4cbc-91e7-9693ea919366,TSLA,2010,3,-0.0252,NaN,3.124100e+07,NaN,unknown,NaN,0,0,0,unknown,consistent miss,NaN,0,0,0,unknown,consistent miss,6fcbeb42885443297049a77dbb8ecc85178ab0ec4c2bd9...,2025-10-27 08:18:49.902736+00:00

In [13]:
# Query the `stock_metadata` table
conn = connect_to_db()
# show all columns
pd.set_option('display.max_columns', None)
if conn:
    query = "SELECT * FROM core.eps_diluted_metrics WHERE tic = 'TSLA' ORDER BY tic, calendar_year DESC, calendar_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_47105/1983549345.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,inference_id,event_id,tic,calendar_year,calendar_quarter,eps_diluted,eps_diluted_ttm,eps_diluted_qoq_growth_pct,eps_diluted_qoq_positive_flag,eps_diluted_qoq_count_4q,eps_diluted_qoq_streak_length,eps_diluted_qoq_growth_class,eps_diluted_qoq_growth_regime,eps_diluted_qoq_volatility_4q,eps_diluted_qoq_volatility_flag,eps_diluted_qoq_growth_drift,eps_diluted_qoq_outlier_flag,eps_diluted_qoq_stability_regime,eps_diluted_qoq_accel,eps_diluted_qoq_accel_count_4q,eps_diluted_qoq_accel_positive_flag,eps_diluted_qoq_accel_streak_length,eps_diluted_qoq_accel_regime,eps_diluted_yoy_growth_pct,eps_diluted_yoy_positive_flag,eps_diluted_yoy_count_4q,eps_diluted_yoy_streak_length,eps_diluted_yoy_growth_class,eps_diluted_yoy_growth_regime,eps_diluted_yoy_volatility_4q,eps_diluted_yoy_volatility_flag,eps_diluted_yoy_growth_drift,eps_diluted_yoy_outlier_flag,eps_diluted_yoy_stability_regime,eps_diluted_yoy_accel,eps_diluted_yoy_accel_count_4q,eps_diluted_yoy_accel_positive_flag,eps_diluted_yoy_accel_streak_length,eps_diluted_yoy_accel_regime,eps_diluted_ttm_growth_pct,eps_diluted_ttm_positive_flag,eps_diluted_ttm_count_4q,eps_diluted_ttm_streak_length,eps_diluted_ttm_growth_class,eps_diluted_ttm_growth_regime,eps_diluted_ttm_volatility_4q,eps_diluted_ttm_volatility_flag,eps_diluted_ttm_growth_drift,eps_diluted_ttm_outlier_flag,eps_diluted_ttm_stability_regime,eps_diluted_ttm_accel,eps_diluted_ttm_accel_count_4q,eps_diluted_ttm_accel_positive_flag,eps_diluted_ttm_accel_streak_length,eps_diluted_ttm_accel_regime,raw_json_sha256,updated_at
0,5564f8b4-6974-4cc1-9b2b-ed1ecb823461,dfc5cddf-2c02-4ebc-b082-0a3ab68d3104,TSLA,2026,1,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,03aa7ad8a5fd4ee8715f2303a7880d4f38e7f1605e1d97...,2025-12-06 17:55:47.623276+00:00
1,0e95d78c-afa9-4a88-8542-f66bf02669d5,dcb60a11-78bc-4c13-9e9a-4433febd2d0e,TSLA,2025,4,NaN,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,1207227a76b1f8f48825c3eb7a265d79b69392ef9820a4...,2025-12-06 17:55:47.623276+00:00
2,4153060e-7834-400f-a7d5-eaef729aeff8,05c32905-2b12-491e-94e0-9c883acd55df,TSLA,2025,3,0.50,1.90,0.250000,1.0,3.0,2.0,strong growth,developing expansion,0.503790,1.0,0.062462,0.0,volatile,-0.231481,1.0,0.0,0.0,persistent deceleration,-0.305556,0.0,1.0,0.0,deep contraction,persistent contraction,0.228659,1.0,-0.127923,0.0,volatile,-0.074786,1.0,0.0,0.0,persistent deceleration,-0.208333,0.0,0.0,0.0,deep contraction,persistent contraction,0.100551,1.0,-0.208880,1.0,volatile,-0.114316,3.0,0.0,0.0,broken acceleration streak,663f84ecd07aab576a70697601880a07f4915e33381a7d...,2025-12-06 17:55:47.623276+00:00
3,c25296a2-2b57-4720-93f1-8c435ac0e8c2,cc937b5b-ffe3-46a2-9074-06ed0f184524,TSLA,2025,2,0.40,2.12,0.481481,1.0,3.0,1.0,very strong growth,developing expansion,0.435103,1.0,-0.019019,0.0,volatile,1.111618,2.0,1.0,1.0,unstable momentum,-0.230769,0.0,2.0,0.0,deep contraction,volatile transition,0.275007,1.0,-0.177373,0.0,volatile,0.169231,2.0,1.0,1.0,unstable momentum,-0.094017,0.0,0.0,0.0,mild contraction,persistent contraction,0.106248,1.0,-0.289126,1.0,volatile,0.085470,4.0,1.0,4.0,sustained acceleration,b0edb44569113fa1a8cc24340f790212af2b9928387157...,2025-12-06 17:55:47.623276+00:00
4,f7852f3f-3011-41c7-992f-5823c0c88511,4f6df69f-2dae-4048-998c-f787b28af700,TSLA,2025,1,0.27,2.24,-0.630137,0.0,3.0,0.0,deep contraction,broken growth streak,0.314959,1.0,0.046966,0.0,volatile,-0.644026,2.0,0.0,0.0,unstable momentum,-0.400000,0.0,2.0,0.0,deep contraction,volatile transition,0.295552,1.0,-0.195020,0.0,volatile,-0.428169,2.0,0.0,0.0,unstable momentum,-0.179487,0.0,0.0,0.0,deep contraction,persistent contraction,0.079046,1.0,-0.316982,1.0,volatile,0.047350,3.0,1.0,3.0,sustained acceleration,0092509ab4d1595475a93f9a805084db97f0c53f843154...,2025-12-06 17:55:47.623276+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,61a42b81-2d38-4ed6-bc02-8165cbc03189,730c5e08-0a8c-45ce-967f-f0cfa482b5c4,TSLA,2011,3,-0.04,-0.14,0.000000,0.0,0.0,0.0,moderate growth,persistent contraction,NaN,1.0,NaN,0.0,None,0.333333,2.0,1.0,1.0,unstable momentum,-0.587302,0.0,NaN,0.0,deep contraction,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,281f591b4cf9ef46ae6d0305d906cf1e420104080251e1...,2025-12-06 17:55:47.623276+00:00
59,9447fd11-9e37-461a-9e14-f64999f0d7db,602d6b34-a4e7-457c-b6c6-e04a7380b428,TSLA,2011,2,-0.04,-0.13,-0.333333,0.0,NaN,0.0,deep contraction,None,NaN,1.0,NaN,0.0,None,-0.333333,1.0,0.0,0.0,persistent deceleration,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,a83a6fb7234e43e680eb34dae90bd2815b41f6ea636ddd...,2025-12-06 17:55:47.623276+00:00
60,06d1296d-354c-4973-ad90-f09ba3ee904f,0e18722f-9e2b-4cff-9437-0577e3898817,TSLA,2011,1,-0.03,NaN,0.000000,0.0,NaN,0.0,moderate growth,None,NaN,1.0,NaN,0.0,None,0.190476,1.0,1.0,1.0,broken deceleration streak,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,371f975d0c7b150fc4c88f2af18b295333cebb04f9002e...,2025-12-06 17:55:47.623276+00:00
61,18ac8811-fbbf-40f5-945e-2cd35e8eacf0,e00edb8f-c4ab-4d12-b4ad-1032a495530a,TSLA,2010,4,-0.03,NaN,-0.190476,0.0,NaN,0.0,deep contraction,None,NaN,1.0,NaN,0.0,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,1f9901f654588898e56a1cc6424faf8d3788eb91f33064...,2025-12-06 17:55:47.623276+00:00
62,96dc35a0-b893-449c-9256-b38177238388,cf173b9a-9615-4cbc-91e7-9693ea919366,TSLA,2010,3,-0.03,NaN,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,None,6fcbeb42885443297049a77dbb8ecc85178ab0ec4c2bd9...,2025-12-06 17:55:47.623276+00:00

In [ ]:
# Query the `stock_metadata` table
conn = connect_to_db()
# show all columns
pd.set_option('display.max_columns', None)
if conn:
    query = \
    """
    SELECT 
        tic, calendar_year, calendar_quarter, 
        eps, eps_estimated, revenue, revenue_estimated 
    FROM core.earnings 
    WHERE tic = 'TSLA' AND eps_estimated IS NOT NULL 
    ORDER BY tic, calendar_year DESC, calendar_quarter DESC 
    LIMIT 9;
    """
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_47105/2994871036.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,event_id,tic,calendar_year,calendar_quarter,earnings_date,fiscal_date,session,eps,eps_estimated,revenue,revenue_estimated,price_before,price_after,source,raw_json,raw_json_sha256,updated_at
0,dcb60a11-78bc-4c13-9e9a-4433febd2d0e,TSLA,2025,4,2026-02-04,2025-12-30,amc,NaN,0.4400,NaN,NaN,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2026-02-04', 'symbol': 'TSLA', 'epsA...",1207227a76b1f8f48825c3eb7a265d79b69392ef9820a4...,2025-10-27 07:39:43.975064+00:00
1,05c32905-2b12-491e-94e0-9c883acd55df,TSLA,2025,3,2025-10-22,2025-09-30,amc,0.50,0.5580,2.809500e+10,2.654037e+10,442.60,448.98,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-10-22', 'symbol': 'TSLA', 'epsA...",663f84ecd07aab576a70697601880a07f4915e33381a7d...,2025-10-27 07:39:43.975064+00:00
2,cc937b5b-ffe3-46a2-9074-06ed0f184524,TSLA,2025,2,2025-07-23,2025-06-30,amc,0.40,0.3972,2.249600e+10,2.227968e+10,332.11,305.30,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-07-23', 'symbol': 'TSLA', 'epsA...",b0edb44569113fa1a8cc24340f790212af2b9928387157...,2025-10-27 07:39:43.975064+00:00
3,4f6df69f-2dae-4048-998c-f787b28af700,TSLA,2025,1,2025-04-22,2025-03-31,None,0.27,0.4136,1.933500e+10,2.126950e+10,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-04-22', 'symbol': 'TSLA', 'epsA...",0092509ab4d1595475a93f9a805084db97f0c53f843154...,2025-10-27 07:39:43.975064+00:00
4,e80609f5-bf85-4744-ad7e-3e5617319265,TSLA,2024,4,2025-01-29,2024-12-31,amc,0.73,0.7740,2.570700e+10,2.725892e+10,397.85,400.07,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-01-29', 'symbol': 'TSLA', 'epsA...",dc231e537902b094383bc63cf81555cba2093e7b09011a...,2025-10-27 07:39:43.975064+00:00
5,48327f9e-3dec-4f9a-9878-a8d5824ce8be,TSLA,2024,3,2024-10-23,2024-09-30,amc,0.72,0.5800,2.518200e+10,2.546837e+10,218.04,259.81,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-10-23', 'symbol': 'TSLA', 'epsA...",3d349970bc8e94dd075fc8afdd9fee5ca0d444b93557df...,2025-10-27 07:39:43.975064+00:00
6,d33f1dd9-6b09-4053-9f2f-6b9bbb4555bd,TSLA,2024,2,2024-07-23,2024-06-30,amc,0.52,0.6200,2.550000e+10,2.453975e+10,251.51,215.99,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-07-23', 'symbol': 'TSLA', 'epsA...",77229d13edf2bcdc85836a2611dde9b889de11e17ace45...,2025-10-27 07:39:43.975064+00:00
7,db00b56a-e52a-4a71-b1bc-fe87bed3bca4,TSLA,2024,1,2024-04-23,2024-03-31,amc,0.45,0.5100,2.130100e+10,2.222003e+10,141.93,162.13,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-04-23', 'symbol': 'TSLA', 'epsA...",9fece6f8eadf8acb2adfb585d43a3f1ede80de1ac5cff6...,2025-10-27 07:39:43.975064+00:00
8,d8c85e9d-1a46-43da-aa49-8cc6dc620194,TSLA,2023,4,2024-01-24,2023-12-31,amc,0.71,0.7500,2.516700e+10,2.554750e+10,209.14,182.63,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-01-24', 'symbol': 'TSLA', 'epsA...",37d72879efafe55c8e356da45b32e8d35524ea52194093...,2025-10-27 07:39:43.975064+00:00

In [12]:
# Query the `stock_metadata` table
conn = connect_to_db()
# show all columns
pd.set_option('display.max_columns', None)
if conn:
    query = \
    """
    WITH latest_earnings AS (
        SELECT 
            tic, calendar_year, calendar_quarter, 
            eps, eps_estimated, revenue, revenue_estimated 
        FROM core.earnings 
        WHERE tic = 'TSLA' AND eps IS NOT NULL 
        ORDER BY tic, calendar_year DESC, calendar_quarter DESC 
    LIMIT 1)
    SELECT eps_surprise_regime, revenue_surprise_regime
    FROM core.earnings_metrics em
    JOIN latest_earnings le
    ON em.tic = le.tic
    AND em.calendar_year = le.calendar_year
    AND em.calendar_quarter = le.calendar_quarter
    WHERE le.tic = 'TSLA'
    ;
    """
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_47105/3588730814.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

  eps_surprise_regime revenue_surprise_regime
0     consistent miss           emerging beat

In [44]:
# Query the `stock_metadata` table
conn = connect_to_db()
# show all columns
pd.set_option('display.max_columns', None)
# show all rows
pd.set_option('display.max_rows', None)
if conn:
    query = \
    """
    WITH latest_date AS (
    SELECT date
    FROM raw.stock_ohlcv_daily
    WHERE tic = 'TSLA'
    ORDER BY date DESC
    LIMIT 1)
    SELECT tic, end_date as date, pt_high, pt_low, pt_p25, pt_median, pt_p75
    FROM core.analyst_rating_quarterly_summary AS arqs
    JOIN latest_date ld
    ON arqs.end_date >= ld.date - INTERVAL '1 year' AND arqs.end_date <= ld.date
    WHERE arqs.tic = 'TSLA'
    ORDER BY date DESC;
    """
    _df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    
    display(_df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_47105/2623568746.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  _df = pd.read_sql_query(query, conn)

      tic        date  pt_high  pt_low   pt_p25  pt_median  pt_p75
0    TSLA  2025-10-24    600.0   247.0  383.750     437.50  501.25
1    TSLA  2025-10-23    600.0   247.0  383.750     437.50  501.25
2    TSLA  2025-10-22    600.0   247.0  342.500     410.00  461.50
3    TSLA  2025-10-21    600.0   247.0  342.500     410.00  461.50
4    TSLA  2025-10-20    600.0   247.0  352.500     410.00  461.50
5    TSLA  2025-10-17    600.0   247.0  352.500     410.00  461.50
6    TSLA  2025-10-16    600.0   247.0  352.500     410.00  461.50
7    TSLA  2025-10-15    600.0   247.0  365.000     422.50  472.25
8    TSLA  2025-10-14    600.0   247.0  365.000     422.50  472.25
9    TSLA  2025-10-13    600.0   247.0  365.000     422.50  472.25
10   TSLA  2025-10-10    600.0   247.0  385.000     422.50  450.75
11   TSLA  2025-10-09    600.0   247.0  385.000     422.50  450.75
12   TSLA  2025-10-08    600.0   247.0  385.000     422.50  450.75
13   TSLA  2025-10-07    600.0   247.0  375.000     410.00  437.50
14   TSLA  2025-10-06    600.0   247.0  375.000     410.00  437.50
15   TSLA  2025-10-03    600.0   355.0  398.750     422.50  438.75
16   TSLA  2025-10-02    600.0   355.0  398.750     422.50  438.75
17   TSLA  2025-10-01    600.0   355.0  398.750     422.50  438.75
18   TSLA  2025-09-30    600.0   355.0  398.750     422.50  438.75
19   TSLA  2025-09-29    600.0   355.0  398.750     422.50  438.75
20   TSLA  2025-09-26    600.0   290.0  375.000     410.00  437.50
21   TSLA  2025-09-25    440.0   290.0  355.000     395.00  410.00
22   TSLA  2025-09-24    440.0   290.0  355.000     395.00  410.00
23   TSLA  2025-09-23    440.0   290.0  355.000     395.00  410.00
24   TSLA  2025-09-22    440.0   290.0  355.000     395.00  410.00
25   TSLA  2025-09-19    440.0   290.0  355.000     395.00  410.00
26   TSLA  2025-09-18    440.0   290.0  355.000     395.00  410.00
27   TSLA  2025-09-17    440.0   290.0  338.750     382.50  417.50
28   TSLA  2025-09-16    440.0   290.0  338.750     382.50  417.50
29   TSLA  2025-09-15    440.0   290.0  338.750     382.50  417.50
30   TSLA  2025-09-12    440.0   290.0  338.750     382.50  417.50
31   TSLA  2025-09-11    440.0   290.0  338.750     382.50  417.50
32   TSLA  2025-09-10    440.0   290.0  338.750     382.50  417.50
33   TSLA  2025-09-09    440.0   290.0  338.750     382.50  417.50
34   TSLA  2025-09-08    440.0   290.0  338.750     382.50  417.50
35   TSLA  2025-09-05    440.0   290.0  338.750     382.50  417.50
36   TSLA  2025-09-04    355.0   290.0  306.250     322.50  338.75
37   TSLA  2025-09-03    500.0   290.0  322.500     355.00  427.50
38   TSLA  2025-09-02    500.0   290.0  322.500     355.00  427.50
39   TSLA  2025-08-29    500.0   290.0  322.500     355.00  427.50
40   TSLA  2025-08-28    500.0   290.0  322.500     355.00  427.50
41   TSLA  2025-08-27    500.0   290.0  322.500     355.00  427.50
42   TSLA  2025-08-26    500.0   290.0  322.500     355.00  427.50
43   TSLA  2025-08-25    500.0   290.0  322.500     355.00  427.50
44   TSLA  2025-08-22    500.0   290.0  322.500     355.00  427.50
45   TSLA  2025-08-21    500.0   290.0  322.500     355.00  427.50
46   TSLA  2025-08-20    500.0   290.0  322.500     355.00  427.50
47   TSLA  2025-08-19    500.0   290.0  322.500     355.00  427.50
48   TSLA  2025-08-18    500.0   290.0  322.500     355.00  427.50
49   TSLA  2025-08-15    500.0   290.0  338.750     372.50  417.50
50   TSLA  2025-08-14    500.0   290.0  338.750     372.50  417.50
51   TSLA  2025-08-13    500.0   290.0  338.750     372.50  417.50
52   TSLA  2025-08-12    500.0   290.0  338.750     372.50  417.50
53   TSLA  2025-08-11    500.0   290.0  338.750     372.50  417.50
54   TSLA  2025-08-08    500.0   290.0  338.750     372.50  417.50
55   TSLA  2025-08-07    500.0   290.0  338.750     372.50  417.50
56   TSLA  2025-08-06    500.0   290.0  338.750     372.50  417.50
57   TSLA  2025-08-05    500.0   290.0  355.000     390.00  400.00
58   TSLA  2025-08-04    500.0   290.0  355.000     390.00  400.00
59   TSLA  2025-08-01    500.0   290.0  355.000     390.00  400.00
60   TSLA  2025-07-31    500.0   290.0  355.000     390.00  400.00
61   TSLA  2025-07-30    500.0   290.0  355.000     390.00  400.00
62   TSLA  2025-07-29    500.0   290.0  355.000     390.00  400.00
63   TSLA  2025-07-28    500.0   290.0  355.000     390.00  400.00
64   TSLA  2025-07-25    500.0   290.0  355.000     390.00  400.00
65   TSLA  2025-07-24    500.0   290.0  355.000     390.00  400.00
66   TSLA  2025-07-23    500.0   290.0  372.500     400.00  430.00
67   TSLA  2025-07-22    500.0   290.0  372.500     400.00  430.00
68   TSLA  2025-07-21    500.0   280.0  338.750     395.00  420.00
69   TSLA  2025-07-18    500.0   280.0  365.000     405.00  435.00
70   TSLA  2025-07-17    500.0   280.0  365.000     405.00  435.00
71   TSLA  2025-07-16    500.0   280.0  365.000     405.00  435.00
72   TSLA  2025-07-15    500.0   137.0  290.000     400.00  430.00
73   TSLA  2025-07-14    500.0   137.0  290.000     400.00  430.00
74   TSLA  2025-07-11    500.0   137.0  290.000     400.00  430.00
75   TSLA  2025-07-10    500.0   137.0  290.000     400.00  430.00
76   TSLA  2025-07-09    500.0   137.0  290.000     400.00  430.00
77   TSLA  2025-07-08    500.0   137.0  290.000     400.00  430.00
78   TSLA  2025-07-07    500.0   137.0  290.000     400.00  430.00
79   TSLA  2025-07-03    500.0   137.0  290.000     400.00  430.00
80   TSLA  2025-07-02    500.0   137.0  290.000     400.00  430.00
81   TSLA  2025-07-01    500.0   137.0  290.000     400.00  430.00
82   TSLA  2025-06-30    500.0   137.0  290.000     400.00  430.00
83   TSLA  2025-06-27    500.0   137.0  345.000     400.00  430.00
84   TSLA  2025-06-26    500.0   137.0  345.000     400.00  430.00
85   TSLA  2025-06-25    500.0   137.0  345.000     400.00  430.00
86   TSLA  2025-06-24    500.0   137.0  345.000     400.00  430.00
87   TSLA  2025-06-23    500.0   137.0  345.000     400.00  430.00
88   TSLA  2025-06-20    500.0   137.0  345.000     400.00  430.00
89   TSLA  2025-06-18    500.0   137.0  345.000     400.00  430.00
90   TSLA  2025-06-17    500.0   137.0  345.000     400.00  430.00
91   TSLA  2025-06-16    500.0   137.0  345.000     400.00  430.00
92   TSLA  2025-06-13    500.0   137.0  356.250     405.00  430.00
93   TSLA  2025-06-12    500.0   137.0  356.250     405.00  430.00
94   TSLA  2025-06-11    500.0   137.0  356.250     405.00  430.00
95   TSLA  2025-06-10    500.0   137.0  356.250     405.00  430.00
96   TSLA  2025-06-09    500.0   137.0  356.250     405.00  430.00
97   TSLA  2025-06-06    500.0   137.0  356.250     405.00  430.00
98   TSLA  2025-06-05    500.0   137.0  357.500     400.00  430.00
99   TSLA  2025-06-04    500.0   137.0  357.500     400.00  430.00
100  TSLA  2025-06-03    450.0   137.0  351.250     395.00  425.00
101  TSLA  2025-06-02    450.0   137.0  351.250     395.00  425.00
102  TSLA  2025-05-30    450.0   137.0  351.250     395.00  425.00
103  TSLA  2025-05-29    450.0   137.0  351.250     395.00  425.00
104  TSLA  2025-05-28    450.0   137.0  351.250     395.00  425.00
105  TSLA  2025-05-27    450.0   137.0  351.250     395.00  425.00
106  TSLA  2025-05-23    450.0   137.0  323.900     390.00  420.00
107  TSLA  2025-05-22    450.0   137.0  323.900     390.00  420.00
108  TSLA  2025-05-21    450.0   137.0  323.900     390.00  420.00
109  TSLA  2025-05-20    450.0   137.0  323.900     390.00  420.00
110  TSLA  2025-05-19    450.0   137.0  323.900     390.00  420.00
111  TSLA  2025-05-16    450.0   137.0  323.900     390.00  420.00
112  TSLA  2025-05-15    450.0   137.0  313.350     385.00  425.00
113  TSLA  2025-05-14    450.0   137.0  313.350     385.00  425.00
114  TSLA  2025-05-13    450.0   137.0  313.350     385.00  425.00
115  TSLA  2025-05-12    450.0   137.0  313.350     385.00  425.00
116  TSLA  2025-05-09    450.0   137.0  315.650     370.00  420.00
117  TSLA  2025-05-08    450.0   137.0  315.650     370.00  420.00
118  TSLA  2025-05-07    450.0   137.0  315.650     370.00  420.00
119  TSLA  2025-05-06    450.0   137.0  315.650     370.00  420.00
120  TSLA  2025-05-05    450.0   137.0  309.225     357.50  425.00
121  TSLA  2025-05-02    450.0   137.0  309.225     357.50  425.00
122  TSLA  2025-05-01    450.0   137.0  309.225     357.50  425.00
123  TSLA  2025-04-30    450.0   137.0  309.225     357.50  425.00
124  TSLA  2025-04-29    450.0   137.0  309.225     357.50  425.00
125  TSLA  2025-04-28    450.0   137.0  309.225     357.50  425.00
126  TSLA  2025-04-25    450.0   137.0  309.225     357.50  425.00
127  TSLA  2025-04-24    450.0   137.0  309.225     357.50  425.00
128  TSLA  2025-04-23    430.0   137.0  297.100     336.75  385.00
129  TSLA  2025-04-22    430.0   137.0  297.100     336.75  385.00
130  TSLA  2025-04-21    550.0   137.0  322.075     357.50  430.00
131  TSLA  2025-04-17    550.0   137.0  315.650     345.00  400.00
132  TSLA  2025-04-16    550.0   137.0  315.650     345.00  400.00
133  TSLA  2025-04-15    550.0   302.8  332.625     357.50  415.00
134  TSLA  2025-04-14    550.0   302.8  332.625     357.50  415.00
135  TSLA  2025-04-11    550.0   302.8  332.625     357.50  415.00
136  TSLA  2025-04-10    550.0   302.8  332.625     357.50  415.00
137  TSLA  2025-04-09    550.0   302.8  332.625     357.50  415.00
138  TSLA  2025-04-08    550.0   302.8  332.625     357.50  415.00
139  TSLA  2025-04-07    550.0   302.8  332.625     357.50  415.00
140  TSLA  2025-04-04    550.0   302.8  332.625     357.50  415.00
141  TSLA  2025-04-03    550.0   302.8  332.625     357.50  415.00
142  TSLA  2025-04-02    550.0   275.0  322.075     357.50  410.50
143  TSLA  2025-04-01    550.0   275.0  322.075     357.50  410.50
144  TSLA  2025-03-31    550.0   275.0  322.075     357.50  410.50
145  TSLA  2025-03-28    550.0   275.0  322.075     357.50  410.50
146  TSLA  2025-03-27    550.0   275.0  315.650     370.00  417.00
147  TSLA  2025-03-26    550.0   275.0  315.650     370.00  417.00
148  TSLA  2025-03-25    550.0   275.0  315.650     370.00  417.00
149  TSLA  2025-03-24    550.0   275.0  315.650     370.00  417.00
150  TSLA  2025-03-21    550.0   275.0  315.650     370.00  417.00
151  TSLA  2025-03-20    550.0   275.0  315.650     370.00  417.00
152  TSLA  2025-03-19    550.0   275.0  315.650     370.00  417.00
153  TSLA  2025-03-18    550.0   275.0  315.650     370.00  417.00
154  TSLA  2025-03-17    550.0   275.0  315.650     370.00  417.00
155  TSLA  2025-03-14    550.0   275.0  315.650     370.00  459.50
156  TSLA  2025-03-13    550.0   275.0  315.650     370.00  459.50
157  TSLA  2025-03-12    550.0   275.0  315.650     370.00  459.50
158  TSLA  2025-03-11    550.0   275.0  315.650     370.00  459.50
159  TSLA  2025-03-10    550.0   275.0  315.650     370.00  459.50
160  TSLA  2025-03-07    550.0   275.0  315.650     370.00  459.50
161  TSLA  2025-03-06    550.0   275.0  315.650     370.00  459.50
162  TSLA  2025-03-05    550.0   275.0  309.225     366.25  487.25
163  TSLA  2025-03-04    550.0   275.0  309.225     366.25  487.25
164  TSLA  2025-03-03    550.0   275.0  309.225     366.25  487.25
165  TSLA  2025-02-28    550.0   275.0  322.075     402.00  437.00
166  TSLA  2025-02-27    550.0   275.0  322.075     402.00  437.00
167  TSLA  2025-02-26    550.0   275.0  322.075     402.00  437.00
168  TSLA  2025-02-25    550.0   275.0  322.075     402.00  437.00
169  TSLA  2025-02-24    550.0   275.0  364.250     404.00  463.00
170  TSLA  2025-02-21    550.0   275.0  364.250     404.00  463.00
171  TSLA  2025-02-20    550.0   275.0  364.250     404.00  463.00
172  TSLA  2025-02-19    550.0   275.0  364.250     404.00  463.00
173  TSLA  2025-02-18    550.0   275.0  364.250     404.00  463.00
174  TSLA  2025-02-14    550.0   270.0  315.125     402.00  437.00
175  TSLA  2025-02-13    550.0   270.0  313.000     400.00  411.00
176  TSLA  2025-02-12    550.0   270.0  313.000     400.00  411.00
177  TSLA  2025-02-11    550.0   270.0  313.000     400.00  411.00
178  TSLA  2025-02-10    550.0   270.0  303.500     402.00  437.00
179  TSLA  2025-02-07    550.0   270.0  303.500     402.00  437.00
180  TSLA  2025-02-06    550.0   270.0  303.500     402.00  437.00
181  TSLA  2025-02-05    550.0   270.0  303.500     402.00  437.00
182  TSLA  2025-02-04    550.0   270.0  303.500     402.00  437.00
183  TSLA  2025-02-03    550.0   270.0  303.500     402.00  437.00
184  TSLA  2025-01-31    550.0   270.0  303.500     402.00  437.00
185  TSLA  2025-01-30    550.0   270.0  303.500     402.00  437.00
186  TSLA  2025-01-29    550.0   270.0  303.500     402.00  437.00
187  TSLA  2025-01-28    550.0   270.0  303.500     402.00  437.00
188  TSLA  2025-01-27    550.0   270.0  313.000     400.00  411.00
189  TSLA  2025-01-24    550.0   270.0  301.750     357.50  409.25
190  TSLA  2025-01-23    550.0   270.0  301.750     357.50  409.25
191  TSLA  2025-01-22    550.0   236.0  255.000     278.00  400.00
192  TSLA  2025-01-21    515.0   236.0  253.750     277.00  336.25
193  TSLA  2025-01-17    515.0   195.0  250.000     276.00  315.00
194  TSLA  2025-01-16    515.0   195.0  250.000     276.00  315.00
195  TSLA  2025-01-15    515.0   195.0  250.000     276.00  315.00
196  TSLA  2025-01-14    515.0   195.0  250.000     276.00  315.00
197  TSLA  2025-01-13    515.0   195.0  249.250     275.50  314.50
198  TSLA  2025-01-10    515.0    88.0  237.500     272.50  313.50
199  TSLA  2025-01-08    515.0    88.0  237.500     272.50  313.50
200  TSLA  2025-01-07    515.0    88.0  237.500     272.50  313.50
201  TSLA  2025-01-06    515.0    88.0  236.500     262.50  309.25
202  TSLA  2025-01-03    515.0    88.0  236.500     262.50  309.25
203  TSLA  2025-01-02    515.0    88.0  236.000     250.00  298.00
204  TSLA  2024-12-31    515.0    88.0  236.000     250.00  298.00
205  TSLA  2024-12-30    515.0    88.0  236.000     250.00  298.00
206  TSLA  2024-12-27    515.0    88.0  236.000     250.00  298.00
207  TSLA  2024-12-26    515.0    88.0  236.000     250.00  298.00
208  TSLA  2024-12-24    515.0    88.0  236.000     250.00  298.00
209  TSLA  2024-12-23    515.0    88.0  236.000     252.50  307.00
210  TSLA  2024-12-20    515.0    88.0  236.000     252.50  307.00
211  TSLA  2024-12-19    515.0    88.0  236.000     255.00  304.00
212  TSLA  2024-12-18    515.0    88.0  236.000     255.00  304.00
213  TSLA  2024-12-17    515.0    88.0  236.000     255.00  304.00
214  TSLA  2024-12-16    515.0    88.0  236.000     255.00  304.00
215  TSLA  2024-12-13    411.0    88.0  236.000     252.50  293.00
216  TSLA  2024-12-12    411.0    88.0  236.000     252.50  293.00
217  TSLA  2024-12-11    411.0    88.0  236.000     254.00  288.00
218  TSLA  2024-12-10    411.0    88.0  236.000     254.00  288.00
219  TSLA  2024-12-09    411.0    88.0  236.000     254.00  288.00
220  TSLA  2024-12-06    411.0    88.0  236.000     254.50  295.75
221  TSLA  2024-12-05    411.0    88.0  236.000     254.50  295.75
222  TSLA  2024-12-04    411.0    88.0  236.000     254.00  295.00
223  TSLA  2024-12-03    411.0    88.0  236.000     254.00  295.00
224  TSLA  2024-12-02    411.0    88.0  236.000     254.00  295.00
225  TSLA  2024-11-29    400.0    88.0  234.500     252.00  282.25
226  TSLA  2024-11-27    315.0    88.0  233.000     250.00  277.00
227  TSLA  2024-11-26    315.0    88.0  233.000     250.00  277.00
228  TSLA  2024-11-25    315.0    88.0  233.000     250.00  277.00
229  TSLA  2024-11-22    315.0    88.0  233.000     250.00  277.00
230  TSLA  2024-11-21    315.0    88.0  233.000     250.00  277.00
231  TSLA  2024-11-20    315.0    88.0  233.000     250.00  277.00
232  TSLA  2024-11-19    315.0    88.0  233.000     250.00  277.00
233  TSLA  2024-11-18    315.0    88.0  233.000     250.00  277.00
234  TSLA  2024-11-15    315.0    88.0  225.000     249.00  277.00
235  TSLA  2024-11-14    315.0    88.0  225.000     249.00  277.00
236  TSLA  2024-11-13    315.0    88.0  222.500     247.00  270.75
237  TSLA  2024-11-12    315.0    88.0  222.500     247.00  270.75
238  TSLA  2024-11-11    315.0    88.0  222.500     247.00  270.75
239  TSLA  2024-11-08    315.0    88.0  222.500     247.00  270.75
240  TSLA  2024-11-07    315.0    88.0  222.500     247.00  270.75
241  TSLA  2024-11-06    315.0    88.0  222.000     245.00  265.50
242  TSLA  2024-11-05    315.0    88.0  222.000     245.00  265.50
243  TSLA  2024-11-04    315.0    88.0  222.000     245.00  265.50
244  TSLA  2024-11-01    315.0    88.0  222.000     245.00  265.50
245  TSLA  2024-10-31    315.0    88.0  222.000     245.00  265.50
246  TSLA  2024-10-30    315.0    88.0  222.000     245.00  265.50
247  TSLA  2024-10-29    315.0    88.0  222.000     245.00  265.50
248  TSLA  2024-10-28    315.0    88.0  218.750     241.50  260.25
249  TSLA  2024-10-25    310.0    88.0  216.250     237.00  254.75
250  TSLA  2024-10-24    310.0    88.0  217.500     238.00  255.00

In [45]:
# Query the `stock_metadata` table
conn = connect_to_db()
# show all columns
pd.set_option('display.max_columns', None)
if conn:
    query = \
    """
    WITH latest_date AS (
        SELECT date
        FROM raw.stock_ohlcv_daily
        WHERE tic = 'TSLA'
        ORDER BY date DESC
        LIMIT 1)
    SELECT sod.tic, sod.date, sod.close
    FROM raw.stock_ohlcv_daily sod
    JOIN latest_date ld
    ON sod.date >= ld.date - INTERVAL '1 year' AND sod.date <= ld.date
    WHERE sod.tic = 'TSLA'
    ORDER BY sod.date DESC
    ;
    """
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_47105/3822793669.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

      tic        date   close
0    TSLA  2025-10-24  433.72
1    TSLA  2025-10-23  448.98
2    TSLA  2025-10-22  438.97
3    TSLA  2025-10-21  442.60
4    TSLA  2025-10-20  447.43
5    TSLA  2025-10-17  439.31
6    TSLA  2025-10-16  428.75
7    TSLA  2025-10-15  435.15
8    TSLA  2025-10-14  429.24
9    TSLA  2025-10-13  435.90
10   TSLA  2025-10-10  413.49
11   TSLA  2025-10-09  435.54
12   TSLA  2025-10-08  438.69
13   TSLA  2025-10-07  433.09
14   TSLA  2025-10-06  453.25
15   TSLA  2025-10-03  429.83
16   TSLA  2025-10-02  436.00
17   TSLA  2025-10-01  459.46
18   TSLA  2025-09-30  444.72
19   TSLA  2025-09-29  443.21
20   TSLA  2025-09-26  440.40
21   TSLA  2025-09-25  423.39
22   TSLA  2025-09-24  442.79
23   TSLA  2025-09-23  425.85
24   TSLA  2025-09-22  434.21
25   TSLA  2025-09-19  426.07
26   TSLA  2025-09-18  416.85
27   TSLA  2025-09-17  425.86
28   TSLA  2025-09-16  421.62
29   TSLA  2025-09-15  410.04
30   TSLA  2025-09-12  395.94
31   TSLA  2025-09-11  368.81
32   TSLA  2025-09-10  347.79
33   TSLA  2025-09-09  346.97
34   TSLA  2025-09-08  346.40
35   TSLA  2025-09-05  350.84
36   TSLA  2025-09-04  338.53
37   TSLA  2025-09-03  334.09
38   TSLA  2025-09-02  329.36
39   TSLA  2025-08-29  333.87
40   TSLA  2025-08-28  345.98
41   TSLA  2025-08-27  349.60
42   TSLA  2025-08-26  351.67
43   TSLA  2025-08-25  346.60
44   TSLA  2025-08-22  340.01
45   TSLA  2025-08-21  320.11
46   TSLA  2025-08-20  323.90
47   TSLA  2025-08-19  329.31
48   TSLA  2025-08-18  335.16
49   TSLA  2025-08-15  330.56
50   TSLA  2025-08-14  335.58
51   TSLA  2025-08-13  339.38
52   TSLA  2025-08-12  340.84
53   TSLA  2025-08-11  339.03
54   TSLA  2025-08-08  329.65
55   TSLA  2025-08-07  322.27
56   TSLA  2025-08-06  319.91
57   TSLA  2025-08-05  308.72
58   TSLA  2025-08-04  309.26
59   TSLA  2025-08-01  302.63
60   TSLA  2025-07-31  308.27
61   TSLA  2025-07-30  319.04
62   TSLA  2025-07-29  321.20
63   TSLA  2025-07-28  325.59
64   TSLA  2025-07-25  316.06
65   TSLA  2025-07-24  305.30
66   TSLA  2025-07-23  332.56
67   TSLA  2025-07-22  332.11
68   TSLA  2025-07-21  328.49
69   TSLA  2025-07-18  329.65
70   TSLA  2025-07-17  319.41
71   TSLA  2025-07-16  321.67
72   TSLA  2025-07-15  310.78
73   TSLA  2025-07-14  316.90
74   TSLA  2025-07-11  313.51
75   TSLA  2025-07-10  309.87
76   TSLA  2025-07-09  295.88
77   TSLA  2025-07-08  297.81
78   TSLA  2025-07-07  293.94
79   TSLA  2025-07-03  315.35
80   TSLA  2025-07-02  315.65
81   TSLA  2025-07-01  300.71
82   TSLA  2025-06-30  317.66
83   TSLA  2025-06-27  323.63
84   TSLA  2025-06-26  325.78
85   TSLA  2025-06-25  327.55
86   TSLA  2025-06-24  340.47
87   TSLA  2025-06-23  348.68
88   TSLA  2025-06-20  322.16
89   TSLA  2025-06-18  322.05
90   TSLA  2025-06-17  316.35
91   TSLA  2025-06-16  329.13
92   TSLA  2025-06-13  325.31
93   TSLA  2025-06-12  319.11
94   TSLA  2025-06-11  326.43
95   TSLA  2025-06-10  326.09
96   TSLA  2025-06-09  308.58
97   TSLA  2025-06-06  295.14
98   TSLA  2025-06-05  284.70
99   TSLA  2025-06-04  332.05
100  TSLA  2025-06-03  344.27
101  TSLA  2025-06-02  342.69
102  TSLA  2025-05-30  346.46
103  TSLA  2025-05-29  358.43
104  TSLA  2025-05-28  356.90
105  TSLA  2025-05-27  362.89
106  TSLA  2025-05-23  339.34
107  TSLA  2025-05-22  341.04
108  TSLA  2025-05-21  334.62
109  TSLA  2025-05-20  343.82
110  TSLA  2025-05-19  342.09
111  TSLA  2025-05-16  349.98
112  TSLA  2025-05-15  342.82
113  TSLA  2025-05-14  347.68
114  TSLA  2025-05-13  334.07
115  TSLA  2025-05-12  318.38
116  TSLA  2025-05-09  298.26
117  TSLA  2025-05-08  284.82
118  TSLA  2025-05-07  276.22
119  TSLA  2025-05-06  275.35
120  TSLA  2025-05-05  280.26
121  TSLA  2025-05-02  287.21
122  TSLA  2025-05-01  280.52
123  TSLA  2025-04-30  282.16
124  TSLA  2025-04-29  292.03
125  TSLA  2025-04-28  285.88
126  TSLA  2025-04-25  284.95
127  TSLA  2025-04-24  259.51
128  TSLA  2025-04-23  250.74
129  TSLA  2025-04-22  237.97
130  TSLA  2025-04-21  227.50
131  TSLA  2025-04-17  241.37
132  TSLA  2025-04-16  241.55
133  TSLA  2025-04-15  254.11
134  TSLA  2025-04-14  252.35
135  TSLA  2025-04-11  252.31
136  TSLA  2025-04-10  252.40
137  TSLA  2025-04-09  272.20
138  TSLA  2025-04-08  221.86
139  TSLA  2025-04-07  233.29
140  TSLA  2025-04-04  239.43
141  TSLA  2025-04-03  267.28
142  TSLA  2025-04-02  282.76
143  TSLA  2025-04-01  268.46
144  TSLA  2025-03-31  259.16
145  TSLA  2025-03-28  263.55
146  TSLA  2025-03-27  273.13
147  TSLA  2025-03-26  272.06
148  TSLA  2025-03-25  288.14
149  TSLA  2025-03-24  278.39
150  TSLA  2025-03-21  248.71
151  TSLA  2025-03-20  236.26
152  TSLA  2025-03-19  235.86
153  TSLA  2025-03-18  225.31
154  TSLA  2025-03-17  238.01
155  TSLA  2025-03-14  249.98
156  TSLA  2025-03-13  240.68
157  TSLA  2025-03-12  248.09
158  TSLA  2025-03-11  230.58
159  TSLA  2025-03-10  222.15
160  TSLA  2025-03-07  262.67
161  TSLA  2025-03-06  263.45
162  TSLA  2025-03-05  279.10
163  TSLA  2025-03-04  272.04
164  TSLA  2025-03-03  284.65
165  TSLA  2025-02-28  292.98
166  TSLA  2025-02-27  281.95
167  TSLA  2025-02-26  290.80
168  TSLA  2025-02-25  302.80
169  TSLA  2025-02-24  330.53
170  TSLA  2025-02-21  337.80
171  TSLA  2025-02-20  354.40
172  TSLA  2025-02-19  360.56
173  TSLA  2025-02-18  354.11
174  TSLA  2025-02-14  355.84
175  TSLA  2025-02-13  355.94
176  TSLA  2025-02-12  336.51
177  TSLA  2025-02-11  328.50
178  TSLA  2025-02-10  350.73
179  TSLA  2025-02-07  361.62
180  TSLA  2025-02-06  374.32
181  TSLA  2025-02-05  378.17
182  TSLA  2025-02-04  392.21
183  TSLA  2025-02-03  383.68
184  TSLA  2025-01-31  404.60
185  TSLA  2025-01-30  400.28
186  TSLA  2025-01-29  389.10
187  TSLA  2025-01-28  398.09
188  TSLA  2025-01-27  397.15
189  TSLA  2025-01-24  406.58
190  TSLA  2025-01-23  412.38
191  TSLA  2025-01-22  415.11
192  TSLA  2025-01-21  424.07
193  TSLA  2025-01-17  426.50
194  TSLA  2025-01-16  413.82
195  TSLA  2025-01-15  428.22
196  TSLA  2025-01-14  396.36
197  TSLA  2025-01-13  403.31
198  TSLA  2025-01-10  394.74
199  TSLA  2025-01-08  394.94
200  TSLA  2025-01-07  394.36
201  TSLA  2025-01-06  411.05
202  TSLA  2025-01-03  410.44
203  TSLA  2025-01-02  379.28
204  TSLA  2024-12-31  403.84
205  TSLA  2024-12-30  417.41
206  TSLA  2024-12-27  431.66
207  TSLA  2024-12-26  454.13
208  TSLA  2024-12-24  462.28
209  TSLA  2024-12-23  430.60
210  TSLA  2024-12-20  421.06
211  TSLA  2024-12-19  436.17
212  TSLA  2024-12-18  440.13
213  TSLA  2024-12-17  479.86
214  TSLA  2024-12-16  463.02
215  TSLA  2024-12-13  436.23
216  TSLA  2024-12-12  418.10
217  TSLA  2024-12-11  424.77
218  TSLA  2024-12-10  400.99
219  TSLA  2024-12-09  389.79
220  TSLA  2024-12-06  389.22
221  TSLA  2024-12-05  369.49
222  TSLA  2024-12-04  357.93
223  TSLA  2024-12-03  351.42
224  TSLA  2024-12-02  357.09
225  TSLA  2024-11-29  345.16
226  TSLA  2024-11-27  332.89
227  TSLA  2024-11-26  338.23
228  TSLA  2024-11-25  338.59
229  TSLA  2024-11-22  352.56
230  TSLA  2024-11-21  339.64
231  TSLA  2024-11-20  342.03
232  TSLA  2024-11-19  346.00
233  TSLA  2024-11-18  338.74
234  TSLA  2024-11-15  320.72
235  TSLA  2024-11-14  311.18
236  TSLA  2024-11-13  330.24
237  TSLA  2024-11-12  328.49
238  TSLA  2024-11-11  350.00
239  TSLA  2024-11-08  321.22
240  TSLA  2024-11-07  296.91
241  TSLA  2024-11-06  288.53
242  TSLA  2024-11-05  251.44
243  TSLA  2024-11-04  242.84
244  TSLA  2024-11-01  248.98
245  TSLA  2024-10-31  249.85
246  TSLA  2024-10-30  257.55
247  TSLA  2024-10-29  259.52
248  TSLA  2024-10-28  262.51
249  TSLA  2024-10-25  269.19
250  TSLA  2024-10-24  260.48

In [47]:
df['date'] = pd.to_datetime(df['date'])
_df['date'] = pd.to_datetime(_df['date'])
df = df.merge(_df, on=['tic', 'date'], how='left')

In [48]:
df

      tic       date   close  pt_high  pt_low   pt_p25  pt_median  pt_p75
0    TSLA 2025-10-24  433.72    600.0   247.0  383.750     437.50  501.25
1    TSLA 2025-10-23  448.98    600.0   247.0  383.750     437.50  501.25
2    TSLA 2025-10-22  438.97    600.0   247.0  342.500     410.00  461.50
3    TSLA 2025-10-21  442.60    600.0   247.0  342.500     410.00  461.50
4    TSLA 2025-10-20  447.43    600.0   247.0  352.500     410.00  461.50
5    TSLA 2025-10-17  439.31    600.0   247.0  352.500     410.00  461.50
6    TSLA 2025-10-16  428.75    600.0   247.0  352.500     410.00  461.50
7    TSLA 2025-10-15  435.15    600.0   247.0  365.000     422.50  472.25
8    TSLA 2025-10-14  429.24    600.0   247.0  365.000     422.50  472.25
9    TSLA 2025-10-13  435.90    600.0   247.0  365.000     422.50  472.25
10   TSLA 2025-10-10  413.49    600.0   247.0  385.000     422.50  450.75
11   TSLA 2025-10-09  435.54    600.0   247.0  385.000     422.50  450.75
12   TSLA 2025-10-08  438.69    600.0   247.0  385.000     422.50  450.75
13   TSLA 2025-10-07  433.09    600.0   247.0  375.000     410.00  437.50
14   TSLA 2025-10-06  453.25    600.0   247.0  375.000     410.00  437.50
15   TSLA 2025-10-03  429.83    600.0   355.0  398.750     422.50  438.75
16   TSLA 2025-10-02  436.00    600.0   355.0  398.750     422.50  438.75
17   TSLA 2025-10-01  459.46    600.0   355.0  398.750     422.50  438.75
18   TSLA 2025-09-30  444.72    600.0   355.0  398.750     422.50  438.75
19   TSLA 2025-09-29  443.21    600.0   355.0  398.750     422.50  438.75
20   TSLA 2025-09-26  440.40    600.0   290.0  375.000     410.00  437.50
21   TSLA 2025-09-25  423.39    440.0   290.0  355.000     395.00  410.00
22   TSLA 2025-09-24  442.79    440.0   290.0  355.000     395.00  410.00
23   TSLA 2025-09-23  425.85    440.0   290.0  355.000     395.00  410.00
24   TSLA 2025-09-22  434.21    440.0   290.0  355.000     395.00  410.00
25   TSLA 2025-09-19  426.07    440.0   290.0  355.000     395.00  410.00
26   TSLA 2025-09-18  416.85    440.0   290.0  355.000     395.00  410.00
27   TSLA 2025-09-17  425.86    440.0   290.0  338.750     382.50  417.50
28   TSLA 2025-09-16  421.62    440.0   290.0  338.750     382.50  417.50
29   TSLA 2025-09-15  410.04    440.0   290.0  338.750     382.50  417.50
30   TSLA 2025-09-12  395.94    440.0   290.0  338.750     382.50  417.50
31   TSLA 2025-09-11  368.81    440.0   290.0  338.750     382.50  417.50
32   TSLA 2025-09-10  347.79    440.0   290.0  338.750     382.50  417.50
33   TSLA 2025-09-09  346.97    440.0   290.0  338.750     382.50  417.50
34   TSLA 2025-09-08  346.40    440.0   290.0  338.750     382.50  417.50
35   TSLA 2025-09-05  350.84    440.0   290.0  338.750     382.50  417.50
36   TSLA 2025-09-04  338.53    355.0   290.0  306.250     322.50  338.75
37   TSLA 2025-09-03  334.09    500.0   290.0  322.500     355.00  427.50
38   TSLA 2025-09-02  329.36    500.0   290.0  322.500     355.00  427.50
39   TSLA 2025-08-29  333.87    500.0   290.0  322.500     355.00  427.50
40   TSLA 2025-08-28  345.98    500.0   290.0  322.500     355.00  427.50
41   TSLA 2025-08-27  349.60    500.0   290.0  322.500     355.00  427.50
42   TSLA 2025-08-26  351.67    500.0   290.0  322.500     355.00  427.50
43   TSLA 2025-08-25  346.60    500.0   290.0  322.500     355.00  427.50
44   TSLA 2025-08-22  340.01    500.0   290.0  322.500     355.00  427.50
45   TSLA 2025-08-21  320.11    500.0   290.0  322.500     355.00  427.50
46   TSLA 2025-08-20  323.90    500.0   290.0  322.500     355.00  427.50
47   TSLA 2025-08-19  329.31    500.0   290.0  322.500     355.00  427.50
48   TSLA 2025-08-18  335.16    500.0   290.0  322.500     355.00  427.50
49   TSLA 2025-08-15  330.56    500.0   290.0  338.750     372.50  417.50
50   TSLA 2025-08-14  335.58    500.0   290.0  338.750     372.50  417.50
51   TSLA 2025-08-13  339.38    500.0   290.0  338.750     372.50  417.50
52   TSLA 2025-08-12  340.84    500.0   290.0  338.750     372.50  417.50
53   TSLA 2025-08-11  339.03    500.0   290.0  338.750     372.50  417.50
54   TSLA 2025-08-08  329.65    500.0   290.0  338.750     372.50  417.50
55   TSLA 2025-08-07  322.27    500.0   290.0  338.750     372.50  417.50
56   TSLA 2025-08-06  319.91    500.0   290.0  338.750     372.50  417.50
57   TSLA 2025-08-05  308.72    500.0   290.0  355.000     390.00  400.00
58   TSLA 2025-08-04  309.26    500.0   290.0  355.000     390.00  400.00
59   TSLA 2025-08-01  302.63    500.0   290.0  355.000     390.00  400.00
60   TSLA 2025-07-31  308.27    500.0   290.0  355.000     390.00  400.00
61   TSLA 2025-07-30  319.04    500.0   290.0  355.000     390.00  400.00
62   TSLA 2025-07-29  321.20    500.0   290.0  355.000     390.00  400.00
63   TSLA 2025-07-28  325.59    500.0   290.0  355.000     390.00  400.00
64   TSLA 2025-07-25  316.06    500.0   290.0  355.000     390.00  400.00
65   TSLA 2025-07-24  305.30    500.0   290.0  355.000     390.00  400.00
66   TSLA 2025-07-23  332.56    500.0   290.0  372.500     400.00  430.00
67   TSLA 2025-07-22  332.11    500.0   290.0  372.500     400.00  430.00
68   TSLA 2025-07-21  328.49    500.0   280.0  338.750     395.00  420.00
69   TSLA 2025-07-18  329.65    500.0   280.0  365.000     405.00  435.00
70   TSLA 2025-07-17  319.41    500.0   280.0  365.000     405.00  435.00
71   TSLA 2025-07-16  321.67    500.0   280.0  365.000     405.00  435.00
72   TSLA 2025-07-15  310.78    500.0   137.0  290.000     400.00  430.00
73   TSLA 2025-07-14  316.90    500.0   137.0  290.000     400.00  430.00
74   TSLA 2025-07-11  313.51    500.0   137.0  290.000     400.00  430.00
75   TSLA 2025-07-10  309.87    500.0   137.0  290.000     400.00  430.00
76   TSLA 2025-07-09  295.88    500.0   137.0  290.000     400.00  430.00
77   TSLA 2025-07-08  297.81    500.0   137.0  290.000     400.00  430.00
78   TSLA 2025-07-07  293.94    500.0   137.0  290.000     400.00  430.00
79   TSLA 2025-07-03  315.35    500.0   137.0  290.000     400.00  430.00
80   TSLA 2025-07-02  315.65    500.0   137.0  290.000     400.00  430.00
81   TSLA 2025-07-01  300.71    500.0   137.0  290.000     400.00  430.00
82   TSLA 2025-06-30  317.66    500.0   137.0  290.000     400.00  430.00
83   TSLA 2025-06-27  323.63    500.0   137.0  345.000     400.00  430.00
84   TSLA 2025-06-26  325.78    500.0   137.0  345.000     400.00  430.00
85   TSLA 2025-06-25  327.55    500.0   137.0  345.000     400.00  430.00
86   TSLA 2025-06-24  340.47    500.0   137.0  345.000     400.00  430.00
87   TSLA 2025-06-23  348.68    500.0   137.0  345.000     400.00  430.00
88   TSLA 2025-06-20  322.16    500.0   137.0  345.000     400.00  430.00
89   TSLA 2025-06-18  322.05    500.0   137.0  345.000     400.00  430.00
90   TSLA 2025-06-17  316.35    500.0   137.0  345.000     400.00  430.00
91   TSLA 2025-06-16  329.13    500.0   137.0  345.000     400.00  430.00
92   TSLA 2025-06-13  325.31    500.0   137.0  356.250     405.00  430.00
93   TSLA 2025-06-12  319.11    500.0   137.0  356.250     405.00  430.00
94   TSLA 2025-06-11  326.43    500.0   137.0  356.250     405.00  430.00
95   TSLA 2025-06-10  326.09    500.0   137.0  356.250     405.00  430.00
96   TSLA 2025-06-09  308.58    500.0   137.0  356.250     405.00  430.00
97   TSLA 2025-06-06  295.14    500.0   137.0  356.250     405.00  430.00
98   TSLA 2025-06-05  284.70    500.0   137.0  357.500     400.00  430.00
99   TSLA 2025-06-04  332.05    500.0   137.0  357.500     400.00  430.00
100  TSLA 2025-06-03  344.27    450.0   137.0  351.250     395.00  425.00
101  TSLA 2025-06-02  342.69    450.0   137.0  351.250     395.00  425.00
102  TSLA 2025-05-30  346.46    450.0   137.0  351.250     395.00  425.00
103  TSLA 2025-05-29  358.43    450.0   137.0  351.250     395.00  425.00
104  TSLA 2025-05-28  356.90    450.0   137.0  351.250     395.00  425.00
105  TSLA 2025-05-27  362.89    450.0   137.0  351.250     395.00  425.00
106  TSLA 2025-05-23  339.34    450.0   137.0  323.900     390.00  420.00
107  TSLA 2025-05-22  341.04    450.0   137.0  323.900     390.00  420.00
108  TSLA 2025-05-21  334.62    450.0   137.0  323.900     390.00  420.00
109  TSLA 2025-05-20  343.82    450.0   137.0  323.900     390.00  420.00
110  TSLA 2025-05-19  342.09    450.0   137.0  323.900     390.00  420.00
111  TSLA 2025-05-16  349.98    450.0   137.0  323.900     390.00  420.00
112  TSLA 2025-05-15  342.82    450.0   137.0  313.350     385.00  425.00
113  TSLA 2025-05-14  347.68    450.0   137.0  313.350     385.00  425.00
114  TSLA 2025-05-13  334.07    450.0   137.0  313.350     385.00  425.00
115  TSLA 2025-05-12  318.38    450.0   137.0  313.350     385.00  425.00
116  TSLA 2025-05-09  298.26    450.0   137.0  315.650     370.00  420.00
117  TSLA 2025-05-08  284.82    450.0   137.0  315.650     370.00  420.00
118  TSLA 2025-05-07  276.22    450.0   137.0  315.650     370.00  420.00
119  TSLA 2025-05-06  275.35    450.0   137.0  315.650     370.00  420.00
120  TSLA 2025-05-05  280.26    450.0   137.0  309.225     357.50  425.00
121  TSLA 2025-05-02  287.21    450.0   137.0  309.225     357.50  425.00
122  TSLA 2025-05-01  280.52    450.0   137.0  309.225     357.50  425.00
123  TSLA 2025-04-30  282.16    450.0   137.0  309.225     357.50  425.00
124  TSLA 2025-04-29  292.03    450.0   137.0  309.225     357.50  425.00
125  TSLA 2025-04-28  285.88    450.0   137.0  309.225     357.50  425.00
126  TSLA 2025-04-25  284.95    450.0   137.0  309.225     357.50  425.00
127  TSLA 2025-04-24  259.51    450.0   137.0  309.225     357.50  425.00
128  TSLA 2025-04-23  250.74    430.0   137.0  297.100     336.75  385.00
129  TSLA 2025-04-22  237.97    430.0   137.0  297.100     336.75  385.00
130  TSLA 2025-04-21  227.50    550.0   137.0  322.075     357.50  430.00
131  TSLA 2025-04-17  241.37    550.0   137.0  315.650     345.00  400.00
132  TSLA 2025-04-16  241.55    550.0   137.0  315.650     345.00  400.00
133  TSLA 2025-04-15  254.11    550.0   302.8  332.625     357.50  415.00
134  TSLA 2025-04-14  252.35    550.0   302.8  332.625     357.50  415.00
135  TSLA 2025-04-11  252.31    550.0   302.8  332.625     357.50  415.00
136  TSLA 2025-04-10  252.40    550.0   302.8  332.625     357.50  415.00
137  TSLA 2025-04-09  272.20    550.0   302.8  332.625     357.50  415.00
138  TSLA 2025-04-08  221.86    550.0   302.8  332.625     357.50  415.00
139  TSLA 2025-04-07  233.29    550.0   302.8  332.625     357.50  415.00
140  TSLA 2025-04-04  239.43    550.0   302.8  332.625     357.50  415.00
141  TSLA 2025-04-03  267.28    550.0   302.8  332.625     357.50  415.00
142  TSLA 2025-04-02  282.76    550.0   275.0  322.075     357.50  410.50
143  TSLA 2025-04-01  268.46    550.0   275.0  322.075     357.50  410.50
144  TSLA 2025-03-31  259.16    550.0   275.0  322.075     357.50  410.50
145  TSLA 2025-03-28  263.55    550.0   275.0  322.075     357.50  410.50
146  TSLA 2025-03-27  273.13    550.0   275.0  315.650     370.00  417.00
147  TSLA 2025-03-26  272.06    550.0   275.0  315.650     370.00  417.00
148  TSLA 2025-03-25  288.14    550.0   275.0  315.650     370.00  417.00
149  TSLA 2025-03-24  278.39    550.0   275.0  315.650     370.00  417.00
150  TSLA 2025-03-21  248.71    550.0   275.0  315.650     370.00  417.00
151  TSLA 2025-03-20  236.26    550.0   275.0  315.650     370.00  417.00
152  TSLA 2025-03-19  235.86    550.0   275.0  315.650     370.00  417.00
153  TSLA 2025-03-18  225.31    550.0   275.0  315.650     370.00  417.00
154  TSLA 2025-03-17  238.01    550.0   275.0  315.650     370.00  417.00
155  TSLA 2025-03-14  249.98    550.0   275.0  315.650     370.00  459.50
156  TSLA 2025-03-13  240.68    550.0   275.0  315.650     370.00  459.50
157  TSLA 2025-03-12  248.09    550.0   275.0  315.650     370.00  459.50
158  TSLA 2025-03-11  230.58    550.0   275.0  315.650     370.00  459.50
159  TSLA 2025-03-10  222.15    550.0   275.0  315.650     370.00  459.50
160  TSLA 2025-03-07  262.67    550.0   275.0  315.650     370.00  459.50
161  TSLA 2025-03-06  263.45    550.0   275.0  315.650     370.00  459.50
162  TSLA 2025-03-05  279.10    550.0   275.0  309.225     366.25  487.25
163  TSLA 2025-03-04  272.04    550.0   275.0  309.225     366.25  487.25
164  TSLA 2025-03-03  284.65    550.0   275.0  309.225     366.25  487.25
165  TSLA 2025-02-28  292.98    550.0   275.0  322.075     402.00  437.00
166  TSLA 2025-02-27  281.95    550.0   275.0  322.075     402.00  437.00
167  TSLA 2025-02-26  290.80    550.0   275.0  322.075     402.00  437.00
168  TSLA 2025-02-25  302.80    550.0   275.0  322.075     402.00  437.00
169  TSLA 2025-02-24  330.53    550.0   275.0  364.250     404.00  463.00
170  TSLA 2025-02-21  337.80    550.0   275.0  364.250     404.00  463.00
171  TSLA 2025-02-20  354.40    550.0   275.0  364.250     404.00  463.00
172  TSLA 2025-02-19  360.56    550.0   275.0  364.250     404.00  463.00
173  TSLA 2025-02-18  354.11    550.0   275.0  364.250     404.00  463.00
174  TSLA 2025-02-14  355.84    550.0   270.0  315.125     402.00  437.00
175  TSLA 2025-02-13  355.94    550.0   270.0  313.000     400.00  411.00
176  TSLA 2025-02-12  336.51    550.0   270.0  313.000     400.00  411.00
177  TSLA 2025-02-11  328.50    550.0   270.0  313.000     400.00  411.00
178  TSLA 2025-02-10  350.73    550.0   270.0  303.500     402.00  437.00
179  TSLA 2025-02-07  361.62    550.0   270.0  303.500     402.00  437.00
180  TSLA 2025-02-06  374.32    550.0   270.0  303.500     402.00  437.00
181  TSLA 2025-02-05  378.17    550.0   270.0  303.500     402.00  437.00
182  TSLA 2025-02-04  392.21    550.0   270.0  303.500     402.00  437.00
183  TSLA 2025-02-03  383.68    550.0   270.0  303.500     402.00  437.00
184  TSLA 2025-01-31  404.60    550.0   270.0  303.500     402.00  437.00
185  TSLA 2025-01-30  400.28    550.0   270.0  303.500     402.00  437.00
186  TSLA 2025-01-29  389.10    550.0   270.0  303.500     402.00  437.00
187  TSLA 2025-01-28  398.09    550.0   270.0  303.500     402.00  437.00
188  TSLA 2025-01-27  397.15    550.0   270.0  313.000     400.00  411.00
189  TSLA 2025-01-24  406.58    550.0   270.0  301.750     357.50  409.25
190  TSLA 2025-01-23  412.38    550.0   270.0  301.750     357.50  409.25
191  TSLA 2025-01-22  415.11    550.0   236.0  255.000     278.00  400.00
192  TSLA 2025-01-21  424.07    515.0   236.0  253.750     277.00  336.25
193  TSLA 2025-01-17  426.50    515.0   195.0  250.000     276.00  315.00
194  TSLA 2025-01-16  413.82    515.0   195.0  250.000     276.00  315.00
195  TSLA 2025-01-15  428.22    515.0   195.0  250.000     276.00  315.00
196  TSLA 2025-01-14  396.36    515.0   195.0  250.000     276.00  315.00
197  TSLA 2025-01-13  403.31    515.0   195.0  249.250     275.50  314.50
198  TSLA 2025-01-10  394.74    515.0    88.0  237.500     272.50  313.50
199  TSLA 2025-01-08  394.94    515.0    88.0  237.500     272.50  313.50
200  TSLA 2025-01-07  394.36    515.0    88.0  237.500     272.50  313.50
201  TSLA 2025-01-06  411.05    515.0    88.0  236.500     262.50  309.25
202  TSLA 2025-01-03  410.44    515.0    88.0  236.500     262.50  309.25
203  TSLA 2025-01-02  379.28    515.0    88.0  236.000     250.00  298.00
204  TSLA 2024-12-31  403.84    515.0    88.0  236.000     250.00  298.00
205  TSLA 2024-12-30  417.41    515.0    88.0  236.000     250.00  298.00
206  TSLA 2024-12-27  431.66    515.0    88.0  236.000     250.00  298.00
207  TSLA 2024-12-26  454.13    515.0    88.0  236.000     250.00  298.00
208  TSLA 2024-12-24  462.28    515.0    88.0  236.000     250.00  298.00
209  TSLA 2024-12-23  430.60    515.0    88.0  236.000     252.50  307.00
210  TSLA 2024-12-20  421.06    515.0    88.0  236.000     252.50  307.00
211  TSLA 2024-12-19  436.17    515.0    88.0  236.000     255.00  304.00
212  TSLA 2024-12-18  440.13    515.0    88.0  236.000     255.00  304.00
213  TSLA 2024-12-17  479.86    515.0    88.0  236.000     255.00  304.00
214  TSLA 2024-12-16  463.02    515.0    88.0  236.000     255.00  304.00
215  TSLA 2024-12-13  436.23    411.0    88.0  236.000     252.50  293.00
216  TSLA 2024-12-12  418.10    411.0    88.0  236.000     252.50  293.00
217  TSLA 2024-12-11  424.77    411.0    88.0  236.000     254.00  288.00
218  TSLA 2024-12-10  400.99    411.0    88.0  236.000     254.00  288.00
219  TSLA 2024-12-09  389.79    411.0    88.0  236.000     254.00  288.00
220  TSLA 2024-12-06  389.22    411.0    88.0  236.000     254.50  295.75
221  TSLA 2024-12-05  369.49    411.0    88.0  236.000     254.50  295.75
222  TSLA 2024-12-04  357.93    411.0    88.0  236.000     254.00  295.00
223  TSLA 2024-12-03  351.42    411.0    88.0  236.000     254.00  295.00
224  TSLA 2024-12-02  357.09    411.0    88.0  236.000     254.00  295.00
225  TSLA 2024-11-29  345.16    400.0    88.0  234.500     252.00  282.25
226  TSLA 2024-11-27  332.89    315.0    88.0  233.000     250.00  277.00
227  TSLA 2024-11-26  338.23    315.0    88.0  233.000     250.00  277.00
228  TSLA 2024-11-25  338.59    315.0    88.0  233.000     250.00  277.00
229  TSLA 2024-11-22  352.56    315.0    88.0  233.000     250.00  277.00
230  TSLA 2024-11-21  339.64    315.0    88.0  233.000     250.00  277.00
231  TSLA 2024-11-20  342.03    315.0    88.0  233.000     250.00  277.00
232  TSLA 2024-11-19  346.00    315.0    88.0  233.000     250.00  277.00
233  TSLA 2024-11-18  338.74    315.0    88.0  233.000     250.00  277.00
234  TSLA 2024-11-15  320.72    315.0    88.0  225.000     249.00  277.00
235  TSLA 2024-11-14  311.18    315.0    88.0  225.000     249.00  277.00
236  TSLA 2024-11-13  330.24    315.0    88.0  222.500     247.00  270.75
237  TSLA 2024-11-12  328.49    315.0    88.0  222.500     247.00  270.75
238  TSLA 2024-11-11  350.00    315.0    88.0  222.500     247.00  270.75
239  TSLA 2024-11-08  321.22    315.0    88.0  222.500     247.00  270.75
240  TSLA 2024-11-07  296.91    315.0    88.0  222.500     247.00  270.75
241  TSLA 2024-11-06  288.53    315.0    88.0  222.000     245.00  265.50
242  TSLA 2024-11-05  251.44    315.0    88.0  222.000     245.00  265.50
243  TSLA 2024-11-04  242.84    315.0    88.0  222.000     245.00  265.50
244  TSLA 2024-11-01  248.98    315.0    88.0  222.000     245.00  265.50
245  TSLA 2024-10-31  249.85    315.0    88.0  222.000     245.00  265.50
246  TSLA 2024-10-30  257.55    315.0    88.0  222.000     245.00  265.50
247  TSLA 2024-10-29  259.52    315.0    88.0  222.000     245.00  265.50
248  TSLA 2024-10-28  262.51    315.0    88.0  218.750     241.50  260.25
249  TSLA 2024-10-25  269.19    310.0    88.0  216.250     237.00  254.75
250  TSLA 2024-10-24  260.48    310.0    88.0  217.500     238.00  255.00