# Database Queries and Analysis
This notebook contains queries for various database tables, identifies potential data issues, and provides insights for further analysis.

In [2]:
# Import required libraries
import pandas as pd
import os
from utils import connect_to_db

In [2]:
# Query the `stock_metadata` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.stock_profiles;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_18432/3899041700.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,name,sector,industry,country,market_cap,employees,description,website,exchange,currency,source,raw_json,raw_json_sha256,updated_at
0,AAPL,Apple Inc.,Technology,Consumer Electronics,United States,3900351184896,150000,"Apple Inc. designs, manufactures, and markets ...",https://www.apple.com,NASDAQ,USD,yfinance,"{'ask': 263.01, 'bid': 262.69, 'zip': '95014',...",bf0aa12b3e7efd09f04e8ad180d2a816be94647f89b999...,2025-10-27 04:03:28.266293+00:00
1,TSLA,"Tesla, Inc.",Consumer Cyclical,Auto Manufacturers,United States,1442474229760,125665,"Tesla, Inc. designs, develops, manufactures, l...",https://www.tesla.com,NASDAQ,USD,yfinance,"{'ask': 447.0, 'bid': 433.18, 'zip': '78725', ...",ad14d1717f063b1dc2637c3636c11d594f1c6315333d87...,2025-10-27 04:03:28.266293+00:00
2,NVDA,NVIDIA Corporation,Technology,Semiconductors,United States,4534872047616,36000,"NVIDIA Corporation, a computing infrastructure...",https://www.nvidia.com,NASDAQ,USD,yfinance,"{'ask': 186.47, 'bid': 185.23, 'zip': '95051',...",2b03f4a47c265a14a12a86ec5e1bae05513e0a87ce196e...,2025-10-27 04:03:28.266293+00:00
3,SOFI,"SoFi Technologies, Inc.",Financial Services,Credit Services,United States,34738028544,5000,"SoFi Technologies, Inc. provides various finan...",https://www.sofi.com,NASDAQ,USD,yfinance,"{'ask': 29.07, 'bid': 28.96, 'zip': '94105', '...",0d2d4bde0e2b3e355e30a5e57bac951e1b5a7ba2788e6a...,2025-10-27 04:03:28.266293+00:00
4,AMZN,"Amazon.com, Inc.",Consumer Cyclical,Internet Retail,United States,2391180050432,1546000,"Amazon.com, Inc. engages in the retail sale of...",https://www.aboutamazon.com,NASDAQ,USD,yfinance,"{'ask': 224.38, 'bid': 224.14, 'zip': '98109-5...",2cae40a3f7e3dd161b3258b39b87893add2384974c997f...,2025-10-27 04:03:28.266293+00:00
5,HOOD,"Robinhood Markets, Inc.",Financial Services,Capital Markets,United States,124227878912,2300,"Robinhood Markets, Inc. operates financial ser...",https://robinhood.com,NASDAQ,USD,yfinance,"{'ask': 139.97, 'bid': 139.57, 'zip': '94025',...",3e4e7e52fd7a673be4366f6cb0aa34e5f06542e069f7e5...,2025-10-27 04:13:49.941686+00:00
6,PLTR,Palantir Technologies Inc.,Technology,Software - Infrastructure,United States,438005596160,4164,Palantir Technologies Inc. builds and deploys ...,https://www.palantir.com,NASDAQ,USD,yfinance,"{'ask': 184.78, 'bid': 184.48, 'zip': '80202',...",3bfb2e9235e3e06e5290f0755be093ceb9eb66ac8b76ad...,2025-10-27 04:13:49.941686+00:00

In [ ]:
# Query the `stock_ohlcv` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.stock_ohlcv;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [3]:
# Query the `earnings` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.earnings ORDER BY tic, earnings_date DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()

    # Replace NaN with None for consistency
    df = df.where(pd.notnull(df), None)

    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_18432/432778468.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,earnings_date,fiscal_date,session,eps,eps_estimated,revenue,revenue_estimated,price_before,price_after,source,raw_json,raw_json_sha256,updated_at
0,AAPL,2026-04-26,2026-03-29,amc,NaN,NaN,NaN,NaN,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2026-04-26', 'symbol': 'AAPL', 'epsA...",06cf18a752284b73358709470c8f7dd84cc48a744e8ce2...,2025-10-27 04:16:53.015930+00:00
1,AAPL,2026-01-28,2025-12-28,amc,NaN,NaN,NaN,NaN,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2026-01-28', 'symbol': 'AAPL', 'epsA...",9a060126cf3f854c7aea63df4875b4582c7785feb0d4e2...,2025-10-27 04:16:53.015930+00:00
2,AAPL,2025-10-30,None,None,NaN,1.73,NaN,1.020888e+11,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-10-30', 'symbol': 'AAPL', 'epsA...",2fda15cd2548d854f25e23b1db4ba5376ab471917f0f48...,2025-10-27 04:16:52.794442+00:00
3,AAPL,2025-07-31,2025-06-28,amc,1.5700,1.44,9.403600e+10,8.956274e+10,209.050,202.38,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-07-31', 'symbol': 'AAPL', 'epsA...",737dcf63b916a8ffe43edeaa69041921417b57df04ae1a...,2025-10-27 04:16:53.015930+00:00
4,AAPL,2025-05-01,2025-03-29,amc,1.6500,1.63,9.535900e+10,9.454218e+10,213.065,204.88,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-05-01', 'symbol': 'AAPL', 'epsA...",09e01e72b1c2a94a6310e83dcedfd1be5c4a3a0d7bde41...,2025-10-27 04:16:53.015930+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,TSLA,2009-03-31,2009-03-31,amc,-0.0076,NaN,2.088600e+07,NaN,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2009-03-31', 'symbol': 'TSLA', 'epsA...",f5098c8acd1d8645449b4114cc7a4bbc8da71e28480599...,2025-10-27 04:16:53.309938+00:00
500,TSLA,2008-12-31,2008-12-31,amc,NaN,NaN,1.416200e+07,NaN,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2008-12-31', 'symbol': 'TSLA', 'epsA...",2fc8274640ead5b8c78eaf731c768fc8ed7400643d809b...,2025-10-27 04:16:53.309938+00:00
501,TSLA,2008-03-31,None,None,-0.0101,NaN,3.685500e+06,NaN,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2008-03-31', 'symbol': 'TSLA', 'epsA...",8deec1a869fd99a3329a80878d899d9f3654511a125625...,2025-10-27 04:16:53.189489+00:00
502,TSLA,2008-01-31,None,None,-0.0101,NaN,3.685500e+06,NaN,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2008-01-31', 'symbol': 'TSLA', 'epsA...",be2fad14cd2d00f6ea2623055c4170ca9fb1e99b3f119d...,2025-10-27 04:16:53.189489+00:00
503,TSLA,2007-03-31,None,None,-0.0096,NaN,1.825000e+04,NaN,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2007-03-31', 'symbol': 'TSLA', 'epsA...",7967ce04e07bc54552ca6368e2ac61e949c409f1ba2fa7...,2025-10-27 04:16:53.189489+00:00

In [11]:
# Query the `earnings` table
conn = connect_to_db()
if conn:
    query = """
    SELECT l.tic, l.earnings_date, r.fiscal_year, r.fiscal_quarter, l.fiscal_date, l.session 
    FROM raw.earnings AS l 
    INNER JOIN raw.income_statements AS r
    ON l.tic = r.tic AND ABS(l.fiscal_date::DATE - r.fiscal_date::DATE) < 15
    WHERE l.tic = 'NVDA'
    ORDER BY earnings_date DESC
    LIMIT 1;
    """
    df = pd.read_sql_query(query, conn)
    conn.close()

    # Replace NaN with None for consistency
    df = df.where(pd.notnull(df), None)

    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_18432/2324093206.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

    tic earnings_date  fiscal_year  fiscal_quarter fiscal_date session
0  NVDA    2025-08-27         2026               2  2025-07-27     amc

In [ ]:
# show all rows 
pd.set_option('display.max_rows', None)
df[df['tic']=='NVDA']

In [ ]:
# check if any duplication from ticker, fiscal_year, fiscal_quarter
df_duplicates = df[df.duplicated(subset=['tic', 'fiscal_year', 'fiscal_quarter'], keep=False)]
if not df_duplicates.empty:
    print("Duplicate entries found:")
    display(df_duplicates)
else:
    print("No duplicate entries found.")

In [ ]:
df[(df['tic']=='TSLA' )]

In [ ]:
# Query the `earnings_transcripts` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.earnings_transcripts;"
    df = pd.read_sql_query(query, conn)
    conn.close()

    # Replace NaN with None for consistency
    df = df.where(pd.notnull(df), None)

    # Display the data
    display(df)

In [ ]:
# show all rows 
pd.set_option('display.max_rows', None)

In [4]:
# Query the `income_statements` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.income_statements ORDER BY tic, fiscal_year DESC, fiscal_quarter DESC;"
    df = pd.read_sql_query(query, conn)
    conn.close()

    # Replace NaN with None for consistency
    df = df.where(pd.notnull(df), None)

    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_18432/4220957486.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,fiscal_year,fiscal_quarter,fiscal_date,source,raw_json,raw_json_sha256,updated_at
0,AAPL,2025,3,2025-06-28,https://financialmodelingprep.com/stable/incom...,"{'cik': '0000320193', 'eps': 1.57, 'date': '20...",65128050794714747c7bb391080a5b220c4322513d339a...,2025-10-27 04:16:04.252770+00:00
1,AAPL,2025,2,2025-03-29,https://financialmodelingprep.com/stable/incom...,"{'cik': '0000320193', 'eps': 1.65, 'date': '20...",36e4a552f7df55e0d1a6dc54fc20dea2807868cb00e017...,2025-10-27 04:16:04.104326+00:00
2,AAPL,2025,1,2024-12-28,https://financialmodelingprep.com/stable/incom...,"{'cik': '0000320193', 'eps': 2.41, 'date': '20...",b733fffd6bc6ad21b0568ac0815df4caf7c89c83a41095...,2025-10-27 04:16:03.960933+00:00
3,AAPL,2024,4,2024-09-28,https://financialmodelingprep.com/stable/incom...,"{'cik': '0000320193', 'eps': 0.97, 'date': '20...",26a2f9f44df3706e8add4adc2bad479fae9339e935466d...,2025-10-27 04:16:04.875276+00:00
4,AAPL,2024,3,2024-06-29,https://financialmodelingprep.com/stable/incom...,"{'cik': '0000320193', 'eps': 1.4, 'date': '202...",1a9db0844b5f8a6a064a89e5af7681e37bb27c04bc76fa...,2025-10-27 04:16:04.252770+00:00
...,...,...,...,...,...,...,...,...
170,TSLA,2021,2,2021-06-30,https://financialmodelingprep.com/stable/incom...,"{'cik': '0001318605', 'eps': 0.39, 'date': '20...",40f591c9302427ddbb5148b2ba39a2e6fbcd21a4297d9f...,2025-10-27 04:16:05.899317+00:00
171,TSLA,2021,1,2021-03-31,https://financialmodelingprep.com/stable/incom...,"{'cik': '0001318605', 'eps': 0.15, 'date': '20...",61d2ff8474e27dbdf496c209877fea606854661a46bb6e...,2025-10-27 04:16:05.171361+00:00
172,TSLA,2021,0,2021-12-31,https://financialmodelingprep.com/stable/incom...,"{'cik': '0001318605', 'eps': 1.87, 'date': '20...",5651eaedd9851dc0f0558d08669d8aa12ae4c523ccaa16...,2025-10-27 04:16:06.412576+00:00
173,TSLA,2020,4,2020-12-31,https://financialmodelingprep.com/stable/incom...,"{'cik': '0001318605', 'eps': 0.0838, 'date': '...",0fb57e51a2a151aa603a320faa30c10730e8b90717f425...,2025-10-27 04:16:06.216848+00:00
174,TSLA,2020,0,2020-12-31,https://financialmodelingprep.com/stable/incom...,"{'cik': '0001318605', 'eps': 0.25, 'date': '20...",123ca3d8c0a8582c511e69ac91c149e3ecabede2ec3e4d...,2025-10-27 04:16:06.412576+00:00

In [ ]:
df[df['fiscal_quarter'] != 0]

In [ ]:
for i in range(5):
    print(df[df['tic'] == 'AAPL']['raw_json'].iloc[i])

In [ ]:
df[df['tic'] == 'AAPL']['raw_json'].iloc[1]

In [ ]:
# Query the `balance_sheets` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.balance_sheets;"
    df = pd.read_sql_query(query, conn)
    conn.close()

    # Replace NaN with None for consistency
    df = df.where(pd.notnull(df), None)

    # Display the data
    display(df)

In [35]:
# Query the `cash_flow_statements` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.cash_flow_statements;"
    df = pd.read_sql_query(query, conn)
    conn.close()

    # Replace NaN with None for consistency
    df = df.where(pd.notnull(df), None)

    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_32774/3981558351.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,fiscal_year,fiscal_quarter,fiscal_date,source,raw_json,raw_json_sha256,updated_at
0,NVDA,2026,1,2025-04-27,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2025-04-27', 'p...",3e49c836b9786942facbe88f8818462df5c398a395aa2f...,2025-10-27 04:15:30.735587+00:00
1,NVDA,2025,1,2024-04-28,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2024-04-28', 'p...",2f86290b9b56feeed537b0c2d64d1d5c5aae8ec5ce892b...,2025-10-27 04:15:30.735587+00:00
2,NVDA,2024,1,2023-04-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2023-04-30', 'p...",b2d18c9958573d5e2c405eb347597d29289eae94a9ea31...,2025-10-27 04:15:30.735587+00:00
3,NVDA,2023,1,2022-05-01,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2022-05-01', 'p...",7da778ed45c97a887ccd8eb49bc62353fa627076fea4a5...,2025-10-27 04:15:30.735587+00:00
4,NVDA,2022,1,2021-05-02,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2021-05-02', 'p...",c918519ec10c414454daf84e8db1252a34003a227381ee...,2025-10-27 04:15:30.735587+00:00
5,NVDA,2026,2,2025-07-27,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2025-07-27', 'p...",44edea53be401927918691dd2db0dfeb8d90ab6e0c5fe5...,2025-10-27 04:15:31.151291+00:00
6,NVDA,2025,2,2024-07-28,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2024-07-28', 'p...",ff2fe31c6be82ff2e74b42e72dff3c7819b429f8a734e0...,2025-10-27 04:15:31.151291+00:00
7,NVDA,2024,2,2023-07-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2023-07-30', 'p...",2a38ab8e71bb7092e5002bc791aade1a872e39b10e94a5...,2025-10-27 04:15:31.151291+00:00
8,NVDA,2023,2,2022-07-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2022-07-31', 'p...",3e3d61027cae3639977d8eeaae9f5816fe3d124aa0b8a8...,2025-10-27 04:15:31.151291+00:00
9,NVDA,2022,2,2021-08-01,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2021-08-01', 'p...",ff168ba860387a80d4751b88cbf2b75680ae768c7db0c0...,2025-10-27 04:15:31.151291+00:00
10,NVDA,2025,3,2024-10-27,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2024-10-27', 'p...",a0a3435f0b929dcb89b4e8fe1b801a04cabc598a50e672...,2025-10-27 04:15:31.298909+00:00
11,NVDA,2024,3,2023-10-29,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2023-10-29', 'p...",c6b04d7af573d08a737481c6bcb39f6bb569dad7967bdd...,2025-10-27 04:15:31.298909+00:00
12,NVDA,2023,3,2022-10-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2022-10-30', 'p...",8eb575b4ef425f4ab11314317282c7854faead1c0b1dd1...,2025-10-27 04:15:31.298909+00:00
13,NVDA,2022,3,2021-10-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2021-10-31', 'p...",7496c9a8021f30a699b9bb4b87aa6d049d5448cb5c6aa2...,2025-10-27 04:15:31.298909+00:00
14,NVDA,2021,3,2020-10-25,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2020-10-25', 'p...",0a30f0c6d7a6417491ad1b09eefcd921e341ea86de4732...,2025-10-27 04:15:31.298909+00:00
15,NVDA,2025,4,2025-01-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2025-01-31', 'p...",d76a1246459bf4d5c435e13f008190a816b7322263ff8a...,2025-10-27 04:15:31.446890+00:00
16,NVDA,2024,4,2024-01-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2024-01-31', 'p...",68b5794e5b14a8cc26b5fe7f838e6cd0b9afdd21e7bd12...,2025-10-27 04:15:31.446890+00:00
17,NVDA,2023,4,2023-01-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2023-01-31', 'p...",47f15e166f63afabc9a6cebeebc9a0464c6fea8a6c936a...,2025-10-27 04:15:31.446890+00:00
18,NVDA,2022,4,2022-01-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2022-01-31', 'p...",08ffd8b36457595ae72d6c88c15715425de0fdbfe0680e...,2025-10-27 04:15:31.446890+00:00
19,NVDA,2021,4,2021-01-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2021-01-31', 'p...",f8e49708ce66f6f793c62c8574fce420f68c5637df2dda...,2025-10-27 04:15:31.446890+00:00
20,NVDA,2025,0,2025-01-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2025-01-31', 'p...",e52c4f4d0e268164713836d480ac593ef5df5914c95c8c...,2025-10-27 04:15:31.597992+00:00
21,NVDA,2024,0,2024-01-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2024-01-31', 'p...",53b387d2b170f605748a09e20b453bd8807377f03b5a28...,2025-10-27 04:15:31.597992+00:00
22,NVDA,2023,0,2023-01-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2023-01-31', 'p...",17bff902b1d0bf238e47c73af1ba9b860ae092093fc150...,2025-10-27 04:15:31.597992+00:00
23,NVDA,2022,0,2022-01-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2022-01-31', 'p...",1d48fb4a630b8cb812f7784097d98847e7420a8994a098...,2025-10-27 04:15:31.597992+00:00
24,NVDA,2021,0,2021-01-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001045810', 'date': '2021-01-31', 'p...",35b40439fee8ff4d679ddd75fa6d12f89aa6f3271b6494...,2025-10-27 04:15:31.597992+00:00
25,AAPL,2025,1,2024-12-28,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2024-12-28', 'p...",6b1183221f73bbcdcd3921b2fd0962ff3f6e3ab6e99df6...,2025-10-27 04:15:31.742632+00:00
26,AAPL,2024,1,2023-12-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2023-12-30', 'p...",d534d5d5c2561467306d60f2ee903b7952e6721ef679d9...,2025-10-27 04:15:31.742632+00:00
27,AAPL,2023,1,2022-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2022-12-31', 'p...",2514ab1353de4609e5f367b412781f6a087c2364f108a4...,2025-10-27 04:15:31.742632+00:00
28,AAPL,2022,1,2021-12-25,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2021-12-25', 'p...",653713537dd1f11a69bcba6234e43f9a35a4a5c193bf36...,2025-10-27 04:15:31.742632+00:00
29,AAPL,2021,1,2020-12-26,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2020-12-26', 'p...",f941d3368ea6e5e223ab4810e80f456a95fc8709d6c62b...,2025-10-27 04:15:31.742632+00:00
30,AAPL,2025,2,2025-03-29,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2025-03-29', 'p...",b6a3791e81098ab886802109c9415bcf5556fe4aeb0dc2...,2025-10-27 04:15:31.891500+00:00
31,AAPL,2024,2,2024-03-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2024-03-30', 'p...",62ac78236b2558d6b89b1a8af38b792d0703f8e6d0a5cf...,2025-10-27 04:15:31.891500+00:00
32,AAPL,2023,2,2023-04-01,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2023-04-01', 'p...",8108dfcdeb637e77934d4a15e7c6c12b28e93a22bce227...,2025-10-27 04:15:31.891500+00:00
33,AAPL,2022,2,2022-03-26,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2022-03-26', 'p...",6a83cb0f26a7be63e8994a452e33fbb64adf97ddca83e8...,2025-10-27 04:15:31.891500+00:00
34,AAPL,2021,2,2021-03-27,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2021-03-27', 'p...",85db5187afb4eb58e1ca43641ed681beb90dedd43b6122...,2025-10-27 04:15:31.891500+00:00
35,AAPL,2025,3,2025-06-28,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2025-06-28', 'p...",56cb81d6c62a5607221795ea7877b8403b4f58aed88d9a...,2025-10-27 04:15:32.042781+00:00
36,AAPL,2024,3,2024-06-29,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2024-06-29', 'p...",e300227a28a8d921fcaa39b5f3fecbce05b515ceae7651...,2025-10-27 04:15:32.042781+00:00
37,AAPL,2023,3,2023-07-01,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2023-07-01', 'p...",3e08b16ed3bdc0664681c4b690276056b7213abdf8bdc5...,2025-10-27 04:15:32.042781+00:00
38,AAPL,2022,3,2022-06-25,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2022-06-25', 'p...",237c99da995ca5ebf08f9c2b7a60ce1e4da1a96ac9495f...,2025-10-27 04:15:32.042781+00:00
39,AAPL,2021,3,2021-06-26,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2021-06-26', 'p...",210366131a0ab642d37725c1d6470a28699a13903fdadf...,2025-10-27 04:15:32.042781+00:00
40,AAPL,2024,4,2024-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2024-09-30', 'p...",6c411132a155d8dd9164b02315743ffc3426eaa89df6e6...,2025-10-27 04:15:32.194627+00:00
41,AAPL,2023,4,2023-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2023-09-30', 'p...",29b324be09744342f56ec85763436ca7a4f72ff23b26ef...,2025-10-27 04:15:32.194627+00:00
42,AAPL,2022,4,2022-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2022-09-30', 'p...",b7209f6ef870a6d60c9e18bbe49d5a0b9f1ff6eeef5aef...,2025-10-27 04:15:32.194627+00:00
43,AAPL,2021,4,2021-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2021-09-30', 'p...",61b78e8b7384b18348d306eab8c92c3538819908741428...,2025-10-27 04:15:32.194627+00:00
44,AAPL,2020,4,2020-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2020-09-30', 'p...",551f1afcb8e9ba348eac952a8e7707508e793f09ece7a5...,2025-10-27 04:15:32.194627+00:00
45,AAPL,2024,0,2024-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2024-09-30', 'p...",a245dcb9ca865fc1cb1ffeff25e2d30bde3fba572777c8...,2025-10-27 04:15:32.338120+00:00
46,AAPL,2023,0,2023-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2023-09-30', 'p...",4f4afbd10877b18219a15229f096adc9e7dc72e2fb183b...,2025-10-27 04:15:32.338120+00:00
47,AAPL,2022,0,2022-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2022-09-30', 'p...",2c20004a81d3c8255a4184e1674dcc88e7c953914cc866...,2025-10-27 04:15:32.338120+00:00
48,AAPL,2021,0,2021-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2021-09-30', 'p...",7dddbef4fd7c6057733fc0839789278510994391678d2b...,2025-10-27 04:15:32.338120+00:00
49,AAPL,2020,0,2020-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0000320193', 'date': '2020-09-30', 'p...",2263270cdfe48d425e714465dead436f9c9734d460b061...,2025-10-27 04:15:32.338120+00:00
50,TSLA,2025,1,2025-03-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2025-03-31', 'p...",163a9e34902919c80f966e062a7b4c6e2dd232092a0ae6...,2025-10-27 04:15:32.486475+00:00
51,TSLA,2024,1,2024-03-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2024-03-31', 'p...",f21b4bf36f8eb80179acfc043dd51d7b394d4b5f09cdb9...,2025-10-27 04:15:32.486475+00:00
52,TSLA,2023,1,2023-03-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2023-03-31', 'p...",aceac92b173045f85f1108e073ca58dead017a4243b809...,2025-10-27 04:15:32.486475+00:00
53,TSLA,2022,1,2022-03-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2022-03-31', 'p...",78b0af8c2be089d9fba30b7a475f6839cb413112c7390b...,2025-10-27 04:15:32.486475+00:00
54,TSLA,2021,1,2021-03-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2021-03-31', 'p...",6a078491bb1fa186ddadc89ba085dc08fa8a84e3f9c84f...,2025-10-27 04:15:32.486475+00:00
55,TSLA,2025,2,2025-06-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2025-06-30', 'p...",ac0c9715424abc75f9024bfa776e75f81e721b95875d98...,2025-10-27 04:15:32.637680+00:00
56,TSLA,2024,2,2024-06-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2024-06-30', 'p...",31ca1693f4e6b7d1a240a3a7b1b821ad19071b44db4fef...,2025-10-27 04:15:32.637680+00:00
57,TSLA,2023,2,2023-06-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2023-06-30', 'p...",4b62c213e7744a2ea2725ca5bdef041ff62fa6bb891be1...,2025-10-27 04:15:32.637680+00:00
58,TSLA,2022,2,2022-06-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2022-06-30', 'p...",d708c2c9f91e73d5a38487ea7059b86f4b4fde9dad39d6...,2025-10-27 04:15:32.637680+00:00
59,TSLA,2021,2,2021-06-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2021-06-30', 'p...",35e26eb7ef0b1bc7a55b548bfd337ee9197e2c18c2fbe8...,2025-10-27 04:15:32.637680+00:00
60,TSLA,2025,3,2025-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2025-09-30', 'p...",6dd84d351f57e7f5344d16ffeecf343555d55182ce7f9b...,2025-10-27 04:15:32.791311+00:00
61,TSLA,2024,3,2024-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2024-09-30', 'p...",066eceae89074de8caa15a4e5c79478bf070675f4c0c66...,2025-10-27 04:15:32.791311+00:00
62,TSLA,2023,3,2023-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2023-09-30', 'p...",2c62ae11eff3cd4644a896b01bcd9091d18db79feef9cf...,2025-10-27 04:15:32.791311+00:00
63,TSLA,2022,3,2022-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2022-09-30', 'p...",188ebbe1251c82fb0aa9390cdec95323e35b0cd1c23237...,2025-10-27 04:15:32.791311+00:00
64,TSLA,2021,3,2021-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2021-09-30', 'p...",a5532b24ef2614a6a804e9eaa352ef55838192967bf995...,2025-10-27 04:15:32.791311+00:00
65,TSLA,2024,4,2024-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2024-12-31', 'p...",9f5b5ff6107b7785c47bcfe34bfd59052ccd8d7b7d94c2...,2025-10-27 04:15:32.949834+00:00
66,TSLA,2023,4,2023-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2023-12-31', 'p...",6ad9cbd9abccd912451a2f4d96c3296c7629b265368c73...,2025-10-27 04:15:32.949834+00:00
67,TSLA,2022,4,2022-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2022-12-31', 'p...",0a2dda9f5fe2dc4de6586c38b7785493b7d08f0c7d6ea1...,2025-10-27 04:15:32.949834+00:00
68,TSLA,2021,4,2021-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2021-12-31', 'p...",4746d650f860bbe0d19a3676a79eb332c55ae6f7571c27...,2025-10-27 04:15:32.949834+00:00
69,TSLA,2020,4,2020-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2020-12-31', 'p...",7b781205b60671fa8eb023578b302a7ca94e0a8fd305e8...,2025-10-27 04:15:32.949834+00:00
70,TSLA,2024,0,2024-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2024-12-31', 'p...",e30b83e1f879f7f012924904b3046abe60edce70a4e4f8...,2025-10-27 04:15:33.094909+00:00
71,TSLA,2023,0,2023-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2023-12-31', 'p...",37e86d8addd4006c8d12ab1fd2294ee6b68802965ddb48...,2025-10-27 04:15:33.094909+00:00
72,TSLA,2022,0,2022-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2022-12-31', 'p...",60666dc159779ff8e3390549da749087519e84ffa24365...,2025-10-27 04:15:33.094909+00:00
73,TSLA,2021,0,2021-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2021-12-31', 'p...",e90f580d420c26dff12548a01ccb789b57e0f7b8e6b9e9...,2025-10-27 04:15:33.094909+00:00
74,TSLA,2020,0,2020-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001318605', 'date': '2020-12-31', 'p...",c3c37abbcf8936b52b39de315f1b30ae7bdb6786ab5d85...,2025-10-27 04:15:33.094909+00:00
75,SOFI,2025,1,2025-03-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2025-03-31', 'p...",1ad7af3dd12b5264dcc2b047202779cf905557c13631cf...,2025-10-27 04:15:33.243790+00:00
76,SOFI,2024,1,2024-03-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2024-03-31', 'p...",e51667fb9c378d07d3c4607ee898634d53711b38ee6beb...,2025-10-27 04:15:33.243790+00:00
77,SOFI,2023,1,2023-03-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2023-03-31', 'p...",693467fa962512476128fea6597666bbfbd1de7311c164...,2025-10-27 04:15:33.243790+00:00
78,SOFI,2022,1,2022-03-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2022-03-31', 'p...",9ba0725f55eccf94a5890c1bfc9adeff16271f825a3bd1...,2025-10-27 04:15:33.243790+00:00
79,SOFI,2021,1,2021-03-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2021-03-31', 'p...",8baaf19aac554253df104ac96e8d5d3b832ca1a4a4f3ac...,2025-10-27 04:15:33.243790+00:00
80,SOFI,2025,2,2025-06-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2025-06-30', 'p...",cbeb1bea53fbca32993fd1c1b803e7c63167285bbc2965...,2025-10-27 04:15:33.389920+00:00
81,SOFI,2024,2,2024-06-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2024-06-30', 'p...",c9d828da4955c9a3331d4f120c2713c6e0c472195dfb3f...,2025-10-27 04:15:33.389920+00:00
82,SOFI,2023,2,2023-06-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2023-06-30', 'p...",5f7a767729cedc74f09f6a4ffa7ccc7b37b8557e6c76bc...,2025-10-27 04:15:33.389920+00:00
83,SOFI,2022,2,2022-06-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2022-06-30', 'p...",8293a728f85005a4bde09a9735289fc4e11c6d9dc94cbf...,2025-10-27 04:15:33.389920+00:00
84,SOFI,2021,2,2021-06-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2021-06-30', 'p...",172272a6fe80807febefdf8f9b4d5a93299c10338c1d8e...,2025-10-27 04:15:33.389920+00:00
85,SOFI,2024,3,2024-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2024-09-30', 'p...",b58cdc90122b33adbde8651233bb22ae0729e58d72fb74...,2025-10-27 04:15:33.533624+00:00
86,SOFI,2023,3,2023-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2023-09-30', 'p...",f30df02bcc0583be840c51b6020a9a9d2c8fc784f88957...,2025-10-27 04:15:33.533624+00:00
87,SOFI,2022,3,2022-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2022-09-30', 'p...",f357614e1438591c4b062495bcbb64f811df5f4046a4b6...,2025-10-27 04:15:33.533624+00:00
88,SOFI,2021,3,2021-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2021-09-30', 'p...",b6d7883dc3a2813e85a7a25e448be12dc564447041970c...,2025-10-27 04:15:33.533624+00:00
89,SOFI,2020,3,2020-09-30,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2020-09-30', 'p...",6fb907e959ce93b3a023033ae8387d3fb962acb633810e...,2025-10-27 04:15:33.533624+00:00
90,SOFI,2024,4,2024-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2024-12-31', 'p...",dfccfa7c5a0b23eb9d5b712454fa792e27d49c79f1176a...,2025-10-27 04:15:33.683059+00:00
91,SOFI,2023,4,2023-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2023-12-31', 'p...",e3317ad23aae0cedb6ed2d163f4d70a93bfdf96217ef35...,2025-10-27 04:15:33.683059+00:00
92,SOFI,2022,4,2022-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2022-12-31', 'p...",8d165551b59882e456b86e679448b941f1e8231ec683b4...,2025-10-27 04:15:33.683059+00:00
93,SOFI,2021,4,2021-12-31,https://financialmodelingprep.com/stable/cash-...,"{'cik': '0001818874', 'date': '2021-12-31', 'p...",90a06ee0d24da5cf22690190ff9a858106d33670d0383f...,2025-10-27 04:15:33.683059+00:00

In [ ]:
# Query the `news` table
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.news;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [31]:
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.analyst_price_targets;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_32774/2388191319.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,url,source,raw_json,raw_json_sha256,updated_at
0,NVDA,https://thefly.com/permalinks/entry.php/id4213...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",64e3c6c6388e5b5ef8aa48a28d6f712a446cbc14a230a0...,2025-10-27 04:30:36.978756+00:00
1,NVDA,https://thefly.com/permalinks/entry.php/id4213...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",2d5e89b49f9ca1432bd22bc1ca2af26fbddc19debbf74d...,2025-10-27 04:30:36.978756+00:00
2,NVDA,https://thefly.com/permalinks/entry.php/id4210...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",580d62f1e3600583dbc1b3ad14917b179e01ed66f29b7c...,2025-10-27 04:30:36.978756+00:00
3,NVDA,https://thefly.com/permalinks/entry.php/id4207...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",dc0683c1b288a0bbd87343e29d054f34463df8e817dda4...,2025-10-27 04:30:36.978756+00:00
4,NVDA,https://thefly.com/permalinks/entry.php/id4207...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",9ab561886feff7ff030ae8d274e5e6d72f95595a387244...,2025-10-27 04:30:36.978756+00:00
5,NVDA,https://thefly.com/permalinks/entry.php/id4204...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",bc78882f8d662cb0855f0fb8a378a5930e47fcdc6d0b5e...,2025-10-27 04:30:36.978756+00:00
6,NVDA,https://thefly.com/permalinks/entry.php/id4202...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",a81c212cbb37fd9002330423eeca1c5b745cd6bf2c10ab...,2025-10-27 04:30:36.978756+00:00
7,NVDA,https://thefly.com/permalinks/entry.php/id4201...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",5fc50cf318ca4a033f3c45e9fd195517cc9b8632ba2404...,2025-10-27 04:30:36.978756+00:00
8,NVDA,https://thefly.com/permalinks/entry.php/id4201...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",29462c45c6cee70d9e3d612bee8402475b482e81665982...,2025-10-27 04:30:36.978756+00:00
9,NVDA,https://pulse2.com/nvidia-nvda-stock-given-250...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://pulse2....",8e3f7ba1e8bd1ca44a26bf586b603cf0fd6ca2b291bb84...,2025-10-27 04:30:37.468695+00:00
10,NVDA,https://thefly.com/permalinks/entry.php/id4190...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",be851703dd9381107af642a09cabf5f0a658389ddbca45...,2025-10-27 04:30:36.978756+00:00
11,NVDA,https://thefly.com/permalinks/entry.php/id4189...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",dbb034c23468ed9100ca02fa5ab23ff9d5fda3ebe392ca...,2025-10-27 04:30:36.978756+00:00
12,NVDA,https://thefly.com/permalinks/entry.php/id4189...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",dd7c91f0f5d2ee77c03504ddef5c43f253be929f25da27...,2025-10-27 04:30:36.978756+00:00
13,NVDA,https://thefly.com/permalinks/entry.php/id4189...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",3378e0dc4183e16737a47458a72a595443ced316d65403...,2025-10-27 04:30:36.978756+00:00
14,NVDA,https://thefly.com/permalinks/entry.php/id4187...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",4b62b4351d6889fae0be024eb6a4cbe827f7797369eb6e...,2025-10-27 04:30:36.978756+00:00
15,NVDA,https://thefly.com/permalinks/entry.php/id4187...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",e6995111a9f3bb9496359fd1e16c806e657758b55cc309...,2025-10-27 04:30:36.978756+00:00
16,NVDA,https://thefly.com/permalinks/entry.php/id4187...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",f5e20dd9f84094b92e699ab57a7ef3aba37e36ce34d8aa...,2025-10-27 04:30:36.978756+00:00
17,NVDA,https://thefly.com/permalinks/entry.php/id4182...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",8bfa1cf2125f476944a041eec88601d9379f31f2d77cfc...,2025-10-27 04:30:36.978756+00:00
18,NVDA,https://thefly.com/permalinks/entry.php/id4169...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",05122a7b1cc081fcff3232ffbec4a34e58546a8805b5c8...,2025-10-27 04:30:36.978756+00:00
19,NVDA,https://thefly.com/permalinks/entry.php/id4159...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",6b08c7b1e54c8bc353111e364ec32bedea4897db2965b5...,2025-10-27 04:30:36.978756+00:00
20,NVDA,https://thefly.com/permalinks/entry.php/id4149...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",8bda362be8ec543f006232d639b74b061af9faa3795b72...,2025-10-27 04:30:36.978756+00:00
21,NVDA,https://thefly.com/permalinks/entry.php/id4137...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",14dbf966bdb3fb62bc47a7d0befc96756bf6fa3031ba19...,2025-10-27 04:30:36.978756+00:00
22,NVDA,https://thefly.com/permalinks/entry.php/id4137...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",d5eb067e1487cfd12cf346a8f7c16ad1102e1bc364bf69...,2025-10-27 04:30:36.978756+00:00
23,NVDA,https://thefly.com/permalinks/entry.php/id4137...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",f3032ad6976448daca043c4c8376c05208978318abde02...,2025-10-27 04:30:36.978756+00:00
24,NVDA,https://www.benzinga.com/analyst-ratings/analy...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",fd60cf6169b5290e70ac6f832f59754031cf02d349ba7e...,2025-10-27 04:30:36.978756+00:00
25,NVDA,https://thefly.com/permalinks/entry.php/id4107...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",1ced0f22de16d9348928ebce2261fb0d5085573d1f3762...,2025-10-27 04:30:36.978756+00:00
26,NVDA,https://www.benzinga.com/analyst-ratings/analy...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",ae0f7499e3a5282a5297aebed115455c3812f9083ad6a8...,2025-10-27 04:30:36.978756+00:00
27,NVDA,https://thefly.com/permalinks/entry.php/id4049...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",0ff8854b3be5a84e89e4e643544123cfec7ca9dd3887bc...,2025-10-27 04:30:36.978756+00:00
28,NVDA,https://thefly.com/permalinks/entry.php/id4048...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",4eaca18ee6bd49e72e308cfb0841825fcbba78add9474a...,2025-10-27 04:30:36.978756+00:00
29,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",44cc9f6b915d5b825059e5bf2927ef38e37b8ad32f7ed4...,2025-10-27 04:30:36.978756+00:00
30,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",842ba3b9cac26c84c0e3abf1d465e8faea822439d72d81...,2025-10-27 04:30:36.978756+00:00
31,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",839c0aec25f9f99c953a515b0dd76714f0500daa778b1a...,2025-10-27 04:30:36.978756+00:00
32,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",abcc2f89dc32bdb7c529b79978c9306cdf8a0bb34dc27e...,2025-10-27 04:30:36.978756+00:00
33,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",5f1714aae6ab65f56b4d7e2a19aea4e0567cdc7a2dfacd...,2025-10-27 04:30:36.978756+00:00
34,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",2e1aeb445bbef24cf721e49896e37480ea5b5d83941ef7...,2025-10-27 04:30:36.978756+00:00
35,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",b897dc5a952ca9d1a5933470a3f140198a56fc44c3b55a...,2025-10-27 04:30:36.978756+00:00
36,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",139ecf9dd984db16c596955400bea9457cc369e1feb0ae...,2025-10-27 04:30:36.978756+00:00
37,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",d43afb96862279ceb804d81f9f1572996a2089e3e5b5fc...,2025-10-27 04:30:36.978756+00:00
38,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",95cba986131b3d22771fb14f8d45e31d16e3abc29b3446...,2025-10-27 04:30:36.978756+00:00
39,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",2794a9a6666000bb27475319f897efe06cef19319f18fd...,2025-10-27 04:30:36.978756+00:00
40,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",af09fd3cfc44ee7a74da6595f3830ab729ed7f1e0bcc65...,2025-10-27 04:30:36.978756+00:00
41,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",5e2f1166eab2292632afce155cc4255745527886fef5f0...,2025-10-27 04:30:36.978756+00:00
42,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",1cb023e87d91e66d1ef6f2b76eb7120db52cd2c1946eba...,2025-10-27 04:30:36.978756+00:00
43,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",b5075c7dcfafe66bec172dcbac48f6019eab1faaa1fee8...,2025-10-27 04:30:36.978756+00:00
44,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",db738f96fd0b7ec5e365f3b3f52483192412241b2723d8...,2025-10-27 04:30:36.978756+00:00
45,NVDA,https://pulse2.com/nvidia-nvda-stock-could-it-...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://pulse2....",03f4a751cc210bc9802aaaf6dfeeb86e7f54df2e7ecd83...,2025-10-27 04:30:37.468695+00:00
46,NVDA,https://www.benzinga.com/analyst-ratings/price...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",eda3add6ab5cafa6078ef207e59806c5d307932b14b822...,2025-10-27 04:30:36.978756+00:00
47,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",24e6eb95d5a1f77546eb79131347ff355bd71b6c00a882...,2025-10-27 04:30:36.978756+00:00
48,NVDA,https://thefly.com/permalinks/entry.php/id3996...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",82a2a422111c7b643fa5ec270c09c52e1da8b124d161f7...,2025-10-27 04:30:36.978756+00:00
49,NVDA,https://www.tipranks.com/news/blurbs/needham-t...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.tip...",53e79ca88b18e92ee64c239118f2b08b399aed942c5653...,2025-10-27 04:30:37.468695+00:00
50,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",fb3e6197e5a24cdaebf2eabc16a823837c1f8345d24826...,2025-10-27 04:30:36.978756+00:00
51,NVDA,https://www.benzinga.com/analyst-ratings/analy...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",185d4651a54204484909e22196a90f042b986980cb6eb7...,2025-10-27 04:30:36.978756+00:00
52,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",036155da7622882e78839a7ce4ff6a468259ea1f1729cc...,2025-10-27 04:30:36.978756+00:00
53,NVDA,https://www.benzinga.com/news/24/08/40659587/n...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",d209bb1d1d46cf357d4720a9ce013440007b5f911f8e67...,2025-10-27 04:30:36.978756+00:00
54,NVDA,https://www.benzinga.com/analyst-ratings/analy...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",bb0c5d41060d2f86eecd9630a7f78d9471fdc744487a6d...,2025-10-27 04:30:36.978756+00:00
55,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",3b2c25812e550b9bdd8a8bafa884a474806018be35298f...,2025-10-27 04:30:36.978756+00:00
56,TSLA,https://pulse2.com/tesla-tsla-stock-1100-and-s...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'TSLA', 'newsURL': 'https://pulse2....",6be2062688b320be0be0373bcf48c2f4cc40c3e9c179a5...,2025-10-27 04:30:39.030816+00:00
57,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",50fa72e36322692a4e637eaec980b479276dcee142d1e8...,2025-10-27 04:30:36.978756+00:00
58,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",8546f7e148c977c019a77ce2d5f9625ad7d681e0c73abf...,2025-10-27 04:30:36.978756+00:00
59,NVDA,https://www.benzinga.com/markets/equities/24/0...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",af2a1a2e71f3a0f68bb7c400a4c085eedfa0afe6d797fa...,2025-10-27 04:30:36.978756+00:00
60,NVDA,https://thefly.com/permalinks/entry.php/id3972...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",236e971aed216bf0b3da0d3deed7ec0f04027918968750...,2025-10-27 04:30:36.978756+00:00
61,NVDA,https://www.benzinga.com/news/24/08/40469719/w...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",064b5aa6f5d9908d07bc30d9373eb425c3316951328c85...,2025-10-27 04:30:36.978756+00:00
62,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",dd0c08a7553c93ed3837fc08aa7da991cf484a9fe76805...,2025-10-27 04:30:36.978756+00:00
63,NVDA,https://thefly.com/permalinks/entry.php/id3960...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",a83b41d787cb12c4c1a5590cf97944ff86d24a726f4e1a...,2025-10-27 04:30:36.978756+00:00
64,NVDA,https://www.benzinga.com/news/24/07/40048770/a...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",7771c78e003afd9a67291974d10ea19601afb5121da8ed...,2025-10-27 04:30:36.978756+00:00
65,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",0bad6879e0a11f0474dce68044afbe4779670cbf22bb8e...,2025-10-27 04:30:36.978756+00:00
66,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",3da53c737e2106c32127cf948e075f5e62317604e68c05...,2025-10-27 04:30:36.978756+00:00
67,NVDA,https://thefly.com/permalinks/entry.php/id3941...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",2621c5172f1a1feffa30646c1d64bc00ac688469dd7c91...,2025-10-27 04:30:36.978756+00:00
68,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",0c817ee230b27b64e37d1fec619df948e0d39e036deb5d...,2025-10-27 04:30:36.978756+00:00
69,NVDA,https://www.benzinga.com/news/24/06/39499816/n...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",b3580b00e9fc67fbf89971f6d67399cd080115ceaf7e5e...,2025-10-27 04:30:36.978756+00:00
70,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",67891139407c7dc3f84efbc81f4fab5f7992a405981054...,2025-10-27 04:30:36.978756+00:00
71,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",7b350611294fb7afc1ccb95440009757f24eb23e32aee6...,2025-10-27 04:30:36.978756+00:00
72,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",dd7b418498d780aa7d504f99613b59075dc9bf2ca4d8c2...,2025-10-27 04:30:36.978756+00:00
73,NVDA,https://thefly.com/permalinks/entry.php/id3931...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",baca7f4bd65609bbe07df07ea9465586e84a9fc9adf5e2...,2025-10-27 04:30:36.978756+00:00
74,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",d2490b3e33923dac2710803038d9f2c9ec3fe495aa425b...,2025-10-27 04:30:36.978756+00:00
75,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",217bf7c65514a7c81b4ddbf7aff43f46241ca3c8abd17d...,2025-10-27 04:30:36.978756+00:00
76,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",002cd74a51d1297a3c25b1f5b4762efffab642713de06e...,2025-10-27 04:30:36.978756+00:00
77,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",ad8fc036257282fca637d9e25daefc7559c4935c059728...,2025-10-27 04:30:36.978756+00:00
78,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",65e8df5530c6169544b0fccf130fc8b91479ddb3db4475...,2025-10-27 04:30:36.978756+00:00
79,NVDA,https://www.benzinga.com/analyst-ratings/analy...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.ben...",ed945c8e83d84e9f9b3fc6c99d3d6780316d926ade9705...,2025-10-27 04:30:36.978756+00:00
80,NVDA,https://www.streetinsider.com/Analyst+Comments...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://www.str...",06b59a47980885bae88d31244271a018a5df108abd4f61...,2025-10-27 04:30:36.978756+00:00
81,NVDA,https://thefly.com/permalinks/entry.php/id3923...,https://financialmodelingprep.com/stable/price...,"{'symbol': 'NVDA', 'newsURL': 'https://thefly....",91dc7a9a42a6a27f880faa574592fc321201edcf5be05b...,2025-10-27 04:30:36.978756+00:00

In [34]:
df['raw_json'].iloc[0]

{'symbol': 'NVDA',
 'newsURL': 'https://thefly.com/permalinks/entry.php/id4213792/5313286394/NVDA-HSBC-upgrades-Nvidia-to-Buy-on-earnings-upside-potential',
 'newsTitle': 'HSBC upgrades Nvidia to Buy on earnings upside potential',
 'analystName': '',
 'newsBaseURL': 'thefly.com',
 'priceTarget': 320,
 'newsPublisher': 'TheFly',
 'publishedDate': '2025-10-15T10:22:14.000Z',
 'adjPriceTarget': 320,
 'analystCompany': 'UBS',
 'priceWhenPosted': 180.03}

In [ ]:
import numpy as np

# df columns expected:
# ['tic','published_at','title','site','analyst_name','company',
#  'price_target','adj_price_target','price_when_posted','url',...]
# Make sure published_at is datetime
df['published_at'] = pd.to_datetime(df['published_at'], errors='coerce')
df = df.sort_values(['tic', 'analyst_name', 'published_at'])

# Choose adjusted PT when available
df['pt'] = df['adj_price_target'].fillna(df['price_target'])

# Sort so shift() is deterministic (tie-break with url)
df = df.sort_values(['tic','analyst_name','published_at','url'], kind='mergesort')

# Previous PT within (tic, analyst); include 'company' too if you want stricter scoping
grp_cols = ['tic','analyst_name']
df['prev_pt'] = df.groupby(grp_cols, sort=False)['pt'].shift(1)
df['prev_published_at'] = df.groupby(grp_cols, sort=False)['published_at'].shift(1)
df['prev_url'] = df.groupby(grp_cols, sort=False)['url'].shift(1)

df['pt_delta'] = df['pt'] - df['prev_pt']
df['pt_change'] = np.select(
    [
        df['prev_pt'].isna(),
        df['pt'] > df['prev_pt'],
        df['pt'] < df['prev_pt'],
    ],
    ['first_seen','upgrade','downgrade'],
    default='reiterate'
)

per_entry_changes = df[
    ['tic','analyst_name','company','published_at','url',
     'prev_published_at','prev_url','prev_pt','pt','pt_delta','pt_change']
].copy()

df = df.sort_values(['tic','published_at'])

In [ ]:
df[df['prev_url'].notnull()]

In [ ]:
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.analyst_grades;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
df['action'].unique()

In [ ]:
df['new_grade'].value_counts() + df['previous_grade'].value_counts()

In [ ]:
conn = connect_to_db()
if conn:
    query = "SELECT tic, published_at::timestamp AT TIME ZONE 'America/New_York', title FROM raw.analyst_grades;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
# show all rows 
pd.set_option('display.max_rows', None)
# show all the content in the column
pd.set_option('display.max_colwidth', None)
df[['tic', 'news_title', 'new_grade']]

In [ ]:
# count values of the new_grade
df['new_grade'].value_counts() + df['previous_grade'].value_counts()

In [ ]:
df['new_grade'].value_counts()

In [ ]:
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.analyst_price_targets;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
df[(df['tic']=='NVDA') & (df['published_at'] <= pd.to_datetime('2023-11-17')) & (df['published_at'] >= pd.to_datetime('2023-10-16'))]

In [ ]:
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.analyst_price_targets as pts " \
    "JOIN raw.analyst_grades as g " \
    "ON  pts.url = g.url " \
    ";"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [ ]:
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.dividends;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

In [5]:
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.earnings WHERE tic='NVDA' ORDER BY earnings_date DESC LIMIT 10;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_82518/4135508740.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,earnings_date,fiscal_date,session,eps,eps_estimated,revenue,revenue_estimated,price_before,price_after,source,raw_json,raw_json_sha256,updated_at
0,NVDA,2026-02-25,2026-01-26,amc,NaN,1.490,NaN,6.546594e+10,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2026-05-26', 'symbol': 'NVDA', 'epsA...",eae16bc8ce026f8c424bb8c80301e70668edcc2f273ab8...,2025-12-18 05:41:23.221043+00:00
1,NVDA,2025-11-19,2025-10-26,amc,1.30,1.260,5.700600e+10,5.491364e+10,181.360,180.640,https://financialmodelingprep.com/stable/earni...,"{'date': '2026-02-25', 'symbol': 'NVDA', 'epsA...",5d73262135dc7c1bf0d3662af46565d0e1017568768d03...,2025-12-18 05:41:23.221043+00:00
2,NVDA,2025-08-27,2025-07-27,amc,1.05,1.010,4.674300e+10,4.604892e+10,181.770,180.170,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-11-19', 'symbol': 'NVDA', 'epsA...",d54467b9b23c92cf6c73138c2ee992a21abc756fc9cf20...,2025-12-18 05:41:23.221043+00:00
3,NVDA,2025-05-28,None,None,0.81,0.737,4.406200e+10,4.333416e+10,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-08-27', 'symbol': 'NVDA', 'epsA...",f767ce394ccb3ec6b5f807cc239e3af7878cb69bcf0456...,2025-12-18 05:41:22.778753+00:00
4,NVDA,2025-02-26,2025-01-26,amc,0.89,0.848,3.933100e+10,3.810135e+10,126.640,120.964,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-05-28', 'symbol': 'NVDA', 'epsA...",5e253e0a42ee76b0edeed56aef3639e1a7c2baed510959...,2025-12-18 05:41:23.221043+00:00
5,NVDA,2024-11-20,2024-10-27,amc,0.81,0.750,3.508200e+10,3.317159e+10,146.380,146.690,https://financialmodelingprep.com/stable/earni...,"{'date': '2025-02-26', 'symbol': 'NVDA', 'epsA...",82190e6b67e3efb5a53c84e99f2f4ae89aebb5fb1119c3...,2025-12-18 05:41:23.221043+00:00
6,NVDA,2024-08-28,2024-07-28,amc,0.68,0.640,3.004000e+10,2.877951e+10,128.270,118.230,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-11-20', 'symbol': 'NVDA', 'epsA...",cd6f341eb444d6659eb6d407ee4193616c2c2061c31058...,2025-12-18 05:41:23.221043+00:00
7,NVDA,2024-05-22,None,None,0.61,0.560,2.604400e+10,2.459280e+10,NaN,NaN,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-08-28', 'symbol': 'NVDA', 'epsA...",d8c8d4ed5d55f22ebf5d150a56bbe653c92632cc370f5c...,2025-12-18 05:41:22.778753+00:00
8,NVDA,2024-02-21,2024-01-28,amc,0.52,0.460,2.210300e+10,2.023880e+10,69.452,78.538,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-05-22', 'symbol': 'NVDA', 'epsA...",4e79432e0b484d4866951784b3344a7c0538b069a68b5d...,2025-12-18 05:41:23.221043+00:00
9,NVDA,2023-11-21,2023-10-29,amc,0.40,0.340,1.812000e+10,1.519460e+10,50.409,48.716,https://financialmodelingprep.com/stable/earni...,"{'date': '2024-02-21', 'symbol': 'NVDA', 'epsA...",705003fbd4507218596093e4268c4ec8b0521e6f8d2829...,2025-12-18 05:41:23.221043+00:00

In [14]:
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.earnings_transcripts WHERE tic='SOFI' ORDER BY earnings_date DESC LIMIT 10;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_33793/1646270773.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,earnings_date,source,raw_json,raw_json_sha256,updated_at
0,SOFI,2025-10-28,https://discountingcashflows.com/company/SOFI/...,{'url': 'https://discountingcashflows.com/comp...,8daea76effb73f2af50d57a290e5b8cc00a40a3de4988a...,2025-12-18 23:40:08.739184+00:00
1,SOFI,2025-07-29,https://discountingcashflows.com/company/SOFI/...,{'url': 'https://discountingcashflows.com/comp...,49873df5b9dffe0f25756c20ef6a4988e03a78d75309c8...,2025-12-18 23:40:08.744000+00:00
2,SOFI,2025-04-29,https://discountingcashflows.com/company/SOFI/...,{'url': 'https://discountingcashflows.com/comp...,388d19a8dcbd323367a95a7884a6f2af12c01511151a6d...,2025-12-18 23:40:08.747880+00:00
3,SOFI,2025-01-27,https://discountingcashflows.com/company/SOFI/...,{'url': 'https://discountingcashflows.com/comp...,5ae8c9e493b30c3a549a769fffa5b6a878a7159c964ca5...,2025-12-18 23:40:08.752052+00:00
4,SOFI,2024-10-29,https://discountingcashflows.com/company/SOFI/...,{'url': 'https://discountingcashflows.com/comp...,828056645fc1da44eda52cfb9ac0beb029051173df879a...,2025-12-18 23:40:08.755584+00:00
5,SOFI,2024-07-30,https://discountingcashflows.com/company/SOFI/...,{'url': 'https://discountingcashflows.com/comp...,d5ca7b6bdbc9139def2ffbefbd2478b8d5a7e0306f3051...,2025-12-19 00:30:38.214334+00:00
6,SOFI,2024-04-29,https://discountingcashflows.com/company/SOFI/...,{'url': 'https://discountingcashflows.com/comp...,1a9d9ce9781ad1731800f16b7803da5d072e4a674e5390...,2025-12-19 00:30:38.223829+00:00
7,SOFI,2024-01-29,https://discountingcashflows.com/company/SOFI/...,{'url': 'https://discountingcashflows.com/comp...,f424e4d16a932e9b32c9c8e2b73a466b94d3da60e4c121...,2025-12-19 00:30:38.225795+00:00

In [6]:
conn = connect_to_db()
if conn:
    query = "SELECT * FROM raw.earnings_transcripts WHERE tic='AAPL' ORDER BY earnings_date DESC LIMIT 10;"
    df = pd.read_sql_query(query, conn)
    conn.close()
    
    # Display the data
    display(df)

/var/folders/cp/knf70myd44x348nchr96hn9h0000gp/T/ipykernel_53974/96509477.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,tic,earnings_date,source,raw_json,raw_json_sha256,transcript_sha256,updated_at
0,AAPL,2025-10-30,https://github.com/defeat-beta/defeatbeta-api,{'url': 'https://github.com/defeat-beta/defeat...,ebd98aa60a7438fb1a73d1cb5188cde00d0013c94958ee...,7367fd8aeacd81045b2e94e34e31e225fa8dde699655ef...,2025-12-19 04:01:42.952517+00:00
1,AAPL,2025-07-31,https://github.com/defeat-beta/defeatbeta-api,{'url': 'https://github.com/defeat-beta/defeat...,c98b83d2292f5cbe240007cf202f45512be6c606b5ea95...,3dbd9b4e2d9b271c169d08896e655157680e8276bd4014...,2025-12-19 04:01:43.005654+00:00
2,AAPL,2025-05-01,https://github.com/defeat-beta/defeatbeta-api,{'url': 'https://github.com/defeat-beta/defeat...,1ed2d9dd999f5ead9c718591c4a9d4f66f86e34704b4b8...,f6c4cea596704d782a702c193ec525bf4ad5d039eecac0...,2025-12-19 04:01:43.011552+00:00
3,AAPL,2025-01-30,https://github.com/defeat-beta/defeatbeta-api,{'url': 'https://github.com/defeat-beta/defeat...,feb3f968665bc0d5eb3dd399d25ce6889d8f69f9fa88e4...,abba2130960470fb89ec6dd28ea23fbeb60cff51be7654...,2025-12-19 04:01:43.015302+00:00
4,AAPL,2024-10-31,https://github.com/defeat-beta/defeatbeta-api,{'url': 'https://github.com/defeat-beta/defeat...,292522c0e451085bf022d0c0e306c0a873895e817a8da5...,168a9a9d5f4884eab786bf7de6dba023a7f954603894ce...,2025-12-19 04:01:43.020572+00:00
5,AAPL,2024-08-01,https://github.com/defeat-beta/defeatbeta-api,{'url': 'https://github.com/defeat-beta/defeat...,15a6796fd4fad2d001722211c58ecbc13871ca68f54c3b...,a7e8ce4d27a9182ff72543d62c37baaa4f839bc8ec0f39...,2025-12-19 04:01:43.023531+00:00
6,AAPL,2024-05-02,https://github.com/defeat-beta/defeatbeta-api,{'url': 'https://github.com/defeat-beta/defeat...,70e8fe6511cc260ddcf04305e45625c5c38caf4797a962...,c52e0a11d92287bcc05feb82a5a6aba85dd892e655fc58...,2025-12-19 04:01:43.028137+00:00
7,AAPL,2024-02-01,https://github.com/defeat-beta/defeatbeta-api,{'url': 'https://github.com/defeat-beta/defeat...,5df60521d2362a8fab2f5dc0c827cf08421d530d397351...,c0eb8a914d492d16492a913a42fff70a97a561d63c508d...,2025-12-19 04:01:43.031374+00:00
8,AAPL,2023-11-02,https://github.com/defeat-beta/defeatbeta-api,{'url': 'https://github.com/defeat-beta/defeat...,d7833c095a94e4a1c254edee3e71357c633b24fa05f2c7...,65bc3709dbc1599573abcbcb9463e50a3505960239c47c...,2025-12-19 04:01:43.035824+00:00
9,AAPL,2023-08-03,https://github.com/defeat-beta/defeatbeta-api,{'url': 'https://github.com/defeat-beta/defeat...,fc388d365b32c63604837cacdc912c08e709ae5c4b5f8c...,d075a33754be375c05bbc67a418f45601a5fa96a59a0c4...,2025-12-19 04:01:43.039265+00:00

In [5]:
df['raw_json'].iloc[0]

{'url': 'https://github.com/defeat-beta/defeatbeta-api',
 'date': '2025-10-30',
 'year': 2025,
 'ticker': 'AAPL',
 'quarter': 'Q4',

In [36]:
import defeatbeta_api
from defeatbeta_api.data.ticker import Ticker
ticker = Ticker('TSLA')

In [37]:
ticker.price()

     symbol report_date    open   close    high     low     volume
0      TSLA  2010-06-29    1.27    1.59    1.67    1.17  281494500
1      TSLA  2010-06-30    1.72    1.59    2.03    1.55  257806500
2      TSLA  2010-07-01    1.67    1.46    1.73    1.35  123282000
3      TSLA  2010-07-02    1.53    1.28    1.54    1.25   77097000
4      TSLA  2010-07-06    1.33    1.07    1.33    1.06  103003500
...     ...         ...     ...     ...     ...     ...        ...
3884   TSLA  2025-12-05  453.03  455.00  458.87  451.66   56427500
3885   TSLA  2025-12-08  447.45  439.58  449.75  435.25   69165800
3886   TSLA  2025-12-09  437.54  445.17  452.39  435.70   62367400
3887   TSLA  2025-12-10  446.07  451.45  456.88  443.61   63257500
3888   TSLA  2025-12-11  448.95  446.89  449.27  440.33   55979500

[3889 rows x 7 columns]

In [38]:
statement = ticker.quarterly_income_statement()

In [39]:
statement.df()

,Breakdown,TTM,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31,2023-09-30,2023-06-30,2023-03-31,2022-12-31,2022-09-30,2022-06-30
0,Total Revenue,92720000000.0,28095000000.0,22496000000.0,19335000000.0,25707000000.0,25182000000.0,25500000000.0,21301000000.0,25167000000.0,23350000000.0,24927000000.0,*,*,*,16934000000.0
1,Operating Revenue,92720000000.0,28095000000.0,22496000000.0,19335000000.0,25707000000.0,25182000000.0,25500000000.0,21301000000.0,25167000000.0,23350000000.0,24927000000.0,*,*,*,16934000000.0
2,Cost of Revenue,76513000000.0,23041000000.0,18618000000.0,16182000000.0,21528000000.0,20185000000.0,20922000000.0,17605000000.0,20729000000.0,19172000000.0,20394000000.0,*,*,*,12700000000.0
3,Gross Profit,16207000000.0,5054000000.0,3878000000.0,3153000000.0,4179000000.0,4997000000.0,4578000000.0,3696000000.0,4438000000.0,4178000000.0,4533000000.0,*,*,*,4234000000.0
4,Operating Expense,10429000000.0,3192000000.0,2955000000.0,2660000000.0,2589000000.0,2225000000.0,2351000000.0,2525000000.0,2374000000.0,2414000000.0,2134000000.0,*,*,*,1628000000.0
5,Selling General and Administrative,5116000000.0,1562000000.0,1366000000.0,1251000000.0,1313000000.0,1186000000.0,1277000000.0,1374000000.0,1280000000.0,1253000000.0,1191000000.0,*,*,*,961000000.0
6,Research & Development,5313000000.0,1630000000.0,1589000000.0,1409000000.0,1276000000.0,1039000000.0,1074000000.0,1151000000.0,1094000000.0,1161000000.0,943000000.0,*,*,*,667000000.0
7,Operating Income,5778000000.0,1862000000.0,923000000.0,493000000.0,1590000000.0,2772000000.0,2227000000.0,1171000000.0,2064000000.0,1764000000.0,2399000000.0,*,*,*,2606000000.0
8,Net Non-Operating Interest Income Expense,1298000000.0,363000000.0,306000000.0,309000000.0,346000000.0,337000000.0,262000000.0,274000000.0,272000000.0,244000000.0,210000000.0,*,*,*,-18000000.0
9,Non-Operating Interest Income,1663000000.0,439000000.0,392000000.0,400000000.0,442000000.0,429000000.0,348000000.0,350000000.0,333000000.0,282000000.0,238000000.0,*,*,*,26000000.0
10,Non-Operating Interest Expense,365000000.0,76000000.0,86000000.0,91000000.0,96000000.0,92000000.0,86000000.0,76000000.0,61000000.0,38000000.0,28000000.0,*,*,*,44000000.0
11,Other Income Expense,377000000.0,-266000000.0,320000000.0,-213000000.0,830000000.0,-318000000.0,-702000000.0,443000000.0,-145000000.0,37000000.0,328000000.0,*,*,*,-114000000.0
12,Special Income Charges,-156000000.0,-238000000.0,0.0,-94000000.0,-7000000.0,-55000000.0,-622000000.0,0.0,0.0,0.0,0.0,*,-34000000.0,0.0,-142000000.0
13,Restructuring & Mergers Acquisition,156000000.0,238000000.0,0.0,94000000.0,7000000.0,55000000.0,622000000.0,0.0,0.0,0.0,0.0,*,34000000.0,0.0,142000000.0
14,Other Non Operating Income Expenses,533000000.0,-28000000.0,320000000.0,-119000000.0,837000000.0,-263000000.0,-80000000.0,443000000.0,-145000000.0,37000000.0,328000000.0,*,*,*,28000000.0
15,Pretax Income,7453000000.0,1959000000.0,1549000000.0,589000000.0,2766000000.0,2791000000.0,1787000000.0,1888000000.0,2191000000.0,2045000000.0,2937000000.0,*,*,*,2474000000.0
16,Tax Provision,1511000000.0,570000000.0,359000000.0,169000000.0,434000000.0,602000000.0,371000000.0,483000000.0,-5752000000.0,167000000.0,323000000.0,*,*,*,205000000.0
17,Net Income Common Stockholders,5921000000.0,1373000000.0,1172000000.0,409000000.0,2314000000.0,2173000000.0,1400000000.0,1432000000.0,7927000000.0,1851000000.0,2703000000.0,*,*,*,2256000000.0
18,Net Income(Attributable to Parent Company Shar...,5921000000.0,1373000000.0,1172000000.0,409000000.0,2314000000.0,2173000000.0,1400000000.0,1390000000.0,7930000000.0,1853000000.0,2703000000.0,*,*,*,2259000000.0
19,Net Income Including Non-Controlling Interests,5942000000.0,1389000000.0,1190000000.0,420000000.0,2332000000.0,2189000000.0,1416000000.0,1405000000.0,7943000000.0,1878000000.0,2614000000.0,*,*,*,2269000000.0
20,Net Income Continuous Operations,5942000000.0,1389000000.0,1190000000.0,420000000.0,2332000000.0,2189000000.0,1416000000.0,1405000000.0,7943000000.0,1878000000.0,2614000000.0,*,*,*,2269000000.0
21,Minority Interests,-21000000.0,-16000000.0,-18000000.0,-11000000.0,-18000000.0,-16000000.0,-16000000.0,-15000000.0,-13000000.0,-25000000.0,89000000.0,*,*,*,-10000000.0
22,Otherunder Preferred Stock Dividend,*,*,*,0.0,*,0.0,*,-42000000.0,*,2000000.0,0.0,-5000000.0,*,0.0,3000000.0
23,Adjustments for Dilutive Securities,0.0,*,*,*,*,*,*,*,0.0,0.0,0.0,*,0.0,0.0,0.0
24,Diluted NI Available to Com Stockholders,5921000000.0,1373000000.0,1172000000.0,409000000.0,2314000000.0,2173000000.0,1400000000.0,1432000000.0,7927000000.0,1851000000.0,2703000000.0,*,*,*,2256000000.0
25,Basic EPS,3.41,0.43,0.36,0.13,0.72,0.68,0.46,0.37,2.49,0.58,0.85,*,*,*,0.73
26,Diluted EPS,3.1,0.39,0.33,0.12,0.66,0.62,0.42,0.34,2.27,0.53,0.78,*,*,*,0.65
27,Basic Average Shares,3168250000.0,3227000000.0,3223000000.0,3218000000.0,3213000000.0,3198000000.0,3191000000.0,3186000000.0,3181000000.0,3176000000.0,3171000000.0,*,*,*,3111000000.0
28,Diluted Average Shares,3480250000.0,3526000000.0,3519000000.0,3521000000.0,3517000000.0,3497000000.0,3481000000.0,3484000000.0,3492000000.0,3493000000.0,3478000000.0,*,*,*,3464000000.0
29,Total Operating Income as Reported,5622000000.0,1624000000.0,923000000.0,399000000.0,1583000000.0,2717000000.0,1605000000.0,1171000000.0,2064000000.0,1764000000.0,2399000000.0,*,*,*,2464000000.0
30,Rent Expense Supplemental,956000000.0,*,228000000.0,239000000.0,242000000.0,247000000.0,245000000.0,269000000.0,296000000.0,301000000.0,338000000.0,*,*,*,*
31,Total Expenses,86942000000.0,26233000000.0,21573000000.0,18842000000.0,24117000000.0,22410000000.0,23273000000.0,20130000000.0,23103000000.0,21586000000.0,22528000000.0,*,*,*,14328000000.0
32,Net Income from Continuing & Discontinued Oper...,5921000000.0,1373000000.0,1172000000.0,409000000.0,2314000000.0,2173000000.0,1400000000.0,1390000000.0,7930000000.0,1853000000.0,2703000000.0,*,*,*,2259000000.0
33,Normalized Income,6045373004.16,1541980000.0,1172000000.0,475740000.0,2319901663.05,2215900000.0,1891380000.0,1390000000.0,7930000000.0,1853000000.0,2703000000.0,*,*,*,2389640000.0
34,Interest Income,1663000000.0,439000000.0,392000000.0,400000000.0,442000000.0,429000000.0,348000000.0,350000000.0,333000000.0,282000000.0,238000000.0,*,*,*,26000000.0
35,Interest Expense,365000000.0,76000000.0,86000000.0,91000000.0,96000000.0,92000000.0,86000000.0,76000000.0,61000000.0,38000000.0,28000000.0,*,*,*,44000000.0
36,Net Interest Income,1298000000.0,363000000.0,306000000.0,309000000.0,346000000.0,337000000.0,262000000.0,274000000.0,272000000.0,244000000.0,210000000.0,*,*,*,-18000000.0
37,EBIT,7818000000.0,2035000000.0,1635000000.0,680000000.0,2862000000.0,2883000000.0,1873000000.0,1964000000.0,2252000000.0,2083000000.0,2965000000.0,*,*,*,2518000000.0
38,EBITDA,13542000000.0,3660000000.0,3068000000.0,2127000000.0,4358000000.0,4231000000.0,3151000000.0,3210000000.0,3484000000.0,3318000000.0,4119000000.0,*,*,*,*
39,Reconciled Cost of Revenue,76513000000.0,23041000000.0,18618000000.0,16182000000.0,21528000000.0,20185000000.0,20922000000.0,17605000000.0,20729000000.0,19172000000.0,20394000000.0,*,*,*,12700000000.0
40,Reconciled Depreciation,5724000000.0,1625000000.0,1433000000.0,1447000000.0,1496000000.0,1348000000.0,1278000000.0,1246000000.0,1232000000.0,1235000000.0,1154000000.0,*,*,*,922000000.0
41,Net Income from Continuing Operation Net Minor...,5921000000.0,1373000000.0,1172000000.0,409000000.0,2314000000.0,2173000000.0,1400000000.0,1390000000.0,7930000000.0,1853000000.0,2703000000.0,*,*,*,2259000000.0
42,Total Unusual Items Excluding Goodwill,-156000000.0,-238000000.0,0.0,-94000000.0,-7000000.0,-55000000.0,-622000000.0,0.0,0.0,0.0,0.0,*,-34000000.0,0.0,-142000000.0
43,Total Unusual Items,-156000000.0,-238000000.0,0.0,-94000000.0,-7000000.0,-55000000.0,-622000000.0,0.0,0.0,0.0,0.0,*,-34000000.0,0.0,-142000000.0
44,Normalized EBITDA,13698000000.0,3898000000.0,3068000000.0,2221000000.0,4365000000.0,4286000000.0,3773000000.0,3210000000.0,3484000000.0,3318000000.0,4119000000.0,*,*,*,3582000000.0
45,Tax Rate for Calcs,0.2,0.29,0.23,0.29,0.16,0.22,0.21,0.26,0.21,0.08,0.11,*,*,*,0.08
46,Tax Effect of Unusual Items,-31626995.84,-69020000.0,0.0,-27260000.0,-1098336.95,-12100000.0,-130620000.0,0.0,0.0,0.0,0.0,*,*,*,-11360000.0

In [42]:
transcripts = ticker.earning_call_transcripts()
df = transcripts.get_transcripts_list()

In [54]:
df

,symbol,fiscal_year,fiscal_quarter,report_date,transcripts,transcripts_id
0,TSLA,2011,2,2011-08-03,"[{'paragraph_number': 1, 'speaker': 'Executive...",303288
1,TSLA,2011,3,2011-11-03,"[{'paragraph_number': 1, 'speaker': 'Executive...",303289
2,TSLA,2011,4,2012-02-16,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303290
3,TSLA,2012,1,2012-05-09,"[{'paragraph_number': 1, 'speaker': 'Executive...",303291
4,TSLA,2012,2,2012-07-25,"[{'paragraph_number': 1, 'speaker': 'Executive...",303292
5,TSLA,2012,3,2012-11-05,"[{'paragraph_number': 1, 'speaker': 'Executive...",303293
6,TSLA,2012,4,2013-02-20,"[{'paragraph_number': 1, 'speaker': 'Executive...",303294
7,TSLA,2013,1,2013-05-08,"[{'paragraph_number': 1, 'speaker': 'Executive...",303295
8,TSLA,2013,2,2013-08-07,"[{'paragraph_number': 1, 'speaker': 'Executive...",303296
9,TSLA,2013,3,2013-11-05,"[{'paragraph_number': 1, 'speaker': 'Executive...",303297
10,TSLA,2013,4,2014-02-19,"[{'paragraph_number': 1, 'speaker': 'Executive...",303298
11,TSLA,2014,1,2014-05-08,"[{'paragraph_number': 1, 'speaker': 'Executive...",303299
12,TSLA,2014,2,2014-08-01,"[{'paragraph_number': 1, 'speaker': 'Executive...",303300
13,TSLA,2014,3,2014-11-05,"[{'paragraph_number': 1, 'speaker': 'Executive...",303301
14,TSLA,2014,4,2015-02-12,"[{'paragraph_number': 1, 'speaker': 'Executive...",303302
15,TSLA,2015,1,2015-05-05,"[{'paragraph_number': 1, 'speaker': 'Executive...",303303
16,TSLA,2015,2,2015-07-30,"[{'paragraph_number': 1, 'speaker': 'Executive...",303304
17,TSLA,2015,3,2015-10-30,"[{'paragraph_number': 1, 'speaker': 'Executive...",303305
18,TSLA,2015,4,2016-02-10,"[{'paragraph_number': 1, 'speaker': 'Executive...",303306
19,TSLA,2016,1,2016-05-05,"[{'paragraph_number': 1, 'speaker': 'Executive...",303308
20,TSLA,2016,2,2016-08-03,"[{'paragraph_number': 1, 'speaker': 'Executive...",303310
21,TSLA,2016,3,2016-10-27,"[{'paragraph_number': 1, 'speaker': 'Executive...",303312
22,TSLA,2016,4,2017-02-23,"[{'paragraph_number': 1, 'speaker': 'Executive...",303314
23,TSLA,2017,1,2017-05-04,"[{'paragraph_number': 1, 'speaker': 'Executive...",303316
24,TSLA,2017,2,2017-08-03,"[{'paragraph_number': 1, 'speaker': 'Executive...",303318
25,TSLA,2017,3,2017-11-02,"[{'paragraph_number': 1, 'speaker': 'Executive...",303320
26,TSLA,2017,4,2018-02-07,"[{'paragraph_number': 1, 'speaker': 'Executive...",303322
27,TSLA,2018,1,2018-05-03,"[{'paragraph_number': 1, 'speaker': 'Executive...",303324
28,TSLA,2018,2,2018-08-02,"[{'paragraph_number': 1, 'speaker': 'Executive...",303327
29,TSLA,2018,3,2018-10-25,"[{'paragraph_number': 1, 'speaker': 'Executive...",303329
30,TSLA,2018,4,2019-01-31,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303331
31,TSLA,2019,1,2019-04-25,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303333
32,TSLA,2019,2,2019-07-24,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303335
33,TSLA,2019,3,2019-10-24,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303337
34,TSLA,2019,4,2020-01-30,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303339
35,TSLA,2020,1,2020-04-29,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303341
36,TSLA,2020,2,2020-07-22,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303343
37,TSLA,2020,3,2020-10-21,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303345
38,TSLA,2020,4,2021-01-27,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303347
39,TSLA,2021,1,2021-04-27,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303349
40,TSLA,2021,2,2021-07-26,"[{'paragraph_number': 1, 'speaker': 'Operator'...",303350
41,TSLA,2021,3,2021-10-20,"[{'paragraph_number': 1, 'speaker': 'Lars Mora...",303352
42,TSLA,2021,4,2022-01-26,"[{'paragraph_number': 1, 'speaker': 'Martin Vi...",303355
43,TSLA,2022,1,2022-04-20,"[{'paragraph_number': 1, 'speaker': 'Martin Vi...",303358
44,TSLA,2022,2,2022-07-20,"[{'paragraph_number': 1, 'speaker': 'Martin Vi...",303360
45,TSLA,2022,3,2022-10-19,"[{'paragraph_number': 1, 'speaker': 'Martin Vi...",303362
46,TSLA,2022,4,2023-01-25,"[{'paragraph_number': 1, 'speaker': 'Martin Vi...",303364
47,TSLA,2023,1,2023-04-19,"[{'paragraph_number': 1, 'speaker': 'Martin Vi...",303366
48,TSLA,2023,2,2023-07-19,"[{'paragraph_number': 1, 'speaker': 'Martin Vi...",303370
49,TSLA,2023,3,2023-10-18,"[{'paragraph_number': 1, 'speaker': 'Elon Musk...",303372
50,TSLA,2023,4,2024-01-24,"[{'paragraph_number': 1, 'speaker': 'Martin Vi...",303374
51,TSLA,2024,1,2024-04-23,"[{'paragraph_number': 1, 'speaker': 'Martin Vi...",303376
52,TSLA,2024,2,2024-07-24,"[{'paragraph_number': 1, 'speaker': 'Travis Ax...",303378
53,TSLA,2024,3,2024-10-23,"[{'paragraph_number': 1, 'speaker': 'Travis Ax...",303380
54,TSLA,2024,4,2025-01-29,"[{'paragraph_number': 1, 'speaker': 'Operator'...",486436
55,TSLA,2025,1,2025-04-22,"[{'paragraph_number': 1, 'speaker': 'AI Insigh...",<NA>
56,TSLA,2025,2,2025-07-23,"[{'paragraph_number': 1, 'speaker': 'Travis Ax...",<NA>
57,TSLA,2025,3,2025-10-22,"[{'paragraph_number': 1, 'speaker': 'Travis Ax...",<NA>

In [52]:
df['transcripts'].iloc[-1][0]

{'paragraph_number': 1,
 'speaker': 'Travis Axelrod',
 'content': "Good afternoon, everyone, and welcome to Tesla's third quarter 2025 Q&A Webcast. My name is Travis Axelrod, Head of Investor Relations. I am joined today by Elon Musk, Vaibhav Taneja, and a number of other executives. Our Q3 results were announced at about 3 PM Central Time in the Update deck we published at the same link as this webcast. During this call, we will discuss our business outlook and make forward-looking statements. These comments are based on our predictions and expectations as of today. Actual events or results could differ materially due to a number of risks and uncertainties, including those mentioned in our most recent filings with the SEC. We urge shareholders to read our definitive proxy statement, which contains important information about the matters we voted on at the 2025 annual meeting. During the question and answer portion of today's call, please limit yourself to one question and one follow-up. Please use the raise hand button to join the question queue. Before we jump into Q&A, Elon has some opening remarks. Elon?"}